---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2021/4/25 15:20
---

local M = class("CompassControl", LikeOO.OOControlBase)

function M:onEnter()
    --倒计时
    self:CountDown()
end

function M:onHandle(msg, data)
    if msg == 99999 then
        if self.m_view.start then
            return
        end
        self:closeView()
        UserDataManager:removeRedDotByKey("roulette_once")
        self:updateMsg("refresh_red_point", nil, "parent")
    elseif msg == "tab_obg_1" then
        self.m_view:switchTabNode(1)
    elseif msg == "tab_obg_2" then
        self.m_view:switchTabNode(2)
    elseif msg == "btn_one" then
        self:requestGacha(1)
    elseif msg == "btn_ten" then
        self:requestGacha(10)
    elseif msg == "btn_refresh" then
        self:requestRefresh()
    elseif msg == "btn_help" then
        if self.m_view.start then
            return
        end
        self:openView("Compass.CompassHelpPop", { cur_index = self.m_model.cur_index, pool_data = self.m_model.data.goods.luckys[tostring(self.m_model.cur_index)] })
    elseif msg == "skip_anim_btn" then
        if self.m_view.start then
            return
        end
        self.m_model:changeSkipAnimFlag()
        self.m_view:updateSkipAnimStatus()
        --Logger.logError("skip_anim_btn = " .. tostring(self.m_model.m_skip_anim_flag))
    end
end

function M:requestGacha(times)
    if self.m_view.start then
        return
    end
    if self.m_model:isMaxTime() then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("tid#limit_1"), delay_close = 2})
        return
    end
    local one_need = ConfigManager:getCommonValueById(375)
    if self.m_model.cur_index == 2 then
        one_need = ConfigManager:getCommonValueById(376)
    end
    local itemData = RewardUtil:getProcessRewardData(one_need)
    if times == 10 then
        local ten_need = ConfigManager:getCommonValueById(363)
        if self.m_model.cur_index == 2 then
            ten_need = ConfigManager:getCommonValueById(364)
        end
        itemData = RewardUtil:getProcessRewardData(ten_need)
    end
    if itemData.user_num < itemData.data_num then
        if self.m_model.cur_index == 2 then
            local flag = QuickOpenFuncUtil:costsTips(itemData)
            if flag then
                return
            end
        end
        GameUtil:lookInfoTips(self, { msg = Language:getTextByKey("compass_str_002"), delay_close = 2 })
        return
    end
    local function netCallback(response)
        if response then
            self.m_model.data.goods = response.goods
            self.m_model.reward = response.gifts
            table.merge(self.m_model.data.day_times, response.day_times)
            for k, v in pairs(response.addon_gifts) do
                table.insert(self.m_model.reward, v)
            end
            self.prize = response.ids[1]
            self.block_id = self.m_model.data.goods.luckys[tostring(self.m_model.cur_index)][tostring(self.prize)].block
            --local lucky_team = self.m_model.roulette_block_cfg[self.m_model.cur_index][self.block_id].lucky_team
            --Logger.logError("中奖id = " .. self.prize .. " block = " .. self.block_id .. " lucky_team = " .. lucky_team)
            if self.m_model.m_skip_anim_flag then
                RewardUtil:rewardTipsByRewards(self.m_model.reward)
                self.m_view:refreshUI()
            else
                self.m_view.m_fTime = 0
                self.m_view.m_fVelocity = 0
                self.m_view.m_fVelocity_2 = 0
                self.m_view.time = nil
                self.m_view:setObjectVisible("UI_Compass_JiHuo_001", false)
                self.m_view:setObjectVisible("UI_Compass_JiHuo_001", true)
                self.m_view:setObjectVisible("UI_Compass_Glow_002", true)
                self.m_view:refreshLimitTimes()
                audio:SendEvtUI("UI_TanCeLuoPan")
                self.m_view.start = true
                self:setOnceTimer(0.65, function()
                    self.m_view:setObjectVisible("UI_Compass_JiHuo_001", false)
                    self.m_view.go = true
                    self.m_view.is_play = false
                    self.m_view.start_2 = true
                    self.m_view.s_turntable_2 = true
                end)
            end
        end
    end

    local params = {
        on_ok_call = function(msg)
            local function callback()
                self.m_model:getNetData("roulette_treasure", { t = self.m_model.cur_index, times = times }, netCallback)
            end
            self:requestRefresh(callback)
        end,
        new_cancel_call = function()
            self.m_model:getNetData("roulette_treasure", { t = self.m_model.cur_index, times = times }, netCallback)
        end,
        tow_close_btn = true,
        no_close_btn = false,
        text = Language:getTextByKey("compass_str_003")
    }
    if table.nums(self.m_model.data.goods.bigprice[tostring(self.m_model.cur_index)]) < 4 then
        self.m_model:getNetData("roulette_treasure", { t = self.m_model.cur_index, times = times }, netCallback)
    else
        local server_time = UserDataManager:getServerTime()
        local last_time = self.m_model.data.next_refresh[tostring(self.m_model.cur_index)]
        local time = last_time - server_time
        local refresh_need = self.m_model:getRefreshNeed()
        if time >0 and refresh_need > 0 then
            params.cost = { RewardUtil.REWARD_TYPE_KEYS.DIAMOND, 0, refresh_need}
        end
        self:openView("Pops.CommonPop", params)
    end
end

function M:requestRefresh(callback)
    if self.m_view.start then
        return
    end
    if self.m_model:isMaxTime(true) and self.m_model:getNextRefresh() > 0 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("tid#limit_1"), delay_close = 2})
        return
    end
    local function netCallback(response)
        if response then
            self.m_model.data.goods = response.goods
            table.merge(self.m_model.data.rtimes, response.rtimes)
            self.m_model.data.next_refresh = response.next_refresh
            self.m_view:refreshUI()
            audio:SendEvtUI("UI_TanBao_Refresh")
            for k, v in pairs(self.m_view.item_list) do
                if k == 1 or k == 4 or k == 7 or k == 10 then
                    v.ShuaXin_002:SetActive(false)
                    v.ShuaXin_002:SetActive(true)
                else
                    v.ShuaXin_001:SetActive(false)
                    v.ShuaXin_001:SetActive(true)
                end
            end
            if callback then
                callback()
            end
        end
    end
    self.m_model:getNetData("roulette_refresh", { t = self.m_model.cur_index }, netCallback)
end

function M:GetIntegralReward(index)
    local function netCallback(response)
        if response then
            self.m_model.data.goods.point[tostring(self.m_model.cur_index)] = response.point
            self.m_model.data.goods.point_index[tostring(self.m_model.cur_index)] = response.point_index
            RewardUtil:rewardTipsByData(response.reward)
            self.m_view:refreshUI()
        end
    end
    self.m_model:getNetData("roulette_point", { t = self.m_model.cur_index, index = index }, netCallback)
end

function M:CountDown()
    local function countDown()
        local refresh_need = self.m_model:getRefreshNeed()
        local server_time = UserDataManager:getServerTime()
        local last_time = self.m_model.data.next_refresh[tostring(self.m_model.cur_index)]
        local time = last_time - server_time
        if time > 0 then
            local text = GameUtil:formatTimeBySecond(time, 999)
            self.m_view:setText("txt_cut_down", Language:getTextByKey("new_str_0064"))
            self.m_view:setText("count_down", text)
            self.m_view:setText("txt_refresh", refresh_need)
            self.m_view:setText("refresh_tips", "")
        else
            self.m_view:setText("txt_cut_down", "")
            self.m_view:setText("count_down", "")
            if self.m_model.refresh_tips then
                self.m_view:setText("refresh_tips", Language:getTextByKey("new_str_0826"))
            else
                self.m_view:setText("refresh_tips", "")
            end
            self.m_view:refreshRefreshLimitTimes()
            self.m_view:setText("txt_refresh", Language:getTextByKey("new_str_0278"))
        end
    end
    if self.count_down_timer == nil then
        self.count_down_timer = self:setTimer(0.1, countDown)
    end
end

function M:destroy()
    if self.count_down_timer then
        self:removeTimer(self.count_down_timer)
        self.count_down_timer = nil
    end
    M.super.destroy(self)
end

return M