---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2021/4/25 15:18
---

local M = class("CompassModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:getData("roulette_roulette_index")
end

function M:onEnter()
    self.cur_index = nil
    self.refresh_tips = false
    self.reward = {}
    self.data = self.m_data
    self.roulette_point_cfg = ConfigManager:getCfgByName("roulette_point")
    self.roulette_block_cfg = ConfigManager:getCfgByName("roulette_block")

    self.m_skip_anim_flag = UserDataManager.local_data:getUserDataByKey("compass_skip_anim_flag", false)
end

function M:getNextRefresh()
    local next_refresh = 0
    local last_time = 0
    if self.data.next_refresh and self.data.next_refresh[tostring(self.cur_index)] then
        last_time = self.data.next_refresh[tostring(self.cur_index)]
    end
    local server_time = UserDataManager:getServerTime()
    next_refresh = last_time - server_time
    return next_refresh
end

function M:getRTimes()
    local refresh_times = 0
    if self.data.rtimes and self.data.rtimes[tostring(self.cur_index)] then
        refresh_times = self.data.rtimes[tostring(self.cur_index)]
    end
    return refresh_times
end

function M:getDayTimes()
    local day_times = 0
    if self.data.day_times and self.data.day_times[tostring(self.cur_index)] then
        day_times = self.data.day_times[tostring(self.cur_index)]
    end
    return day_times
end
function M:isMaxTime(isRefresh)
    local max_times, max_refresh_times = self:getMaxTimes()
    local limit_times = isRefresh and max_refresh_times or max_times
    local cur_compass_times = self:getDayTimes()
    local cur_refresh_times = self:getRTimes()
    local cur_times = isRefresh and cur_refresh_times or cur_compass_times
    local is_max_time = false
    if limit_times == 0 then
    elseif cur_times >= limit_times then
        is_max_time = true
    end
    return is_max_time
end

function M:getMaxTimes()
    local limit_id, refresh_limit_id =  444, 452
    if self.m_index == 2 then
        limit_id, refresh_limit_id = 445, 453
    end
    local max_times = ConfigManager:getCommonValueById(limit_id,0)
    local max_refresh_times = ConfigManager:getCommonValueById(refresh_limit_id,0)
    return max_times, max_refresh_times
end

function M:getRefreshNeed()
    local refresh_need = ConfigManager:getCommonValueById(439, 0)--低级刷新消耗
    if self.cur_index == 2 then
        refresh_need = ConfigManager:getCommonValueById(362, 0)--高级刷新消耗
    end
    return refresh_need
end

function M:getStageReward()
    local cur_stage = UserDataManager:getCurStage();
    local need_stage_tab = {}
    for k, v in pairs(self.roulette_point_cfg) do
        need_stage_tab[#need_stage_tab + 1] = k
    end
    table.sort(need_stage_tab)
    local stage_index = 1
    for i = 1, #need_stage_tab do
        if need_stage_tab[i] <= cur_stage then
            stage_index = i
        end
    end
    return self.roulette_point_cfg[need_stage_tab[stage_index]]
end

function M:GetRoulettePointDataByType(type)
    local temp = {}
    local reward_cfg = {}
    if self.roulette_point_cfg[1] and self.roulette_point_cfg[1][1] and self.roulette_point_cfg[1][1].point then
        reward_cfg = self.roulette_point_cfg
    else
        reward_cfg = self:getStageReward()
    end
    for i=1, 2 do
        temp[i] = {}
        for k, v in pairs(reward_cfg[i]) do
            temp[i][#temp[i] + 1] = v
        end
    end
    local sortFunc = function (v1, v2)
        if v1.point < v2.point then
            return true
        end
    end
    table.sort(temp[type], sortFunc)
    return temp[type]
end

function M:GetRouletteBlockDataByType(type)
    local temp = {}
    for i=1, 2 do
        temp[i] = {}
        for k, v in pairs(self.roulette_block_cfg[i]) do
            temp[i][v.lucky_team] = v
        end
    end
    return temp[type]
end

function M:getRightListReward(point_cfg)
    local cur_season = UserDataManager:getCurSeason() -- 当前赛季
    local reward = nil
    for i = cur_season, 0 , -1  do
        reward = point_cfg.season_rewards[i]
        if reward then
            return reward[1]
        end
    end
    return reward
end

function M:changeSkipAnimFlag()
    self.m_skip_anim_flag = not self.m_skip_anim_flag
    UserDataManager.local_data:setUserDataByKey("compass_skip_anim_flag", self.m_skip_anim_flag)
end

function M:destroy()
    M.super.destroy(self)
end

return M