---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/12/3 10:14
---

local M = class("KancilGiftBagNode", LikeOO.OOUIbase)
-- 礼包屋
M.m_uiName = "DoubleFestivalActivity/KancilGiftBagNode"
M.cacheSpineName = ""
function M:onEnter()
    EventDispatcher:registerEvent(GlobalConfig.EVENT_KEYS.EVERY_DAY_EVENT, {self, self.everyDayRefreshEvent})
    self.grayImage = self:findImage("img_grayImage")
    self.dayTimerText = self:findText("time_down")
    self.m_openId = 230
    self.m_activityData = self.m_model.m_activityDatas[self.m_openId] or {}
    self:bindUI()
    self:refreshUI()
end

function M:everyDayRefreshEvent()
    self.m_control:refreshChildView(true, false)
    self:refreshUI()
end

function M:bindUI()
    self:refreshActivityTimer()
    local activityXlsxData = self.m_model.m_activityXlsxData[self.m_openId] or {}
    local titleName = activityXlsxData.name_2 or ""
    self:setTextByLanKey("titleName_text", titleName)
end

function M:refreshActivityTimer()
    local startTimer = self.m_activityData.start_ts -- show_start_ts
    local endTimer = self.m_activityData.end_ts
    local starT = TimeUtil.gmTime(startTimer)
    local endT = TimeUtil.gmTime(endTimer)
    local timerFormat = Language:getTextByKey("doubleFestival_text_0019", starT.year, starT.month, starT.day,
            endT.year, endT.month, endT.day)
    self:setText("text_timer", timerFormat)
end

function M:refreshUI()
    self.m_serverData = self.m_model.m_serverDatas[self.m_openId] or {}
    self.m_openDay = GameUtil:getActityOpenDayCount(self.m_activityData.start_ts)

    self:refreshGiftBagList()
    self:refreshLeftHeroNode()
end

function M:refreshDayTimer(timerFormat)
    if not IsNull(self.dayTimerText) then
        self.dayTimerText.text = Language:getTextByKey("doubleFestival_text_0033",timerFormat);
    end
end

function M:refreshGiftBagList()
    -- 任务列表
    local data = self.m_model:getGiftRoomData(self.m_serverData.gifts)
    if self.m_taskScroll_view == nil then
        local loopscroll = self:findGameObject("task_loopscroll")
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshTaskItem(index, cell_obj, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
            end
        }
        self.m_taskScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_taskScroll_view:reloadData(data, true)
    end
end

function M:refreshTaskItem(index, cell_obj, cell_data)
    local parentLuaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    for i = 1, 3 do
        local itemObj = parentLuaBehaviour:FindGameObject("itemNode"..i)
        local itemData = cell_data[i]
        local isExistGiftData = (itemData ~= nil)
        LuaBehaviourUtil.setObjectVisible(parentLuaBehaviour, "itemNode"..i, isExistGiftData)
        if isExistGiftData then
            local xlsxData = itemData.xlsxData
            local luaBehaviour = UIUtil.findLuaBehaviour(itemObj)
            if luaBehaviour then
                local transform = itemObj.transform
                LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_bgImg", itemData.isCanBuy and (xlsxData.background == "1"))
                LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_bgImg2", itemData.isCanBuy and (xlsxData.background == "2"))
                LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_maskImg", (not itemData.isCanBuy))
                LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_titleText", xlsxData.gift_name)
                local buyCountFormat = Language:getTextByKey("doubleFestival_text_0016", itemData.curBuyCount, xlsxData.time_limit)
                LuaBehaviourUtil.setText(luaBehaviour, "text_buyCount", "" )

                if xlsxData.price == 0 then
                    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_money", Language:getTextByKey("new_str_0278") )
                else
                    LuaBehaviourUtil.setText(luaBehaviour, "text_money", GameUtil:getMoneyTypeNum(xlsxData.price) )
                end
                
                local return_per_text = luaBehaviour:FindText("return_per_text")
                if return_per_text then
                    return_per_text.text = GameUtil:formatNum(xlsxData.return_per * 100) .. "%"
                end

                local parent = luaBehaviour:FindGameObject("itemParent")
                UIUtil.destroyAllChild(parent.transform)
                local rewards = GameUtil:createGiftRewards(parent.transform, xlsxData.reward, true, true)
                if not itemData.isCanBuy then
                    LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_buyBtn", false)
                    LuaBehaviourUtil.setObjectVisible(luaBehaviour, "sellout_text", true)
                    LuaBehaviourUtil.setText(luaBehaviour, "text_money", "" )
                    for k,v in pairs(rewards) do
                        local reward_luaBehaviour = UIUtil.findLuaBehaviour(v)
                        if reward_luaBehaviour then
                            LuaBehaviourUtil.setObjectVisible(reward_luaBehaviour, "duigoudi_img", true)
                        end
                    end
                else
                    LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_buyBtn", true)
                    LuaBehaviourUtil.setObjectVisible(luaBehaviour, "sellout_text", false)
                end
                ---- 宝箱按钮
                --for index = 1, 4 do
                --    local awardData = xlsxData.reward[index]
                --    local awardTrans = UIUtil.findRectTransform(itemObj.transform, "awardNode"..index)
                --    UIUtil.destroyAllChild(awardTrans)
                --    if awardData then
                --        local itemNode = GameUtil:createItemElement(awardData, true, true)
                --        itemNode.transform:SetParent(awardTrans, false)
                --    end
                --end
                --itemData.isCanBuy = false
                if xlsxData.time_limit == 0 then
                    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "buy_limit_text", "gf_str_0105")
                else
                    local residueCount = (xlsxData.time_limit-itemData.buyCount)
                    residueCount = itemData.isCanBuy and residueCount or 0
                    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "buy_limit_text", "gf_str_0050", residueCount)
                end
                
                -- 购买按钮
                local btn_buyBtn = luaBehaviour:FindGameObject("btn_buyBtn")
                UIUtil.setButtonClick(
                        btn_buyBtn.transform,
                        function()
                            if not itemData.isCanBuy then
                                return
                            end
                            local params = {}
                            if xlsxData.price == 0 then
                                params.vsn = self.m_model.m_version
                                params.place = itemData.index
                                params.open_id = self.m_openId
                            else
                                params.version = self.m_model.m_version
                                params.gift_id = itemData.cid
                                params.charge_id = xlsxData.charge_id
                            end
                            params.price = xlsxData.price
                            self.m_control:updateMsg("btn_buyGiftBtn", params)

                        end
                )
            end
        end
    end
end

function M:refreshLeftHeroNode()
    local skinData = self.m_model:getSkinGiftRoomData(self.m_serverData.buySkinLog)
    local xlsxData = skinData.xlsxData

    local moneyFormat = skinData.isGot and Language:getTextByKey("doubleFestival_text_0029") or GameUtil:getMoneyTypeNum(xlsxData.price_new)
    self:setText("text_buySkinText", moneyFormat)
    
    self:setText("text_discountText", xlsxData.return_per)
    self:setTextByLanKey("text_originalMoney", "doubleFestival_text_0030", GameUtil:switchMoneyType(xlsxData.price_old) )
    self:setObjectVisible("eft_grayEft", skinData.isGot)
    self:setObjectVisible("eft_normalEft", (not skinData.isGot))

    ---- 皮肤礼包刷新
    local reward = xlsxData.reward
    local reward_data = RewardUtil:getProcessRewardData(reward[1])
    if reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT then
        local cfg = UserDataManager.hero_data:getHeroConfigByCid(reward_data.data_id)
        if cfg then
            local icon = cfg.hero_spine
            if self.cacheSpineName == icon then
                return
            else
                self.cacheSpineName = icon
            end
        end
    elseif reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
        local cur_skin_cfg = ConfigManager:getHeroSkinCfg(reward_data.data_id)
        local icon = cur_skin_cfg.hero_spine
        if self.cacheSpineName == icon then
            return
        else
            self.cacheSpineName = icon
        end
    end
    if self.cacheSpineName then
        local play_img = self:findGameObject("hero_spine")
        GameUtil:updateSpineLoadSet(play_img, "RoleSpine/" .. self.cacheSpineName, "idle", 0, true)
    end

    -- 设置名字
    local heroId = reward_data.item_cfg.hero
    if heroId == nil then
        heroId = reward_data.data_id
    end
    local m_hero_cfg = UserDataManager.hero_data:getHeroConfigByCid(heroId)
    local m_shin_data_cfg = UserDataManager.hero_data:getHeroCurSkinCfgByData({skin = reward_data.data_id}, m_hero_cfg)
    local frame_data = GlobalConfig.QUALITY_FRAME[m_hero_cfg.max_evo]
    self:setImg(GameUtil:get_lineframename(m_hero_cfg.Ex_hero,m_hero_cfg.max_evo), "common_ui","hero_evo")
    local race = GlobalConfig.TYPE_HERO_RACE[m_hero_cfg.race].big_race_icon
    self:setImg(race,  ResourceUtil:getLanAtlas(), "hero_race")
    local class_str = Language:getTextByKey(m_hero_cfg.class)
    local name_str = Language:getTextByKey(m_shin_data_cfg.name)
    if m_shin_data_cfg.name == nil then
        name_str = Language:getTextByKey(m_hero_cfg.name)
    end
    self:setTextByLanKey("hero_name", class_str)
    self:setTextByLanKey("hero_name2", name_str)
    self:setObjectVisible("hero_name_con", true)
    local btn_heroSkinBtn = self:findGameObject("btn_heroSkinBtn")
    UIUtil.setButtonClick(
            btn_heroSkinBtn.transform,
            function()
                if reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT then
                    static_rootControl:openView("Pops.HeroLookInfo", {hero_id = heroId, is_new = false})
                elseif reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
                    static_rootControl:openView("Pops.HeroSkinLookInfo", {is_new = false, skin_id = reward_data.data_id})
                end
            end
    )
end

function M:onButtonClick(obj, name)
    if name == "btn_buySkinBtn" then
        local skinData = self.m_model:getSkinGiftRoomData(self.m_serverData.buySkinLog)
        if skinData.isGot then
            return
        end
        self.m_control:updateMsg("btn_buySkinBtn", {charge_id = skinData.xlsxData.charge_id })
    end
end

function M:destroy()
    EventDispatcher:unRegisterEvent(GlobalConfig.EVENT_KEYS.EVERY_DAY_EVENT, {self, self.everyDayRefreshEvent})
    M.super.destroy(self)
end

return M