---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/12/3 10:14
---

local M = class("KancilShopNode", LikeOO.OOUIbase)
-- 灵鹿集市
M.m_uiName = "DoubleFestivalActivity/KancilShopNode"
M.cacheSpineName = ""
function M:onEnter()
    self.m_attr_node = GameUtil:commonAttrNode(self.m_control, {mode = 26})
    self.m_openId = 229
    -- 用于获取该活动的skin信息
    self.m_brotherDataOpenId = 230      
    self.m_activityData = self.m_model.m_activityDatas[self.m_openId] or {}
    self:bindUI()
    self:refreshUI()
    RedPointUtil:saveLocalRedPointFreshTime("linglu_shopRedDot")
end

function M:bindUI()
    self:refreshActivityTimer()
    self:refreshLeftHeroNode()
    local activityXlsxData = self.m_model.m_activityXlsxData[self.m_openId] or {}
    local titleName = activityXlsxData.name_2 or ""
    self:setTextByLanKey("titleName_text", titleName)
end


function M:refreshLeftHeroNode()
    ---- 皮肤礼包刷新
    local brotherData = self.m_model.m_serverDatas[self.m_brotherDataOpenId] or {}
    local skinData = self.m_model:getExchangeCardData(brotherData.buySkinLog)
    local xlsxData = skinData.xlsxData
    local reward = xlsxData.hero_id
    local reward_data = RewardUtil:getProcessRewardData(reward)
    if reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT then
        local cfg = UserDataManager.hero_data:getHeroConfigByCid(reward_data.data_id)
        if cfg then
            local icon = cfg.hero_spine
            if self.cacheSpineName == icon then
                return
            else
                self.cacheSpineName = icon
            end
        end
    elseif reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
        local cur_skin_cfg = ConfigManager:getHeroSkinCfg(reward_data.data_id)
        local icon = cur_skin_cfg.hero_spine
        if self.cacheSpineName == icon then
            return
        else
            self.cacheSpineName = icon
        end
    end
    if self.cacheSpineName then
        local play_img = self:findGameObject("hero_spine")
        GameUtil:updateSpineLoadSet(play_img, "RoleSpine/" .. self.cacheSpineName, "idle", 0, true)
    end

    local moneyFormat = skinData.isGot and Language:getTextByKey("doubleFestival_text_0029") or Language:getTextByKey("doubleFestival_text_0028", xlsxData.price_new)
    self:setText("text_buySkinText", moneyFormat)
    self:setText("text_discountText", xlsxData.return_per)
    self:setTextByLanKey("text_originalMoney", "doubleFestival_text_0030", xlsxData.price_old)

    -- 设置名字
    local heroId = reward_data.item_cfg.hero
    if heroId == nil then
        heroId = reward_data.data_id
    end
    local m_hero_cfg = UserDataManager.hero_data:getHeroConfigByCid(heroId)
    local m_shin_data_cfg = UserDataManager.hero_data:getHeroCurSkinCfgByData({skin = reward_data.data_id}, m_hero_cfg)
    --local frame_data = GlobalConfig.QUALITY_FRAME[m_hero_cfg.max_evo]
    self:setImg(GameUtil:get_lineframename(m_hero_cfg.Ex_hero,m_hero_cfg.max_evo), "common_ui","hero_evo")
    local race = GlobalConfig.TYPE_HERO_RACE[m_hero_cfg.race].big_race_icon
    self:setImg(race,  ResourceUtil:getLanAtlas(), "hero_race")
    local class_str = Language:getTextByKey(m_hero_cfg.class)
    local name_str = Language:getTextByKey(m_shin_data_cfg.name)
    if m_shin_data_cfg.name == nil then
        name_str = Language:getTextByKey(m_hero_cfg.name)
    end
    self:setTextByLanKey("hero_name", class_str)
    self:setTextByLanKey("hero_name2", name_str)
    self:setObjectVisible("hero_name_con", true)
    local btn_heroSkinBtn = self:findGameObject("btn_heroSkinBtn")
    UIUtil.setButtonClick(
            btn_heroSkinBtn.transform,
            function()
                if reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT then
                    static_rootControl:openView("Pops.HeroLookInfo", {hero_id = heroId, is_new = false})
                elseif reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
                    static_rootControl:openView("Pops.HeroSkinLookInfo", {is_new = false, skin_id = reward_data.data_id})
                end
            end
    )
end


function M:refreshActivityTimer()
    local startTimer = self.m_activityData.start_ts
    local endTimer = self.m_activityData.end_ts
    local starT = TimeUtil.gmTime(startTimer)
    local endT = TimeUtil.gmTime(endTimer)
    local timerFormat = Language:getTextByKey("doubleFestival_text_0019", starT.year, starT.month, starT.day,
            endT.year, endT.month, endT.day)
    self:setText("text_timer", timerFormat)
end

function M:refreshUI()
    self.m_serverData = self.m_model.m_serverDatas[self.m_openId] or {}
    self:refreshTaskList()
end

function M:refreshTaskList()
    -- 任务列表
    local data = self.m_model:getkancilShopData(self.m_serverData.exchangeData)
    if self.m_taskScroll_view == nil then
        local loopscroll = self:findGameObject("task_loopscroll")
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshTaskItem(cell_obj, cell_data,false)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_goBtn" or click_name == "btn_canGotBtn" then
                    audio:SendEvtUI("UI_Tab_N5")
                    if cell_data.curExchangeCount >= cell_data.allCount then
                        GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("doubleFestival_text_0025"), delay_close = 2})
                        return
                    end
                    if cell_data.userNum < cell_data.needNum then
                        GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("doubleFestival_text_0026"), delay_close = 2})
                        return
                    end
                    local params = {version = self.m_model.m_version, gift_id = cell_data.id, openId = self.m_openId}
                    self.m_control:updateMsg("btn_gotShopTaskBtn", params)
                end
            end
        }
        self.m_taskScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_taskScroll_view:reloadData(data, true)
    end
end

function M:refreshTaskItem(cell_obj, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local transform = cell_obj.transform
        local xlsxData = cell_data.xlsxData
        local needAwardData = xlsxData.need_reward[1]
        local awardDatas = xlsxData.out_reward
        ---- 奖励
        for i = 1, 3 do
            local awardData = (i == 1) and needAwardData or awardDatas[(i - 1)]
            local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData then
                local itemNode = GameUtil:createItemElement(awardData, true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_goBtnText","doubleFestival_text_0014")
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_canGotBtnText","doubleFestival_text_0014")
        local isCanGot = (cell_data.userNum >= cell_data.needNum) and (cell_data.curExchangeCount < cell_data.allCount)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_canGotBtn", isCanGot)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_goBtn", (not isCanGot))
        local residueCount = (xlsxData.times - cell_data.curExchangeCount)
        residueCount = residueCount > 0 and residueCount or 0
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_residueText","doubleFestival_text_0024", residueCount )
    end
end

function M:onButtonClick(obj, name)
    
end

function M:destroy()
    if self.m_attr_node then
        self.m_attr_node:destroy()
        self.m_attr_node = nil
    end
    M.super.destroy(self)
end

return M