---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/8 16:17
---

local M = class("DoubleFestivalMainModel", LikeOO.OODataBase)

local __TAB_BTN_NODE = {
    {open_id = 227, index = 1, isRechargeActivity = false, lua_name = "UI.DoubleFestivalActivity.DoubleFestivalMain.SmashEggsNode"}, -- 砸金蛋
    {open_id = 228, index = 2, isRechargeActivity = false, lua_name = "UI.DoubleFestivalActivity.DoubleFestivalMain.WishingTaskNode"}, -- 许愿树
    {open_id = 229, index = 3, isRechargeActivity = false, lua_name = "UI.DoubleFestivalActivity.DoubleFestivalMain.KancilShopNode"}, -- 灵鹿集市
    {open_id = 230, index = 4, isRechargeActivity = true,  lua_name = "UI.DoubleFestivalActivity.DoubleFestivalMain.KancilGiftBagNode"}, -- 礼包屋
}

function M:onCreate()
    -- 主活动的openId
    self.m_mainOpenId = 226
    
    --M.super.onCreate(self)
    -- 跳转进来的页签，默认是1，代金券是4
    self.m_jumpIndex = self.m_params.jumpIndex or 1
    local select_open_id = self.m_params.open_id or 0
    if select_open_id == -1 then --代金券进入
        self.m_is_token = true
    else
        self.m_is_token = false
    end
    self:getData("new_year_index")
end

function M:onEnter()
    self.m_open_tab_index = 0
    self.m_max_day = 10
    self.m_start_ts = 0
    --self.m_package_refresh_time = 0 -- 年货坊刷新倒计时
    self.m_tab_Node = __TAB_BTN_NODE
    --table.sort(self.m_tab_Node, function(itemData1, itemData2)
    --    return itemData1.index < itemData2.index
    --end)
    --
    self:refreshData(self.m_data)
    self:refreshActivityXlsx()

    local new_yearData = ConfigManager:getCfgByName("new_year")
    local itemXlsxData = new_yearData[self.m_version]
    self.itemXlsxInfo = itemXlsxData.gacha[1] or {}
end

function M:getXlsxActivityByOpenId(openId, isRechargeActivity)
    local xlsxName = isRechargeActivity and "active_recharge" or "active"
    local active = ConfigManager:getCfgByName(xlsxName)
    for _,itemData in pairs(active) do
        if (itemData.version == self.m_version) and (openId == itemData.open_id) then
            return itemData
        end
    end
    return nil
end

function M:refreshActivityXlsx()
    self.m_activityXlsxData = {}
    for _, itemData in pairs(self.m_tab_Node) do
        local openId = itemData.open_id
        self.m_activityXlsxData[openId] = self:getXlsxActivityByOpenId(openId, itemData.isRechargeActivity)
    end
    self.m_activityXlsxData[self.m_mainOpenId] = self:getXlsxActivityByOpenId(self.m_mainOpenId, false)
end

function M:updateNetData(newData)
    table.merge(self.m_data, newData)
end

-- 刷新单个界面
function M:refreshItemActivityData(responseData, tab_index)
    local openId = responseData.openId
    if tab_index and self.m_tab_Node[tab_index] and self.m_tab_Node[tab_index].open_id then
        openId = self.m_tab_Node[tab_index].open_id
    end
    local response = tab_index and responseData or responseData.response
    local itemData = self.m_serverDatas[openId]
    if openId == 227 then
        self:refreshEggsData(itemData, response)
    elseif openId == 228 then
        self:refreshTreeData(itemData, response)
    elseif openId == 229 then
        self:refreshShopData(itemData, response)
    elseif openId == 230 then
        self:refreshGiftRoomData(itemData, response)
    end
end

-- 礼包屋
function M:refreshGiftRoomData(itemData, response, configData)
    --buyGiftLog = buyGiftLog,
    --buySkinLog = buySkinLog,
    --itemData = itemData,
    --isShowRedDot = isShowRedDot,
    local isShowRedDot = nil
    if response.gifts ~= nil then
        --local buyGiftLog = {}
        --for strId, buyCount in pairs(response.gifts) do
        --    local id = tonumber(strId)
        --    buyGiftLog[id] = buyCount
        --end
        --itemData.buyGiftLog = buyGiftLog
        itemData.gifts = response.gifts
        isShowRedDot = self:refreshGiftRoomRedDot(response.gifts)
    end
    if response.clothes_gifts ~= nil then
        local buySkinLog = {}
        for strId, buyCount in pairs(response.clothes_gifts) do
            local id = tonumber(strId)
            buySkinLog[id] = buyCount
        end
        itemData.buySkinLog = buySkinLog
    end
    itemData.isShowRedDot = isShowRedDot == nil and itemData.isShowRedDot  or isShowRedDot
    if configData ~= nil then
        itemData.itemData = configData
    end
end

-- 灵鹿集市数据
function M:refreshShopData(itemData, response, configData)
    --exchangeData = exchangeData,
    --itemData = itemData,
    --isShowRedDot = isShowRedDot,
    local isShowRedDot = nil
    if response.exchange ~= nil then
        local exchangeData = {}
        for strId, exchangeCount in pairs(response.exchange) do
            local id = tonumber(strId)
            exchangeData[id] = exchangeCount
        end
        itemData.exchangeData = exchangeData
    end
    isShowRedDot = RedPointUtil:localRedPointJudge("linglu_shopRedDot") --self:refreshExchangeRedDot(itemData.exchangeData)
    itemData.isShowRedDot = isShowRedDot == nil and itemData.isShowRedDot or isShowRedDot
    if configData ~= nil then
        itemData.itemData = configData
    end
end

--- 许愿树数据
function M:refreshTreeData(itemData, response, configData)
    --score = response.score,
    --serverTaskData = taskData,
    --gotAwardIds = gotAwardIds,
    --itemData = itemData,
    --isShowRedDot = isShowRedDot,
    itemData.score = response.score or itemData.score
    local isShowRedDot = nil
    if response.recv_list ~= nil then
        local gotAwardIds = {}
        for i = 1, #response.recv_list do
            local awardId = response.recv_list[i]
            gotAwardIds[awardId] = awardId
        end
        itemData.gotAwardIds = gotAwardIds
    end
    if response.quests ~= nil then
        local taskData = {}
        for strId, itemData in pairs(response.quests) do
            local taskId = tonumber(strId)
            taskData[taskId] = itemData
        end
        itemData.serverTaskData = taskData
    end
    isShowRedDot = self:refreshWishingTreeRedDot(response, itemData.gotAwardIds, itemData.serverTaskData)
    itemData.isShowRedDot = isShowRedDot == nil and itemData.isShowRedDot or isShowRedDot
    if configData ~= nil then
        itemData.itemData = configData
    end
end

function M:getCurDay()
    local server_time = UserDataManager:getServerTime()
    local start_time = self.m_start_ts
    local current_day = math.floor((server_time - start_time) / (60 * 60 * 24)) + 1
    return current_day
end

function M:setCurDay(cur_day)
    self.m_cur_day = cur_day or 1
end

-- 砸蛋数据
function M:refreshEggsData(itemData, response, configData)
    --    allSmashCount = response.egg_times,
    --    daySmashCount = response.daily_egg_times, 
    --    gotAwardIds = gotAwardIds,
    --    itemData = itemData,
    --    isShowRedDot = isShowRedDot,
    itemData.allSmashCount = response.egg_times or itemData.allSmashCount
    local itemUnit = RewardUtil:getProcessRewardData(self.itemXlsxInfo)
    itemData.daySmashCount = itemUnit.user_num
    local isShowRedDot = nil
    if response.egg_recv ~= nil then
        local gotAwardIds = {}
        for i = 1, #response.egg_recv do
            local awardId = response.egg_recv[i]
            gotAwardIds[awardId] = awardId
        end
        itemData.gotAwardIds = gotAwardIds
    end
    isShowRedDot = self:refreshSmashEggRedDot(itemData.allSmashCount,itemData.daySmashCount,itemData.gotAwardIds)
    itemData.isShowRedDot = isShowRedDot == nil and itemData.isShowRedDot or isShowRedDot
    if configData ~= nil then
        itemData.itemData = configData
    end
end

function M:refreshCurSmashEggCount(openId)
    local itemUnit = RewardUtil:getProcessRewardData(self.itemXlsxInfo)
    if self.m_serverDatas[openId] ~= nil then
        self.m_serverDatas[openId].daySmashCount = itemUnit.user_num
    end
end

function M:isOpenStatusByOpenId(tab_index)
    local openId = nil
    if tab_index and self.m_tab_Node[tab_index] and self.m_tab_Node[tab_index].open_id then
        openId = self.m_tab_Node[tab_index].open_id
    end
    if not openId then
        return false
    end
    local curActivityData = self.m_activityDatas[openId]
    local curTimer = UserDataManager:getServerTime()
    return (curTimer < curActivityData.show_start_ts )
end

function M:refreshData(response)
    self.m_data = response
    self.m_activityDatas = self:getActivityData(response)
    self.m_version = response.version
    self.m_charge_num = response.charge_sum or 0
    --self.m_package_refresh_time = response.gift_end_ts
    self.m_serverDatas = {}
    if response and response.charge_actives then
        for i, v in pairs(response.charge_actives) do
            if v.open_id == 230 then
                self.m_start_ts = v.start_ts
            end
        end
    end
    self:setCurDay(self:getCurDay())
    for _, itemData in pairs(self.m_tab_Node) do
        local openId = itemData.open_id
        self.m_serverDatas[openId] = {}
        if openId == 227 then
            -- 砸金蛋
            self:refreshEggsData(self.m_serverDatas[openId], response, itemData)
        elseif openId == 228 then
            -- 许愿树
            self:refreshTreeData(self.m_serverDatas[openId], response, itemData)
        elseif openId == 229 then
            -- 灵鹿集市
            self:refreshShopData(self.m_serverDatas[openId], response, itemData)
        elseif openId == 230 then
            -- 礼包屋
            self:refreshGiftRoomData(self.m_serverDatas[openId], response, itemData)
        end
    end
end

-- 礼包屋红点
function M:refreshGiftRoomRedDot(buyGiftLog)
    local isShowRedDot = false
    local new_year_giftData = ConfigManager:getCfgByName("new_year_gift") or {}
    local versionData = new_year_giftData[self.m_version] or {}
    local dayData = versionData[self.m_cur_day]
    if dayData and buyGiftLog and buyGiftLog.data then
        for index, data in pairs(buyGiftLog.data) do
            index = tonumber(index)
            local xlsxSeatGiftDatas = dayData[index] or {}
            local cid = data.cid
            local curGiftData = xlsxSeatGiftDatas[cid]
            if curGiftData then
                if cid > 0 then
                    curGiftData = xlsxSeatGiftDatas[cid]
                    if curGiftData.price <= 0 then
                        if data.times == 0 then
                            isShowRedDot = true
                            break
                        end
                    end
                end
            end
        end
    end
    return isShowRedDot
end

-- 灵鹿集市红点
function M:refreshExchangeRedDot(exchangeData)
    local isShowRedDot = false
    local new_year_exchangeData = ConfigManager:getCfgByName("new_year_exchange")
    local versionData = new_year_exchangeData[self.m_version]
    for _, itemData in pairs(versionData) do
        local curExchangeCount = exchangeData[itemData.id] or 0
        if curExchangeCount < itemData.times then
            local isExist = false
            for _, itemData in pairs(itemData.need_reward) do
                local awardData = RewardUtil:getProcessRewardData(itemData)
                isExist = (awardData.user_num >= awardData.data_num)
                if isExist then
                    break
                end
            end
            if isExist then
                isShowRedDot = true
                break
            end
        end
    end
    return isShowRedDot
end

-- 是否显示许愿树页签
function M:setIsShowTreeTab(m_isShowTree)
    self.m_isShowTree = m_isShowTree
end

-- 许愿树红点
function M:refreshWishingTreeRedDot(response, gotAwardIds, serverTaskData)
    local openAstrictIndex = ConfigManager:getCommonValueById(610) or 0
    if (openAstrictIndex == 0) then
        local curTimer = UserDataManager:getServerTime()
        local targetTimer = ConfigManager:getCommonValueById(611) or curTimer
        if curTimer < targetTimer then
            return false
        end
    end
    local isShowRedDot = false
    for _, itemData in pairs(serverTaskData) do
        if (itemData.status == 1) then
            isShowRedDot = true
            break
        end
    end
    if not isShowRedDot then
        isShowRedDot = (response.score >= self:getWishingThreeAwardValue() and table.nums(gotAwardIds) < 7)
    end
    return isShowRedDot
end

--砸蛋红点
function M:refreshSmashEggRedDot(egg_times, daily_egg_times, gotAwardIds)
    gotAwardIds = gotAwardIds or {}
    local egg_rewardData = ConfigManager:getCfgByName("egg_reward")
    local versionData = egg_rewardData[self.m_version]
    local isShowRedDot = daily_egg_times > 0
    if not isShowRedDot then
        for i = 1, #versionData do
            local itemData = versionData[i]
            local itemSmashCount = itemData.time
            if (egg_times >= itemSmashCount) and (gotAwardIds[i] == nil) then
                isShowRedDot = true
            end
        end
    end
    return isShowRedDot
end

function M:getActivityData(response)
    local activityData = {}
    for _, itemData in pairs(response.actives) do
        activityData[itemData.open_id] = itemData
    end
    for _, itemData in pairs(response.charge_actives) do
        activityData[itemData.open_id] = itemData
    end
    return activityData
end

function M:refreshRedDotDatas()
    self.reddotData = {}
    for _, itemData in pairs(self.m_tab_Node) do
        local openId = itemData.open_id
        if openId == 204 then
            
        end
    end
end

function M:trimXlsxWishingTaskData()
    local tempData = {}
    local egg_rewardData = ConfigManager:getCfgByName("tree_quest")
    local versionData = egg_rewardData[self.m_version]
    for id, itemData in pairs(versionData) do
        if not tempData[itemData.sort] then
            tempData[itemData.sort] = {}
        end
        local sortList = tempData[itemData.sort]
        -- 1每日， 2 永久任务
        if itemData.sort == 1 then
            if not sortList[itemData.day] then
                sortList[itemData.day] = {}
            end
            table.insert(sortList[itemData.day], {
                id = id,
                xlsxData = itemData,
            })
        else
            table.insert(sortList, {
                id = id,
                xlsxData = itemData,
            })
        end
    end
    return tempData
end

-- 礼包屋皮肤数据
function M:getSkinGiftRoomData(buySkinLog)
    local tempData = {}
    local new_year_clothesData = ConfigManager:getCfgByName("new_year_clothes")
    local versionData = new_year_clothesData[self.m_version]
    for id, itemData in pairs(versionData) do
        -- 一个version一个皮肤
        tempData = {
            xlsxData = itemData,
            isGot = (buySkinLog[id] ~= nil),
        }
        break
    end
    return tempData
end

-- 灵鹿集皮肤数据
function M:getExchangeCardData(buySkinLog)
    local tempData = {}
    local new_year_exchangeData = ConfigManager:getCfgByName("new_year_exchange")
    local versionData = new_year_exchangeData[self.m_version]
    for id, itemData in pairs(versionData) do
        -- 一个version一个皮肤
        tempData = {
            xlsxData = itemData,
        }
        break
    end
    return tempData
end

-- 修改阶梯礼包数据，判断规则：限购次数，VIP等级，累计金额，章节限制，章节范围限制
function M:trimEveryDayLadderBagData(curGiftData, data, pastRechargeMoneyCount)
    local cid = data.cid
    local isCanBuy = true
    if (curGiftData.time_limit > 0) then
        isCanBuy = data.times < curGiftData.time_limit
    end
    local userDataManager = UserDataManager
    local curVipLevel = userDataManager.user_data:getUserStatusDataByKey("vip")
    if isCanBuy and (curGiftData.vip > 0) then
        isCanBuy = curVipLevel >= curGiftData.vip
    end
    if isCanBuy and (curGiftData.add_recharge > 0) then
        isCanBuy = pastRechargeMoneyCount >= curGiftData.add_recharge
    end
    local curChapterId = userDataManager:getCurStage()
    if isCanBuy and (curGiftData.stage > 0) then
        isCanBuy = curChapterId >= curGiftData.stage
    end
    if isCanBuy and curGiftData.stage_limit and #curGiftData.stage_limit > 0 then
        local chapterLimit = curGiftData.stage_limit
        isCanBuy = curChapterId >= chapterLimit[1] and curChapterId <= chapterLimit[2]
    end
    cid = isCanBuy and cid or (cid - 1)
    -- 1. 只有一层，买完后要显示已售罄
    -- 2. 只有一层，不符合条件要隐藏
    if cid <= 0 then
        cid = (data.times <= 0) and 0 or 1  --times 买没买过
    end
    return cid, isCanBuy
end

-- 礼包屋礼包数据
function M:getGiftRoomData(buyGiftLog)
    local tempData = {}
    local curVip = UserDataManager.user_data:getUserStatusDataByKey("vip") or 0
    local season_data = UserDataManager.m_season_data or {}
    local curSeason = season_data.season or 0
    local new_year_giftData = ConfigManager:getCfgByName("new_year_gift")
    local versionData = new_year_giftData[self.m_version] or {}
    local dayData = versionData[self.m_cur_day]
    if dayData and buyGiftLog and buyGiftLog.data then
        for index, data in pairs(buyGiftLog.data) do
            index = tonumber(index)
            local xlsxSeatGiftDatas = dayData[index] or {}
            local cid = data.cid
            local curGiftData = xlsxSeatGiftDatas[cid]
            if curGiftData then
                -- 限购次数，VIP等级，累计金额，章节限制，章节范围限制
                local isCanBuy = true
                cid, isCanBuy = self:trimEveryDayLadderBagData(curGiftData, data, self.m_charge_num)
                -- <=0, 表示第一个礼包，第一个礼包不符合购买需求则隐藏礼包
                if cid > 0 then
                    curGiftData = xlsxSeatGiftDatas[cid]
                    table.insert(tempData, {
                        xlsxData = curGiftData,
                        cid = data.cid,
                        buyCount = data.times,
                        isCanBuy = isCanBuy,
                        index = index,
                        isSpecialPlace = false,
                    })
                end
            end
        end
    else
        Logger.logError("new_year_gift表缺少第"..tostring(self.m_version).. "期第"..tostring(self.m_cur_day).."天的配置")
    end
    table.sort(tempData, function(itemData1, itemData2)
        return itemData1.index < itemData2.index
    end)
    
    local returnData = {}
    local showCount = 3
    --local tempData = {1,2,3,4,5}        -- 数据内容
    local count =  math.floor(#tempData / showCount) + 1
    for i=1,count do
        for index = (i - 1) * showCount + 1,(i - 1) * showCount + showCount do
            if tempData[index] then
                if not returnData[i] then
                    returnData[i] = {}
                end
                table.insert(returnData[i], tempData[index] )
            end
        end
    end
    return returnData
end

-- 灵鹿集市数据
function M:getkancilShopData(serverExchangeData)
    local tempData = {}
    local curVip = UserDataManager.user_data:getUserStatusDataByKey("vip") or 0
    local season_data = UserDataManager.m_season_data or {}
    local curSeason = season_data.season or 0
    local new_year_exchangeData = ConfigManager:getCfgByName("new_year_exchange")
    local versionData = new_year_exchangeData[self.m_version]
    for id, itemData in pairs(versionData) do
        local curExchangeCount = serverExchangeData[id] or 0
        local awardData = RewardUtil:getProcessRewardData(itemData.need_reward[1])
        if (curVip >= itemData.vip) and (curSeason >= itemData.season) then
            if (itemData.season1 < 0) or (itemData.season1 == curSeason) then
                table.insert(tempData, {
                    id = id,
                    xlsxData = itemData,
                    userNum = awardData.user_num,
                    needNum = awardData.data_num,
                    curExchangeCount = curExchangeCount,
                    allCount = itemData.times,
                })
            end
        end
    end
    table.sort(tempData, function(itemData1, itemData2)
        local sortIndex1 = (itemData1.curExchangeCount >= itemData1.allCount) and 1 or -1
        local sortIndex2 = (itemData2.curExchangeCount >= itemData2.allCount) and 1 or -1
        if sortIndex1 ~= sortIndex2 then
            return sortIndex1 < sortIndex2
        else
            return itemData1.id < itemData2.id
        end
    end)
    return tempData
end

-- 许愿树奖励数据
function M:getWishingThreeAwards()
    local tree_rewardData = ConfigManager:getCfgByName("tree_reward")
    local versionData = tree_rewardData[self.m_version]
    return versionData
end

-- 许愿树领取积分值
function M:getWishingThreeAwardValue()
    if not self.m_wishingThreeAwardValue then
        local new_yearData = ConfigManager:getCfgByName("new_year")
        local versionData = new_yearData[self.m_version]
        self.m_wishingThreeAwardValue = versionData.tree or 999
    end
    return self.m_wishingThreeAwardValue or 999
end

-- 许愿树任务列表
function M:getWishingTaskData(serverData, selectIndex, openDay)
    if not self.m_xlsxWishingTaskData then
        self.m_xlsxWishingTaskData = self:trimXlsxWishingTaskData()
    end
    local selectTypeData = self.m_xlsxWishingTaskData[selectIndex]
    local curDayTaskData = selectTypeData
    if (selectIndex == 1) then
        curDayTaskData = selectTypeData[openDay] or {}
    end
    local tempData = {}
    for _, itemData in pairs(curDayTaskData) do
        local serverTaskItemData = serverData[itemData.id] or {}
        if serverTaskItemData then
            table.insert(tempData, {
                id = itemData.id,
                xlsxData = itemData.xlsxData,
                progress = serverTaskItemData.value or 0,
                status = serverTaskItemData.status or 0,
            })
        end
    end
    table.sort(tempData, function(itemData1, itemData2)
        local sortIndex1 = (itemData1.status == 1) and -1 or itemData1.status
        local sortIndex2 = (itemData2.status == 1) and -1 or itemData2.status
        if sortIndex1 ~= sortIndex2 then
            return sortIndex1 < sortIndex2
        else
            return itemData1.id < itemData2.id
        end
    end)
    return tempData
end

--获取各个阶段结束时间
function M:getDayTimer()
    local curServerTimer = UserDataManager:getServerTime()
    local targetTimer = PushUtil:getTargetTimer(1)
    local timer = targetTimer - curServerTimer
    local day, hour, min, sec = GameUtil:getTimeLayoutBySecond(timer)
    if day > 0 then
        hour = hour + day * 24;
    end
    return string.format("%02d:%02d:%02d", hour, min, sec),timer
end

return M