---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/1 23:19
---

local M = class("SmashEggsNode", LikeOO.OOUIbase)
--砸蛋
M.m_uiName = "DoubleFestivalActivity/SmashEggsNode"
M.cacheSpineName = ""
function M:onEnter()
    self.eggAni = self:findGameObject("egg_spine")
    self.m_openId = 227
    self.m_activityData = self.m_model.m_activityDatas[self.m_openId] or {}
    self.m_isCanSmash = true
    self.m_attr_node = GameUtil:commonAttrNode(self.m_control, {item_id = self.m_model.itemXlsxInfo[2]})
    self:bindUI()
    self:refreshUI()
    self:setTextByLanKey("text_awardInfoText", "castingSword_str_0006")
end

function M:showEggIdleAniNode()
    GameUtil:updateSpineLoadSet(self.eggAni, "RoleSpine/" .. "zajindan_SkeletonData", "pose", 0, true)
end

-- 砸蛋
function M:showSmashEggAniNode(params)
    self.m_isCanSmash = false
    GameUtil:updateSpineLoadSet(self.eggAni, "RoleSpine/" .. "zajindan_SkeletonData", "break", 0, true)
    local smashEggTimer = 3.4
    self.m_control:setOnceTimer(smashEggTimer,function()
        self:showEggIdleAniNode()
        self.m_isCanSmash = true
    end)
    -- 策划需求动画结束后一秒发送协议
    self.m_control:updateMsg("showSmashEggAniEvent",{timer = (smashEggTimer - 2), params = params, msgName = "btn_smashEggsBtn"})
end

-- 晃锤子
function M:showShakeHammerAniNode()
    GameUtil:updateSpineLoadSet(self.eggAni, "RoleSpine/" .. "zajindan_SkeletonData", "idle", 0, true)
end

function M:bindUI()
    self.m_new_box_reward_slider = self:findSlider("slider")
    self:refreshActivityTimer()
    local activityXlsxData = self.m_model.m_activityXlsxData[self.m_openId] or {}
    local titleName = activityXlsxData.name_2 or ""
    self:setTextByLanKey("titleName_text", titleName)

    self:setTextByLanKey("text_oneInfo1", "doubleFestival_text_0036")
    self:setTextByLanKey("text_tenInfo1", "doubleFestival_text_0036")
    local oneIndex = 1
    local tenIndex = 10
    self:setText("text_oneInfo2", "x"..oneIndex)
    self:setText("text_tenInfo2", "x"..tenIndex)
    self:setTextByLanKey("text_one", "doubleFestival_text_0037", oneIndex)
    self:setTextByLanKey("text_ten", "doubleFestival_text_0037", tenIndex)
end

function M:refreshActivityTimer()
    local startTimer = self.m_activityData.start_ts
    local endTimer = self.m_activityData.end_ts
    local starT = TimeUtil.gmTime(startTimer)
    local endT = TimeUtil.gmTime(endTimer)
    local timerFormat = Language:getTextByKey("doubleFestival_text_0019", starT.year, starT.month, starT.day,
            endT.year, endT.month, endT.day)
    self:setText("text_timer", timerFormat)
end

function M:refreshUI()
    self.m_serverData = self.m_model.m_serverDatas[self.m_openId] or {}
    self:refreshAwardNode()
    self:setTextByLanKey("text_residueCount", "doubleFestival_text_0006", self.m_serverData.allSmashCount)
    if self.m_serverData.daySmashCount > 0 then
        self:showShakeHammerAniNode()
    else
        self:showEggIdleAniNode()
    end
end

function M:refreshAwardNode()
    local egg_rewardData = ConfigManager:getCfgByName("egg_reward")
    local awardAllData = egg_rewardData[self.m_model.m_version]
    local data = {}
    for id, itemData in pairs(awardAllData) do
        table.insert(data, {id = id, itemData = itemData})
    end
    if #data > 0 then
        table.sort(data, function(itemData1, itemData2) return itemData1.id > itemData2.id end)
    end
    if self.m_awardScroll_view == nil then
        local loopscroll = self:findGameObject("award_loopscroll")
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshAwardItem(cell_obj, cell_data,index, data)
            end,
            ui_name = self.m_uiName,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "canGotAward_btn" then
                    self:gotAwardSend(cell_data.id)
                elseif click_name == "got_btn" then
                    self:lookAward(cell_data.id, cell_object)
                elseif click_name == "box_btn" then
                    self:lookAward(cell_data.id, cell_object)
                end
            end
        }
        self.m_awardScroll_view = LoopScrollViewUtil.new(params)
        --self.m_awardScroll_view:setVerticalNormalizedPosition(0)
    else
        self.m_awardScroll_view:reloadData(data, true)
    end
    self:retreshScroll(#data)
end

--刷新滑动条位置
function M:retreshScroll(dataCount)
    if self.m_awardScroll_view ~= nil then
        local gotCount = table.nums(self.m_serverData.gotAwardIds)
        gotCount = gotCount > 0 and gotCount or 1
        local curIndex = dataCount - gotCount
        curIndex = curIndex - 1
        curIndex = curIndex <= 0 and 0 or curIndex
        self.m_awardScroll_view:moveToCellIndex(curIndex)
    end
end

function M:refreshAwardItem(cell_obj, cell_data,index, data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local index = cell_data.id
        local isFirst = index == 1
        local curValue = self.m_serverData.allSmashCount
        local gotLog = self.m_serverData.gotAwardIds
        local targetCount = cell_data.itemData.time
        local score = targetCount ~= nil and targetCount or 0
        LuaBehaviourUtil.setText(luaBehaviour, "awardCount",score)
        local isGotAward = (gotLog[index] ~= nil)
        local isCanGot = (curValue >= score) and (not isGotAward)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "canGotAward_btn", isCanGot)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "got_btn", isGotAward)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "box_btn", (not isCanGot) and (not isGotAward))
        local lastAwardValue = 0
        if not isFirst then
            local lastAwardData = data[#data - (index - 2)]
            lastAwardValue = lastAwardData.itemData.time
        end
        local allValue = (score - lastAwardValue)
        local maxSliderValue = allValue * 0.5
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "slider1", (not isFirst))
        local isLast = index == table.nums(data)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "slider2", (not isLast))
        if not isLast then
            local slider2 = luaBehaviour:FindSlider("slider2")
            local slider2AllCount = score + maxSliderValue
            local slider2StartCount = score
            if curValue > slider2StartCount and curValue <= slider2AllCount then
                local offsetValue = (curValue - slider2StartCount)
                slider2.value = offsetValue > maxSliderValue and maxSliderValue or offsetValue / maxSliderValue
            elseif curValue <= slider2StartCount then
                slider2.value = 0
            elseif curValue > slider2AllCount then
                slider2.value = 1
            end
        end
        if not isFirst then
            local slider1 = luaBehaviour:FindSlider("slider1")
            local slider1AllCount = score
            local slider1StartCount = score - maxSliderValue
            if curValue > slider1StartCount and curValue <= slider1AllCount then
                local offsetValue = (curValue - slider1StartCount)
                slider1.value = offsetValue >= maxSliderValue and maxSliderValue or offsetValue / maxSliderValue
            elseif curValue <= slider1StartCount then
                slider1.value = 0
            elseif curValue > slider1AllCount then
                slider1.value = 1
            end
        end

        local gotCount = table.nums(self.m_serverData.gotAwardIds)
        gotCount = gotCount + 1
        local isShowAward = gotCount == index
        if isShowAward then
            local awardItemNode = luaBehaviour:FindGameObject("ItemNode")
            local reward = cell_data.itemData.reward[1]
            local rewardUnit = RewardUtil:getProcessRewardData(reward)
            GameUtil:updateItemElementByData(awardItemNode, rewardUnit, true, true)
        end
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "newAwardNode", isShowAward)
        
    end
end

function M:refreshGiftBagSlider(rewardVersionData)
    local max_index = 0
    local max_num = 0
    local box_num = table.nums(rewardVersionData)
    local cur_num = self.m_serverData.allSmashCount
    for index, awardItemData in ipairs(rewardVersionData) do
        local itemXlsxData = awardItemData
        max_num = itemXlsxData.time
        max_index = index
        if max_num >= cur_num then
            break
        end
    end
    max_num = max_num > 0 and max_num or 99999
    local start_mun_data = rewardVersionData[max_index-1]
    local start_mun = start_mun_data and start_mun_data.time or 0
    local showSliderValue = math.max(0, (max_index - 1))/box_num + (cur_num - start_mun)/(max_num - start_mun)/box_num
    self.m_new_box_reward_slider.value = showSliderValue
    self:setObjectVisible("lightLine2", (showSliderValue >= 1))
end

function M:onButtonClick(obj, name)
    if name == "btn_awardInfoBtn" then
        -- 奖励预览
        audio:SendEvtUI("UI_Popup_N1")
        self:openView("DoubleFestivalActivity.SmashEggsAwardInfo", {version = self.m_model.m_version})
    elseif name == "btn_infoBtn" then
        local new_yearData = ConfigManager:getCfgByName("new_year")
        local versionData = new_yearData[self.m_model.m_version]
        local content = versionData.des
        self:openView("Pops.CommonHelpPop", { title = "lantern_text_0013", content = content })
    elseif name == "btn_one" then
        self:clickSmashEggEvent(1)
    elseif name == "btn_ten" then
        self:clickSmashEggEvent(10)
    elseif name == "gift_bag_btn" then
        self:openView("DoubleFestivalActivity.SmashEggBuyPop", {is_token= self.m_model.m_is_token,m_openId = self.m_openId, m_version = self.m_model.m_version})
    end
end

function M:clickSmashEggEvent(index)
    if not self.m_isCanSmash then
        return
    end
    if self.m_serverData.daySmashCount < index then
        GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("doubleFestival_text_0038"), delay_close = 2})
        return
    end
    audio:SendEvtUI("UI_ZJDan")
    -- 砸蛋,一天一次
    --if self.m_serverData.daySmashCount > 0 then
    --    GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("doubleFestival_text_0020"), delay_close = 2})
    --    return
    --end
    self:showSmashEggAniNode({vsn = self.m_model.m_version, openId = self.m_openId, times = index})
end

function M:gotAwardSend(index)
    audio:SendEvtUI("UI_Gold_Reward")
    self.m_control:updateMsg("btn_gotEggBoxAwardBtn", {version = self.m_model.m_version, openId = self.m_openId})
end

function M:lookAward(index, cell_obj)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local showAwardNode = luaBehaviour:FindGameObject("showAwardNode")
        if not IsNull(showAwardNode) then
            audio:SendEvtUI("UI_Gold_Reward")
            local egg_rewardData = ConfigManager:getCfgByName("egg_reward")
            local rewardVersionData = egg_rewardData[self.m_model.m_version]
            local xlsxData = rewardVersionData[index]
            local rewards = xlsxData.reward
            self:openView("Pops.LookRewardTips",{rewards = rewards, click_transform = showAwardNode.transform, show_check_mark = false})
        end
    end
end

function M:destroy()
    if self.m_attr_node then
        self.m_attr_node:destroy()
        self.m_attr_node = nil
    end
    M.super.destroy(self)
end

return M