---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/12/3 10:14
---

local M = class("WishingTaskNode", LikeOO.OOUIbase)
-- 许愿树
M.m_uiName = "DoubleFestivalActivity/WishingTaskNode"
M.cacheSpineName = ""
function M:onEnter()
    EventDispatcher:registerEvent(GlobalConfig.EVENT_KEYS.EVERY_DAY_EVENT, {self, self.everyDayRefreshEvent})
    self.treeAni = self:findGameObject("tree_spine")
    self.spine_shakeBtnAni = self:findGameObject("spine_shakeBtn")
    self.m_openId = 228
    self.m_activityData = self.m_model.m_activityDatas[self.m_openId] or {}
    self.m_isCanShake = true
    self:switchSelectIndex(1, true)
    self:bindUI()
    self:refreshUI()
    self:showAniNode()
end

function M:everyDayRefreshEvent()
    self.m_control:refreshChildView(true, false)
    self:refreshUI()
end

function M:showAniNode()
    GameUtil:updateSpineLoadSet(self.treeAni, "RoleSpine/" .. "xuyuanshu_SkeletonData", "idle", 0, true)
end

-- 摇晃树动画
function M:showShakeTreeAniNode()
    self.m_isCanShake = false
    GameUtil:updateSpineLoadSet(self.treeAni, "RoleSpine/" .. "xuyuanshu_SkeletonData", "touch", 0, true)
    self.m_control:setOnceTimer(1,function()
        self:showAniNode()
        self.m_isCanShake = true
    end)
end

function M:bindUI()
    self:refreshActivityTimer()
    self:setTextByLanKey("text_tabBtnName1", "doubleFestival_text_0012")
    self:setTextByLanKey("text_tabBtnName2", "doubleFestival_text_0013")
    self:setTextByLanKey("text_hintText", "doubleFestival_text_0023")

    local activityXlsxData = self.m_model.m_activityXlsxData[self.m_openId] or {}
    local titleName = activityXlsxData.name_2 or ""
    self:setTextByLanKey("titleName_text", titleName)
end

function M:refreshActivityTimer()
    local startTimer = self.m_activityData.start_ts
    local endTimer = self.m_activityData.end_ts
    local starT = TimeUtil.gmTime(startTimer)
    local endT = TimeUtil.gmTime(endTimer)
    local timerFormat = Language:getTextByKey("doubleFestival_text_0019", starT.year, starT.month, starT.day,
            endT.year, endT.month, endT.day)
    self:setText("text_timer", timerFormat)
end

function M:refreshThreeAwardNode()
    local allAward = self.m_model:getWishingThreeAwards()
    local gotAwardIds = self.m_serverData.gotAwardIds
    for i = 1, 7 do
        local itemObj = self:findGameObject("maxAwardNode"..i)
        local transform = itemObj.transform
        local itemData = allAward[i]
        local awardData = itemData.reward[1]
        local reward_node = UIUtil.findRectTransform(transform, "threeAwardNode"..i)
        UIUtil.destroyAllChild(reward_node)
        if awardData then
            local itemNode = GameUtil:createItemElement(awardData, true, true)
            itemNode.transform:SetParent(reward_node.transform, false)
        end
        self:setObjectVisible("lock_image"..i, gotAwardIds[i] ~= nil)
    end
    
    -- 分数
    local curScore = self.m_serverData.score
    local maxScore = self.m_model:getWishingThreeAwardValue()
    self:setTextByLanKey("text_taskValue", "doubleFestival_text_0010", curScore .. "/"..maxScore)

    local isShowShakeBtn = table.nums(self.m_serverData.gotAwardIds) < 7
    self:setObjectVisible("spine_shakeBtn", isShowShakeBtn)
    self:setObjectVisible("img_gray_shake", (not isShowShakeBtn))
    local shakeBtnText = isShowShakeBtn and "doubleFestival_text_0009" or "doubleFestival_text_0034"
    self:setTextByLanKey("text_awardInfo", shakeBtnText)
    self:setObjectVisible("text_awardInfo", true)
end

function M:refreshUI()
    self.m_serverData = self.m_model.m_serverDatas[self.m_openId] or {}
    self.m_openDay = GameUtil:getActityOpenDayCount(self.m_activityData.start_ts)
    self:refreshTab()
    self:refreshTabRedDots()
    self:refreshTaskList()
    self:refreshThreeAwardNode()
    self:refreshShakeBtnAni()
end

function M:refreshTabRedDots()
    self.m_everyDayListData = self.m_model:getWishingTaskData(self.m_serverData.serverTaskData, 1, self.m_openDay)
    self.m_allListData = self.m_model:getWishingTaskData(self.m_serverData.serverTaskData, 2, self.m_openDay)
    local everyDayRedDot = false
    for _, itemData in pairs(self.m_everyDayListData) do
        if itemData.status == 1 then
            everyDayRedDot = true
            break
        end
    end
    self:setObjectVisible("img_redDot1", everyDayRedDot)
    local allRedDot = false
    for _, itemData in pairs(self.m_allListData) do
        if itemData.status == 1 then
            allRedDot = true
            break
        end
    end
    self:setObjectVisible("img_redDot2", allRedDot)
end

function M:refreshShakeBtnAni()
    local curScore = self.m_serverData.score
    local maxScore = self.m_model:getWishingThreeAwardValue()
    local isCanGot = (curScore >= maxScore) and (table.nums(self.m_serverData.gotAwardIds) < 7)
    local aniName = (not isCanGot) and "idle1" or "idle2"
    --local sk_anim = self.spine_shakeBtnAni:GetComponent("SkeletonGraphic")
    --sk_anim.AnimationState:SetAnimation(0, aniName, true)
    GameUtil:updateSpineLoadSet(self.spine_shakeBtnAni, "RoleSpine/" .. "WishingTaskNode_SkeletonData", aniName, 0, true)
end

function M:refreshTaskList()
    -- 任务列表
    local data = (self.m_selectIndex == 1) and self.m_everyDayListData or self.m_allListData
    if self.m_taskScroll_view == nil then
        local loopscroll = self:findGameObject("task_loopscroll")
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshTaskItem(index, cell_obj, cell_data, #data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_goBtn" then
                    audio:SendEvtUI("Play_UI_NormalClick")
                    local xlsxData = cell_data.xlsxData
                    local jumpId = xlsxData.go_type
                    QuickOpenFuncUtil:openFunc(jumpId)
                    if (jumpId == 1) or (jumpId == 31) then
                        -- 前往主页, 前往挂机奖励
                        static_rootControl:closeAllViewPop()
                    else
                        self.m_control:closeView()
                    end
                elseif click_name == "btn_getBtn" then
                    local params = {version = self.m_model.m_version, quest_id = cell_data.id, openId = self.m_openId}
                    self.m_control:updateMsg("btn_wishingTaskBtn", params)
                elseif click_name == "jifen_obj" then
                    -- 点击积分弹出
                    GameUtil:lookInfoTips(self.m_control, {click_transform = click_object.transform, msg = Language:getTextByKey("tid#lingluyingchun_01")})
                end
            end
        }
        self.m_taskScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_taskScroll_view:reloadData(data, true)
    end
end

function M:refreshTaskItem(index, cell_obj, cell_data, allCount)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local transform = cell_obj.transform
        local xlsxData = cell_data.xlsxData
        local awardDatas = xlsxData.reward
        ---- 奖励
        for i = 1, 2 do
            local awardData = awardDatas[i]
            local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData then
                local itemNode = GameUtil:createItemElement(awardData, true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
        local status = cell_data.status
        -- 0: 未完成,1：已完成，2：已领取
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_getBtn", status == 1)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_gotBtnText", status == 2)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_goBtn", status == 0)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_getBtnText","doubleFestival_text_0008")
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_gotBtnText","doubleFestival_text_0022")
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_goBtnText","doubleFestival_text_0021")
        local titleName = Language:getTextByKey(xlsxData.name)
        LuaBehaviourUtil.setText(luaBehaviour, "text_taskTitle", titleName)
        LuaBehaviourUtil.setText(luaBehaviour, "reward_num_text", xlsxData.score)
        local curValue = (cell_data.progress > xlsxData.target_value) and xlsxData.target_value or cell_data.progress
        LuaBehaviourUtil.setText(luaBehaviour, "text_progress",  "("..curValue.."/".. xlsxData.target_value..")")
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "line", (index ~= allCount))
    end
end

function M:refreshTab()
    self:setObjectVisible("img_tagImg1", self.m_selectIndex == 1)
    self:setObjectVisible("img_tagImg2", self.m_selectIndex == 2)
end

function M:switchSelectIndex(index, isInit)
    self.m_selectIndex = index
    for i = 1, 2 do
        local tabName = "text_tabBtnName" .. i
        local nameColor = (self.m_selectIndex == i) and Color(113/255,47/255,30/255,1) or Color(250/255,230/255,194/255,1)
        self:setTextColor(tabName, nameColor)
    end
    if not isInit then
        audio:SendEvtUI("UI_Tab_N3")
        self:refreshUI()
    end
end

function M:onButtonClick(obj, name)
    if name == "btn_tabBtn1" then
       self:switchSelectIndex(1)
    elseif name == "btn_tabBtn2" then
        self:switchSelectIndex(2)
    elseif name == "btn_shakeBtn" then
        if not self.m_isCanShake then
            return
        end
        audio:SendEvtUI("UI_XYShu")
        local curScore = self.m_serverData.score
        local maxScore = self.m_model:getWishingThreeAwardValue()
        if curScore < maxScore then
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("doubleFestival_text_0011", maxScore), delay_close = 2})
            return
        end
        if table.nums(self.m_serverData.gotAwardIds) >= 7 then
            -- 七个奖励全部领取
            return
        end
        self:showShakeTreeAniNode()
        self.m_control:updateMsg("btn_shakeWishingBtn", {version = self.m_model.m_version, openId = self.m_openId})
    end
end

function M:destroy()
    EventDispatcher:unRegisterEvent(GlobalConfig.EVENT_KEYS.EVERY_DAY_EVENT, {self, self.everyDayRefreshEvent})
    M.super.destroy(self)
end

return M