---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 15:53
---

local M = class("PetardGiftBagNewView",LikeOO.OOPopBase)
-- 礼包界面
M.m_uiName = "PetardActivity/PetardGiftBagNew"  -- prefab name
M.m_size_type = 1
M.m_iphoneXAdapter = true

function M:onEnter()
    self.m_gray_img = self:findImage("gray_img")
    local activityXlsxData = self.m_model:getXlsxActivityByOpenId(self.m_model.m_open_id, true)
    self:setTextByLanKey("close_title_text", activityXlsxData.name)
    self:setTextByLanKey("text_timer", self.m_model:getActiveShowTime())
    RedPointUtil:saveLocalRedPointFreshTime("TongYongFanLiRedDot")
    self:refreshUI()  
end

function M:refreshUI()
    self:createLoopScroll()
    self:updateTime()
    self:setObjectVisible("skinGiftBag", self.m_model.m_hero_gift_cfg.type == 1)
    self:setObjectVisible("box_node", self.m_model.m_hero_gift_cfg.type == 2)
    if self.m_model.m_hero_gift_cfg.type == 1 then
        self:refreshLeftNode()
    elseif self.m_model.m_hero_gift_cfg.type == 2 then
        self:refreshLeftBox()
    end
end


function M:createLoopScroll()
    self.m_gift_tab = {}
    local data = self.m_model:get_ladderGiftData()
    if self.m_scroll_view == nil then
        local loopscroll = self:findGameObject("loopscroll")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self.m_gift_tab[index] = cell_obj
                self:updateCell(cell_obj, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                local cfg = cell_data.xlsxData
                if cfg.price == 0 then
                    self:updateMsg("get_free_ladder_gift", { id = cfg.id} )
                else
                    self:updateMsg("buy", cell_data.xlsxData.charge_id)
                end
            end
        }
        self.m_scroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_scroll_view:reloadData(data, true)
    end
end

function M:updateCell(itemObj, data)
    if IsNull(itemObj) then
        return
    end
    local luaBehaviour = UIUtil.findLuaBehaviour(itemObj)
    if not luaBehaviour then
        return
    end
    -- 奖励
    local transform = itemObj.transform
    local giftData = data
    if not giftData then
        return
    end
    local xlsxData = giftData.xlsxData
    local awardData = {}
    table.insert(awardData, xlsxData.return_money[1])
    for k,v in ipairs(xlsxData.reward) do
        table.insert(awardData, v)
    end
    local reward_node = luaBehaviour:FindGameObject("awardNode")
    UIUtil.destroyAllChild(reward_node.transform)
    for k,v in ipairs(awardData) do
        local itemNode = GameUtil:createItemElement(v, true, true)
        itemNode.transform:SetParent(reward_node.transform, false)
    end
    
    -- 按钮
    local btn_buyBtn = luaBehaviour:FindGameObject("btn_buyBtn")
    UIUtil.setButtonClick(
            btn_buyBtn.transform,
            function()
                if giftData.isCanBuy == true then
                    self.m_control:buyForSDK(xlsxData.charge_id)
                end
            end
    )
    LuaBehaviourUtil.setImg(luaBehaviour, "btn_awardBtn", xlsxData.background, "item_icon")

    -- LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_itemHint", "petard_text_0020", xlsxData.return_per)   
    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_itemTitle", xlsxData.gift_name..xlsxData.return_moneyper)    
    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_astrictCount", "petard_text_0021", (xlsxData.time_limit-giftData.buyCount))
    local isCanBuy = (xlsxData.time_limit > 0)
    local priceFormat = (not isCanBuy) and Language:getTextByKey("petard_text_0018") or Language:getTextByKey("petard_text_0011",xlsxData.price)
    LuaBehaviourUtil.setText(luaBehaviour, "text_buyText",priceFormat)
    local btn_buyBtnImg = luaBehaviour:FindImage("btn_buyBtn")
    if not giftData.isCanBuy then
        btn_buyBtnImg.material = self.m_gray_img.material
    else
        btn_buyBtnImg.material = nil
    end
   
end




 ---- 皮肤礼包刷新
function M:refreshLeftNode()
    -- 价格
    local xlsxData = self.m_model.m_hero_gift_cfg
    local isBuy = self.m_model:checkClothGift() == 1
    self:setText("text_discountText", xlsxData.return_per)
    self:setTextByLanKey("text_originalMoney", "petard_text_0024", xlsxData.price_old)
    
    local btn_buySkinBtn = self:findImage("btn_buySkinBtn")
    if self.m_model:checkClothGift() == 1 then
        btn_buySkinBtn.material = self.m_gray_img.material
        self:setTextByLanKey("text_buySkinText", "gf_str_0048")
    else
        btn_buySkinBtn.material = nil
        self:setTextByLanKey("text_buySkinText", "new_str_0789", tostring(self.m_model.m_hero_gift_cfg.price_new) )
    end
   
    local reward = xlsxData.reward
    local reward_data = RewardUtil:getProcessRewardData(reward[1])
    if reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT then
        local cfg = UserDataManager.hero_data:getHeroConfigByCid(reward_data.data_id)
        if cfg then
            local icon = cfg.hero_spine
            if self.cacheSpineName == icon then
                return
            else
                self.cacheSpineName = icon
            end
        end
    elseif reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
        local cur_skin_cfg = ConfigManager:getHeroSkinCfg(reward_data.data_id)
        local icon = cur_skin_cfg.hero_spine
        if self.cacheSpineName == icon then
            return
        else
            self.cacheSpineName = icon
        end
    end
    if self.cacheSpineName then
        local play_img = self:findGameObject("hero_spine")
        GameUtil:updateSpineLoadSet(play_img, "RoleSpine/" .. self.cacheSpineName, "idle", 0, true)
    end

    -- 设置名字
    local heroId = reward_data.item_cfg.hero
    if heroId == nil then
        heroId = reward_data.data_id
    end
    local m_hero_cfg = UserDataManager.hero_data:getHeroConfigByCid(heroId)
    local m_shin_data_cfg = UserDataManager.hero_data:getHeroCurSkinCfgByData({skin = reward_data.data_id}, m_hero_cfg)
    local frame_data = GlobalConfig.QUALITY_FRAME[m_hero_cfg.max_evo]
    self:setImg(GameUtil:get_lineframename(m_hero_cfg.Ex_hero,m_hero_cfg.max_evo), "common_ui","hero_evo")
    local race = GlobalConfig.TYPE_HERO_RACE[m_hero_cfg.race].big_race_icon
    self:setImg(race,  ResourceUtil:getLanAtlas(), "hero_race")
    local class_str = Language:getTextByKey(m_hero_cfg.class)
    local name_str = Language:getTextByKey(m_shin_data_cfg.name)
    if m_shin_data_cfg.name == nil then
        name_str = Language:getTextByKey(m_hero_cfg.name)
    end
    self:setTextByLanKey("hero_name", class_str)
    self:setTextByLanKey("hero_name2", name_str)
    self:setObjectVisible("hero_name_con", true)
    local btn_heroSkinBtn = self:findGameObject("btn_heroSkinBtn")
    UIUtil.setButtonClick(
            btn_heroSkinBtn.transform,
            function()
                if reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT then
                    static_rootControl:openView("Pops.HeroLookInfo", {hero_id = heroId, is_new = false})
                elseif reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
                    static_rootControl:openView("Pops.HeroSkinLookInfo", {is_new = false, skin_id = reward_data.data_id})
                end
            end
    )
end

 ---- 宝箱礼包刷新
function M:refreshLeftBox()
    local item_content = self:findGameObject("item_content")
    UIUtil.destroyAllChild(item_content.transform)
    for k,v in pairs(self.m_model.m_hero_gift_cfg.reward or {}) do
        local itemNode,ui_element = GameUtil:createItemElement(v,true,true)
        itemNode.transform:SetParent(item_content.transform, false)
        UIUtil.setScale(itemNode.transform, 0.8,0.8)
        ui_element.duigoudi_img:SetActive(self.m_model:checkClothGift() == 1)
    end
    self:setTextByLanKey("text_originalMoney", "petard_text_0024", self.m_model.m_hero_gift_cfg.price_old)
    self:setTextByLanKey("box_discountText", self.m_model.m_hero_gift_cfg.return_per)
    local btn_buyBoxBtn = self:findImage("btn_buyBoxBtn")
    if self.m_model:checkClothGift() == 1 then
        btn_buyBoxBtn.material = self.m_gray_img.material
        self:setTextByLanKey("text_buyboxText", "gf_str_0048")
    else
        btn_buyBoxBtn.material = nil
        self:setTextByLanKey("text_buyboxText", "new_str_0789",self.m_model.m_hero_gift_cfg.price_new)
    end
end


function M:updateTime()
    local end_ts = self.m_model:getEndTs()
    local down_time = end_ts - UserDataManager:getServerTime()
    if down_time >= 0 then
        local text = Language:getTextByKey("petard_text_0023", GameUtil:formatTimeBySecond(down_time, 999))
        self:setTextByLanKey("text_giftTime", text)
    elseif down_time == 0 then
        self:updateMsg("refresh_data")
    end
end

function M:destroy()
    self.m_control:updateMsg("everyDayrefresh", nil, "FlowerFestival.FlowerMain")
    M.super.destroy(self)
end


return M


