---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/28 20:23
---

local M = class("TreasureQuestPopControl", LikeOO.OOControlBase)

function M:onEnter()

end

function M:onHandle(msg, data)
    if msg == 99999 then -- 关闭
        self:closeView()
    elseif msg == "get_reward_btn" then
        local task_cfg = self.m_model:getTreasureQuestCfg()
        local go_type = task_cfg.go_type 
        local jump = ConfigManager:getCfgByName("jump")
        local jump_item = jump[go_type[1]]
        local open_condition_id = jump_item.open_condition_id or 0
        local open_flag, tips_str = BtnOpenUtil:isBtnOpen(open_condition_id)
        if open_flag == true then
            static_rootControl:closeAllViewPop()
            QuickOpenFuncUtil:openFunc(go_type)
        else
            GameUtil:lookInfoTips(self, { msg = tips_str, delay_close = 2})
        end
    end
end

return M
