---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/28 20:26
---

local M = class("TreasureQuestPopModel", LikeOO.OODataBase)

M.point = {}

function M:onCreate()
    self.m_transfer = "scale"
    self:getData()
end

function M:onEnter()
    self.m_index = self.m_params.id or 1
    self.m_task_data = self.m_params.data
end

--藏宝图任务配置
function M:getTreasureQuestCfg()
    local treasure_tab = ConfigManager:getCfgByName("treasure_quest")
    return treasure_tab[self.m_task_data.version or 1][self.m_index]
end

--藏宝图任务数据
function M:getTreasureQuestData()
    local treasure_data = self.m_task_data.quests[tostring(self.m_index)]
    return treasure_data
end

return M