---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/12/13 19:22
---

--奇门遁甲
---@class QiMenDunJiaScene_View : Scene_View @
---@field super Scene_View @Scene_View
local M = class("QiMenDunJiaScene_View",Battle.Scene_View)

function M:init(model)
    M.super.init(self,model)
end

function M:getCurSceneObjName()
    return "qimendunjiascene_data"
end

--进入场景
function M:enter( data )
    M.super.enter(self, data)
end

function M:sceneLoadFinish()

end

--奇门遁甲场景
function M:getCurSceneName()
    self:createSceneConfig(1001) 
    --return self.scene_info.resource;
    return "qimendunjia";                   -------------------------------------------------------------------------------- 测试代码，
end


return M