---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/19 16:29
---
local M = class("CastingSwordMainModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self.open_id = self.m_params.open_id
    self.m_response = self.m_params.response
    self.m_score = self.m_params.response.score
    self.m_version = self.m_params.response.version
    --
    local score_vsn = self.m_params.response.item_score_vsn
    local item_score_base_cfg = ConfigManager:getCfgByName("item_score_base")
    local cfg = item_score_base_cfg[score_vsn]
    local active_ids = cfg.active_ids
    self.m_items = {{active_id = -1, open_id = -1,btn_name = "item_1_btn",btn_txt_name = "item_1_btn_text",item_value = ""},
                    {active_id = -1, open_id = -1,btn_name = "item_2_btn",btn_txt_name = "item_2_btn_text",item_value = ""},
                    {active_id = -1,open_id = -1, btn_name = "item_3_btn",btn_txt_name = "item_3_btn_text",item_value = ""},
                    {active_id = -1, open_id = -1,btn_name = "item_4_btn",btn_txt_name = "item_4_btn_text",item_value = ""},}
    for k, v in pairs(active_ids) do
        local item = self:getActiveData(v)
        if item ~= nil then
            self.m_items[k].active_id = v
            self.m_items[k].open_id = item.open_id
            self.m_items[k].item_value = item.name
        end
    end

    self:setAllAwardsData()
    self:setAwardState()    -- self.m_curAwardIndex
    self:getData()
end

function M:onEnter()
    
end

function M:refreshData(response)
    self.open_id = response.open_id
    self.m_response = response
    self.m_score = response.score
    self:setAwardState()    -- self.m_curAwardIndex
end

function M:setSelectTabIndex(index)
    self.selectTabIndex = index
end

function M:setAllAwardsData()
    local sword_questData = ConfigManager:getCfgByName("sword_reward")
    local versionRankAwardData = sword_questData[self.m_version] or {}
    self.m_allAwardsData = {}
    for id, itemData in ipairs(versionRankAwardData) do
        self.m_allAwardsData[id] = {
            xlsxData = itemData,
            id = id,
        }

    end
end

function M:setPersonAwardsData()
    local sword_questData = ConfigManager:getCfgByName("sword_person_reward")
    local versionRankAwardData = sword_questData[self.m_version] or {}
    self.m_allPersonAwardsData = {}
    for id, itemData in ipairs(versionRankAwardData) do
        self.m_allPersonAwardsData[id] = {
            xlsxData = itemData,
            id = id,
        }

    end
end

function M:setAwardState()
    self.m_curAwardIndex = 1
    for id, itemData in ipairs(self.m_allAwardsData) do
        if self.m_score >= itemData.xlsxData.score then
            self.m_curAwardIndex = id + 1
        end
    end
    self.m_curAwardIndex = self.m_curAwardIndex > 4 and 4 or self.m_curAwardIndex
end

-- 获取任务数据
function M:getTaskData()
    -- 整理数据，显示今日任务，然后是所有任务，注意要给标题留数据(isTitle, isCurDay)
    return {}
end

--获取活动数据
function M:getActiveData(active_id)
    local id = self.active_id
    if active_id then
        id = active_id
    end
    local active_tab = ConfigManager:getCfgByName("active")
    if active_tab[id] ~= nil then
        return active_tab[id]
    end
    local active_recharge_tab = ConfigManager:getCfgByName("active_recharge")
    if active_recharge_tab[id] ~= nil then
        return active_recharge_tab[id]
    end
    return nil
end

function M:getItem(btn_name)
    for k, v in pairs(self.m_items) do
        if btn_name == v.btn_name then
            return v
        end
    end
    return nil
end

return M