---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/19 16:28
---

local M = class("CastingSwordMainView",LikeOO.OOPopBase)

M.m_uiName = "CastingSwordMeeting/CastingSwordMain"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

--- 
local __TAB_BTN_NODE = {            --- 顺序不能乱
    {open_id = 204,redDotIndex = 1, net_url = "sword_quest_index", lua_name = "CastingSwordMeeting.CastingSwordTask"}, -- 全民铸剑
    {open_id = 411,redDotIndex = 2, net_url = "sign_daily_index", lua_name = "UI.GiftBag.GifBagDailyNode"}, -- 江湖召集
    {open_id = 314,redDotIndex = 3, net_url = "active_hero_gather_index", lua_name = "UI.GiftBag.GifBagHeroCadeNode"}, -- 明星好礼
    {open_id = 451,redDotIndex = 4}, -- 江湖大事件
    {open_id = 331,redDotIndex = 5}, -- 决战光明顶
}

local JianInfo = {
    {animName = "CastingSwordTask_jian01-02", eftName = "eft1", jianName = "jian_01"},
    {animName = "CastingSwordTask_jian01-02", eftName = "eft2", jianName = "jian_02"},
    {animName = "CastingSwordTask_jian02-03", eftName = "eft3", jianName = "jian_03"},
    {animName = "CastingSwordTask_jian03-04", eftName = "eft4", jianName = "jian_04"},
}

function M:onEnter()
    self.jianInfo = JianInfo
    EventDispatcher:registerEvent(GlobalConfig.EVENT_KEYS.CLOSE_VIEW, {self, self.addHandler})
    self.tab_Node = __TAB_BTN_NODE
    self:bindUI()
    self:refreshJianEft()
    self:playSceneAnim()
    self:setBgScale()
    --
    local items = self.m_model.m_items
    for k, v in pairs(items) do
        if v.active_id > 0 then
            self:setObjectVisible(v.btn_name,true)
            self:setTextByLanKey(v.btn_txt_name, v.item_value)
        else
            self:setObjectVisible(v.btn_name,false)
        end
    end
end

function M:setBgScale()
    local screen_width = U3DUtil:Screen_Width()
    if screen_width >= 1920 then
        local bgObj = self:findGameObject("bg_spine")
        local rect = bgObj:GetComponent("RectTransform")
        rect.localScale = Vector3(1.12,1.12,1.12);
    end
end

function M:playSceneAnim()
    --[[
    local anim = self.m_ui_obj:GetComponent("Animator")
    --不置空播放相同片段会出现不播放情况
    anim:PlayInFixedTime(nil)
    --local animName = isEnter and "CastingSword_bg_1" or "CastingSword_bg_2"
    --anim:CrossFade(animName, 0)
    anim:PlayInFixedTime("CastingSword_bg_1")
    anim.enabled = true
    self:playTabAnim(true)
   ]]--
end

function M:playTabAnim(isEnter)
    --[[
    local tabParentObj = self:findGameObject("content_node")
    local tabAnim = tabParentObj:GetComponent("Animator")
    tabAnim:PlayInFixedTime(nil)
    local tabAnimName = isEnter and "CastingSwordMain_content_node_enter" or "CastingSwordMain_content_node_exit"
    tabAnim:PlayInFixedTime(tabAnimName)
    ]]--
end

function M:addHandler(event, data)
    if data.name == "Loading.SmallLoading" then
        return
    end
    self:playSceneAnim()
    self:refreshAllRedDot()
    self.m_model:getNetData("sword_quest_index", {openType = 1}, function(response)
        if response then
            if response["end"] == 1 then
                GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
                self.m_control:closeView()
                return
            end
            self.m_model:refreshData(response)
            self:refreshJianEft()
        end
    end, nil, nil, nil)
end

function M:bindUI()
    --castingSword_str_0043 = "神兵再临",
    --castingSword_str_0042 = "决战光明顶",
    --castingSword_str_0041 = "江湖大事记",
    --castingSword_str_0040 = "明星好礼",
    --castingSword_str_0039 = "江湖召集",
    --castingSword_str_0038 = "全民铸剑",
    self:setTextByLanKey("close_title_text", UserDataManager.m_activity_name)
    --self:setTextByLanKey("close_title_text", "castingSword_str_0043")
    self:setTextByLanKey("text_taskBtnText", "castingSword_str_0038")
    self:setTextByLanKey("text_shareBtnText", "castingSword_str_0039")
    self:setTextByLanKey("text_spokesmanBtnText", "castingSword_str_0040")
    self:setTextByLanKey("text_eventBtnText", "castingSword_str_0041")
    self:setTextByLanKey("text_battleBtnText", "castingSword_str_0042")

    -- 按照渠道判断是否显示直播按钮
    local applicationId = SDKUtil.sdk_params.applicationId
    local sinatvChannelData = ConfigManager:getCfgByName("channel_id")
    local isShowBtn_207 = false
    local isShowBtn_208 = false
    for channel, itemData in pairs(sinatvChannelData) do
        -- channel策划填的是包名，没改名字
        if channel == applicationId then
            isShowBtn_207 = (itemData.status1 == 1)
            isShowBtn_208 = (itemData.status == 1)
            break
        end
    end
    
    local curTimer = UserDataManager:getServerTime()
    for _, itemData in pairs(self.tab_Node) do
        local btnObj = self:findGameObject("btn_openBtn"..itemData.redDotIndex)
        if not IsNull(btnObj) then
            local openId = itemData.open_id
            local activityData = UserDataManager:getActivesDataByOpenId(openId)
            local isShowBtn = false
            if activityData then
                isShowBtn = curTimer >= activityData.start_ts and  curTimer < activityData.end_ts
                if isShowBtn then
                    if (openId == 207) then
                        isShowBtn = isShowBtn_207
                    elseif (openId == 208) then
                        isShowBtn = isShowBtn_208
                    end
                end
            end
            btnObj:SetActive(isShowBtn)
        end
    end
    self:refreshAllRedDot()
end

function M:refreshAllRedDot()
    for _, itemData in pairs(self.tab_Node) do
        if itemData.redDotIndex and itemData.open_id then
            local red_bl = RedPointUtil:isFuncRedPointById(itemData.open_id)
            local red_point_img = self:findGameObject("red_point"..itemData.redDotIndex)
            red_point_img:SetActive(red_bl == true)
        end
    end
end

-- isJumpState是否调到下个形态
function M:refreshJianEft()
    --[[
    local curIndex = self.m_model.m_curAwardIndex
    local curJianInfo = self.jianInfo[curIndex]
    local jianObj = self:findGameObject("CastingSword_jian")
    local anim = jianObj:GetComponent("Animator")
    anim.enabled = false
    for index = 1, 4 do
        local jianInfo = self.jianInfo[index]
        local jianNode = self:findGameObject(jianInfo.jianName)
        jianNode:SetActive(curIndex == index)
    end
    --anim:CrossFade(curJianInfo.animName, 0)
    jianObj:SetActive(true)
    --self.m_control:setOnceTimer(0.9,function()
    --    anim.enabled = false
    --end)
    local jianEft = self:findGameObject(curJianInfo.eftName)
    self.m_control:setOnceTimer(9/30,function()
        jianEft:SetActive(true)
    end)
    ]]--
end

function M:destroy()
    EventDispatcher:unRegisterEvent(GlobalConfig.EVENT_KEYS.CLOSE_VIEW, {self, self.addHandler})
    M.super.destroy(self)
end

return M