---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wt.
--- DateTime: 2021/2/24 15:55
---
--模式1
---@class SceneGuideMode3_Model : GuideModeBase_Model @
---@field super GuideModeBase_Model @GuideModeBase_Model
local M = class("SceneGuideMode3_Model",Battle.GuideModeBase_Model)

--模式1
--
function M:init( scene, mode )
    M.super.init(self, scene, mode )
    
    --挂机战斗总每波怪最大数量
    self.maxMonsterNum = 1
    --当前的怪物数量
    self.curMonsterNum = 0
    self.curMonsterIndex = 0;
    self:set_dir( FixVector3.right() );
    --当前等待时间
    self.waitHitEnemyTime = GlobalTools.base6;
    self.curWaitHitEnemyTime = 0;
    --当前场景中存在的最大怪物数量
    self.curSceneLiveMonsterNum = 1;
    self.fristTime = true;
    --开始先不创建敌人
    self.checkEnemy = false;
    --移动速度
    self.curSpeed = GlobalTools.base6;
    --敌人死完了，需要等待时间
    self.waitTime = GlobalTools.base0_1;
    --移动结束时间
    self.curWaitTime =  self.waitTime;
    --显示奖励时间
    self.showRewardTime = GlobalTools.base0_2
    self.cur_showRewardTime = 0;
    --起始位置
    -- -46.45
    -- -4.4
    self.startPosition.x = -47564;
    self.startPosition.y = 0;
    self.startPosition.z = -4505;
    
    --设定位置
    self:setPos( self.startPosition );
    self.canStartFlag = true
    self:resetPlayerPosition();
    
    self.deadTime = GlobalTools.base0_5;
    self.deadCurTime = self.deadTime;

    self.chaseCount = 0
end

--设定位置前,子类重写
function M:setPositionBefore( pos )
    self.maxLength = GlobalTools.base480;
    self.triggerDis = GlobalTools.base13
    --每隔5秒创建一波敌人
    self.createEnemyTime = GlobalTools.base3;
    --当前创建敌人的时间
    self.curCreateEnemyTime = self.createEnemyTime;
end

--检测主人 的位置
function M:checkMainPlayerPosition()
    --我和要追的点的距离
    --人物拉回原地
    if self.scene.mainPlayer ~= nil then
        local pos = self.scene.mainPlayer.position;
        if pos.x >= self.maxLength then
            --重新设定所有玩家的位置
            self:resetPlayerPosition();
            --guide拉回原地
            self:reset()
        end
    end
end


--重置
function M:reset()
    self:setPos( self.startPosition )
end


--重新设置玩家位置
function M:resetPlayerPosition()
    local players = self.scene.plyMgr:getPlayers(1);
    --别的英雄重新排位
    for i = 1, players.Count do
        local player = players:get(i-1)
        --第一个近战攻击
        local pos = self.scene:findSpawnPosition(1, player:get_index())
        player:setPos(pos)
    end
end

--移动模式
function M:moveMode(dt)
    self:checkMainPlayerPosition();

    --self:old_move(dt);
    self:new_move(dt);
end

function M:new_move(dt)
    --向导移动
    if self.canStartFlag == false then
        local forward = self:get_dir();
        local forward_speed = forward * self.curSpeed
        local outPos = forward_speed * dt
        self:setPos( self.position + outPos )
    end
    
    --开始检测敌人 
    if self.checkEnemy then
        --死亡时间
        if self.deadCurTime <= 0 then
            if self.chaseCount > 0 then
                local random_x =  GlobalTools.base10
                local random_z = 0;
                local monster_data = self.monster_list:get(self.curMonsterIndex-1)
                self:enemyCreateRandom(random_x, random_z, monster_data, GlobalTools.base0_1)
                self.curMonsterIndex = self.curMonsterIndex + 1;
                if self.curMonsterIndex > self.monster_list.Count then
                    self.curMonsterIndex = 1;
                end
                self.deadCurTime = self.deadTime;
                self.chaseCount = self.chaseCount - 1;
            else
                --当前等待时间
                if self.curWaitTime > 0 then
                    self.curWaitTime = self.curWaitTime - dt;
                    if self.curWaitTime <= 0 then
                        if self.canStartFlag == false then
                            self.canStartFlag = true
                            self.cur_showRewardTime = self.showRewardTime;
                        end
                        self.curWaitTime = 0;
                    end
                end
                
                --显示奖励时间
                if self.cur_showRewardTime > 0 then
                    self.cur_showRewardTime = self.cur_showRewardTime - dt;
                    if self.cur_showRewardTime <= 0 then
                        self.checkEnemy = false
                        EventDispatcher:dipatchEvent("voyage_show_reward_event")
                        self.scene.mainPlayer.moveEffect:SetActive(false);
                        self.cur_showRewardTime = 0;
                    end
                end
            end
        else
            self.deadCurTime = self.deadCurTime - dt;
        end
    end
end

function M:startGoto(chase_count)
    if self.canStartFlag then
        local ply_speed = nil
        if chase_count > 1 then
            self.curSpeed = GlobalTools.base15
            self.waitTime = GlobalTools.base0_1;
            ply_speed = GlobalTools.base15
        else
            self.curSpeed = GlobalTools.base8
            self.waitTime = GlobalTools.base0_3;
            ply_speed = GlobalTools.base6
        end
        
        self.scene.mainPlayer.data:set_moveSpeed( ply_speed );
        self.scene.mainPlayer.moveEffect:SetActive(true);
        
        self.curWaitHitEnemyTime = self.waitHitEnemyTime;
        self.cur_showRewardTime = 0;
        --当前的怪物数量
        self.chaseCount = chase_count;
        self.curMonsterNum = 1
        self.curMonsterIndex = 1
        self.checkEnemy = true;
        self.fristTime = true;
        self.curWaitTime = self.waitTime;
        self.canStartFlag = false
    end
end

function M:getCanStartFlag()
    return self.canStartFlag
end

return M