---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wt.
--- DateTime: 2021/2/24 15:55
---
--模式2
local SceneGuideMode1_Model = require("Battle.Sce.Guide.SceneGuideMode1_Model")
---@class SceneGuideMode2_Model : SceneGuideMode1_Model @
---@field super SceneGuideMode1_Model @SceneGuideMode1_Model
local M = class("SceneGuideMode2_Model",SceneGuideMode1_Model)

function M:init( scene, mode )
    M.super.init(self, scene, mode )
    --当前等待时间
    self.waitHitEnemyTime = GlobalTools.base1;
    self.curWaitHitEnemyTime = self.waitHitEnemyTime;
    --敌人死完了，需要等待时间
    self.waitTime = GlobalTools.base1;
    self.curWaitTime =  self.waitTime;
end

--移动模式
function M:moveMode(dt)
    self:checkMainPlayerPosition();
    --向导移动
    if self.curWaitHitEnemyTime > 0 then
        self.curWaitHitEnemyTime = self.curWaitHitEnemyTime - dt;
        --local forward = self:get_dir();
        --local forward_speed = forward * self.curSpeed
        --local outPos = forward_speed * dt
        --self:setPos( self.position + outPos )
        if self.curWaitHitEnemyTime <= 0 then
            self.curWaitHitEnemyTime = 0;
            self.checkEnemy = true;
            SelectTargetTool:clear();
        end
    end

    --开始检测敌人 
    if self.checkEnemy then
        local enemys = self.scene.plyMgr:getPlayers(-1)
        if self.curMonsterNum > 0 then
            if enemys.Count < self.curSceneLiveMonsterNum then
                local random_x = 0
                if self.dir > 0 then
                    random_x = -GlobalTools.base10;
                    self.dir = -1
                else
                    random_x = GlobalTools.base10;
                    self.dir = 1
                end
                local random_z = GlobalTools:ToFix( math.random(-5, 5) )
                local monster_data = self.monster_list:get(self.curMonsterIndex-1)
                if self.fristTime then
                    random_x = GlobalTools.base10;
                end
                self:enemyCreateRandom(random_x, random_z, monster_data )
                self.curMonsterIndex = self.curMonsterIndex + 1;
                if self.curMonsterIndex > self.monster_list.Count then
                    self.curMonsterIndex = 1;
                end
                self.curMonsterNum = self.curMonsterNum - 1;
            else
                if self.fristTime then
                    self.fristTime = false;
                end
            end
        else
            if enemys.Count <= 0 then
                if self.curWaitTime > GlobalTools.base0 then
                    self.curWaitTime = self.curWaitTime - dt;
                    if self.curWaitTime <= GlobalTools.base0 then
                        self.curWaitHitEnemyTime = self.waitHitEnemyTime;
                        --当前的怪物数量
                        self.curMonsterNum = self.maxMonsterNum;
                        self.curMonsterIndex = 1
                        self.checkEnemy = true;
                        self.fristTime = false;
                        self.curWaitTime =  self.waitTime;
                    end
                end
            end
        end
    end
end


return M