---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 16:45
---

local M = class("FlowerAllRankControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_awardInfoBtn" then
        ---- 奖励详情，可领取
        self:openView("PetardActivity.PetardTaskInfo",{
            m_scoreTaskData = self.m_model.m_scoreTaskData,
            m_version = self.m_model.m_version,
            titleName = self.m_model.m_xlsxActivity.name,
        })
    elseif msg == "explain_btn" then
        -- 提示  
        local flowerData = ConfigManager:getCfgByName("flower_festival")
        local versionData = flowerData[self.m_model.m_version]
        local mainActiveData = self.m_model:getXlsxActivityByOpenId(self.m_model.m_openId, false)
        self:openView("Pops.CommonHelpPop", { title = Language:getTextByKey(mainActiveData.name), content = Language:getTextByKey(versionData.flower_des) })
    elseif msg == "btn_getBtn" then
        self.m_model:getNetData("double_twelve_receive_quest", data, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                RewardUtil:rewardTipsByData(response.reward)
                EventDispatcher:dipatchEvent("forceRefresh_petardInfoData")
                self.m_view:refreshUI()
            end
        end, nil, nil, nil)
    elseif msg == "rank_reward_btn" then
        self:openView("FlowerFestival.FlowerServerRankReward", {version = self.m_model.m_version})
    elseif msg == "refresh_flowerEvent" then
        self.m_model:getNetData("flower_index", {vsn = self.m_model.m_version, start = 1, stop = 10}, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                self.m_model:refreshRankData(response)
                self.m_view:refreshUI()
            end
        end, nil, nil, nil)
    elseif msg == "btn_myTab" then
        self.m_model:setSelectIndex(1)
        self.m_view:switchTabView()
    elseif msg == "btn_myTeamTab" then
        self.m_model:setSelectIndex(2)
        self.m_view:switchTabView()
    end
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView("PetardActivity.PetardMain")
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M
