---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 16:09
---

local M = class("FlowerAllRankModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self.m_version = self.m_params.version or 1
    self.m_openId = self.m_params.openId or 291
    self.m_selectTabIndex = 1
    self:getData("flower_index", {vsn = self.m_version, start = 1, stop = 10})
end

function M:setSelectIndex(index)
    self.m_selectTabIndex = index
end

function M:onEnter()
    self:refreshRankData(self.m_data)
end

function M:refreshRankData(m_data)
    local personData = m_data.person
    local guildData = m_data.guild
    self.roleRankData = personData.ranks
    self.roleRankCount = personData.count
    if self.roleRankCount > 0 and table.nums(self.roleRankData) > 0 then
        table.sort(self.roleRankData, function(itemData1, itemData2) return itemData1.rank < itemData2.rank end)
    end
    self.teamRankData = guildData.ranks
    self.teamRankCount = guildData.count
    if self.teamRankCount > 0 and table.nums(self.teamRankData) > 0 then
        table.sort(self.teamRankData, function(itemData1, itemData2) return itemData1.rank < itemData2.rank end)
    end
    
    self.myInfoData = {
        rank = personData.rank,
        score = personData.score,
    }
    self.myTeamData = {
        rank = guildData.rank,
        score = guildData.score,
        flag = guildData.flag,
    }
end

function M:getXlsxActivityByOpenId(openId, isRechargeActivity)
    local xlsxName = isRechargeActivity and "active_recharge" or "active"
    local active = ConfigManager:getCfgByName(xlsxName)
    for _,itemData in pairs(active) do
        if (itemData.version == self.m_version) and (openId == itemData.open_id) then
            return itemData
        end
    end
    return nil
end

return M