---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:24
---


local M = class("CommonTipsPopControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        if self.m_model.m_close_callback then
            self.m_model.m_close_callback()
        end
        self:closeView()
    elseif msg == "btn_ok" then
        if self.m_model.m_right_callback then
            self.m_model.m_right_callback()
        end
        if self.m_model.is_hint and self.m_model.m_noPopHint then
            RedPointUtil:saveLocalRedPointFreshTime(self.m_model.m_hint_key)
        end
        self:closeView()
    elseif msg == "btn_cancel" then
        if self.m_model.m_left_callback then
            self.m_model.m_left_callback()
        end
        self:closeView()
    elseif msg == "btn_duiGouBtn" then
        if self.m_model.is_hint then --需要今日提示
            self.m_model:switchNoPopHint()
            self.m_view:refreshUI()
        end
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M