---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---
local TYPE_PARAMAS = {
    left_name = "new_str_0007", --取消
    right_name = "new_str_0006", --确认
    title_text = "new_str_0005", --温馨提示
    is_hint = false, --是否显示今日提示
    hint_key = "common_tips_pop_1", -- is_hint == true  生效
    hint_text = "new_str_0910", -- 今日不在提示
    tips_text = "",
    left_callback = nil,
    right_callback = nil,
    close_callback = nil,
}

local M = class("CommonTipsPopModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:getData()
end

function M:refreshData()
    self.m_left_name = self.m_params.left_name or TYPE_PARAMAS.left_name
    self.m_right_name = self.m_params.right_name or TYPE_PARAMAS.right_name
    self.m_title_text = self.m_params.title_text or TYPE_PARAMAS.title_text
    self.is_hint = self.m_params.is_hint or TYPE_PARAMAS.is_hint
    self.m_hint_key = self.m_params.hint_key or TYPE_PARAMAS.hint_key
    self.m_hint_text = self.m_params.hint_text or TYPE_PARAMAS.hint_text
    self.m_tips_text= self.m_params.tips_text or TYPE_PARAMAS.tips_text
    self.m_left_callback = self.m_params.left_callback or TYPE_PARAMAS.left_callback
    self.m_right_callback = self.m_params.right_callback or TYPE_PARAMAS.right_callback
    self.m_close_callback = self.m_params.close_callback or TYPE_PARAMAS.close_callback
    self.m_noPopHint = false
end

function M:switchNoPopHint()
    self.m_noPopHint = not self.m_noPopHint
end

function M:onEnter()
    self:refreshData()
end

return M