return {
	[1]={
		[1]={
			["uk"]=1,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					600,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=2,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					5085,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=3,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1027,
					60,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=4,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1416,
					100,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=5,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5086,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[2]={
		[1]={
			["uk"]=6,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=7,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320003,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=8,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					106,
					0,
					5000,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=9,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1011,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=10,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
		[6]={
			["uk"]=11,
			["pre_reward_chapter"]=5,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1417,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_106",
			["chapter_des"]="tid#SeasonChapterDes_106",
		},
	},
	[3]={
		[1]={
			["uk"]=12,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=13,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1420,
					100,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=14,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1532,
					3,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=15,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1106,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=16,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1431,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[4]={
		[1]={
			["uk"]=17,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=18,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					201002,
					40,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=19,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1420,
					200,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=20,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1417,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=21,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5311,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[5]={
		[1]={
			["uk"]=22,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=23,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1512,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=24,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=25,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1011,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=26,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1411,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[6]={
		[1]={
			["uk"]=27,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=28,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=29,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1420,
					600,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=30,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1422,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=31,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1418,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[7]={
		[1]={
			["uk"]=32,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=33,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1417,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=34,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1011,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=35,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1420,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=36,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5046,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[8]={
		[1]={
			["uk"]=37,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=38,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1106,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=39,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1422,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=40,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					2415,
					60,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=41,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1431,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[9]={
		[1]={
			["uk"]=42,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=43,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					5217,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=44,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=45,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					101,
					117,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=46,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5313,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[10]={
		[1]={
			["uk"]=47,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=48,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					5564,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=49,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1417,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=50,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					101,
					217,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=51,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1418,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[11]={
		[1]={
			["uk"]=52,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=53,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1417,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=54,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=55,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					101,
					612,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=56,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1431,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[12]={
		[1]={
			["uk"]=57,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=58,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					5217,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=59,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1422,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=60,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5592,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=61,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5046,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[13]={
		[1]={
			["uk"]=62,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=63,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=64,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1417,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=65,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5592,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=66,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1418,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[14]={
		[1]={
			["uk"]=67,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=68,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1532,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=69,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1422,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=70,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5592,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=71,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1431,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[15]={
		[1]={
			["uk"]=72,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=73,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=74,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1417,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=75,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1420,
					1500,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=76,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5592,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[16]={
		[1]={
			["uk"]=77,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=78,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=79,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1417,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=80,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1420,
					1500,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=81,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5592,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[17]={
		[1]={
			["uk"]=82,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=83,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=84,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1417,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=85,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1420,
					1500,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=86,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5592,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
	[18]={
		[1]={
			["uk"]=87,
			["pre_reward_chapter"]=0,
			["time_limit"]=1,
			["reward"]={
				{
					107,
					0,
					1000,
				},
			},
			["name"]="tid#SeasonChapterName_101",
			["chapter_des"]="tid#SeasonChapterDes_101",
		},
		[2]={
			["uk"]=88,
			["pre_reward_chapter"]=1,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					320005,
					10,
				},
			},
			["name"]="tid#SeasonChapterName_102",
			["chapter_des"]="tid#SeasonChapterDes_102",
		},
		[3]={
			["uk"]=89,
			["pre_reward_chapter"]=2,
			["time_limit"]=1,
			["reward"]={
				{
					103,
					1417,
					2,
				},
			},
			["name"]="tid#SeasonChapterName_103",
			["chapter_des"]="tid#SeasonChapterDes_103",
		},
		[4]={
			["uk"]=90,
			["pre_reward_chapter"]=3,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					1420,
					1500,
				},
			},
			["name"]="tid#SeasonChapterName_104",
			["chapter_des"]="tid#SeasonChapterDes_104",
		},
		[5]={
			["uk"]=91,
			["pre_reward_chapter"]=4,
			["time_limit"]=0,
			["reward"]={
				{
					103,
					5592,
					1,
				},
			},
			["name"]="tid#SeasonChapterName_105",
			["chapter_des"]="tid#SeasonChapterDes_105",
		},
	},
}