return {
	[1000101]={
		["option_txt"]="三侠五义·疑窦丛生",
		["start_event"]=1101,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=101,
		["item_disappear"]={
		},
		["display_object"]={
			1000101,
			1000103,
			1000104,
			1000201,
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000102]={
		["option_txt"]="出去看看",
		["start_event"]=1102,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1000202,
			1000301,
			1000302,
			1000303,
		},
		["destroy_object"]={
			1000201,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000103]={
		["option_txt"]="不如去这妇人家中看看",
		["start_event"]=1103,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1000401,
			1000402,
		},
		["destroy_object"]={
			1000303,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000104]={
		["option_txt"]="找这刘寡妇一问便知",
		["start_event"]=1201,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1000501,
			1000502,
			1000503,
			1000403,
		},
		["destroy_object"]={
			1000401,
			1000402,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000105]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=10002,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000106]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=10003,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000201]={
		["option_txt"]="正有此意",
		["start_event"]=1202,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1000601,
			1000602,
			1000603,
		},
		["destroy_object"]={
			1000501,
			1000503,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000202]={
		["option_txt"]="不如去前面茶馆细细聊聊",
		["start_event"]=1301,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1000701,
			1000702,
			1000703,
		},
		["destroy_object"]={
			1000601,
			1000602,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000203]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=10005,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000301]={
		["option_txt"]="正有此意",
		["start_event"]=1302,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1000801,
			1000802,
		},
		["destroy_object"]={
			1000703,
			1000702,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000302]={
		["option_txt"]="正有此意",
		["start_event"]=1401,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1000901,
		},
		["destroy_object"]={
			1000801,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000303]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=10007,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000401]={
		["option_txt"]="正有此意",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
			1000901,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000404]={
		["option_txt"]="三侠五义·沉冤得雪",
		["start_event"]=1402,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1010102,
			1010103,
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000402]={
		["option_txt"]="正有此意",
		["start_event"]=1501,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1010201,
			1010202,
		},
		["destroy_object"]={
			1010101,
			1010102,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000403]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=10009,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000501]={
		["option_txt"]="巧了，我知道这里有一酒家非常有名",
		["start_event"]=1502,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1010301,
			1010302,
			1010303,
		},
		["destroy_object"]={
			1010201,
			1010202,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000502]={
		["option_txt"]="正有此意",
		["start_event"]=1601,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1010401,
			1010402,
			1010403,
		},
		["destroy_object"]={
			1010301,
			1010302,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000503]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=10102,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000601]={
		["option_txt"]="正有此意",
		["start_event"]=1701,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			1010501,
			1010502,
			1010503,
			1010504,
			1010505,
			1010506,
		},
		["destroy_object"]={
			1010401,
			1010402,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[1000602]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=10105,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000100]={
		["option_txt"]="三侠五义·疑窦丛生",
		["start_event"]=2101,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=201,
		["item_disappear"]={
		},
		["display_object"]={
			2000102,
			2000103,
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000101]={
		["option_txt"]="正有此意",
		["start_event"]=2102,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2000202,
			2000203,
			2000204,
			2000205,
		},
		["destroy_object"]={
			2000103,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000102]={
		["option_txt"]="找这刘家寡妇一问便知",
		["start_event"]=2201,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2000301,
			2000302,
			2000303,
			2000206,
		},
		["destroy_object"]={
			2000204,
			2000205,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000103]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=20003,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000201]={
		["option_txt"]="正有此意",
		["start_event"]=2202,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2000401,
			2000402,
			2000403,
		},
		["destroy_object"]={
			2000301,
			2000303,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000202]={
		["option_txt"]="前面有家茶馆不如坐着说",
		["start_event"]=2301,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2000501,
			2000502,
			2000503,
		},
		["destroy_object"]={
			2000401,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000203]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=20005,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000301]={
		["option_txt"]="正有此意",
		["start_event"]=2401,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2000601,
		},
		["destroy_object"]={
			2000502,
			2000503,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000401]={
		["option_txt"]="白少侠好身手",
		["start_event"]=2402,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2000602,
			2000603,
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000402]={
		["option_txt"]="你别卖关子了",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000505]={
		["option_txt"]="三侠五义·沉冤得雪",
		["start_event"]=2501,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2010101,
			2010103,
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=0,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000501]={
		["option_txt"]="正有此意",
		["start_event"]=2502,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2010201,
			2010202,
			2010103,
		},
		["destroy_object"]={
			2010101,
			2010102,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000502]={
		["option_txt"]="巧了，我知道这里有一酒家非常有名",
		["start_event"]=2601,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2010301,
			2010302,
			2010303,
		},
		["destroy_object"]={
			2010201,
			2010202,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000503]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=20102,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000504]={
		["option_txt"]="正有此意",
		["start_event"]=2701,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2010401,
			2010402,
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000601]={
		["option_txt"]="正有此意",
		["start_event"]=2702,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
			2010403,
			2010501,
			2010502,
			2010503,
			2010504,
			2010505,
			2010506,
		},
		["destroy_object"]={
			2010401,
			2010402,
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000701]={
		["option_txt"]="正有此意",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=0,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
	[2000702]={
		["option_txt"]="",
		["start_event"]=0,
		["battle_id"]=0,
		["battle_param"]={
		},
		["closeoption_id"]={
		},
		["item_id"]={
		},
		["animation_open"]="",
		["voice_open"]=0,
		["map_id"]=20105,
		["event_team_id"]=0,
		["item_disappear"]={
		},
		["display_object"]={
		},
		["destroy_object"]={
		},
		["disappear_OPEN"]=1,
		["option_hide"]=0,
		["combat_param"]={
		},
		["event_battle"]=0,
		["event_reward"]={
		},
		["event_after"]=0,
		["defeat_id"]=0,
		["Conditional_hints"]=0,
		["delegation_id"]=0,
	},
}