return {
	[1]={
		["des"]="tid#CardExchangeDes",
	},
	[2]={
		["des"]="tid#CardExchangeDes",
	},
	[3]={
		["des"]="tid#CardExchangeDes",
	},
	[4]={
		["des"]="tid#CardExchangeDes",
	},
	[5]={
		["des"]="tid#CardExchangeDes",
	},
	[6]={
		["des"]="tid#CardExchangeDes",
	},
	[7]={
		["des"]="tid#CardExchangeDes",
	},
	[8]={
		["des"]="tid#CardExchangeDes",
	},
	[9]={
		["des"]="tid#CardExchangeDes",
	},
	[10]={
		["des"]="tid#CardExchangeDes",
	},
	[11]={
		["des"]="tid#CardExchangeDes",
	},
	[12]={
		["des"]="tid#CardExchangeDes",
	},
	[13]={
		["des"]="tid#CardExchangeDes",
	},
	[14]={
		["des"]="tid#CardExchangeDes",
	},
	[15]={
		["des"]="tid#CardExchangeDes",
	},
	[16]={
		["des"]="tid#CardExchangeDes",
	},
	[17]={
		["des"]="tid#CardExchangeDes",
	},
	[18]={
		["des"]="tid#CardExchangeDes",
	},
	[19]={
		["des"]="tid#CardExchangeDes",
	},
	[20]={
		["des"]="tid#CardExchangeDes",
	},
	[21]={
		["des"]="tid#CardExchangeDes",
	},
	[22]={
		["des"]="tid#CardExchangeDes",
	},
	[23]={
		["des"]="tid#CardExchangeDes",
	},
	[24]={
		["des"]="tid#CardExchangeDes",
	},
	[25]={
		["des"]="tid#CardExchangeDes",
	},
	[26]={
		["des"]="tid#CardExchangeDes",
	},
	[27]={
		["des"]="tid#CardExchangeDes",
	},
	[28]={
		["des"]="tid#CardExchangeDes",
	},
	[29]={
		["des"]="tid#CardExchangeDes",
	},
	[30]={
		["des"]="tid#CardExchangeDes",
	},
	[31]={
		["des"]="tid#CardExchangeDes",
	},
	[32]={
		["des"]="tid#CardExchangeDes",
	},
	[33]={
		["des"]="tid#CardExchangeDes",
	},
	[34]={
		["des"]="tid#CardExchangeDes",
	},
	[35]={
		["des"]="tid#CardExchangeDes",
	},
	[36]={
		["des"]="tid#CardExchangeDes",
	},
	[37]={
		["des"]="tid#CardExchangeDes",
	},
	[38]={
		["des"]="tid#CardExchangeDes",
	},
	[39]={
		["des"]="tid#CardExchangeDes",
	},
	[40]={
		["des"]="tid#CardExchangeDes",
	},
	[41]={
		["des"]="tid#CardExchangeDes",
	},
	[42]={
		["des"]="tid#CardExchangeDes",
	},
	[43]={
		["des"]="tid#CardExchangeDes",
	},
	[44]={
		["des"]="tid#CardExchangeDes",
	},
	[45]={
		["des"]="tid#CardExchangeDes",
	},
	[46]={
		["des"]="tid#CardExchangeDes",
	},
	[47]={
		["des"]="tid#CardExchangeDes",
	},
	[48]={
		["des"]="tid#CardExchangeDes",
	},
	[49]={
		["des"]="tid#CardExchangeDes",
	},
	[50]={
		["des"]="tid#CardExchangeDes",
	},
	[51]={
		["des"]="tid#CardExchangeDes",
	},
	[52]={
		["des"]="tid#CardExchangeDes",
	},
	[53]={
		["des"]="tid#CardExchangeDes",
	},
	[54]={
		["des"]="tid#CardExchangeDes",
	},
	[55]={
		["des"]="tid#CardExchangeDes",
	},
	[56]={
		["des"]="tid#CardExchangeDes",
	},
	[57]={
		["des"]="tid#CardExchangeDes",
	},
	[58]={
		["des"]="tid#CardExchangeDes",
	},
	[59]={
		["des"]="tid#CardExchangeDes",
	},
	[60]={
		["des"]="tid#CardExchangeDes",
	},
	[61]={
		["des"]="tid#CardExchangeDes",
	},
	[62]={
		["des"]="tid#CardExchangeDes",
	},
	[63]={
		["des"]="tid#CardExchangeDes",
	},
	[64]={
		["des"]="tid#CardExchangeDes",
	},
	[65]={
		["des"]="tid#CardExchangeDes",
	},
	[66]={
		["des"]="tid#CardExchangeDes",
	},
	[67]={
		["des"]="tid#CardExchangeDes",
	},
	[68]={
		["des"]="tid#CardExchangeDes",
	},
	[69]={
		["des"]="tid#CardExchangeDes",
	},
	[70]={
		["des"]="tid#CardExchangeDes",
	},
	[71]={
		["des"]="tid#CardExchangeDes",
	},
	[72]={
		["des"]="tid#CardExchangeDes",
	},
	[73]={
		["des"]="tid#CardExchangeDes",
	},
	[74]={
		["des"]="tid#CardExchangeDes",
	},
	[75]={
		["des"]="tid#CardExchangeDes",
	},
	[76]={
		["des"]="tid#CardExchangeDes",
	},
	[77]={
		["des"]="tid#CardExchangeDes",
	},
	[78]={
		["des"]="tid#CardExchangeDes",
	},
	[79]={
		["des"]="tid#CardExchangeDes",
	},
	[80]={
		["des"]="tid#CardExchangeDes",
	},
	[81]={
		["des"]="tid#CardExchangeDes",
	},
	[82]={
		["des"]="tid#CardExchangeDes",
	},
	[83]={
		["des"]="tid#CardExchangeDes",
	},
	[84]={
		["des"]="tid#CardExchangeDes",
	},
	[85]={
		["des"]="tid#CardExchangeDes",
	},
	[86]={
		["des"]="tid#CardExchangeDes",
	},
	[87]={
		["des"]="tid#CardExchangeDes",
	},
	[88]={
		["des"]="tid#CardExchangeDes",
	},
	[89]={
		["des"]="tid#CardExchangeDes",
	},
	[90]={
		["des"]="tid#CardExchangeDes",
	},
	[91]={
		["des"]="tid#CardExchangeDes",
	},
	[92]={
		["des"]="tid#CardExchangeDes",
	},
	[93]={
		["des"]="tid#CardExchangeDes",
	},
	[94]={
		["des"]="tid#CardExchangeDes",
	},
	[95]={
		["des"]="tid#CardExchangeDes",
	},
	[96]={
		["des"]="tid#CardExchangeDes",
	},
	[97]={
		["des"]="tid#CardExchangeDes",
	},
	[98]={
		["des"]="tid#CardExchangeDes",
	},
	[99]={
		["des"]="tid#CardExchangeDes",
	},
	[100]={
		["des"]="tid#CardExchangeDes",
	},
	[101]={
		["des"]="tid#CardExchangeDes",
	},
	[102]={
		["des"]="tid#CardExchangeDes",
	},
	[103]={
		["des"]="tid#CardExchangeDes",
	},
	[104]={
		["des"]="tid#CardExchangeDes",
	},
	[105]={
		["des"]="tid#CardExchangeDes",
	},
	[106]={
		["des"]="tid#CardExchangeDes",
	},
	[107]={
		["des"]="tid#CardExchangeDes",
	},
	[108]={
		["des"]="tid#CardExchangeDes",
	},
	[109]={
		["des"]="tid#CardExchangeDes",
	},
	[110]={
		["des"]="tid#CardExchangeDes",
	},
	[111]={
		["des"]="tid#CardExchangeDes",
	},
	[112]={
		["des"]="tid#CardExchangeDes",
	},
	[113]={
		["des"]="tid#CardExchangeDes",
	},
	[114]={
		["des"]="tid#CardExchangeDes",
	},
	[115]={
		["des"]="tid#CardExchangeDes",
	},
	[116]={
		["des"]="tid#CardExchangeDes",
	},
	[117]={
		["des"]="tid#CardExchangeDes",
	},
	[118]={
		["des"]="tid#CardExchangeDes",
	},
	[119]={
		["des"]="tid#CardExchangeDes",
	},
	[120]={
		["des"]="tid#CardExchangeDes",
	},
	[121]={
		["des"]="tid#CardExchangeDes",
	},
	[122]={
		["des"]="tid#CardExchangeDes",
	},
	[123]={
		["des"]="tid#CardExchangeDes",
	},
	[124]={
		["des"]="tid#CardExchangeDes",
	},
	[125]={
		["des"]="tid#CardExchangeDes",
	},
	[126]={
		["des"]="tid#CardExchangeDes",
	},
	[127]={
		["des"]="tid#CardExchangeDes",
	},
	[128]={
		["des"]="tid#CardExchangeDes",
	},
	[129]={
		["des"]="tid#CardExchangeDes",
	},
	[130]={
		["des"]="tid#CardExchangeDes",
	},
	[131]={
		["des"]="tid#CardExchangeDes",
	},
	[132]={
		["des"]="tid#CardExchangeDes",
	},
	[133]={
		["des"]="tid#CardExchangeDes",
	},
	[134]={
		["des"]="tid#CardExchangeDes",
	},
	[135]={
		["des"]="tid#CardExchangeDes",
	},
	[136]={
		["des"]="tid#CardExchangeDes",
	},
	[137]={
		["des"]="tid#CardExchangeDes",
	},
	[138]={
		["des"]="tid#CardExchangeDes",
	},
	[139]={
		["des"]="tid#CardExchangeDes",
	},
	[140]={
		["des"]="tid#CardExchangeDes",
	},
	[141]={
		["des"]="tid#CardExchangeDes",
	},
	[142]={
		["des"]="tid#CardExchangeDes",
	},
	[143]={
		["des"]="tid#CardExchangeDes",
	},
	[144]={
		["des"]="tid#CardExchangeDes",
	},
	[145]={
		["des"]="tid#CardExchangeDes",
	},
	[146]={
		["des"]="tid#CardExchangeDes",
	},
	[147]={
		["des"]="tid#CardExchangeDes",
	},
	[148]={
		["des"]="tid#CardExchangeDes",
	},
	[149]={
		["des"]="tid#CardExchangeDes",
	},
	[150]={
		["des"]="tid#CardExchangeDes",
	},
	[151]={
		["des"]="tid#CardExchangeDes",
	},
}