return {
	[410]={
		[1]={
			[9]={
				[1]={
					["group"]=1,
					["group_id"]=2,
					["name"]="起源",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=0,
					["stage_link"]={
						2,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300133,
					["battle_event2"]=0,
					["reward"]={
						{
							106,
							0,
							2000,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[2]={
					["group"]=2,
					["group_id"]=2,
					["name"]="貂蝉-1",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=1,
					["stage_link"]={
						3,
						4,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1110,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1507,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[3]={
					["group"]=3,
					["group_id"]=1,
					["name"]="貂蝉-2",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						5,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1120,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1510,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[4]={
					["group"]=3,
					["group_id"]=3,
					["name"]="貂蝉-3",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						6,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1130,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1009,
							2,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[5]={
					["group"]=4,
					["group_id"]=1,
					["name"]="貂蝉-4",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						7,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300134,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1106,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[6]={
					["group"]=4,
					["group_id"]=3,
					["name"]="貂蝉-5",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						8,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1201,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1011,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[7]={
					["group"]=5,
					["group_id"]=1,
					["name"]="貂蝉-6",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
						20,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1210,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1504,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[8]={
					["group"]=5,
					["group_id"]=3,
					["name"]="貂蝉-7",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1220,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1010,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[9]={
					["group"]=6,
					["group_id"]=2,
					["name"]="貂蝉-8",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=7,
					["stage_link"]={
						10,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300135,
					["battle_event2"]=0,
					["reward"]={
						{
							107,
							0,
							300,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[10]={
					["group"]=7,
					["group_id"]=2,
					["name"]="貂蝉-9",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=9,
					["stage_link"]={
						11,
						12,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1401,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1105,
							5,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[11]={
					["group"]=8,
					["group_id"]=1,
					["name"]="貂蝉-10",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300136,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1420,
							300,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[12]={
					["group"]=8,
					["group_id"]=3,
					["name"]="貂蝉-11",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1501,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1008,
							30,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
			},
		},
		[2]={
			[13]={
				[1]={
					["group"]=1,
					["group_id"]=2,
					["name"]="起源",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=0,
					["stage_link"]={
						2,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1108,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							106,
							0,
							2000,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[2]={
					["group"]=2,
					["group_id"]=2,
					["name"]="木兰-1",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=1,
					["stage_link"]={
						3,
						4,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1110,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1507,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[3]={
					["group"]=3,
					["group_id"]=1,
					["name"]="木兰-2",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						5,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1120,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1510,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[4]={
					["group"]=3,
					["group_id"]=3,
					["name"]="木兰-3",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						6,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1125,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1009,
							2,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[5]={
					["group"]=4,
					["group_id"]=1,
					["name"]="木兰-4",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						7,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1130,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1106,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[6]={
					["group"]=4,
					["group_id"]=3,
					["name"]="木兰-5",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						8,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1201,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1011,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[7]={
					["group"]=5,
					["group_id"]=1,
					["name"]="木兰-6",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
						20,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1210,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1504,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[8]={
					["group"]=5,
					["group_id"]=3,
					["name"]="木兰-7",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1220,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1010,
							1,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[9]={
					["group"]=6,
					["group_id"]=2,
					["name"]="木兰-8",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=7,
					["stage_link"]={
						10,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1230,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							107,
							0,
							300,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[10]={
					["group"]=7,
					["group_id"]=2,
					["name"]="木兰-9",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=9,
					["stage_link"]={
						11,
						12,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1401,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1105,
							5,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[11]={
					["group"]=8,
					["group_id"]=1,
					["name"]="木兰-10",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1430,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1420,
							300,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[12]={
					["group"]=8,
					["group_id"]=3,
					["name"]="木兰-11",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1501,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1008,
							30,
						},
						{
							103,
							5602,
							1,
						},
					},
					["hero_id"]={
						719,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
			},
		},
		[3]={
			[14]={
				[1]={
					["group"]=1,
					["group_id"]=2,
					["name"]="起源",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=0,
					["stage_link"]={
						2,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							106,
							0,
							2000,
						},
						{
							103,
							5771,
							1,
						},
					},
					["hero_id"]={
						721,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[2]={
					["group"]=2,
					["group_id"]=2,
					["name"]="小乔-1",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=1,
					["stage_link"]={
						3,
						4,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1110,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1507,
							1,
						},
						{
							103,
							5771,
							1,
						},
					},
					["hero_id"]={
						721,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[3]={
					["group"]=3,
					["group_id"]=1,
					["name"]="小乔-2",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						5,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1120,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1510,
							1,
						},
						{
							103,
							5771,
							1,
						},
					},
					["hero_id"]={
						721,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[4]={
					["group"]=3,
					["group_id"]=3,
					["name"]="小乔-3",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						6,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1130,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1009,
							2,
						},
						{
							103,
							5771,
							1,
						},
					},
					["hero_id"]={
						721,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[5]={
					["group"]=4,
					["group_id"]=1,
					["name"]="小乔-4",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						7,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1106,
							1,
						},
						{
							103,
							5771,
							1,
						},
					},
					["hero_id"]={
						721,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[6]={
					["group"]=4,
					["group_id"]=3,
					["name"]="小乔-5",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						8,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1201,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1011,
							1,
						},
						{
							103,
							5771,
							1,
						},
					},
					["hero_id"]={
						721,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[7]={
					["group"]=5,
					["group_id"]=1,
					["name"]="小乔-6",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1210,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1504,
							1,
						},
						{
							103,
							5771,
							1,
						},
					},
					["hero_id"]={
						721,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[8]={
					["group"]=5,
					["group_id"]=3,
					["name"]="小乔-7",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1220,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1010,
							1,
						},
						{
							103,
							5771,
							1,
						},
					},
					["hero_id"]={
						721,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[9]={
					["group"]=6,
					["group_id"]=2,
					["name"]="小乔-8",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=7,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							107,
							0,
							300,
						},
						{
							103,
							5771,
							1,
						},
					},
					["hero_id"]={
						721,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
			},
		},
		[4]={
			[15]={
				[1]={
					["group"]=1,
					["group_id"]=2,
					["name"]="起源",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=0,
					["stage_link"]={
						2,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300133,
					["battle_event2"]=0,
					["reward"]={
						{
							106,
							0,
							2000,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[2]={
					["group"]=2,
					["group_id"]=2,
					["name"]="貂蝉-1",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=1,
					["stage_link"]={
						3,
						4,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1110,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1507,
							1,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[3]={
					["group"]=3,
					["group_id"]=1,
					["name"]="貂蝉-2",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						5,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1120,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1510,
							1,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[4]={
					["group"]=3,
					["group_id"]=3,
					["name"]="貂蝉-3",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						6,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1130,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1009,
							2,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[5]={
					["group"]=4,
					["group_id"]=1,
					["name"]="貂蝉-4",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						7,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300134,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1106,
							1,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[6]={
					["group"]=4,
					["group_id"]=3,
					["name"]="貂蝉-5",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						8,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1201,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1011,
							1,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[7]={
					["group"]=5,
					["group_id"]=1,
					["name"]="貂蝉-6",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
						20,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1210,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1504,
							1,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[8]={
					["group"]=5,
					["group_id"]=3,
					["name"]="貂蝉-7",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1220,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1010,
							1,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[9]={
					["group"]=6,
					["group_id"]=2,
					["name"]="貂蝉-8",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=7,
					["stage_link"]={
						10,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300135,
					["battle_event2"]=0,
					["reward"]={
						{
							107,
							0,
							300,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[10]={
					["group"]=7,
					["group_id"]=2,
					["name"]="貂蝉-9",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=9,
					["stage_link"]={
						11,
						12,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1401,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1105,
							5,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[11]={
					["group"]=8,
					["group_id"]=1,
					["name"]="貂蝉-10",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300136,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1420,
							300,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[12]={
					["group"]=8,
					["group_id"]=3,
					["name"]="貂蝉-11",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1501,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1008,
							30,
						},
						{
							103,
							5777,
							1,
						},
					},
					["hero_id"]={
						716,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
			},
		},
		[5]={
			[16]={
				[1]={
					["group"]=1,
					["group_id"]=2,
					["name"]="起源",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=0,
					["stage_link"]={
						2,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1108,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							106,
							0,
							2000,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[2]={
					["group"]=2,
					["group_id"]=2,
					["name"]="周瑜-1",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=1,
					["stage_link"]={
						3,
						4,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1110,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1507,
							1,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[3]={
					["group"]=3,
					["group_id"]=1,
					["name"]="周瑜-2",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						5,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1120,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1510,
							1,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[4]={
					["group"]=3,
					["group_id"]=3,
					["name"]="周瑜-3",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						6,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1125,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1009,
							2,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[5]={
					["group"]=4,
					["group_id"]=1,
					["name"]="周瑜-4",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						7,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1130,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1106,
							1,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[6]={
					["group"]=4,
					["group_id"]=3,
					["name"]="周瑜-5",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						8,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1201,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1011,
							1,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[7]={
					["group"]=5,
					["group_id"]=1,
					["name"]="周瑜-6",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
						20,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1210,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1504,
							1,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[8]={
					["group"]=5,
					["group_id"]=3,
					["name"]="周瑜-7",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1220,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1010,
							1,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[9]={
					["group"]=6,
					["group_id"]=2,
					["name"]="周瑜-8",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=7,
					["stage_link"]={
						10,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1230,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							107,
							0,
							300,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[10]={
					["group"]=7,
					["group_id"]=2,
					["name"]="周瑜-9",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=9,
					["stage_link"]={
						11,
						12,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1401,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1105,
							5,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[11]={
					["group"]=8,
					["group_id"]=1,
					["name"]="周瑜-10",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1430,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1420,
							300,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[12]={
					["group"]=8,
					["group_id"]=3,
					["name"]="周瑜-11",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1501,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1027,
							30,
						},
						{
							103,
							5783,
							1,
						},
					},
					["hero_id"]={
						723,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
			},
		},
	},
	[420]={
		[1]={
			[10]={
				[1]={
					["group"]=1,
					["group_id"]=2,
					["name"]="起源",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=0,
					["stage_link"]={
						2,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300137,
					["battle_event2"]=0,
					["reward"]={
						{
							106,
							0,
							2000,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[2]={
					["group"]=2,
					["group_id"]=2,
					["name"]="狄仁杰-1",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=1,
					["stage_link"]={
						3,
						4,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1110,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1507,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[3]={
					["group"]=3,
					["group_id"]=1,
					["name"]="狄仁杰-2",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						5,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1120,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1510,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[4]={
					["group"]=3,
					["group_id"]=3,
					["name"]="狄仁杰-3",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						6,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1130,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1009,
							2,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[5]={
					["group"]=4,
					["group_id"]=1,
					["name"]="狄仁杰-4",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						7,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300138,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1106,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[6]={
					["group"]=4,
					["group_id"]=3,
					["name"]="狄仁杰-5",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						8,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1201,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1011,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[7]={
					["group"]=5,
					["group_id"]=1,
					["name"]="狄仁杰-6",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
						20,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1210,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1504,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[8]={
					["group"]=5,
					["group_id"]=3,
					["name"]="狄仁杰-7",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1220,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1010,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[9]={
					["group"]=6,
					["group_id"]=2,
					["name"]="狄仁杰-8",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=7,
					["stage_link"]={
						10,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300139,
					["battle_event2"]=0,
					["reward"]={
						{
							107,
							0,
							300,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[10]={
					["group"]=7,
					["group_id"]=2,
					["name"]="狄仁杰-9",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=9,
					["stage_link"]={
						11,
						12,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1401,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1105,
							5,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[11]={
					["group"]=8,
					["group_id"]=1,
					["name"]="狄仁杰-10",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300140,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1420,
							300,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[12]={
					["group"]=8,
					["group_id"]=3,
					["name"]="狄仁杰-11",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1501,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1008,
							30,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						718,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
			},
			[11]={
				[13]={
					["group"]=1,
					["group_id"]=2,
					["name"]="起源",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=0,
					["stage_link"]={
						14,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300141,
					["battle_event2"]=0,
					["reward"]={
						{
							106,
							0,
							2000,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[14]={
					["group"]=2,
					["group_id"]=2,
					["name"]="武则天-1",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=13,
					["stage_link"]={
						15,
						16,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1110,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1507,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[15]={
					["group"]=3,
					["group_id"]=1,
					["name"]="武则天-2",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=14,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1120,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1510,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[16]={
					["group"]=3,
					["group_id"]=3,
					["name"]="武则天-3",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=14,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1130,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1009,
							2,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[17]={
					["group"]=4,
					["group_id"]=2,
					["name"]="武则天-4",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=15,
					["stage_link"]={
						18,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1201,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1106,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[18]={
					["group"]=5,
					["group_id"]=2,
					["name"]="武则天-5",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=17,
					["stage_link"]={
						19,
						20,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1210,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1011,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[19]={
					["group"]=6,
					["group_id"]=1,
					["name"]="武则天-6",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=18,
					["stage_link"]={
						21,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1310,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1504,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[20]={
					["group"]=6,
					["group_id"]=3,
					["name"]="武则天-7",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=18,
					["stage_link"]={
						22,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300142,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1010,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[21]={
					["group"]=7,
					["group_id"]=1,
					["name"]="武则天-8",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=19,
					["stage_link"]={
						23,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1401,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							107,
							0,
							300,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[22]={
					["group"]=7,
					["group_id"]=3,
					["name"]="武则天-9",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=20,
					["stage_link"]={
						24,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1430,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1105,
							5,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[23]={
					["group"]=8,
					["group_id"]=1,
					["name"]="武则天-10",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=21,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1501,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1420,
							300,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[24]={
					["group"]=8,
					["group_id"]=3,
					["name"]="武则天-11",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=22,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300143,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1008,
							30,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[25]={
					["group"]=9,
					["group_id"]=2,
					["name"]="武则天-12",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=23,
					["stage_link"]={
						26,
						27,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1530,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1504,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[26]={
					["group"]=10,
					["group_id"]=1,
					["name"]="武则天-13",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=25,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1601,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							103,
							1010,
							1,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[27]={
					["group"]=10,
					["group_id"]=3,
					["name"]="武则天-14",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=25,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300144,
					["battle_event2"]=0,
					["reward"]={
						{
							107,
							0,
							300,
						},
						{
							103,
							5635,
							1,
						},
					},
					["hero_id"]={
						717,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
			},
		},
		[2]={
			[12]={
				[1]={
					["group"]=1,
					["group_id"]=2,
					["name"]="起源",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=0,
					["stage_link"]={
						2,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300155,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							6,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[2]={
					["group"]=2,
					["group_id"]=2,
					["name"]="关羽-1",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=1,
					["stage_link"]={
						3,
						4,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1110,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							7,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[3]={
					["group"]=3,
					["group_id"]=1,
					["name"]="关羽-2",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						5,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1120,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							8,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[4]={
					["group"]=3,
					["group_id"]=3,
					["name"]="关羽-3",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=2,
					["stage_link"]={
						6,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1130,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							5,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[5]={
					["group"]=4,
					["group_id"]=1,
					["name"]="关羽-4",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						7,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300156,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							6,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[6]={
					["group"]=4,
					["group_id"]=3,
					["name"]="关羽-5",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=3,
					["stage_link"]={
						8,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1201,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							7,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[7]={
					["group"]=5,
					["group_id"]=1,
					["name"]="关羽-6",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
						20,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1210,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							8,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[8]={
					["group"]=5,
					["group_id"]=3,
					["name"]="关羽-7",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=5,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1220,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							5,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[9]={
					["group"]=6,
					["group_id"]=2,
					["name"]="关羽-8",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=7,
					["stage_link"]={
						10,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300157,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							6,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[10]={
					["group"]=7,
					["group_id"]=2,
					["name"]="关羽-9",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=9,
					["stage_link"]={
						11,
						12,
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1401,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							7,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
				[11]={
					["group"]=8,
					["group_id"]=1,
					["name"]="关羽-10",
					["type"]=1,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=0,
					["battle_stage"]=0,
					["battle_event1"]=300158,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							8,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
					},
					["hero_evo"]={
					},
					["equip_evo"]={
					},
					["equip_lv"]={
					},
				},
				[12]={
					["group"]=8,
					["group_id"]=3,
					["name"]="关羽-11",
					["type"]=2,
					["cost"]=1,
					["stage_front"]=10,
					["stage_link"]={
					},
					["lock"]=0,
					["open_condition"]={
					},
					["event"]=0,
					["option"]={
					},
					["battle_id"]=1501,
					["battle_stage"]=120,
					["battle_event1"]=0,
					["battle_event2"]=0,
					["reward"]={
						{
							177,
							5,
							1,
						},
						{
							103,
							5681,
							1,
						},
					},
					["hero_id"]={
						720,
					},
					["hero_limit"]=0,
					["hero_lv"]={
						100,
					},
					["hero_evo"]={
						19,
					},
					["equip_evo"]={
						5,
					},
					["equip_lv"]={
					},
				},
			},
		},
	},
}