return {
	[1]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_04",
		["words"]="爆竹声中一岁除，春风送暖入屠苏",
	},
	[2]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_07",
		["words"]="新年福到，恭喜发财，红包拿来~",
	},
	[3]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_06",
		["words"]="少侠，今天晚宴的主菜是什么呢",
	},
	[4]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_08",
		["words"]="有了这道菜，少侠一定可以甜甜的一整年哦！",
	},
	[5]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_05",
		["words"]="过年啦，少侠有没有和家人团聚呢",
	},
	[6]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_10",
		["words"]="今年的年夜饭一定非常丰盛，少侠要和阿闲一起吃吗！",
	},
	[7]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_11",
		["words"]="哇，怎么还不过年呢，阿闲现在就想跟少侠一起过年呢！",
	},
	[8]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_12",
		["words"]="哼哼哼，少侠又添新菜了！",
	},
	[9]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_13",
		["words"]="鲈鱼鲈鱼，年年有余~",
	},
	[10]={
		["bank"]="Vo_AXian",
		["vo"]="Vo_NYear_AXian_14",
		["words"]="阿闲想换一张更大的桌子了，这么多菜都快放不下惹",
	},
	[11]={
		["bank"]="Vo_AXian",
		["vo"]="VoA_GFond_AXian_01",
		["words"]="哇，喜欢！开心~",
	},
	[12]={
		["bank"]="Vo_AXian",
		["vo"]="VoA_GFond_AXian_02",
		["words"]="少侠对阿闲这么好，阿闲都要害羞惹",
	},
	[999]={
		["bank"]="Vo_AXian",
		["vo"]="VoA_GFond_AXian_01",
		["words"]="哇，喜欢！开心~",
	},
}