return {
	[2]={
		["item_id1"]={
			{
				103,
				5558,
				1,
			},
		},
		["item_id2"]={
		},
		["mail_id1"]=199,
		["mail_id2"]=200,
		["flower_des"]="tid#FlowerFestivalDes_1",
		["flower_des2"]="tid#FlowerFestivalDes_2",
	},
	[3]={
		["item_id1"]={
			{
				103,
				5558,
				1,
			},
		},
		["item_id2"]={
		},
		["mail_id1"]=199,
		["mail_id2"]=200,
		["flower_des"]="tid#FlowerFestivalDes_1",
		["flower_des2"]="tid#FlowerFestivalDes_2",
	},
	[4]={
		["item_id1"]={
			{
				103,
				5558,
				1,
			},
		},
		["item_id2"]={
		},
		["mail_id1"]=199,
		["mail_id2"]=200,
		["flower_des"]="tid#FlowerFestivalDes_1",
		["flower_des2"]="tid#FlowerFestivalDes_2",
	},
	[5]={
		["item_id1"]={
			{
				103,
				5558,
				1,
			},
		},
		["item_id2"]={
		},
		["mail_id1"]=199,
		["mail_id2"]=200,
		["flower_des"]="tid#FlowerFestivalDes_1",
		["flower_des2"]="tid#FlowerFestivalDes_2",
	},
	[6]={
		["item_id1"]={
			{
				103,
				5558,
				1,
			},
		},
		["item_id2"]={
		},
		["mail_id1"]=199,
		["mail_id2"]=200,
		["flower_des"]="tid#FlowerFestivalDes_1",
		["flower_des2"]="tid#FlowerFestivalDes_2",
	},
	[7]={
		["item_id1"]={
			{
				103,
				5558,
				1,
			},
		},
		["item_id2"]={
		},
		["mail_id1"]=199,
		["mail_id2"]=200,
		["flower_des"]="tid#FlowerFestivalDes_1",
		["flower_des2"]="tid#FlowerFestivalDes_2",
	},
	[8]={
		["item_id1"]={
			{
				103,
				5558,
				1,
			},
		},
		["item_id2"]={
		},
		["mail_id1"]=199,
		["mail_id2"]=200,
		["flower_des"]="tid#FlowerFestivalDes_1",
		["flower_des2"]="tid#FlowerFestivalDes_2",
	},
}