return {
	[1]={
		[1]={
			["start_day"]=1,
			["end_day"]=3,
			["icon"]="a_gj_hd_jstx_shengshou",
			["name"]="凶兽围剿",
			["phase_time"]="11.21-11.30",
			["type"]=1,
			["phase_round"]={
			},
		},
		[2]={
			["start_day"]=4,
			["end_day"]=8,
			["icon"]="a_gj_hd_jstx_shengshou",
			["name"]="凶兽围剿",
			["phase_time"]="11.21-11.30",
			["type"]=1,
			["phase_round"]={
			},
		},
		[8]={
			["start_day"]=9,
			["end_day"]=10,
			["icon"]="a_gj_hd_jstx_shengshou",
			["name"]="凶兽围剿",
			["phase_time"]="11.21-11.30",
			["type"]=1,
			["phase_round"]={
			},
		},
		[3]={
			["start_day"]=11,
			["end_day"]=12,
			["icon"]="a_gj_hd_jstx_jifensai",
			["name"]="全服积分赛",
			["phase_time"]="12.01-12.12",
			["type"]=2,
			["phase_round"]={
			},
		},
		[4]={
			["start_day"]=13,
			["end_day"]=22,
			["icon"]="a_gj_hd_jstx_jifensai",
			["name"]="全服积分赛",
			["phase_time"]="12.01-12.12",
			["type"]=2,
			["phase_round"]={
				10,
				10,
			},
		},
		[5]={
			["start_day"]=23,
			["end_day"]=26,
			["icon"]="a_gj_hd_jstx_jinjisai",
			["name"]="全服晋级赛",
			["phase_time"]="12.13-12.22",
			["type"]=3,
			["phase_round"]={
			},
		},
		[6]={
			["start_day"]=27,
			["end_day"]=32,
			["icon"]="a_gj_hd_jstx_jinjisai",
			["name"]="全服晋级赛",
			["phase_time"]="12.13-12.22",
			["type"]=3,
			["phase_round"]={
				6,
			},
		},
		[7]={
			["start_day"]=33,
			["end_day"]=45,
			["icon"]="a_gj_hd_jstx_sanqiang",
			["name"]="冠军展示",
			["phase_time"]="12.23-01.04",
			["type"]=4,
			["phase_round"]={
			},
		},
	},
}