return {
	[1]={
		["start_id"]=1001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=1,
		["type"]=2,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[3]={
		["start_id"]=3001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=3,
		["type"]=3,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[4]={
		["start_id"]=4001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=4,
		["type"]=3,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[8]={
		["start_id"]=8001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=8,
		["type"]=3,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[21]={
		["start_id"]=21001,
		["client_type"]=1,
		["open_level"]=1,
		["sort"]=21,
		["type"]=1,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[22]={
		["start_id"]=22001,
		["client_type"]=1,
		["open_level"]=1,
		["sort"]=22,
		["type"]=1,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[23]={
		["start_id"]=23001,
		["client_type"]=1,
		["open_level"]=1,
		["sort"]=23,
		["type"]=1,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[24]={
		["start_id"]=24001,
		["client_type"]=1,
		["open_level"]=1,
		["sort"]=24,
		["type"]=3,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[27]={
		["start_id"]=27001,
		["client_type"]=1,
		["open_level"]=1,
		["sort"]=27,
		["type"]=2,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[28]={
		["start_id"]=28001,
		["client_type"]=1,
		["open_level"]=1,
		["sort"]=28,
		["type"]=3,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[29]={
		["start_id"]=29001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=29,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[30]={
		["start_id"]=30001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=30,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[31]={
		["start_id"]=31001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=31,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[32]={
		["start_id"]=32001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=32,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[33]={
		["start_id"]=33001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=33,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[38]={
		["start_id"]=38001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=38,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[39]={
		["start_id"]=39001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=39,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[40]={
		["start_id"]=40001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=40,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[41]={
		["start_id"]=41001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=41,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[46]={
		["start_id"]=46001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=46,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[50]={
		["start_id"]=50001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=50,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[51]={
		["start_id"]=51001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=51,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[52]={
		["start_id"]=52001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=52,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[53]={
		["start_id"]=53001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=53,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[55]={
		["start_id"]=55001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=55,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[56]={
		["start_id"]=56001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=56,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[57]={
		["start_id"]=57001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=57,
		["type"]=2,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[44]={
		["start_id"]=44001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=44,
		["type"]=2,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[45]={
		["start_id"]=45001,
		["client_type"]=3,
		["open_level"]=1,
		["sort"]=45,
		["type"]=2,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[-100]={
		["start_id"]=1001001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-100,
		["type"]=1,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[-99]={
		["start_id"]=1002001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-99,
		["type"]=1,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[-98]={
		["start_id"]=1003001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-98,
		["type"]=1,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[-97]={
		["start_id"]=1010001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-97,
		["type"]=1,
		["is_open"]=1,
		["is_done"]={
		},
	},
	[-96]={
		["start_id"]=1011001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-96,
		["type"]=1,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[-95]={
		["start_id"]=1012001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-95,
		["type"]=1,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[-94]={
		["start_id"]=1013001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-94,
		["type"]=1,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[-93]={
		["start_id"]=1013002,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-93,
		["type"]=1,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[-92]={
		["start_id"]=1013003,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-92,
		["type"]=1,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[-91]={
		["start_id"]=1004001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-91,
		["type"]=1,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[-90]={
		["start_id"]=1007001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-90,
		["type"]=1,
		["is_open"]=0,
		["is_done"]={
		},
	},
	[-50]={
		["start_id"]=1009001,
		["client_type"]=2,
		["open_level"]=1,
		["sort"]=-50,
		["type"]=2,
		["is_open"]=0,
		["is_done"]={
		},
	},
}