return {
	[1]={
		["name"]="营地大门",
		["status"]={
			80000002,
		},
		["turn_points"]=0,
		["onetime_points"]=0,
		["text"]="帮会大本营的大门,如果被占领则立即失败。\n在本区域作战，己方可以获得属性加成\n\n生命提升<color=#FF0000>30%</color>\n攻击提升<color=#FF0000>30%</color>",
		["img"]="guild_war_damen",
	},
	[2]={
		["name"]="护卫石像",
		["status"]={
			80000001,
		},
		["turn_points"]=0,
		["onetime_points"]=0,
		["text"]="极为重要的防御工事，营地大门之前的最后壁垒。\n在本区域作战，己方可以获得属性加成\n\n生命提升<color=#FF0000>20%</color>\n攻击提升<color=#FF0000>20%</color>",
		["img"]="guild_war_diaoxiang",
	},
	[3]={
		["name"]="烽火台",
		["status"]={
			80000005,
		},
		["turn_points"]=0,
		["onetime_points"]=0,
		["text"]="极为重要的防御工事\n可以占领方的所有单位获得属性加成\n\n生命提升<color=#FF0000>5%</color>\n攻击提升<color=#FF0000>5%</color>",
		["img"]="guild_war_fenghuotai",
	},
	[4]={
		["name"]="祭台",
		["status"]={
			80000003,
		},
		["turn_points"]=0,
		["onetime_points"]=0,
		["text"]="极为重要的防御工事\n可以使己方所有单位获得属性加成\n\n生命提升<color=#FF0000>10%</color>\n攻击提升<color=#FF0000>10%</color>",
		["img"]="guild_war_jitai",
	},
	[5]={
		["name"]="佛祖像",
		["status"]={
			80000004,
		},
		["turn_points"]=500,
		["onetime_points"]=0,
		["text"]="兵家必争之地\n占领该区域的帮会每日可获得积分奖励\n在本区域作战，疲劳效果加倍\n\n额外获得<color=#FF0000>500积分</color>",
		["img"]="guild_war_foxiang",
	},
	[0]={
		["name"]="空地",
		["status"]={
		},
		["turn_points"]=0,
		["onetime_points"]=0,
		["text"]="没有特别之处的平凡战场",
		["img"]="guild_war_kongdi",
	},
}