return {
	[1]={
		["icon"]="a_bh_icon_1",
		["unlock_level"]=1,
	},
	[2]={
		["icon"]="a_bh_icon_2",
		["unlock_level"]=1,
	},
	[3]={
		["icon"]="a_bh_icon_3",
		["unlock_level"]=1,
	},
	[4]={
		["icon"]="a_bh_icon_4",
		["unlock_level"]=1,
	},
	[5]={
		["icon"]="a_bh_icon_5",
		["unlock_level"]=3,
	},
	[6]={
		["icon"]="a_bh_icon_6",
		["unlock_level"]=5,
	},
	[7]={
		["icon"]="a_bh_icon_7",
		["unlock_level"]=7,
	},
	[8]={
		["icon"]="a_bh_icon_8",
		["unlock_level"]=9,
	},
	[9]={
		["icon"]="a_bh_icon_9",
		["unlock_level"]=10,
	},
	[10]={
		["icon"]="a_bh_icon_10",
		["unlock_level"]=12,
	},
}