return {
	[3]={
		[1]={
			["name"]="外出游历",
			["story"]="tid#Herolegend1_508",
		},
		[2]={
			["name"]="才名卓绝",
			["story"]="tid#Herolegend2_508",
		},
		[3]={
			["name"]="风流韵事",
			["story"]="tid#Herolegend3_508",
		},
		[4]={
			["name"]="魔高一尺",
			["story"]="tid#Herolegend4_508",
		},
		[5]={
			["name"]="锋芒初露",
			["story"]="tid#Herolegend5_508",
		},
		[6]={
			["name"]="枪破长空",
			["story"]="tid#herolegend6_508",
		},
		[7]={
			["name"]="英雄归来",
			["story"]="tid#herolegend7_508",
		},
	},
	[4]={
		[1]={
			["name"]="春神降世",
			["story"]="tid#Herolegend1_503",
		},
		[2]={
			["name"]="云隐结缘",
			["story"]="tid#Herolegend2_503",
		},
		[3]={
			["name"]="风起云涌",
			["story"]="tid#Herolegend3_503",
		},
		[4]={
			["name"]="别离故友",
			["story"]="tid#Herolegend4_503",
		},
		[5]={
			["name"]="探访中原",
			["story"]="tid#Herolegend5_503",
		},
		[6]={
			["name"]="终成九天",
			["story"]="tid#herolegend6_503",
		},
		[7]={
			["name"]="坚守正义",
			["story"]="tid#herolegend7_503",
		},
	},
	[5]={
		[1]={
			["name"]="有备无患",
			["story"]="tid#Herolegend1_608",
		},
		[2]={
			["name"]="悲惨过去",
			["story"]="tid#Herolegend2_608",
		},
		[3]={
			["name"]="崭露头角",
			["story"]="tid#Herolegend3_608",
		},
		[4]={
			["name"]="脱颖而出",
			["story"]="tid#Herolegend4_608",
		},
		[5]={
			["name"]="独孤一门",
			["story"]="tid#Herolegend5_608",
		},
		[6]={
			["name"]="复仇之火",
			["story"]="tid#herolegend6_608",
		},
		[7]={
			["name"]="重获新生",
			["story"]="tid#herolegend7_608",
		},
	},
	[6]={
		[1]={
			["name"]="月寒往事",
			["story"]="tid#Herolegend1_512",
		},
		[2]={
			["name"]="功法精进",
			["story"]="tid#Herolegend2_512",
		},
		[3]={
			["name"]="踏入江湖",
			["story"]="tid#Herolegend3_512",
		},
		[4]={
			["name"]="只身游历",
			["story"]="tid#Herolegend4_512",
		},
		[5]={
			["name"]="萍水相逢",
			["story"]="tid#Herolegend5_512",
		},
		[6]={
			["name"]="平静时光",
			["story"]="tid#herolegend6_512",
		},
		[7]={
			["name"]="复仇寒光",
			["story"]="tid#herolegend7_512",
		},
	},
	[7]={
		[1]={
			["name"]="身如浮萍",
			["story"]="tid#Herolegend1_705",
		},
		[2]={
			["name"]="江湖扬名",
			["story"]="tid#Herolegend2_705",
		},
		[3]={
			["name"]="身法精妙",
			["story"]="tid#Herolegend3_705",
		},
		[4]={
			["name"]="巧妙脱逃",
			["story"]="tid#Herolegend4_705",
		},
		[5]={
			["name"]="人生转折",
			["story"]="tid#Herolegend5_705",
		},
		[6]={
			["name"]="偶遇蓬莱",
			["story"]="tid#herolegend6_705",
		},
		[7]={
			["name"]="淡出江湖",
			["story"]="tid#herolegend7_705",
		},
	},
	[8]={
		[1]={
			["name"]="江湖扬名",
			["story"]="tid#Herolegend1_715",
		},
		[2]={
			["name"]="仗剑远游",
			["story"]="tid#Herolegend2_715",
		},
		[3]={
			["name"]="步入仕途",
			["story"]="tid#Herolegend3_715",
		},
		[4]={
			["name"]="天下历练",
			["story"]="tid#Herolegend4_715",
		},
		[5]={
			["name"]="一代宗师",
			["story"]="tid#Herolegend5_715",
		},
		[6]={
			["name"]="历尽艰险",
			["story"]="tid#herolegend6_715",
		},
		[7]={
			["name"]="谪仙归位",
			["story"]="tid#herolegend7_715",
		},
	},
}