return {
	[1]={
		[1]={
			["name"]="金币",
			["limit_time"]=1,
			["reward"]=432000,
		},
		[2]={
			["name"]="修为",
			["limit_time"]=1,
			["reward"]=432000,
		},
		[3]={
			["name"]="突破丹",
			["limit_time"]=1,
			["reward"]=216000,
		},
		[4]={
			["name"]="元宝",
			["limit_time"]=1,
			["reward"]=2000,
		},
		[5]={
			["name"]="抽卡券",
			["limit_time"]=1,
			["reward"]=20,
		},
		[6]={
			["name"]="种族抽",
			["limit_time"]=1,
			["reward"]=20,
		},
		[7]={
			["name"]="聚宝山骰子",
			["limit_time"]=1,
			["reward"]=30,
		},
		[10]={
			["name"]="银司南",
			["limit_time"]=1,
			["reward"]=40,
		},
		[11]={
			["name"]="金司南",
			["limit_time"]=1,
			["reward"]=10,
		},
		[12]={
			["name"]="闯王币",
			["limit_time"]=1,
			["reward"]=10000,
		},
		[13]={
			["name"]="演武币",
			["limit_time"]=1,
			["reward"]=10000,
		},
		[14]={
			["name"]="巅峰论剑币",
			["limit_time"]=1,
			["reward"]=1500,
		},
		[15]={
			["name"]="五行刀币",
			["limit_time"]=1,
			["reward"]=2000,
		},
		[16]={
			["name"]="黄金刀币",
			["limit_time"]=1,
			["reward"]=2000,
		},
		[17]={
			["name"]="交子",
			["limit_time"]=1,
			["reward"]=2000,
		},
		[8]={
			["name"]="付费快速挂机次数",
			["limit_time"]=1,
			["reward"]=5,
		},
		[9]={
			["name"]="四象阵次数",
			["limit_time"]=1,
			["reward"]=10,
		},
	},
}