return {
	[1]={
		[1]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=0.3,
				["atk"]=0.0,
			},
		},
		[2]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=0.8,
				["atk"]=0.0,
			},
		},
		[3]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=1.5,
				["atk"]=0.0,
			},
		},
		[4]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=2.5,
				["atk"]=0.0,
			},
		},
		[5]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=4.0,
				["atk"]=0.0,
			},
		},
		[6]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=5.0,
				["atk"]=0.0,
			},
		},
		[7]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=6.0,
				["atk"]=0.0,
			},
		},
		[8]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=7.0,
				["atk"]=0.0,
			},
		},
		[9]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=8.0,
				["atk"]=0.0,
			},
		},
		[10]={
			["unlock_type"]=1,
			["unlock_param"]=100,
			["attr_add"]={
				["hp"]=12.0,
				["atk"]=0.0,
			},
		},
		[11]={
			["unlock_type"]=1,
			["unlock_param"]=200,
			["attr_add"]={
				["hp"]=16.0,
				["atk"]=0.0,
			},
		},
		[12]={
			["unlock_type"]=1,
			["unlock_param"]=260,
			["attr_add"]={
				["hp"]=20.0,
				["atk"]=0.0,
			},
		},
		[13]={
			["unlock_type"]=1,
			["unlock_param"]=300,
			["attr_add"]={
				["hp"]=24.0,
				["atk"]=0.0,
			},
		},
		[14]={
			["unlock_type"]=1,
			["unlock_param"]=340,
			["attr_add"]={
				["hp"]=28.0,
				["atk"]=0.0,
			},
		},
		[15]={
			["unlock_type"]=1,
			["unlock_param"]=380,
			["attr_add"]={
				["hp"]=32.0,
				["atk"]=0.0,
			},
		},
		[16]={
			["unlock_type"]=1,
			["unlock_param"]=420,
			["attr_add"]={
				["hp"]=40.0,
				["atk"]=0.0,
			},
		},
		[17]={
			["unlock_type"]=1,
			["unlock_param"]=460,
			["attr_add"]={
				["hp"]=48.0,
				["atk"]=0.0,
			},
		},
		[18]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=56.0,
				["atk"]=0.0,
			},
		},
		[19]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=64.0,
				["atk"]=0.0,
			},
		},
		[20]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=72.0,
				["atk"]=0.0,
			},
		},
		[21]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=80.0,
				["atk"]=0.0,
			},
		},
		[22]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=88.0,
				["atk"]=0.0,
			},
		},
		[23]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=96.0,
				["atk"]=0.0,
			},
		},
		[24]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=104.0,
				["atk"]=0.0,
			},
		},
		[25]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=112.0,
				["atk"]=0.0,
			},
		},
		[26]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=120.0,
				["atk"]=0.0,
			},
		},
		[27]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=128.0,
				["atk"]=0.0,
			},
		},
		[28]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=136.0,
				["atk"]=0.0,
			},
		},
		[29]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=144.0,
				["atk"]=0.0,
			},
		},
		[30]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=152.0,
				["atk"]=0.0,
			},
		},
		[31]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=160.0,
				["atk"]=0.0,
			},
		},
		[32]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=168.0,
				["atk"]=0.0,
			},
		},
		[33]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=176.0,
				["atk"]=0.0,
			},
		},
		[34]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=184.0,
				["atk"]=0.0,
			},
		},
		[35]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=192.0,
				["atk"]=0.0,
			},
		},
		[36]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=200.0,
				["atk"]=0.0,
			},
		},
		[37]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=208.0,
				["atk"]=0.0,
			},
		},
		[38]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=216.0,
				["atk"]=0.0,
			},
		},
		[39]={
			["unlock_type"]=1,
			["unlock_param"]=490,
			["attr_add"]={
				["hp"]=224.0,
				["atk"]=0.0,
			},
		},
		[40]={
			["unlock_type"]=1,
			["unlock_param"]=500,
			["attr_add"]={
				["hp"]=324.0,
				["atk"]=0.0,
			},
		},
		[41]={
			["unlock_type"]=1,
			["unlock_param"]=505,
			["attr_add"]={
				["hp"]=424.0,
				["atk"]=0.0,
			},
		},
		[42]={
			["unlock_type"]=1,
			["unlock_param"]=510,
			["attr_add"]={
				["hp"]=524.0,
				["atk"]=0.0,
			},
		},
		[43]={
			["unlock_type"]=1,
			["unlock_param"]=515,
			["attr_add"]={
				["hp"]=624.0,
				["atk"]=0.0,
			},
		},
		[44]={
			["unlock_type"]=1,
			["unlock_param"]=520,
			["attr_add"]={
				["hp"]=724.0,
				["atk"]=0.0,
			},
		},
		[45]={
			["unlock_type"]=1,
			["unlock_param"]=525,
			["attr_add"]={
				["hp"]=824.0,
				["atk"]=0.0,
			},
		},
		[46]={
			["unlock_type"]=1,
			["unlock_param"]=530,
			["attr_add"]={
				["hp"]=924.0,
				["atk"]=0.0,
			},
		},
		[47]={
			["unlock_type"]=1,
			["unlock_param"]=535,
			["attr_add"]={
				["hp"]=1024.0,
				["atk"]=0.0,
			},
		},
		[48]={
			["unlock_type"]=1,
			["unlock_param"]=540,
			["attr_add"]={
				["hp"]=1124.0,
				["atk"]=0.0,
			},
		},
		[49]={
			["unlock_type"]=1,
			["unlock_param"]=545,
			["attr_add"]={
				["hp"]=1224.0,
				["atk"]=0.0,
			},
		},
		[50]={
			["unlock_type"]=1,
			["unlock_param"]=0,
			["attr_add"]={
				["hp"]=1324.0,
				["atk"]=0.0,
			},
		},
	},
	[2]={
		[1]={
			["unlock_type"]=2,
			["unlock_param"]=60,
			["attr_add"]={
				["hp"]=1.0,
				["atk"]=0.0,
			},
		},
		[2]={
			["unlock_type"]=2,
			["unlock_param"]=60,
			["attr_add"]={
				["hp"]=1.0,
				["atk"]=0.2,
			},
		},
		[3]={
			["unlock_type"]=2,
			["unlock_param"]=60,
			["attr_add"]={
				["hp"]=1.0,
				["atk"]=0.5,
			},
		},
		[4]={
			["unlock_type"]=2,
			["unlock_param"]=60,
			["attr_add"]={
				["hp"]=1.0,
				["atk"]=0.8,
			},
		},
		[5]={
			["unlock_type"]=2,
			["unlock_param"]=60,
			["attr_add"]={
				["hp"]=1.0,
				["atk"]=1.0,
			},
		},
		[6]={
			["unlock_type"]=2,
			["unlock_param"]=60,
			["attr_add"]={
				["hp"]=1.0,
				["atk"]=1.5,
			},
		},
		[7]={
			["unlock_type"]=2,
			["unlock_param"]=60,
			["attr_add"]={
				["hp"]=1.0,
				["atk"]=2.5,
			},
		},
		[8]={
			["unlock_type"]=2,
			["unlock_param"]=60,
			["attr_add"]={
				["hp"]=1.0,
				["atk"]=3.0,
			},
		},
		[9]={
			["unlock_type"]=2,
			["unlock_param"]=0,
			["attr_add"]={
				["hp"]=1.0,
				["atk"]=4.0,
			},
		},
	},
}