return {
	[401]={
		[1]={
			[1]={
				["type"]=1,
				["quest"]="tid#LuckybagLogin1",
				["target_day"]=1,
				["quest_name"]="今日登录",
				["share"]=0,
				["refresh"]=1,
				["reward"]={
					{
						103,
						5583,
						1,
					},
				},
				["bag_content"]={
					{
						107,
						0,
						66666,
					},
					{
						103,
						5222,
						1,
					},
					{
						103,
						1412,
						1,
					},
					{
						103,
						5195,
						1,
					},
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[2]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin30",
				["target_day"]=5,
				["quest_name"]="5天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[3]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin100",
				["target_day"]=10,
				["quest_name"]="10天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						1888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[4]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin200",
				["target_day"]=20,
				["quest_name"]="20天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						2888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[5]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin365",
				["target_day"]=30,
				["quest_name"]="30天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						3888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[6]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin500",
				["target_day"]=45,
				["quest_name"]="45天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						3888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[7]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=60,
				["quest_name"]="60天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						3888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[8]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=75,
				["quest_name"]="75天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						3888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[9]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=90,
				["quest_name"]="90天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						3888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[10]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=120,
				["quest_name"]="120天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						5888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[11]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=150,
				["quest_name"]="150天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						5888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[12]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=180,
				["quest_name"]="180天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						5888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[13]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=210,
				["quest_name"]="210天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						5888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[14]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=240,
				["quest_name"]="240天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						6666,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[15]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=270,
				["quest_name"]="270天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						6666,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[16]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=300,
				["quest_name"]="300天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						6666,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[17]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=330,
				["quest_name"]="330天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						6666,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[18]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=365,
				["quest_name"]="365天",
				["share"]=1,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						28888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
					{
						103,
						90004,
						1,
					},
					{
						142,
						30112,
						1,
					},
					{
						101,
						716,
						1,
					},
					{
						122,
						62,
						1,
					},
				},
				["mail_id"]=227,
			},
			[19]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=400,
				["quest_name"]="400天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						18888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[20]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=450,
				["quest_name"]="450天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						18888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[21]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=500,
				["quest_name"]="500天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						18888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[22]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=550,
				["quest_name"]="550天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						18888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[23]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=600,
				["quest_name"]="600天",
				["share"]=1,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						58888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=227,
			},
			[24]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=650,
				["quest_name"]="650天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						18888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[25]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=700,
				["quest_name"]="700天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						18888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[26]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=760,
				["quest_name"]="760天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						28888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[27]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=820,
				["quest_name"]="820天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						28888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[28]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=880,
				["quest_name"]="880天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						28888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[29]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=940,
				["quest_name"]="940天",
				["share"]=0,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						28888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=0,
			},
			[30]={
				["type"]=2,
				["quest"]="tid#LuckybagLogin900",
				["target_day"]=1000,
				["quest_name"]="1000天",
				["share"]=1,
				["refresh"]=0,
				["reward"]={
					{
						107,
						0,
						88888,
					},
				},
				["bag_content"]={
				},
				["share_reward"]={
				},
				["mail_id"]=227,
			},
		},
	},
}