return {
	[91]={
		["entrance_pic"]="regional_ls_101",
		["name"]="江南",
		["quantity"]=156,
		["item_reward"]={
			{
				103,
				1010,
				10,
			},
		},
		["unlock"]=0,
		["complete_resources"]="a_map_jq_daditu",
		["map_resources"]="a_ui_jianghu_daditu",
		["sections_name"]="剑荡江南",
		["season"]=0,
	},
	[92]={
		["entrance_pic"]="regional_ls_101002",
		["name"]="中原",
		["quantity"]=0,
		["item_reward"]={
			{
				103,
				1010,
				10,
			},
		},
		["unlock"]=832,
		["complete_resources"]="a_map_jq_daditu",
		["map_resources"]="a_ui_jianghu_daditu",
		["sections_name"]="逐鹿中原",
		["season"]=0,
	},
	[93]={
		["entrance_pic"]="regional_ls_101001",
		["name"]="陇右",
		["quantity"]=0,
		["item_reward"]={
			{
				103,
				1010,
				10,
			},
		},
		["unlock"]=1601,
		["complete_resources"]="a_map_jq_daditu",
		["map_resources"]="a_ui_jianghu_daditu",
		["sections_name"]="塞外风云",
		["season"]=1,
	},
	[94]={
		["entrance_pic"]="regional_ls_101001",
		["name"]="巴蜀",
		["quantity"]=0,
		["item_reward"]={
			{
				103,
				1010,
				10,
			},
		},
		["unlock"]=2401,
		["complete_resources"]="a_map_jq_daditu",
		["map_resources"]="a_ui_jianghu_daditu",
		["sections_name"]="千里侠行",
		["season"]=2,
	},
}