return {
	[101]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[102]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=1,
		["gain"]="",
		["UI_effect"]="",
	},
	[103]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=1,
		["gain"]="",
		["UI_effect"]="",
	},
	[104]={
		["name"]="tid#MoneyGuide_104",
		["go_type"]={
			30,
			31,
			10037,
		},
		["item_id"]={
			1501,
			1502,
			1503,
			1504,
			1513,
			1514,
			1515,
			1516,
			1529,
			1530,
			1531,
			1532,
		},
		["story"]="tid#MoneyGuide_1104",
		["itype"]=1,
		["user_key"]="coin",
		["icon"]="DJ_tongqian",
		["sort"]=2,
		["num"]={
			2,
			4,
			8,
			12,
			999999999,
		},
		["quality"]={
			2,
			3,
			5,
			6,
			7,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_104",
		["UI_effect"]="",
	},
	[105]={
		["name"]="tid#MoneyGuide_105",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1105",
		["itype"]=1,
		["user_key"]="exp",
		["icon"]="DJ_yueli",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			3,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_105",
		["UI_effect"]="",
	},
	[106]={
		["name"]="tid#MoneyGuide_106",
		["go_type"]={
			30,
			31,
			10037,
		},
		["item_id"]={
			1509,
			1510,
			1511,
			1512,
			1513,
			1514,
			1515,
			1516,
		},
		["story"]="tid#MoneyGuide_1106",
		["itype"]=1,
		["user_key"]="dust",
		["icon"]="DJ_tupodan",
		["sort"]=1,
		["num"]={
			49,
			99,
			499,
			999,
			999999999,
		},
		["quality"]={
			2,
			3,
			5,
			6,
			7,
		},
		["if_inbag"]=1,
		["gain"]="tid#money_guide_gain_106",
		["UI_effect"]="",
	},
	[107]={
		["name"]="tid#MoneyGuide_107",
		["go_type"]={
			10037,
			10017,
		},
		["item_id"]={
			1517,
			1518,
			1519,
			1520,
		},
		["story"]="tid#MoneyGuide_1107",
		["itype"]=1,
		["user_key"]="diamond",
		["icon"]="DJ_yuanbao",
		["sort"]=1,
		["num"]={
			99,
			499,
			999,
			999999999,
		},
		["quality"]={
			3,
			5,
			6,
			7,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_107",
		["UI_effect"]="",
	},
	[108]={
		["name"]="tid#MoneyGuide_108",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1108",
		["itype"]=1,
		["user_key"]="vip_exp",
		["icon"]="DJ_VIPyueli",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_108",
		["UI_effect"]="",
	},
	[109]={
		["name"]="tid#MoneyGuide_109",
		["go_type"]={
			18,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1109",
		["itype"]=1,
		["user_key"]="maze_coin",
		["icon"]="icon_mizangbi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			3,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_109",
		["UI_effect"]="",
	},
	[110]={
		["name"]="tid#MoneyGuide_110",
		["go_type"]={
			30,
			31,
			10037,
		},
		["item_id"]={
			1505,
			1506,
			1507,
			1508,
			1513,
			1514,
			1515,
			1516,
		},
		["story"]="tid#MoneyGuide_1110",
		["itype"]=1,
		["user_key"]="hero_exp",
		["icon"]="DJ_jingyan",
		["sort"]=2,
		["num"]={
			2,
			4,
			8,
			12,
			999999999,
		},
		["quality"]={
			2,
			3,
			5,
			6,
			7,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_110",
		["UI_effect"]="",
	},
	[111]={
		["name"]="tid#MoneyGuide_111",
		["go_type"]={
			9,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1111",
		["itype"]=1,
		["user_key"]="hero_coin",
		["icon"]="DJ_daibi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_111",
		["UI_effect"]="",
	},
	[112]={
		["name"]="tid#MoneyGuide_112",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1112",
		["itype"]=1,
		["user_key"]="crystal",
		["icon"]="icon_shenshushuidi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_112",
		["UI_effect"]="",
	},
	[113]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1113",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[114]={
		["name"]="tid#MoneyGuide_114",
		["go_type"]={
			11,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1114",
		["itype"]=1,
		["user_key"]="friend_coin",
		["icon"]="DJ_youqing",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			3,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_114",
		["UI_effect"]="",
	},
	[115]={
		["name"]="tid#MoneyGuide_115",
		["go_type"]={
			23,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1115",
		["itype"]=1,
		["user_key"]="guild_coin",
		["icon"]="icon_banghuibi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_115",
		["UI_effect"]="",
	},
	[116]={
		["name"]="tid#MoneyGuide_116",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1116",
		["itype"]=1,
		["user_key"]="valor_medals",
		["icon"]="a_fl_icon_jingyan_diji",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_116",
		["UI_effect"]="",
	},
	[117]={
		["name"]="tid#MoneyGuide_117",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1117",
		["itype"]=1,
		["user_key"]="heroic_merit",
		["icon"]="a_fl_icon_jingyan_gaoji",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_117",
		["UI_effect"]="",
	},
	[118]={
		["name"]="tid#MoneyGuide_118",
		["go_type"]={
			25,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1118",
		["itype"]=1,
		["user_key"]="arena_coin",
		["icon"]="icon_jingjichangbi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_118",
		["UI_effect"]="",
	},
	[119]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=1,
		["gain"]="",
		["UI_effect"]="",
	},
	[120]={
		["name"]="tid#MoneyGuide_120",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1120",
		["itype"]=1,
		["user_key"]="guild_exp",
		["icon"]="icon_banghuijianshezhi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			3,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_120",
		["UI_effect"]="",
	},
	[1]={
		["name"]="tid#MoneyGuide_1070",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1107",
		["itype"]=1,
		["user_key"]="diamond",
		["icon"]="DJ_yuanbao",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[201]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[301]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[302]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[303]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=0,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[304]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[121]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=1,
		["gain"]="",
		["UI_effect"]="",
	},
	[122]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[123]={
		["name"]="tid#MoneyGuide_123",
		["go_type"]={
			30,
			31,
			10,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1123",
		["itype"]=1,
		["user_key"]="power_exp",
		["icon"]="waigong_exp",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_123",
		["UI_effect"]="",
	},
	[124]={
		["name"]="tid#MoneyGuide_124",
		["go_type"]={
			30,
			31,
			10,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1124",
		["itype"]=1,
		["user_key"]="speed_exp",
		["icon"]="shenfa_exp",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_124",
		["UI_effect"]="",
	},
	[125]={
		["name"]="tid#MoneyGuide_125",
		["go_type"]={
			30,
			31,
			10,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1125",
		["itype"]=1,
		["user_key"]="force_exp",
		["icon"]="neigong_exp",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_125",
		["UI_effect"]="",
	},
	[126]={
		["name"]="tid#MoneyGuide_126",
		["go_type"]={
			30,
			31,
			10,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1126",
		["itype"]=1,
		["user_key"]="super_exp",
		["icon"]="jueji_exp",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_126",
		["UI_effect"]="",
	},
	[127]={
		["name"]="tid#MoneyGuide_127",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1127",
		["itype"]=1,
		["user_key"]="tripod_coin",
		["icon"]="icon_qifudian",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_127",
		["UI_effect"]="",
	},
	[128]={
		["name"]="tid#MoneyGuide_128",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1128",
		["itype"]=1,
		["user_key"]="",
		["icon"]="a_ui_youqingdian",
		["sort"]=1,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_128",
		["UI_effect"]="",
	},
	[129]={
		["name"]="tid#MoneyGuide_129",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1129",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_129",
		["UI_effect"]="",
	},
	[130]={
		["name"]="tid#MoneyGuide_130",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1130",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			8,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[131]={
		["name"]="tid#MoneyGuide_131",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1131",
		["itype"]=1,
		["user_key"]="thief_coin",
		["icon"]="icon_daoshuaibi_big",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			9,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="UI_ItemNode_Glow_002",
	},
	[132]={
		["name"]="tid#MoneyGuide_132",
		["go_type"]={
			24,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1132",
		["itype"]=1,
		["user_key"]="race_arena_coin",
		["icon"]="icon_daobi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			3,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[133]={
		["name"]="tid#MoneyGuide_133",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1133",
		["itype"]=1,
		["user_key"]="high_arena_coin",
		["icon"]="icon_yanwubi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			3,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[134]={
		["name"]="tid#MoneyGuide_134",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1134",
		["itype"]=1,
		["user_key"]="top_arena_coin",
		["icon"]="icon_longtingzi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[135]={
		["name"]="tid#MoneyGuide_135",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1135",
		["itype"]=1,
		["user_key"]="quiz_coin",
		["icon"]="icon_yupei",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			3,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[136]={
		["name"]="tid#MoneyGuide_136",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1136",
		["itype"]=1,
		["user_key"]="richman_point",
		["icon"]="icon_jiaozi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[137]={
		["name"]="tid#MoneyGuide_137",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1137",
		["itype"]=1,
		["user_key"]="voucher",
		["icon"]="icon_daijinquan",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="UI_ItemNode_Glow_002",
	},
	[138]={
		["name"]="tid#MoneyGuide_138",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1138",
		["itype"]=1,
		["user_key"]="top_race_arena_coin",
		["icon"]="icon_tianjidaobi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[139]={
		["name"]="tid#MoneyGuide_139",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1139",
		["itype"]=1,
		["user_key"]="relic_coin",
		["icon"]="icon_neigongT5",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[140]={
		["name"]="tid#MoneyGuide_140",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1140",
		["itype"]=2,
		["user_key"]="relic",
		["icon"]="icon_neigongT5",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[141]={
		["name"]="tid#MoneyGuide_141",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1141",
		["itype"]=2,
		["user_key"]="ft_heirloom  ",
		["icon"]="icon_neigongT5",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[142]={
		["name"]="tid#MoneyGuide_142",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1142",
		["itype"]=2,
		["user_key"]="title",
		["icon"]="icon_chenghao_tongyong",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[143]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=1,
		["gain"]="",
		["UI_effect"]="",
	},
	[144]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[145]={
		["name"]="tid#MoneyGuide_144",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1144",
		["itype"]=1,
		["user_key"]="mining_gold_coin",
		["icon"]="icon_mjmb_jin",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[146]={
		["name"]="tid#MoneyGuide_145",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1145",
		["itype"]=1,
		["user_key"]="mining_wood_coin",
		["icon"]="icon_mjmb_mu",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[147]={
		["name"]="tid#MoneyGuide_146",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1146",
		["itype"]=1,
		["user_key"]="mining_water_coin",
		["icon"]="icon_mjmb_shui",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[148]={
		["name"]="tid#MoneyGuide_147",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1147",
		["itype"]=1,
		["user_key"]="mining_fire_coin",
		["icon"]="icon_mjmb_huo",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[149]={
		["name"]="tid#MoneyGuide_149",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1149",
		["itype"]=1,
		["user_key"]="season_coin",
		["icon"]="icon_jifen",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[150]={
		["name"]="tid#MoneyGuide_150",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1150",
		["itype"]=1,
		["user_key"]="chenghao_coin",
		["icon"]="icon_chenghao_tongyong_suipian",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[151]={
		["name"]="tid#MoneyGuide_151",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1151",
		["itype"]=2,
		["user_key"]="dt_heirloom",
		["icon"]="icon_neigongT5",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[152]={
		["name"]="tid#MoneyGuide_152",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1152",
		["itype"]=1,
		["user_key"]="guild_relic_exp",
		["icon"]="icon_neigongT52",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_152",
		["UI_effect"]="",
	},
	[153]={
		["name"]="tid#MoneyGuide_153",
		["go_type"]={
			30,
			31,
			10037,
		},
		["item_id"]={
			1529,
			1530,
			1531,
			1532,
		},
		["story"]="tid#MoneyGuide_1153",
		["itype"]=1,
		["user_key"]="equip_exp",
		["icon"]="icon_yuntiechen",
		["sort"]=1,
		["num"]={
			16,
			999999999,
		},
		["quality"]={
			5,
			6,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_110",
		["UI_effect"]="",
	},
	[154]={
		["name"]="tid#MoneyGuide_154",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1154",
		["itype"]=1,
		["user_key"]="newyear2022_gacha",
		["icon"]="icon_xinnian_hutoumao",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			9,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="UI_ItemNode_Glow_002",
	},
	[155]={
		["name"]="tid#MoneyGuide_155",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1155",
		["itype"]=1,
		["user_key"]="arena_mountain_hua_coin",
		["icon"]="icon_xuantiesuipian",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			9,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="UI_ItemNode_Glow_002",
	},
	[156]={
		["name"]="tid#MoneyGuide_156",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1156",
		["itype"]=1,
		["user_key"]="act_mining_silver",
		["icon"]="icon_xianglian",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[157]={
		["name"]="tid#MoneyGuide_157",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1157",
		["itype"]=1,
		["user_key"]="act_mining_coin",
		["icon"]="icon_xiaobao",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[158]={
		["name"]="tid#MoneyGuide_158",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1158",
		["itype"]=1,
		["user_key"]="flagon",
		["icon"]="icon_jiuhu",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[159]={
		["name"]="tid#MoneyGuide_159",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1159",
		["itype"]=1,
		["user_key"]="medal",
		["icon"]="icon_qiyu",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[160]={
		["name"]="tid#MoneyGuide_160",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1160",
		["itype"]=1,
		["user_key"]="myth_coin",
		["icon"]="a_wlsh_jifendaoju",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			8,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[161]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1161",
		["itype"]=2,
		["user_key"]="",
		["icon"]="a_icon_chongwudan",
		["sort"]=1,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[162]={
		["name"]="tid#MoneyGuide_162",
		["go_type"]={
			91,
			92,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1162",
		["itype"]=1,
		["user_key"]="pet_exp",
		["icon"]="a_icon_chongwujingyandan",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_1162",
		["UI_effect"]="",
	},
	[163]={
		["name"]="tid#MoneyGuide_163",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1163",
		["itype"]=1,
		["user_key"]="pet_coin",
		["icon"]="a_icon_chongwubi",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[164]={
		["name"]="",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1164",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[165]={
		["name"]="tid#MoneyGuide_165",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1165",
		["itype"]=1,
		["user_key"]="",
		["icon"]="jinbi",
		["sort"]=1,
		["num"]={
		},
		["quality"]={
			5,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_1165",
		["UI_effect"]="",
	},
	[166]={
		["name"]="tid#MoneyGuide_165",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1166",
		["itype"]=2,
		["user_key"]="record",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			8,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_166",
		["UI_effect"]="",
	},
	[167]={
		["name"]="tid#MoneyGuide_166",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1167",
		["itype"]=1,
		["user_key"]="auction_coin",
		["icon"]="icon_longtingzi",
		["sort"]=1,
		["num"]={
		},
		["quality"]={
			8,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_167",
		["UI_effect"]="",
	},
	[168]={
		["name"]="tid#MoneyGuide_168",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1168",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			8,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_168",
		["UI_effect"]="",
	},
	[170]={
		["name"]="tid#MoneyGuide_170",
		["go_type"]={
			43,
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1170",
		["itype"]=2,
		["user_key"]="",
		["icon"]="icon_fuzhuan_tuwei",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
			8,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_170",
		["UI_effect"]="",
	},
	[171]={
		["name"]="tid#MoneyGuide_171",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1171",
		["itype"]=1,
		["user_key"]="ghw_coin",
		["icon"]="icon_waigongT4",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_171",
		["UI_effect"]="",
	},
	[172]={
		["name"]="tid#MoneyGuide_172",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1172",
		["itype"]=1,
		["user_key"]="full_service_coin",
		["icon"]="icon_sixiangqi",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_172",
		["UI_effect"]="",
	},
	[173]={
		["name"]="tid#MoneyGuide_173",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="",
		["itype"]=2,
		["user_key"]="",
		["icon"]="",
		["sort"]=0,
		["num"]={
		},
		["quality"]={
		},
		["if_inbag"]=0,
		["gain"]="",
		["UI_effect"]="",
	},
	[174]={
		["name"]="tid#MoneyGuide_174",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1174",
		["itype"]=1,
		["user_key"]="guild_talent_coin",
		["icon"]="a_icon_sjjzbh",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_174",
		["UI_effect"]="",
	},
	[175]={
		["name"]="tid#MoneyGuide_175",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1175",
		["itype"]=1,
		["user_key"]="talent_attr_coin",
		["icon"]="a_icon_sjjzbb",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_175",
		["UI_effect"]="",
	},
	[176]={
		["name"]="tid#MoneyGuide_176",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1176",
		["itype"]=1,
		["user_key"]="talent_buff_coin",
		["icon"]="a_icon_sjjzbl",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_176",
		["UI_effect"]="",
	},
	[177]={
		["name"]="tid#MoneyGuide_177",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1177",
		["itype"]=2,
		["user_key"]="talent_attr_coin",
		["icon"]="a_icon_sjjzbl",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=1,
		["gain"]="tid#money_guide_gain_176",
		["UI_effect"]="",
	},
	[178]={
		["name"]="tid#MoneyGuide_178",
		["go_type"]={
		},
		["item_id"]={
		},
		["story"]="tid#MoneyGuide_1178",
		["itype"]=1,
		["user_key"]="hero_isle_coin",
		["icon"]="icon_neigongT2",
		["sort"]=1,
		["num"]={
			999999999,
		},
		["quality"]={
			6,
		},
		["if_inbag"]=0,
		["gain"]="tid#money_guide_gain_178",
		["UI_effect"]="",
	},
}