return {
	[20101]={
		["name"]="tid#MysticBuffName_20101",
		["des"]="tid#MysticBuffDes_20101",
		["param"]={
			100020101,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20103]={
		["name"]="tid#MysticBuffName_20103",
		["des"]="tid#MysticBuffDes_20103",
		["param"]={
			100020103,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20105]={
		["name"]="tid#MysticBuffName_20105",
		["des"]="tid#MysticBuffDes_20105",
		["param"]={
			100020105,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20201]={
		["name"]="tid#MysticBuffName_20201",
		["des"]="tid#MysticBuffDes_20201",
		["param"]={
			100020201,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[20203]={
		["name"]="tid#MysticBuffName_20203",
		["des"]="tid#MysticBuffDes_20203",
		["param"]={
			100020203,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[20205]={
		["name"]="tid#MysticBuffName_20205",
		["des"]="tid#MysticBuffDes_20205",
		["param"]={
			100020205,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[20301]={
		["name"]="tid#MysticBuffName_20301",
		["des"]="tid#MysticBuffDes_20301",
		["param"]={
			100020301,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"time",
		},
		["condition_param"]={
			{
				{
					"time",
					30720,
				},
			},
		},
		["des_class"]="",
	},
	[20303]={
		["name"]="tid#MysticBuffName_20303",
		["des"]="tid#MysticBuffDes_20303",
		["param"]={
			100020303,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"time",
		},
		["condition_param"]={
			{
				{
					"time",
					30720,
				},
			},
		},
		["des_class"]="",
	},
	[20305]={
		["name"]="tid#MysticBuffName_20305",
		["des"]="tid#MysticBuffDes_20305",
		["param"]={
			100020305,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"time",
		},
		["condition_param"]={
			{
				{
					"time",
					30720,
				},
			},
		},
		["des_class"]="",
	},
	[20401]={
		["name"]="tid#MysticBuffName_20401",
		["des"]="tid#MysticBuffDes_20401",
		["param"]={
			100020401,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					204,
				},
			},
		},
		["des_class"]="",
	},
	[20403]={
		["name"]="tid#MysticBuffName_20403",
		["des"]="tid#MysticBuffDes_20403",
		["param"]={
			100020403,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					204,
				},
			},
		},
		["des_class"]="",
	},
	[20405]={
		["name"]="tid#MysticBuffName_20405",
		["des"]="tid#MysticBuffDes_20405",
		["param"]={
			100020405,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					204,
				},
			},
		},
		["des_class"]="",
	},
	[20501]={
		["name"]="tid#MysticBuffName_20501",
		["des"]="tid#MysticBuffDes_20501",
		["param"]={
			100020501,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20503]={
		["name"]="tid#MysticBuffName_20503",
		["des"]="tid#MysticBuffDes_20503",
		["param"]={
			100020503,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20505]={
		["name"]="tid#MysticBuffName_20505",
		["des"]="tid#MysticBuffDes_20505",
		["param"]={
			100020505,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20601]={
		["name"]="tid#MysticBuffName_20601",
		["des"]="tid#MysticBuffDes_20601",
		["param"]={
			100020601,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"buff",
		},
		["condition_param"]={
			{
				{
					"tag",
					"pojia",
				},
				{
					"tag",
					"zhongdu",
				},
				{
					"tag",
					"liuxue",
				},
			},
		},
		["des_class"]="",
	},
	[20603]={
		["name"]="tid#MysticBuffName_20603",
		["des"]="tid#MysticBuffDes_20603",
		["param"]={
			100020603,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"buff",
		},
		["condition_param"]={
			{
				{
					"tag",
					"pojia",
				},
				{
					"tag",
					"zhongdu",
				},
				{
					"tag",
					"liuxue",
				},
			},
		},
		["des_class"]="",
	},
	[20605]={
		["name"]="tid#MysticBuffName_20605",
		["des"]="tid#MysticBuffDes_20605",
		["param"]={
			100020605,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"buff",
		},
		["condition_param"]={
			{
				{
					"tag",
					"pojia",
				},
				{
					"tag",
					"zhongdu",
				},
				{
					"tag",
					"liuxue",
				},
			},
		},
		["des_class"]="",
	},
	[20701]={
		["name"]="tid#MysticBuffName_20701",
		["des"]="tid#MysticBuffDes_20701",
		["param"]={
			100020701,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20703]={
		["name"]="tid#MysticBuffName_20703",
		["des"]="tid#MysticBuffDes_20703",
		["param"]={
			100020703,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20705]={
		["name"]="tid#MysticBuffName_20705",
		["des"]="tid#MysticBuffDes_20705",
		["param"]={
			100020705,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20801]={
		["name"]="tid#MysticBuffName_20801",
		["des"]="tid#MysticBuffDes_20801",
		["param"]={
			100020801,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[20803]={
		["name"]="tid#MysticBuffName_20803",
		["des"]="tid#MysticBuffDes_20803",
		["param"]={
			100020803,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[20805]={
		["name"]="tid#MysticBuffName_20805",
		["des"]="tid#MysticBuffDes_20805",
		["param"]={
			100020805,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[20901]={
		["name"]="tid#MysticBuffName_20901",
		["des"]="tid#MysticBuffDes_20901",
		["param"]={
			100020901,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"time",
		},
		["condition_param"]={
			{
				{
					"time",
					30720,
				},
			},
		},
		["des_class"]="",
	},
	[20903]={
		["name"]="tid#MysticBuffName_20903",
		["des"]="tid#MysticBuffDes_20903",
		["param"]={
			100020903,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"time",
		},
		["condition_param"]={
			{
				{
					"time",
					30720,
				},
			},
		},
		["des_class"]="",
	},
	[20905]={
		["name"]="tid#MysticBuffName_20905",
		["des"]="tid#MysticBuffDes_20905",
		["param"]={
			100020905,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"time",
		},
		["condition_param"]={
			{
				{
					"time",
					30720,
				},
			},
		},
		["des_class"]="",
	},
	[21001]={
		["name"]="tid#MysticBuffName_21001",
		["des"]="tid#MysticBuffDes_21001",
		["param"]={
			100021001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					204,
				},
			},
		},
		["des_class"]="",
	},
	[21003]={
		["name"]="tid#MysticBuffName_21003",
		["des"]="tid#MysticBuffDes_21003",
		["param"]={
			100021003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					204,
				},
			},
		},
		["des_class"]="",
	},
	[21005]={
		["name"]="tid#MysticBuffName_21005",
		["des"]="tid#MysticBuffDes_21005",
		["param"]={
			100021005,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					204,
				},
			},
		},
		["des_class"]="",
	},
	[30101]={
		["name"]="tid#MysticBuffName_30101",
		["des"]="tid#MysticBuffDes_30101",
		["param"]={
			100030101,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[30103]={
		["name"]="tid#MysticBuffName_30103",
		["des"]="tid#MysticBuffDes_30103",
		["param"]={
			100030103,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[30105]={
		["name"]="tid#MysticBuffName_30105",
		["des"]="tid#MysticBuffDes_30105",
		["param"]={
			100030105,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[30201]={
		["name"]="tid#MysticBuffName_30201",
		["des"]="tid#MysticBuffDes_30201",
		["param"]={
			100030201,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[30203]={
		["name"]="tid#MysticBuffName_30203",
		["des"]="tid#MysticBuffDes_30203",
		["param"]={
			100030203,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[30205]={
		["name"]="tid#MysticBuffName_30205",
		["des"]="tid#MysticBuffDes_30205",
		["param"]={
			100030205,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[30301]={
		["name"]="tid#MysticBuffName_30301",
		["des"]="tid#MysticBuffDes_30301",
		["param"]={
			100030301,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[30303]={
		["name"]="tid#MysticBuffName_30303",
		["des"]="tid#MysticBuffDes_30303",
		["param"]={
			100030303,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[30305]={
		["name"]="tid#MysticBuffName_30305",
		["des"]="tid#MysticBuffDes_30305",
		["param"]={
			100030305,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[30401]={
		["name"]="tid#MysticBuffName_30401",
		["des"]="tid#MysticBuffDes_30401",
		["param"]={
			100030401,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[30403]={
		["name"]="tid#MysticBuffName_30403",
		["des"]="tid#MysticBuffDes_30403",
		["param"]={
			100030403,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[30405]={
		["name"]="tid#MysticBuffName_30405",
		["des"]="tid#MysticBuffDes_30405",
		["param"]={
			100030405,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[30501]={
		["name"]="tid#MysticBuffName_30501",
		["des"]="tid#MysticBuffDes_30501",
		["param"]={
			100030501,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
			{
				{
					"hp",
					204,
				},
			},
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[30503]={
		["name"]="tid#MysticBuffName_30503",
		["des"]="tid#MysticBuffDes_30503",
		["param"]={
			100030503,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
			{
				{
					"hp",
					204,
				},
			},
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[30505]={
		["name"]="tid#MysticBuffName_30505",
		["des"]="tid#MysticBuffDes_30505",
		["param"]={
			100030505,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
			{
				{
					"hp",
					204,
				},
			},
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[40101]={
		["name"]="tid#MysticBuffName_40101",
		["des"]="tid#MysticBuffDes_40101",
		["param"]={
			100040101,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang2",
		["condition"]={
			"hpper",
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[40103]={
		["name"]="tid#MysticBuffName_40103",
		["des"]="tid#MysticBuffDes_40103",
		["param"]={
			100040103,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang2",
		["condition"]={
			"hpper",
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[40105]={
		["name"]="tid#MysticBuffName_40105",
		["des"]="tid#MysticBuffDes_40105",
		["param"]={
			100040105,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang1",
		["condition"]={
			"hpper",
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
			{
				{
					"hp",
					102,
				},
			},
		},
		["des_class"]="",
	},
	[40201]={
		["name"]="tid#MysticBuffName_40201",
		["des"]="tid#MysticBuffDes_40201",
		["param"]={
			100040201,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_emei1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[40203]={
		["name"]="tid#MysticBuffName_40203",
		["des"]="tid#MysticBuffDes_40203",
		["param"]={
			100040203,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_emei1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[40205]={
		["name"]="tid#MysticBuffName_40205",
		["des"]="tid#MysticBuffDes_40205",
		["param"]={
			100040205,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jujing4",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[40301]={
		["name"]="tid#MysticBuffName_40301",
		["des"]="tid#MysticBuffDes_40301",
		["param"]={
			100040301,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[40303]={
		["name"]="tid#MysticBuffName_40303",
		["des"]="tid#MysticBuffDes_40303",
		["param"]={
			100040303,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[40305]={
		["name"]="tid#MysticBuffName_40305",
		["des"]="tid#MysticBuffDes_40305",
		["param"]={
			100040305,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_wudang3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[40401]={
		["name"]="tid#MysticBuffName_40401",
		["des"]="tid#MysticBuffDes_40401",
		["param"]={
			100040401,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_taishan3",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[40403]={
		["name"]="tid#MysticBuffName_40403",
		["des"]="tid#MysticBuffDes_40403",
		["param"]={
			100040403,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_taishan3",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[40405]={
		["name"]="tid#MysticBuffName_40405",
		["des"]="tid#MysticBuffDes_40405",
		["param"]={
			100040405,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_xingyi1",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[40501]={
		["name"]="tid#MysticBuffName_40501",
		["des"]="tid#MysticBuffDes_40501",
		["param"]={
			100040501,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_xuanwu4",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					204,
				},
			},
		},
		["des_class"]="",
	},
	[40503]={
		["name"]="tid#MysticBuffName_40503",
		["des"]="tid#MysticBuffDes_40503",
		["param"]={
			100040503,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_xuanwu4",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					204,
				},
			},
		},
		["des_class"]="",
	},
	[40505]={
		["name"]="tid#MysticBuffName_40505",
		["des"]="tid#MysticBuffDes_40505",
		["param"]={
			100040505,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jueqing1",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					204,
				},
			},
		},
		["des_class"]="",
	},
	[40601]={
		["name"]="tid#MysticBuffName_40601",
		["des"]="tid#MysticBuffDes_40601",
		["param"]={
			100040601,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jingang1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[40603]={
		["name"]="tid#MysticBuffName_40603",
		["des"]="tid#MysticBuffDes_40603",
		["param"]={
			100040603,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jingang1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[40605]={
		["name"]="tid#MysticBuffName_40605",
		["des"]="tid#MysticBuffDes_40605",
		["param"]={
			100040605,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jinqian4",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[40701]={
		["name"]="tid#MysticBuffName_40701",
		["des"]="tid#MysticBuffDes_40701",
		["param"]={
			100040701,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_changge2",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[40703]={
		["name"]="tid#MysticBuffName_40703",
		["des"]="tid#MysticBuffDes_40703",
		["param"]={
			100040703,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_changge2",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[40705]={
		["name"]="tid#MysticBuffName_40705",
		["des"]="tid#MysticBuffDes_40705",
		["param"]={
			100040705,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_changge2",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[40801]={
		["name"]="tid#MysticBuffName_40801",
		["des"]="tid#MysticBuffDes_40801",
		["param"]={
			100040801,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"controlend",
		},
		["condition_param"]={
			{
				{
					"times",
					2,
				},
			},
		},
		["des_class"]="",
	},
	[40803]={
		["name"]="tid#MysticBuffName_40803",
		["des"]="tid#MysticBuffDes_40803",
		["param"]={
			100040803,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"controlend",
		},
		["condition_param"]={
			{
				{
					"times",
					2,
				},
			},
		},
		["des_class"]="",
	},
	[40805]={
		["name"]="tid#MysticBuffName_40805",
		["des"]="tid#MysticBuffDes_40805",
		["param"]={
			100040805,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"controlend",
		},
		["condition_param"]={
			{
				{
					"times",
					2,
				},
			},
		},
		["des_class"]="",
	},
	[51001]={
		["name"]="tid#MysticBuffName_51001",
		["des"]="tid#MysticBuffDes_51001",
		["param"]={
			100051001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[51002]={
		["name"]="tid#MysticBuffName_51002",
		["des"]="tid#MysticBuffDes_51002",
		["param"]={
			100051002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[51003]={
		["name"]="tid#MysticBuffName_51003",
		["des"]="tid#MysticBuffDes_51003",
		["param"]={
			100051003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[61001]={
		["name"]="tid#MysticBuffName_61001",
		["des"]="tid#MysticBuffDes_61001",
		["param"]={
			100061001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[61002]={
		["name"]="tid#MysticBuffName_61002",
		["des"]="tid#MysticBuffDes_61002",
		["param"]={
			100061002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[61003]={
		["name"]="tid#MysticBuffName_61003",
		["des"]="tid#MysticBuffDes_61003",
		["param"]={
			100061003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[62001]={
		["name"]="tid#MysticBuffName_62001",
		["des"]="tid#MysticBuffDes_62001",
		["param"]={
			100062001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[62002]={
		["name"]="tid#MysticBuffName_62002",
		["des"]="tid#MysticBuffDes_62002",
		["param"]={
			100062002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"time",
		},
		["condition_param"]={
			{
				{
					"time",
					20480,
				},
			},
		},
		["des_class"]="",
	},
	[62003]={
		["name"]="tid#MysticBuffName_62003",
		["des"]="tid#MysticBuffDes_62003",
		["param"]={
			100062003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[71001]={
		["name"]="tid#MysticBuffName_71001",
		["des"]="tid#MysticBuffDes_71001",
		["param"]={
			100071001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[71002]={
		["name"]="tid#MysticBuffName_71002",
		["des"]="tid#MysticBuffDes_71002",
		["param"]={
			100071002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[71003]={
		["name"]="tid#MysticBuffName_71003",
		["des"]="tid#MysticBuffDes_71003",
		["param"]={
			100071003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[71004]={
		["name"]="tid#MysticBuffName_71004",
		["des"]="tid#MysticBuffDes_71004",
		["param"]={
			100071004,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[71005]={
		["name"]="tid#MysticBuffName_71005",
		["des"]="tid#MysticBuffDes_71005",
		["param"]={
			100071005,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[71006]={
		["name"]="tid#MysticBuffName_71006",
		["des"]="tid#MysticBuffDes_71006",
		["param"]={
			100071006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[72001]={
		["name"]="tid#MysticBuffName_72001",
		["des"]="tid#MysticBuffDes_72001",
		["param"]={
			100072001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[72002]={
		["name"]="tid#MysticBuffName_72002",
		["des"]="tid#MysticBuffDes_72002",
		["param"]={
			100072002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[72003]={
		["name"]="tid#MysticBuffName_72003",
		["des"]="tid#MysticBuffDes_72003",
		["param"]={
			100072003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"buff",
		},
		["condition_param"]={
			{
				{
					"tag",
					"pojia",
				},
				{
					"tag",
					"zhongdu",
				},
				{
					"tag",
					"liuxue",
				},
			},
		},
		["des_class"]="",
	},
	[72004]={
		["name"]="tid#MysticBuffName_72004",
		["des"]="tid#MysticBuffDes_72004",
		["param"]={
			100072004,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[72005]={
		["name"]="tid#MysticBuffName_72005",
		["des"]="tid#MysticBuffDes_72005",
		["param"]={
			100072005,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[72006]={
		["name"]="tid#MysticBuffName_72006",
		["des"]="tid#MysticBuffDes_72006",
		["param"]={
			100072006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[81001]={
		["name"]="tid#MysticBuffName_81001",
		["des"]="tid#MysticBuffDes_81001",
		["param"]={
			100081001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[81002]={
		["name"]="tid#MysticBuffName_81002",
		["des"]="tid#MysticBuffDes_81002",
		["param"]={
			100081002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[81003]={
		["name"]="tid#MysticBuffName_81003",
		["des"]="tid#MysticBuffDes_81003",
		["param"]={
			100081003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[81004]={
		["name"]="tid#MysticBuffName_81004",
		["des"]="tid#MysticBuffDes_81004",
		["param"]={
			100081004,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[81005]={
		["name"]="tid#MysticBuffName_81005",
		["des"]="tid#MysticBuffDes_81005",
		["param"]={
			100081005,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[81006]={
		["name"]="tid#MysticBuffName_81006",
		["des"]="tid#MysticBuffDes_81006",
		["param"]={
			100081006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[82001]={
		["name"]="tid#MysticBuffName_82001",
		["des"]="tid#MysticBuffDes_82001",
		["param"]={
			100082001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[82002]={
		["name"]="tid#MysticBuffName_82002",
		["des"]="tid#MysticBuffDes_82002",
		["param"]={
			100082002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[82003]={
		["name"]="tid#MysticBuffName_82003",
		["des"]="tid#MysticBuffDes_82003",
		["param"]={
			100082003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"buff",
		},
		["condition_param"]={
			{
				{
					"tag",
					"pojia",
				},
				{
					"tag",
					"zhongdu",
				},
				{
					"tag",
					"liuxue",
				},
			},
		},
		["des_class"]="",
	},
	[82004]={
		["name"]="tid#MysticBuffName_82004",
		["des"]="tid#MysticBuffDes_82004",
		["param"]={
			100082004,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[82005]={
		["name"]="tid#MysticBuffName_82005",
		["des"]="tid#MysticBuffDes_82005",
		["param"]={
			100082005,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[82006]={
		["name"]="tid#MysticBuffName_82006",
		["des"]="tid#MysticBuffDes_82006",
		["param"]={
			100082006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[91001]={
		["name"]="tid#MysticBuffName_91001",
		["des"]="tid#MysticBuffDes_91001",
		["param"]={
			100091001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[91002]={
		["name"]="tid#MysticBuffName_91002",
		["des"]="tid#MysticBuffDes_91002",
		["param"]={
			100091002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[91003]={
		["name"]="tid#MysticBuffName_91003",
		["des"]="tid#MysticBuffDes_91003",
		["param"]={
			100091003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[91004]={
		["name"]="tid#MysticBuffName_91004",
		["des"]="tid#MysticBuffDes_91004",
		["param"]={
			100091004,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[91005]={
		["name"]="tid#MysticBuffName_91005",
		["des"]="tid#MysticBuffDes_91005",
		["param"]={
			100091005,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[91006]={
		["name"]="tid#MysticBuffName_91006",
		["des"]="tid#MysticBuffDes_91006",
		["param"]={
			100091006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[92001]={
		["name"]="tid#MysticBuffName_92001",
		["des"]="tid#MysticBuffDes_92001",
		["param"]={
			100092001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[92002]={
		["name"]="tid#MysticBuffName_92002",
		["des"]="tid#MysticBuffDes_92002",
		["param"]={
			100092002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_guigu1",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[92003]={
		["name"]="tid#MysticBuffName_92003",
		["des"]="tid#MysticBuffDes_92003",
		["param"]={
			100092003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_hengshan3",
		["condition"]={
			"controlend",
		},
		["condition_param"]={
			{
				{
					"times",
					2,
				},
			},
		},
		["des_class"]="",
	},
	[92004]={
		["name"]="tid#MysticBuffName_92004",
		["des"]="tid#MysticBuffDes_92004",
		["param"]={
			100092004,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[920041]={
		["name"]="tid#MysticBuffName_92004",
		["des"]="tid#MysticBuffDes_920041",
		["param"]={
			1000920041,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[920042]={
		["name"]="tid#MysticBuffName_92004",
		["des"]="tid#MysticBuffDes_920042",
		["param"]={
			1000920042,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					819,
				},
			},
			{
				{
					"hp",
					409,
				},
			},
		},
		["des_class"]="",
	},
	[920043]={
		["name"]="tid#MysticBuffName_92004",
		["des"]="tid#MysticBuffDes_920043",
		["param"]={
			1000920043,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[920044]={
		["name"]="tid#MysticBuffName_92004",
		["des"]="tid#MysticBuffDes_920044",
		["param"]={
			1000920044,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					819,
				},
			},
			{
				{
					"hp",
					409,
				},
			},
		},
		["des_class"]="",
	},
	[92005]={
		["name"]="tid#MysticBuffName_92005",
		["des"]="tid#MysticBuffDes_92005",
		["param"]={
			100092005,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jiuli3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					512,
				},
			},
		},
		["des_class"]="",
	},
	[92006]={
		["name"]="tid#MysticBuffName_92006",
		["des"]="tid#MysticBuffDes_92006",
		["param"]={
			100092006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_songshan3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					409,
				},
			},
		},
		["des_class"]="",
	},
	[92007]={
		["name"]="tid#MysticBuffName_92007",
		["des"]="tid#MysticBuffDes_92007",
		["param"]={
			100092007,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang2",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[920071]={
		["name"]="tid#MysticBuffName_92007",
		["des"]="tid#MysticBuffDes_920071",
		["param"]={
			1000920071,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang2",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[920072]={
		["name"]="tid#MysticBuffName_92007",
		["des"]="tid#MysticBuffDes_920072",
		["param"]={
			1000920072,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang2",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[920073]={
		["name"]="tid#MysticBuffName_92007",
		["des"]="tid#MysticBuffDes_920073",
		["param"]={
			1000920073,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang2",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[920074]={
		["name"]="tid#MysticBuffName_92007",
		["des"]="tid#MysticBuffDes_920074",
		["param"]={
			1000920074,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang2",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[10001]={
		["name"]="tid#MysticBuffName_10001",
		["des"]="tid#MysticBuffDes_10001",
		["param"]={
			100010002,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_changge2",
		["condition"]={
			"Mystic_01",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[10002]={
		["name"]="tid#MysticBuffName_10002",
		["des"]="tid#MysticBuffDes_10002",
		["param"]={
			100010003,
			1,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang4",
		["condition"]={
			"Mystic_02",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[10003]={
		["name"]="tid#MysticBuffName_10003",
		["des"]="tid#MysticBuffDes_10003",
		["param"]={
			100010004,
			5,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_emei1",
		["condition"]={
			"Mystic_03",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[10004]={
		["name"]="tid#MysticBuffName_10004",
		["des"]="tid#MysticBuffDes_10004",
		["param"]={
			100010005,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jujing1",
		["condition"]={
			"Mystic_04",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[10005]={
		["name"]="tid#MysticBuffName_10005",
		["des"]="tid#MysticBuffDes_10005",
		["param"]={
			99999,
			2,
			1,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_kongtong4",
		["condition"]={
			"Mystic_05",
		},
		["condition_param"]={
			{
				{
					"tag",
					"liuxue",
				},
			},
		},
		["des_class"]="",
	},
	[10006]={
		["name"]="tid#MysticBuffName_10006",
		["des"]="tid#MysticBuffDes_10006",
		["param"]={
			1,
			99999,
			2,
			10,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_longmen2",
		["condition"]={
			"Mystic_06",
		},
		["condition_param"]={
			{
				{
					"tag_extra",
					"AddBlood",
				},
			},
		},
		["des_class"]="",
	},
	[20001]={
		["name"]="tid#MysticBuffName_20001",
		["des"]="tid#MysticBuffDes_20001",
		["param"]={
			100020001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_changge2",
		["condition"]={
			"Mystic_01",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20002]={
		["name"]="tid#MysticBuffName_20002",
		["des"]="tid#MysticBuffDes_20002",
		["param"]={
			100020002,
			2,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang4",
		["condition"]={
			"Mystic_02",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20003]={
		["name"]="tid#MysticBuffName_20003",
		["des"]="tid#MysticBuffDes_20003",
		["param"]={
			100020003,
			5,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_emei1",
		["condition"]={
			"Mystic_03",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20004]={
		["name"]="tid#MysticBuffName_20004",
		["des"]="tid#MysticBuffDes_20004",
		["param"]={
			100020004,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jujing1",
		["condition"]={
			"Mystic_04",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[20005]={
		["name"]="tid#MysticBuffName_20005",
		["des"]="tid#MysticBuffDes_20005",
		["param"]={
			99999,
			3,
			2,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_kongtong4",
		["condition"]={
			"Mystic_05",
		},
		["condition_param"]={
			{
				{
					"tag",
					"liuxue",
				},
				{
					"tag",
					"zhongdu",
				},
			},
		},
		["des_class"]="",
	},
	[20006]={
		["name"]="tid#MysticBuffName_20006",
		["des"]="tid#MysticBuffDes_20006",
		["param"]={
			2,
			99999,
			2,
			9,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_longmen2",
		["condition"]={
			"Mystic_06",
		},
		["condition_param"]={
			{
				{
					"tag_extra",
					"AddBlood",
				},
				{
					"tag_extra",
					"shield",
				},
			},
		},
		["des_class"]="",
	},
	[30001]={
		["name"]="tid#MysticBuffName_30001",
		["des"]="tid#MysticBuffDes_30001",
		["param"]={
			100030001,
			1000300012,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_changge2",
		["condition"]={
			"Mystic_01",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[30002]={
		["name"]="tid#MysticBuffName_30002",
		["des"]="tid#MysticBuffDes_30002",
		["param"]={
			100030002,
			2,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_cihang4",
		["condition"]={
			"Mystic_02",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[30003]={
		["name"]="tid#MysticBuffName_30003",
		["des"]="tid#MysticBuffDes_30003",
		["param"]={
			100030003,
			5,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_emei1",
		["condition"]={
			"Mystic_03",
		},
		["condition_param"]={
		},
		["des_class"]="",
	},
	[30004]={
		["name"]="tid#MysticBuffName_30004",
		["des"]="tid#MysticBuffDes_30004",
		["param"]={
			100030004,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_jujing1",
		["condition"]={
			"Mystic_04",
		},
		["condition_param"]={
			{
				{
					"hp",
					307,
				},
			},
		},
		["des_class"]="",
	},
	[30005]={
		["name"]="tid#MysticBuffName_30005",
		["des"]="tid#MysticBuffDes_30005",
		["param"]={
			99999,
			4,
			3,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_kongtong4",
		["condition"]={
			"Mystic_05",
		},
		["condition_param"]={
			{
				{
					"tag",
					"liuxue",
				},
				{
					"tag",
					"zhongdu",
				},
				{
					"damageRaise",
					1024,
				},
			},
		},
		["des_class"]="",
	},
	[30006]={
		["name"]="tid#MysticBuffName_30006",
		["des"]="tid#MysticBuffDes_30006",
		["param"]={
			3,
			99999,
			3,
			8,
			100030006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_longmen2",
		["condition"]={
			"Mystic_06",
		},
		["condition_param"]={
			{
				{
					"tag_extra",
					"AddBlood",
				},
				{
					"tag_extra",
					"shield",
				},
			},
		},
		["des_class"]="",
	},
	[300061]={
		["name"]="tid#MysticBuffName_30006",
		["des"]="tid#MysticBuffDes_300061",
		["param"]={
			3,
			99999,
			3,
			8,
			100030006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_longmen2",
		["condition"]={
			"Mystic_06",
		},
		["condition_param"]={
			{
				{
					"tag_extra",
					"AddBlood",
				},
				{
					"tag_extra",
					"shield",
				},
			},
		},
		["des_class"]="",
	},
	[300062]={
		["name"]="tid#MysticBuffName_30006",
		["des"]="tid#MysticBuffDes_300062",
		["param"]={
			3,
			99999,
			4,
			8,
			100030006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_longmen2",
		["condition"]={
			"Mystic_06",
		},
		["condition_param"]={
			{
				{
					"tag_extra",
					"AddBlood",
				},
				{
					"tag_extra",
					"shield",
				},
			},
		},
		["des_class"]="",
	},
	[300063]={
		["name"]="tid#MysticBuffName_30006",
		["des"]="tid#MysticBuffDes_300063",
		["param"]={
			3,
			99999,
			3,
			6,
			100030006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_longmen2",
		["condition"]={
			"Mystic_06",
		},
		["condition_param"]={
			{
				{
					"tag_extra",
					"AddBlood",
				},
				{
					"tag_extra",
					"shield",
				},
			},
		},
		["des_class"]="",
	},
	[300064]={
		["name"]="tid#MysticBuffName_30006",
		["des"]="tid#MysticBuffDes_300064",
		["param"]={
			3,
			99999,
			4,
			6,
			100030006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_longmen2",
		["condition"]={
			"Mystic_06",
		},
		["condition_param"]={
			{
				{
					"tag_extra",
					"AddBlood",
				},
				{
					"tag_extra",
					"shield",
				},
			},
		},
		["des_class"]="",
	},
	[93001]={
		["name"]="tid#MysticBuffName_93001",
		["des"]="tid#MysticBuffDes_93001",
		["param"]={
			100093001,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_huashan4",
		["condition"]={
			"Mystic_Kill",
		},
		["condition_param"]={
			{
				{
					"check_role_type",
					1,
				},
			},
		},
		["des_class"]="tid#MysticBuffDesclass_93001",
	},
	[93011]={
		["name"]="tid#MysticBuffName_93001",
		["des"]="tid#MysticBuffDes_93001",
		["param"]={
			100093011,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_huashan4",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_93001",
	},
	[93002]={
		["name"]="tid#MysticBuffName_93002",
		["des"]="tid#MysticBuffDes_93002",
		["param"]={
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_duanshi4",
		["condition"]={
			"Mystic_Backstab",
		},
		["condition_param"]={
			{
				{
					"damageRaise",
					1024,
				},
				{
					"critDamageRaise",
					1024,
				},
				{
					"check_role_type",
					1,
				},
			},
		},
		["des_class"]="tid#MysticBuffDesclass_93002",
	},
	[93012]={
		["name"]="tid#MysticBuffName_93002",
		["des"]="tid#MysticBuffDes_93002",
		["param"]={
			100093012,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_duanshi4",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_93002",
	},
	[93003]={
		["name"]="tid#MysticBuffName_93003",
		["des"]="tid#MysticBuffDes_93003",
		["param"]={
			100093003,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_tianxiahui3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_93003",
	},
	[930031]={
		["name"]="tid#MysticBuffName_93003",
		["des"]="tid#MysticBuffDes_930031",
		["param"]={
			1000930031,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_tianxiahui3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_93003",
	},
	[930032]={
		["name"]="tid#MysticBuffName_93003",
		["des"]="tid#MysticBuffDes_930032",
		["param"]={
			1000930032,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_tianxiahui3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_93003",
	},
	[930033]={
		["name"]="tid#MysticBuffName_93003",
		["des"]="tid#MysticBuffDes_930031",
		["param"]={
			1000930031,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_tianxiahui3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_930031",
	},
	[930034]={
		["name"]="tid#MysticBuffName_93003",
		["des"]="tid#MysticBuffDes_930032",
		["param"]={
			1000930032,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_tianxiahui3",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_930031",
	},
	[93013]={
		["name"]="tid#MysticBuffName_93003",
		["des"]="tid#MysticBuffDes_93003",
		["param"]={
			100093013,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_tianxiahui3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					358,
				},
				{
					"check_role_type",
					1,
				},
			},
		},
		["des_class"]="tid#MysticBuffDesclass_93003",
	},
	[930131]={
		["name"]="tid#MysticBuffName_93003",
		["des"]="tid#MysticBuffDes_930031",
		["param"]={
			1000930131,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_tianxiahui3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					358,
				},
				{
					"check_role_type",
					1,
				},
			},
		},
		["des_class"]="tid#MysticBuffDesclass_930031",
	},
	[930132]={
		["name"]="tid#MysticBuffName_93003",
		["des"]="tid#MysticBuffDes_930032",
		["param"]={
			1000930131,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_tianxiahui3",
		["condition"]={
			"hpper",
		},
		["condition_param"]={
			{
				{
					"hp",
					358,
				},
				{
					"check_role_type",
					1,
				},
			},
		},
		["des_class"]="tid#MysticBuffDesclass_930031",
	},
	[93004]={
		["name"]="tid#MysticBuffName_93004",
		["des"]="tid#MysticBuffDes_93004",
		["param"]={
			100093004,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_wanhua4",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_93004",
	},
	[93014]={
		["name"]="tid#MysticBuffName_93014",
		["des"]="tid#MysticBuffDes_93014",
		["param"]={
			100093014,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_wanhua4",
		["condition"]={
			"Mystic_07",
		},
		["condition_param"]={
			{
				{
					"check_role_type",
					1,
				},
			},
		},
		["des_class"]="tid#MysticBuffDesclass_93014",
	},
	[93005]={
		["name"]="tid#MysticBuffName_93005",
		["des"]="tid#MysticBuffDes_93005",
		["param"]={
			100093005,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_lingjiu4",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_93005",
	},
	[93015]={
		["name"]="tid#MysticBuffName_93015",
		["des"]="tid#MysticBuffDes_93015",
		["param"]={
			2,
			100093015,
			10,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_lingjiu4",
		["condition"]={
			"Mystic_08",
		},
		["condition_param"]={
			{
				{
					"check_role_type",
					1,
				},
			},
		},
		["des_class"]="tid#MysticBuffDesclass_93015",
	},
	[93006]={
		["name"]="tid#MysticBuffName_93006",
		["des"]="tid#MysticBuffDes_93006",
		["param"]={
			100093006,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_taiji1",
		["condition"]={
			"start",
		},
		["condition_param"]={
		},
		["des_class"]="tid#MysticBuffDesclass_93006",
	},
	[930161]={
		["name"]="tid#MysticBuffName_93016",
		["des"]="tid#MysticBuffDes_93016",
		["param"]={
			1000930161,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_taiji1",
		["condition"]={
			"start",
		},
		["condition_param"]={
			{
				{
					"check_role_type",
					1,
				},
			},
		},
		["des_class"]="tid#MysticBuffDesclass_93016",
	},
	[930162]={
		["name"]="tid#MysticBuffName_93016",
		["des"]="tid#MysticBuffDes_93016",
		["param"]={
			1000930162,
			1000930163,
		},
		["race_id"]=0,
		["hero_type"]=0,
		["hero_id"]={
		},
		["icon"]="JN_taiji1",
		["condition"]={
			"Mystic_09",
		},
		["condition_param"]={
			{
				{
					"check_role_type",
					1,
				},
			},
		},
		["des_class"]="tid#MysticBuffDesclass_93016",
	},
}