return {
	[10001]={
		["name"]="早上",
		["config"]={
			[0]={
				["words"]="早安！带阿闲出去玩吗？",
				["bank"]="Vo_AXian",
				["vo"]="Vo_First_AXian_01",
				["sort"]=0,
				["stage"]=0,
				["action"]="chayao",
			},
		},
	},
	[10002]={
		["name"]="上午",
		["config"]={
			[0]={
				["words"]="上午好上午好~~休息的好吗？嗯？",
				["bank"]="Vo_AXian",
				["vo"]="Vo_First_AXian_02",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk_xushu",
			},
		},
	},
	[10003]={
		["name"]="中午",
		["config"]={
			[0]={
				["words"]="已经是中午啦！有没有想念阿闲呢~？",
				["bank"]="Vo_AXian",
				["vo"]="Vo_First_AXian_03",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk_beishou",
			},
		},
	},
	[10004]={
		["name"]="下午",
		["config"]={
			[0]={
				["words"]="今天已经过去一半啦，目标完成了嘛？",
				["bank"]="Vo_AXian",
				["vo"]="Vo_First_AXian_04",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk_tanshou",
			},
		},
	},
	[10005]={
		["name"]="晚上",
		["config"]={
			[0]={
				["words"]="月儿高高空中挂！小小阿闲出来玩~",
				["bank"]="Vo_AXian",
				["vo"]="Vo_First_AXian_05",
				["sort"]=0,
				["stage"]=0,
				["action"]="happy",
			},
		},
	},
	[20001]={
		["name"]="打招呼1",
		["config"]={
			[0]={
				["words"]="江湖快驿首席掌柜阿闲！前来报到！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_01",
				["sort"]=0,
				["stage"]=0,
				["action"]="taibangle",
			},
			[5]={
				["words"]="恭喜恭喜恭喜你呀恭喜恭喜恭喜你~",
				["bank"]="Vo_AXian",
				["vo"]="Vo_NYear_AXian_01",
				["sort"]=0,
				["stage"]=0,
				["action"]="happy",
			},
		},
	},
	[20002]={
		["name"]="打招呼2",
		["config"]={
			[0]={
				["words"]="你好！~你是来买报纸的吗？",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_02",
				["sort"]=0,
				["stage"]=0,
				["action"]="daoju_baozhi",
			},
			[5]={
				["words"]="新年好呀新年好，祝福少侠新年好~",
				["bank"]="Vo_AXian",
				["vo"]="Vo_NYear_AXian_02",
				["sort"]=0,
				["stage"]=0,
				["action"]="taibangle",
			},
		},
	},
	[20003]={
		["name"]="打招呼3",
		["config"]={
			[0]={
				["words"]="想不想~和阿闲一起去冒险？",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_03",
				["sort"]=0,
				["stage"]=0,
				["action"]="shy",
			},
			[5]={
				["words"]="恭喜发财！红包 拿来！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_NYear_AXian_03",
				["sort"]=0,
				["stage"]=0,
				["action"]="chayao",
			},
		},
	},
	[20004]={
		["name"]="打招呼4",
		["config"]={
			[0]={
				["words"]="劳逸结合~要注意休息哦少侠。",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_04",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
			[5]={
				["words"]="爆竹声中一岁除~春风送暖入屠苏！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_NYear_AXian_04",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk",
			},
		},
	},
	[20005]={
		["name"]="打招呼5",
		["config"]={
			[0]={
				["words"]="有什么信要阿闲代送吗~使命必达哦！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_05",
				["sort"]=0,
				["stage"]=0,
				["action"]="dazhaohu",
			},
			[5]={
				["words"]="过年啦！少侠有没有和家人团聚呢？",
				["bank"]="Vo_AXian",
				["vo"]="Vo_NYear_AXian_05",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk_think",
			},
		},
	},
	[30001]={
		["name"]="5级奖励",
		["config"]={
			[0]={
				["words"]="哇！少侠到达了5级哦！真厉害诶！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Email_AXian_01",
				["sort"]=0,
				["stage"]=0,
				["action"]="happy",
			},
		},
	},
	[30002]={
		["name"]="10级奖励",
		["config"]={
			[0]={
				["words"]="恭喜呀少侠，已经到达10级了哦~",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Email_AXian_02",
				["sort"]=0,
				["stage"]=0,
				["action"]="taibangle",
			},
		},
	},
	[30003]={
		["name"]="15级奖励",
		["config"]={
			[0]={
				["words"]="快来看！已经是15级的少侠了呢！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Email_AXian_03",
				["sort"]=0,
				["stage"]=0,
				["action"]="happy",
			},
		},
	},
	[30004]={
		["name"]="20级奖励",
		["config"]={
			[0]={
				["words"]="真不愧是你！这么快就已经20级了！少侠棒棒哒！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Email_AXian_04",
				["sort"]=0,
				["stage"]=0,
				["action"]="taibangle",
			},
		},
	},
	[30005]={
		["name"]="25级奖励",
		["config"]={
			[0]={
				["words"]="25级的少侠！应该要叫大侠了吧！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Email_AXian_05",
				["sort"]=0,
				["stage"]=0,
				["action"]="happy",
			},
		},
	},
	[30006]={
		["name"]="30级奖励",
		["config"]={
			[0]={
				["words"]="天啦噜！阿闲有生之年居然能看到30级的巨侠！阿闲佩服佩服！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Email_AXian_06",
				["sort"]=0,
				["stage"]=0,
				["action"]="taibangle",
			},
		},
	},
	[40001]={
		["name"]="好感度0-3级-1",
		["config"]={
			[0]={
				["words"]="少侠明明知道阿闲没办法拒绝你的呀。",
				["bank"]="Vo_AXian",
				["vo"]="VoA_GNormal_AXian_01",
				["sort"]=1,
				["stage"]=1,
				["action"]="daoju_baozhi",
			},
		},
	},
	[40002]={
		["name"]="好感度0-3级-2",
		["config"]={
			[0]={
				["words"]="哈哈，谢谢少侠呀~",
				["bank"]="Vo_AXian",
				["vo"]="VoA_GNormal_AXian_02",
				["sort"]=1,
				["stage"]=1,
				["action"]="daoju_fengche",
			},
		},
	},
	[40003]={
		["name"]="好感度0-3级-3",
		["config"]={
			[0]={
				["words"]="那阿闲就收下了哦~",
				["bank"]="Vo_AXian",
				["vo"]="VoA_GNormal_AXian_03",
				["sort"]=1,
				["stage"]=1,
				["action"]="shy",
			},
		},
	},
	[40004]={
		["name"]="好感度0-3级-4",
		["config"]={
			[0]={
				["words"]="喜欢~开心~",
				["bank"]="Vo_AXian",
				["vo"]="VoA_GFond_AXian_01",
				["sort"]=2,
				["stage"]=1,
				["action"]="daoju_tanghulu",
			},
		},
	},
	[40005]={
		["name"]="好感度0-3级-5",
		["config"]={
			[0]={
				["words"]="少侠总是对阿闲这么好，阿闲都要害羞啦。",
				["bank"]="Vo_AXian",
				["vo"]="VoA_GFond_AXian_02",
				["sort"]=2,
				["stage"]=1,
				["action"]="daoju_zheshan",
			},
		},
	},
	[40006]={
		["name"]="好感度0-3级-6",
		["config"]={
			[0]={
				["words"]="果然！我和少侠心有灵犀！",
				["bank"]="Vo_AXian",
				["vo"]="VoA_GFond_AXian_03",
				["sort"]=2,
				["stage"]=1,
				["action"]="zhaodongxi",
			},
		},
	},
	[50001]={
		["name"]="好感度4-7级-1",
		["config"]={
			[0]={
				["words"]="少侠对阿闲真好！",
				["bank"]="Vo_AXian",
				["vo"]="VoB_GNormal_AXian_01",
				["sort"]=1,
				["stage"]=2,
				["action"]="daoju_baozhi",
			},
		},
	},
	[50002]={
		["name"]="好感度4-7级-2",
		["config"]={
			[0]={
				["words"]="少侠给的一定是好东西没错了！",
				["bank"]="Vo_AXian",
				["vo"]="VoB_GNormal_AXian_02",
				["sort"]=1,
				["stage"]=2,
				["action"]="daoju_fengche",
			},
		},
	},
	[50003]={
		["name"]="好感度4-7级-3",
		["config"]={
			[0]={
				["words"]="嗯嗯！少侠对阿闲的好阿闲一定永远记得！",
				["bank"]="Vo_AXian",
				["vo"]="VoB_GNormal_AXian_03",
				["sort"]=1,
				["stage"]=2,
				["action"]="shy",
			},
		},
	},
	[50004]={
		["name"]="好感度4-7级-4",
		["config"]={
			[0]={
				["words"]="绝对会珍惜哒，我 保 证~",
				["bank"]="Vo_AXian",
				["vo"]="VoB_GFond_AXian_01",
				["sort"]=2,
				["stage"]=2,
				["action"]="daoju_tanghulu",
			},
		},
	},
	[50005]={
		["name"]="好感度4-7级-5",
		["config"]={
			[0]={
				["words"]="哈！少侠果然最了解阿闲啦！",
				["bank"]="Vo_AXian",
				["vo"]="VoB_GFond_AXian_02",
				["sort"]=2,
				["stage"]=2,
				["action"]="daoju_zheshan",
			},
		},
	},
	[50006]={
		["name"]="好感度4-7级-6",
		["config"]={
			[0]={
				["words"]="这下可帮了大忙啦！",
				["bank"]="Vo_AXian",
				["vo"]="VoB_GFond_AXian_03",
				["sort"]=2,
				["stage"]=2,
				["action"]="zhaodongxi",
			},
		},
	},
	[60001]={
		["name"]="好感度8-11级-1",
		["config"]={
			[0]={
				["words"]="超开心~少侠的心一起给阿闲好不好~",
				["bank"]="Vo_AXian",
				["vo"]="VoC_GNormal_AXian_01",
				["sort"]=1,
				["stage"]=3,
				["action"]="daoju_baozhi",
			},
		},
	},
	[60002]={
		["name"]="好感度8-11级-2",
		["config"]={
			[0]={
				["words"]="诶？少侠是只对阿闲这么好吗还是……",
				["bank"]="Vo_AXian",
				["vo"]="VoC_GNormal_AXian_02",
				["sort"]=1,
				["stage"]=3,
				["action"]="daoju_fengche",
			},
		},
	},
	[60003]={
		["name"]="好感度8-11级-3",
		["config"]={
			[0]={
				["words"]="阿闲也会努力回报少侠的，期待吗？",
				["bank"]="Vo_AXian",
				["vo"]="VoC_GNormal_AXian_03",
				["sort"]=1,
				["stage"]=3,
				["action"]="shy",
			},
		},
	},
	[60004]={
		["name"]="好感度8-11级-4",
		["config"]={
			[0]={
				["words"]="不能对我以外的人这么善良了哦。",
				["bank"]="Vo_AXian",
				["vo"]="VoC_GFond_AXian_01",
				["sort"]=2,
				["stage"]=3,
				["action"]="daoju_tanghulu",
			},
		},
	},
	[60005]={
		["name"]="好感度8-11级-5",
		["config"]={
			[0]={
				["words"]="嘻嘻，我要摆到屋子最显眼的地方！",
				["bank"]="Vo_AXian",
				["vo"]="VoC_GFond_AXian_02",
				["sort"]=2,
				["stage"]=3,
				["action"]="daoju_zheshan",
			},
		},
	},
	[60006]={
		["name"]="好感度8-11级-6",
		["config"]={
			[0]={
				["words"]="太好啦，这下阿闲可要好好炫耀一下。",
				["bank"]="Vo_AXian",
				["vo"]="VoC_GFond_AXian_03",
				["sort"]=2,
				["stage"]=3,
				["action"]="zhaodongxi",
			},
		},
	},
	[70001]={
		["name"]="好感度12-15级-1",
		["config"]={
			[0]={
				["words"]="少侠的关心就是阿闲最好的蜜糖啦。",
				["bank"]="Vo_AXian",
				["vo"]="VoD_GNormal_AXian_01",
				["sort"]=1,
				["stage"]=4,
				["action"]="daoju_baozhi",
			},
		},
	},
	[70002]={
		["name"]="好感度12-15级-2",
		["config"]={
			[0]={
				["words"]="嗯嗯~少侠的爱，阿闲收到了哦！",
				["bank"]="Vo_AXian",
				["vo"]="VoD_GNormal_AXian_02",
				["sort"]=1,
				["stage"]=4,
				["action"]="daoju_fengche",
			},
		},
	},
	[70003]={
		["name"]="好感度12-15级-3",
		["config"]={
			[0]={
				["words"]="阿闲想……再加一个抱抱会不会更好呢！",
				["bank"]="Vo_AXian",
				["vo"]="VoD_GNormal_AXian_03",
				["sort"]=1,
				["stage"]=4,
				["action"]="shy",
			},
		},
	},
	[70004]={
		["name"]="好感度12-15级-4",
		["config"]={
			[0]={
				["words"]="怎么报答你呢？嗯……一个飞吻怎么样？",
				["bank"]="Vo_AXian",
				["vo"]="VoD_GFond_AXian_01",
				["sort"]=2,
				["stage"]=4,
				["action"]="daoju_tanghulu",
			},
		},
	},
	[70005]={
		["name"]="好感度12-15级-5",
		["config"]={
			[0]={
				["words"]="哇！少侠一定是听到了我的梦话，才送了我最喜欢的礼物！",
				["bank"]="Vo_AXian",
				["vo"]="VoD_GFond_AXian_02",
				["sort"]=2,
				["stage"]=4,
				["action"]="daoju_zheshan",
			},
		},
	},
	[70006]={
		["name"]="好感度12-15级-6",
		["config"]={
			[0]={
				["words"]="啊哈！我要拿去给咕咕看看少侠对我的爱！",
				["bank"]="Vo_AXian",
				["vo"]="VoD_GFond_AXian_03",
				["sort"]=2,
				["stage"]=4,
				["action"]="zhaodongxi",
			},
		},
	},
	[80001]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="奉项目组之命，阿闲要充当小掌柜兼小客服兼小会计，但阿闲只想发福利（委屈）~",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="baishoufouding",
			},
		},
	},
	[80002]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="邮局里总觉得少了点什么，以后要好好布置一下~",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="shy",
			},
		},
	},
	[80003]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="阿闲最拿手的就是给少侠发福利！",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="happy",
			},
		},
	},
	[80004]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="十连抽了没？听说清觉贼强，值得拥有~",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk_think",
			},
		},
	},
	[80005]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="邮局里总觉得少了点什么，以后要好好布置一下~",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="sad",
			},
		},
	},
	[80006]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="重置侠客，培养资源可以全部返还哦！",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk",
			},
		},
	},
	[80007]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="策划说十连抽最多可以出3张紫卡，少侠抽到过吗(｀・ω・´)，没抽到等会阿闲再来问",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="zhaodongxi",
			},
		},
	},
	[80008]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="少侠少侠，侠客升到70级需要品质达到紫色1星哦~",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk_xushu",
			},
		},
	},
	[80009]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="上阵侠客拥有羁绊属性，同属性3、4、5名侠客一起上阵均有不同的效果~",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk_tanshou",
			},
		},
	},
	[80010]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="火克金，金克木，那阿闲克谁？",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="talk_beishou",
			},
		},
	},
	[90001]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="3日登录送超强力侠客——少林！",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
		},
	},
	[90002]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="阿闲发现了一个神奇的地方，少侠快来传功殿看看哦。",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
		},
	},
	[90003]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="少侠莫急，这里还有很多资源哦，点击快速挂机试试看？",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="chayao",
			},
		},
	},
	[90004]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="是时候来体验真正的中原风情啦，快来江湖哦。",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
		},
	},
	[90005]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="武林求武，武学无尽，天机楼天机莫测，少侠要当心哦。",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
		},
	},
	[90006]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="帮会什么的最开心啦，可以和大家一起玩哦！",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
		},
	},
	[90007]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="侠客们其实可以为少侠争取额外奖励哦，来看看吧！",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="chayao",
			},
		},
	},
	[90008]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="闯王宝藏里有无限的挑战和宝物哦，少侠来看看吗？",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
		},
	},
	[90009]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="想要试试看自己实力的时候，可以来论剑山庄看看呀！",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="sad",
			},
		},
	},
	[90010]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="猜猜阿闲发现了什么！在练武场等你哦！",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="chayao",
			},
		},
	},
	[90011]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="上古凶兽24小时待机等待少侠来拿宝箱哦。",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
		},
	},
	[90012]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="哇这里真的有好多大神喔，快来看快来看！",
				["bank"]="",
				["vo"]="",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
		},
	},
	[100001]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="江湖快驿首席掌柜阿闲！前来报到！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_01",
				["sort"]=0,
				["stage"]=0,
				["action"]="taibangle",
			},
		},
	},
	[100002]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="你好！~你是来买报纸的吗？",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_02",
				["sort"]=0,
				["stage"]=0,
				["action"]="daoju_baozhi",
			},
		},
	},
	[100003]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="想不想~和阿闲一起去冒险？",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_03",
				["sort"]=0,
				["stage"]=0,
				["action"]="shy",
			},
		},
	},
	[100004]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="劳逸结合~要注意休息哦少侠。",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_04",
				["sort"]=0,
				["stage"]=0,
				["action"]="baibai",
			},
		},
	},
	[100005]={
		["name"]="",
		["config"]={
			[0]={
				["words"]="有什么信要阿闲代送吗~使命必达哦！",
				["bank"]="Vo_AXian",
				["vo"]="Vo_Greet_AXian_05",
				["sort"]=0,
				["stage"]=0,
				["action"]="dazhaohu",
			},
		},
	},
}