return {
	["obey_master_in_pupil"]={
		["text"]="tid#Prompt_obey_master_in_pupil",
	},
	["arena_revenge_win_in_pupil"]={
		["text"]="tid#Prompt_arena_revenge_win_in_pupil",
	},
	["arena_revenge_lose_in_pupil"]={
		["text"]="tid#Prompt_arena_revenge_lose_in_pupil",
	},
	["reward_by_adventure_in_pupil"]={
		["text"]="tid#Prompt_reward_by_adventure_in_pupil",
	},
	["reward_by_bounty_in_pupil"]={
		["text"]="tid#Prompt_reward_by_bounty_in_pupil",
	},
	["reward_by_charge_in_pupil"]={
		["text"]="tid#Prompt_reward_by_charge_in_pupil",
	},
	["graduate_in_pupil"]={
		["text"]="tid#Prompt_graduate_in_pupil",
	},
	["obey_master_in_master"]={
		["text"]="tid#Prompt_obey_master_in_master",
	},
	["arena_revenge_win_in_master"]={
		["text"]="tid#Prompt_arena_revenge_win_in_master",
	},
	["arena_revenge_lose_in_master"]={
		["text"]="tid#Prompt_arena_revenge_lose_in_master",
	},
	["reward_by_adventure_in_master"]={
		["text"]="tid#Prompt_reward_by_adventure_in_master",
	},
	["reward_by_bounty_in_master"]={
		["text"]="tid#Prompt_reward_by_bounty_in_master",
	},
	["reward_by_charge_in_master"]={
		["text"]="tid#Prompt_reward_by_charge_in_master",
	},
	["graduate_in_master"]={
		["text"]="tid#Prompt_graduate_in_master",
	},
}