return {
	[1]={
		["sort"]=1,
		["push_type"]="push_sixClockLogin",
		["season"]=0,
		["title"]="tid#PushMessage1",
		["message"]="tid#PushMessage1001",
	},
	[2]={
		["sort"]=2,
		["push_type"]="push_sevenDay",
		["season"]=0,
		["title"]="tid#PushMessage2",
		["message"]="tid#PushMessage1002",
	},
	[3]={
		["sort"]=3,
		["push_type"]="push_hours24",
		["season"]=0,
		["title"]="tid#PushMessage3",
		["message"]="tid#PushMessage1003",
	},
	[4]={
		["sort"]=4,
		["push_type"]="",
		["season"]=1,
		["title"]="",
		["message"]="",
	},
	[5]={
		["sort"]=4,
		["push_type"]="",
		["season"]=2,
		["title"]="",
		["message"]="",
	},
	[6]={
		["sort"]=4,
		["push_type"]="",
		["season"]=3,
		["title"]="",
		["message"]="",
	},
}