return {
	[340]={
		[1]={
			[1]={
				["name"]="被诓上山",
				["story"]="tid#Herolegend1_509",
			},
			[2]={
				["name"]="身陷囹圄",
				["story"]="tid#Herolegend2_509",
			},
			[3]={
				["name"]="含冤入狱",
				["story"]="tid#Herolegend3_509",
			},
			[4]={
				["name"]="逼上梁山",
				["story"]="tid#Herolegend4_509",
			},
			[5]={
				["name"]="捉史文恭",
				["story"]="tid#Herolegend5_509",
			},
			[6]={
				["name"]="南征北战",
				["story"]="tid#herolegend6_509",
			},
			[7]={
				["name"]="麒麟陨落",
				["story"]="tid#herolegend7_509",
			},
		},
		[2]={
			[1]={
				["name"]="禁军教头",
				["story"]="tid#Herolegend1_704",
			},
			[2]={
				["name"]="衙内结仇",
				["story"]="tid#Herolegend2_704",
			},
			[3]={
				["name"]="误入白虎堂",
				["story"]="tid#Herolegend3_704",
			},
			[4]={
				["name"]="野猪林被救",
				["story"]="tid#Herolegend4_704",
			},
			[5]={
				["name"]="棒打洪教头",
				["story"]="tid#Herolegend5_704",
			},
			[6]={
				["name"]="风雪山神庙",
				["story"]="tid#herolegend6_704",
			},
			[7]={
				["name"]="火并王伦",
				["story"]="tid#herolegend7_704",
			},
		},
		[3]={
			[1]={
				["name"]="飞将出世",
				["story"]="tid#Herolegend1_708",
			},
			[2]={
				["name"]="镇守虎牢关",
				["story"]="tid#Herolegend2_708",
			},
			[3]={
				["name"]="刺杀董卓",
				["story"]="tid#Herolegend3_708",
			},
			[4]={
				["name"]="逃离长安",
				["story"]="tid#Herolegend4_708",
			},
			[5]={
				["name"]="争夺兖州",
				["story"]="tid#Herolegend5_708",
			},
			[6]={
				["name"]="徐州风云",
				["story"]="tid#herolegend6_708",
			},
			[7]={
				["name"]="败亡下邳",
				["story"]="tid#herolegend7_708",
			},
		},
	},
}