return {
	[1101]={
		["condition_des"]="",
		["type"]=1,
		["option_id"]=10001,
	},
	[1102]={
		["condition_des"]="通关潘金莲侠客志后可解锁！",
		["type"]=2,
		["option_id"]=11,
	},
	[1103]={
		["condition_des"]="通关花荣侠客志后可解锁！",
		["type"]=2,
		["option_id"]=22,
	},
	[1104]={
		["condition_des"]="通关扈三娘侠客志后可解锁！",
		["type"]=2,
		["option_id"]=46,
	},
	[1105]={
		["condition_des"]="通关宋江侠客志后可解锁！",
		["type"]=2,
		["option_id"]=60,
	},
	[1106]={
		["condition_des"]="通关赵云侠客志后可解锁！",
		["type"]=2,
		["option_id"]=86,
	},
}