return {
	[407]={
		[1]={
			[1]={
				["type"]=1,
				["des"]="累计开启宝箱100次",
				["count"]=100,
				["name"]="tid#RedbagName_1",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[2]={
				["type"]=1,
				["des"]="累计开启宝箱300次",
				["count"]=300,
				["name"]="tid#RedbagName_2",
				["content"]={
					{
						107,
						0,
						3000,
					},
				},
				["random_num"]=10,
			},
			[3]={
				["type"]=1,
				["des"]="累计开启宝箱500次",
				["count"]=500,
				["name"]="tid#RedbagName_3",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
			[4]={
				["type"]=1,
				["des"]="累计开启宝箱800次",
				["count"]=800,
				["name"]="tid#RedbagName_4",
				["content"]={
					{
						107,
						0,
						8000,
					},
				},
				["random_num"]=20,
			},
			[5]={
				["type"]=2,
				["des"]="首次充值6元",
				["count"]=6,
				["name"]="tid#RedbagName_6",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[6]={
				["type"]=3,
				["des"]="累计充值%",
				["count"]=500,
				["name"]="tid#RedbagName_7",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
		},
		[2]={
			[1]={
				["type"]=1,
				["des"]="累计开启宝箱100次",
				["count"]=100,
				["name"]="tid#RedbagName_1",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[2]={
				["type"]=1,
				["des"]="累计开启宝箱300次",
				["count"]=300,
				["name"]="tid#RedbagName_2",
				["content"]={
					{
						107,
						0,
						3000,
					},
				},
				["random_num"]=10,
			},
			[3]={
				["type"]=1,
				["des"]="累计开启宝箱500次",
				["count"]=500,
				["name"]="tid#RedbagName_3",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
			[4]={
				["type"]=1,
				["des"]="累计开启宝箱800次",
				["count"]=800,
				["name"]="tid#RedbagName_4",
				["content"]={
					{
						107,
						0,
						8000,
					},
				},
				["random_num"]=20,
			},
			[5]={
				["type"]=2,
				["des"]="首次充值6元",
				["count"]=6,
				["name"]="tid#RedbagName_6",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[6]={
				["type"]=3,
				["des"]="累计充值%",
				["count"]=500,
				["name"]="tid#RedbagName_7",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
		},
		[3]={
			[1]={
				["type"]=1,
				["des"]="累计开启宝箱100次",
				["count"]=100,
				["name"]="tid#RedbagName_1",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[2]={
				["type"]=1,
				["des"]="累计开启宝箱300次",
				["count"]=300,
				["name"]="tid#RedbagName_2",
				["content"]={
					{
						107,
						0,
						3000,
					},
				},
				["random_num"]=10,
			},
			[3]={
				["type"]=1,
				["des"]="累计开启宝箱500次",
				["count"]=500,
				["name"]="tid#RedbagName_3",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
			[4]={
				["type"]=1,
				["des"]="累计开启宝箱800次",
				["count"]=800,
				["name"]="tid#RedbagName_4",
				["content"]={
					{
						107,
						0,
						8000,
					},
				},
				["random_num"]=20,
			},
			[5]={
				["type"]=2,
				["des"]="首次充值6元",
				["count"]=6,
				["name"]="tid#RedbagName_6",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[6]={
				["type"]=3,
				["des"]="累计充值%",
				["count"]=500,
				["name"]="tid#RedbagName_7",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
		},
		[4]={
			[1]={
				["type"]=1,
				["des"]="累计开启宝箱100次",
				["count"]=100,
				["name"]="tid#RedbagName_1",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[2]={
				["type"]=1,
				["des"]="累计开启宝箱300次",
				["count"]=300,
				["name"]="tid#RedbagName_2",
				["content"]={
					{
						107,
						0,
						3000,
					},
				},
				["random_num"]=10,
			},
			[3]={
				["type"]=1,
				["des"]="累计开启宝箱500次",
				["count"]=500,
				["name"]="tid#RedbagName_3",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
			[4]={
				["type"]=1,
				["des"]="累计开启宝箱800次",
				["count"]=800,
				["name"]="tid#RedbagName_4",
				["content"]={
					{
						107,
						0,
						8000,
					},
				},
				["random_num"]=20,
			},
			[5]={
				["type"]=2,
				["des"]="首次充值6元",
				["count"]=6,
				["name"]="tid#RedbagName_6",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[6]={
				["type"]=3,
				["des"]="累计充值%",
				["count"]=500,
				["name"]="tid#RedbagName_7",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
		},
		[5]={
			[1]={
				["type"]=1,
				["des"]="累计开启宝箱100次",
				["count"]=100,
				["name"]="tid#RedbagName_1",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[2]={
				["type"]=1,
				["des"]="累计开启宝箱300次",
				["count"]=300,
				["name"]="tid#RedbagName_2",
				["content"]={
					{
						107,
						0,
						3000,
					},
				},
				["random_num"]=10,
			},
			[3]={
				["type"]=1,
				["des"]="累计开启宝箱500次",
				["count"]=500,
				["name"]="tid#RedbagName_3",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
			[4]={
				["type"]=1,
				["des"]="累计开启宝箱800次",
				["count"]=800,
				["name"]="tid#RedbagName_4",
				["content"]={
					{
						107,
						0,
						8000,
					},
				},
				["random_num"]=20,
			},
			[5]={
				["type"]=2,
				["des"]="首次充值6元",
				["count"]=6,
				["name"]="tid#RedbagName_6",
				["content"]={
					{
						107,
						0,
						1000,
					},
				},
				["random_num"]=4,
			},
			[6]={
				["type"]=3,
				["des"]="累计充值%",
				["count"]=500,
				["name"]="tid#RedbagName_7",
				["content"]={
					{
						107,
						0,
						5000,
					},
				},
				["random_num"]=15,
			},
		},
	},
}