return {
	[101]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=100,
		["task_id"]={
			10000,
			10040,
		},
		["task_title"]="出海风波",
		["task_describe"]="到了约定出海的日子，我将是蓬莱数年以来第一个离岛的人，中原是什么样子的呢，这一切十分令人期待。",
		["article_id"]={
		},
	},
	[103]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=102,
		["task_id"]={
			10120,
			10210,
		},
		["task_title"]="神犀决",
		["task_describe"]="侠客岛有一武学圣地，其石壁刻有无上内功神犀决，这门武功不仅是中原绝学，更是吸引着异邦武学人士。",
		["article_id"]={
		},
	},
	[105]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=105,
		["task_id"]={
			10300,
			10400,
		},
		["task_title"]="码头之乱",
		["task_describe"]="认识林良俊和李郡之后，我本想在码头修整几日，顺便结交下这两位朋友，可就在这时一伙武士入侵了出海码头。",
		["article_id"]={
		},
	},
	[106]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=114,
		["task_id"]={
			11080,
			11190,
		},
		["task_title"]="霓裳羽衣",
		["task_describe"]="自公孙大娘将坊主之位交给苏婉仪，花间派一派欣欣向荣，但是有人发现近日苏婉仪总是愁眉不展，似乎有什么心事。",
		["article_id"]={
		},
	},
	[107]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=106,
		["task_id"]={
			10600,
			10660,
		},
		["task_title"]="一较高下",
		["task_describe"]="离湘君山庄还有一些距离，放小遥提议去前面的茶铺喝一杯凉茶休息一下",
		["article_id"]={
		},
	},
	[109]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=108,
		["task_id"]={
			10410,
			10510,
		},
		["task_title"]="道不同",
		["task_describe"]="周湘君因事离开庄园，托付我代为照看他的徒弟沫沫。一日，一些不速之客突然找上门来……",
		["article_id"]={
		},
	},
	[110]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=111,
		["task_id"]={
			10800,
			10880,
			10890,
		},
		["task_title"]="扬州之巅",
		["task_describe"]="郭惊涛的归期已定，他在扬州城门找到我，希望用上毕生所学与我进行一次决斗。",
		["article_id"]={
		},
	},
	[113]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=110,
		["task_id"]={
			11000,
			11060,
		},
		["task_title"]="明珠失窃案",
		["task_describe"]="来到再来镇，有一位官差在询问可疑路人，问到细节原来是王员外家夜明珠失窃，调查一番",
		["article_id"]={
		},
	},
	[114]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=116,
		["task_id"]={
			11600,
			11630,
		},
		["task_title"]="东篱除恶",
		["task_describe"]="在路上遇到一个惊慌的村民，又是东篱寨那帮恶人在作祟，这次一定要一网打尽",
		["article_id"]={
		},
	},
	[115]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=115,
		["task_id"]={
			11500,
			11560,
		},
		["task_title"]="万金家产",
		["task_describe"]="来到金水镇，似乎有一家丧事没办完就开始抢起了家产，金家族长拜托你找到金老爷遗嘱",
		["article_id"]={
		},
	},
	[117]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=117,
		["task_id"]={
			11700,
			11810,
		},
		["task_title"]="天问",
		["task_describe"]="名剑大会召开的日子悄然临近，名剑山庄打造了一柄名为天问的宝剑，用以奖励夺得魁首的侠客。",
		["article_id"]={
		},
	},
	[118]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=118,
		["task_id"]={
			118001,
			118013,
		},
		["task_title"]="鲜味汤",
		["task_describe"]="千岛湖风景秀丽，物产丰富，各色美食多不胜数，但其中最为知名的，还要数鲜味坊的招牌菜——鲜味汤！",
		["article_id"]={
		},
	},
	[119]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=119,
		["task_id"]={
			119001,
			119006,
		},
		["task_title"]="林海之围",
		["task_describe"]="本是帮姜笑川寻找遗失的包裹，但姜笑川却突然消失不见了……",
		["article_id"]={
		},
	},
	[120]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=120,
		["task_id"]={
			12000,
			12100,
		},
		["task_title"]="太白",
		["task_describe"]="姑苏慕容作为武林正派一大魁首，弟子如云。其武功以琴音合剑，攻伐手法多变，然如今姑苏慕容日益低迷，令慕容清月愁心不止。",
		["article_id"]={
		},
	},
	[200]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=200,
		["task_id"]={
			20010,
			20050,
		},
		["task_title"]="凌霄峡之变",
		["task_describe"]="凌霄峡深处有一座舍利塔，这里的和尚被黑衣人围攻，黑衣人似乎有不可告人的企图",
		["article_id"]={
		},
	},
	[201]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=201,
		["task_id"]={
			20100,
			20140,
		},
		["task_title"]="偷师",
		["task_describe"]="达摩洞，这里是少林寺中僧人面壁苦修的地方，自灵霄峡之围后，这里似乎也不太平",
		["article_id"]={
		},
	},
	[202]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=202,
		["task_id"]={
			20200,
			20330,
		},
		["task_title"]="如是我闻",
		["task_describe"]="清觉接待了一群前来避难的薛家村村民，不日朝廷大军杀到，围堵了少林寺。",
		["article_id"]={
		},
	},
	[203]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=203,
		["task_id"]={
			20350,
			20380,
		},
		["task_title"]="三杯倒",
		["task_describe"]="落枫谷前有个驿站，来到这里不如进去歇歇",
		["article_id"]={
		},
	},
	[204]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=204,
		["task_id"]={
			20400,
			20460,
		},
		["task_title"]="无级神兵",
		["task_describe"]="到了无极镇碰到一个说书先生，正说着早年神刀门的弟子柳无情，偷出无极神兵建立无极镇的故事，郭惊涛欲言又止",
		["article_id"]={
		},
	},
	[205]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=205,
		["task_id"]={
			20500,
			20600,
		},
		["task_title"]="扬刀天下",
		["task_describe"]="神刀门的扬刀大会如期举办，如今的神刀百废待兴，不如看看有什么能帮郭惊涛的吧。",
		["article_id"]={
		},
	},
	[206]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=206,
		["task_id"]={
			20610,
			20650,
		},
		["task_title"]="燕然峰之围",
		["task_describe"]="在去燕然峰的路上碰到一个受伤的斥候，斥候说燕然峰被黑衣人控制，黑衣人似乎不是中原人",
		["article_id"]={
		},
	},
	[207]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=207,
		["task_id"]={
			20700,
			20750,
		},
		["task_title"]="夜袭天门关",
		["task_describe"]="把在燕然峰发现契丹人的事告诉天门关守关大将，防止有细作混进来",
		["article_id"]={
		},
	},
	[208]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=208,
		["task_id"]={
			20800,
			20920,
		},
		["task_title"]="潜龙勿用",
		["task_describe"]="途径太原之时，偶遇薛家军的薛忘，误打误撞之下，一场事关玄甲军与太原府的阴谋浮出水面。",
		["article_id"]={
		},
	},
	[209]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=209,
		["task_id"]={
			20930,
			20980,
		},
		["task_title"]="桃花醉",
		["task_describe"]="在赶往玄甲堡的路上走进了一个满是桃花的村子，这里犹如室外桃源，好像有说书先生在说故事，一时之间忘记了赶路的疲惫，去看看",
		["article_id"]={
		},
	},
	[210]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=210,
		["task_id"]={
			21010,
			21070,
		},
		["task_title"]="古战先人",
		["task_describe"]="边关战事吃紧，周城戒严，在投宿于广武城时，陆小遥发现了一个可疑的男子。",
		["article_id"]={
		},
	},
	[211]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=211,
		["task_id"]={
			21100,
			21200,
		},
		["task_title"]="赤龙玄甲",
		["task_describe"]="边关战事吃紧，周城戒严，在投宿于广武城时，陆小遥发现了一个可疑的男子。",
		["article_id"]={
		},
	},
	[212]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=212,
		["task_id"]={
			21210,
			21270,
		},
		["task_title"]="雪崩",
		["task_describe"]="前方轰隆有声，似乎发生了雪崩往前走走看看",
		["article_id"]={
		},
	},
	[213]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=213,
		["task_id"]={
			21310,
			21360,
		},
		["task_title"]="雁门关之役",
		["task_describe"]="雁门关防备森严，似乎最近又有敌人来袭，上去看看有什么可疑帮助他们",
		["article_id"]={
		},
	},
	[214]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=214,
		["task_id"]={
			21400,
			21500,
		},
		["task_title"]="金丹客",
		["task_describe"]="在纯阳山下发现一名昏迷在风雪中的剑客，为救其性命，背着他向纯阳宫行去。",
		["article_id"]={
		},
	},
	[215]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=215,
		["task_id"]={
			21510,
			21560,
		},
		["task_title"]="论剑",
		["task_describe"]="天下四族谁强谁弱并没有一个定论，这次高人摆下剑阵，似乎可以前往破阵见识天下英雄",
		["article_id"]={
		},
	},
	[216]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=216,
		["task_id"]={
			21610,
			21660,
		},
		["task_title"]="内外之争",
		["task_describe"]="内功强还是外功强总是武林之人讨论的日常话题，这次又发生了什么",
		["article_id"]={
		},
	},
	[217]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=217,
		["task_id"]={
			21700,
			21790,
		},
		["task_title"]="剑气近",
		["task_describe"]="整个华山派最能惹事的宁不凡被关了禁闭，被禁足在思过洞中。而此时，数日前他所惹下的祸事正在发酵，一场悲剧就此诞生。",
		["article_id"]={
		},
	},
	[300]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=300,
		["task_id"]={
			30010,
			30090,
		},
		["task_title"]="凤求凰",
		["task_describe"]="山间有音律流出，山上似乎有个山庄，声音是从山庄里传出来的，进去看看",
		["article_id"]={
		},
	},
	[301]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=301,
		["task_id"]={
			30100,
			30200,
		},
		["task_title"]="子不语",
		["task_describe"]="长安城内最近出现花鬼索命的传闻，多有平民遇害，京兆府上下因此事焦头烂额。朝廷不得已派出六扇门查案，责令三日之内缉拿真凶。",
		["article_id"]={
		},
	},
	[302]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=302,
		["task_id"]={
			30210,
			30280,
		},
		["task_title"]="伪君子",
		["task_describe"]="前面有一群人围住一个妇人，上去问问发生了什么",
		["article_id"]={
		},
	},
	[303]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=303,
		["task_id"]={
			30300,
			30390,
		},
		["task_title"]="神鹿传说",
		["task_describe"]="马嵬驿万年县流传着一个传说，在深山的森林中，有一头神鹿，它会帮助遇到危险的人，并能治愈病人的伤痛。",
		["article_id"]={
		},
	},
	[304]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=304,
		["task_id"]={
			30410,
			30490,
		},
		["task_title"]="火烧南河",
		["task_describe"]="前面村子火光冲天，过去看看发生了什么",
		["article_id"]={
		},
	},
	[305]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=305,
		["task_id"]={
			30500,
			30592,
		},
		["task_title"]="春风不度",
		["task_describe"]="玉门关附近的柯木村近日出现了怪事，多家的废木炭均不翼而飞，同事每日都会发现家中多出钱财。",
		["article_id"]={
		},
	},
	[306]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=306,
		["task_id"]={
			30610,
			30690,
		},
		["task_title"]="紧急物资",
		["task_describe"]="沙漠中遇见了熟人，去看看是否需要帮助",
		["article_id"]={
		},
	},
	[307]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=307,
		["task_id"]={
			30700,
			30780,
		},
		["task_title"]="龙门客栈",
		["task_describe"]="行至龙门，天干地燥，只有一家客栈开着，但是据别人说，这客栈可不算太平。",
		["article_id"]={
		},
	},
	[400]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=400,
		["task_id"]={
			40000,
			40400,
		},
		["task_title"]="传世佳肴",
		["task_describe"]="终于来到了洞庭湖畔，丐帮的沈念已经等候多时，摆宴以待。",
		["article_id"]={
		},
	},
	[401]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=401,
		["task_id"]={
			40100,
			40190,
		},
		["task_title"]="风雨连环坞",
		["task_describe"]="行至巴蜀腹地，在一处水泽颇多的地方迷了路，据说十二连环坞就在附近，可千万不要遇到那些水匪才好。",
		["article_id"]={
		},
	},
	[402]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=402,
		["task_id"]={
			40200,
			40226,
		},
		["task_title"]="落英集霞录",
		["task_describe"]="途经落英轩时看到了有老人倒在路边，一旁还有少女在哭泣，上前问问她们是否需要帮助。",
		["article_id"]={
		},
	},
	[403]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=403,
		["task_id"]={
			40300,
			40390,
		},
		["task_title"]="胭脂玉佩",
		["task_describe"]="来到巴蜀腹地的成都城，这里真是热闹非凡，我已经迫不及待找个客栈大吃一顿了。",
		["article_id"]={
		},
	},
	[404]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=404,
		["task_id"]={
			40400,
			40480,
		},
		["task_title"]="无蕊蓝蝶",
		["task_describe"]="唐门位处险地，今年与武林中许多门派有摩擦，这里的弟子浑身透露着一股肃杀之气。",
		["article_id"]={
		},
	},
	[405]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=405,
		["task_id"]={
			40500,
			40519,
		},
		["task_title"]="瘗玉埋香",
		["task_describe"]="来到大理山城，发现镇民们在围着一篇告示议论纷纷，你们决定上前看看。",
		["article_id"]={
		},
	},
	[406]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=406,
		["task_id"]={
			40600,
			40618,
		},
		["task_title"]="此去经年",
		["task_describe"]="拜访五毒教，被阿岚热情的招待，按照当地的风俗习惯，要先和五毒教的姑娘们对山歌……",
		["article_id"]={
		},
	},
	[407]={
		["task_frist"]=0,
		["tasks_types"]=2,
		["map_id"]=407,
		["task_id"]={
			40700,
			40726,
		},
		["task_title"]="浩然正气",
		["task_describe"]="行至落雁城，被天枢子邀请至武林盟中做客，趁此机会可以结识一下武林盟中的“七星”。",
		["article_id"]={
		},
	},
	[10000]={
		["task_frist"]=0,
		["tasks_types"]=3,
		["map_id"]=100,
		["task_id"]={
			1000010,
		},
		["task_title"]="测试密令",
		["task_describe"]="",
		["article_id"]={
		},
	},
}