return {
	[101]={
		["resource"]="chapter10",
		["bgm"]="Set_State_GuaJ03",
		["idle_type"]=1,
	},
	[102]={
		["resource"]="jiaowai",
		["bgm"]="Set_State_XiaYi",
		["idle_type"]=1,
	},
	[103]={
		["resource"]="migong",
		["bgm"]="Set_State_Cwbz",
		["idle_type"]=1,
	},
	[104]={
		["resource"]="shijie91",
		["bgm"]="Set_State_JiangHu",
		["idle_type"]=1,
	},
	[105]={
		["resource"]="tianjilou",
		["bgm"]="Set_State_Battle02",
		["idle_type"]=1,
	},
	[106]={
		["resource"]="unionboss",
		["bgm"]="Set_State_Xwyj",
		["idle_type"]=1,
	},
	[107]={
		["resource"]="wuxingzhen",
		["bgm"]="Set_State_SiXiang",
		["idle_type"]=1,
	},
	[108]={
		["resource"]="chapter_five",
		["bgm"]="Set_State_Battle02",
		["idle_type"]=1,
	},
	[109]={
		["resource"]="boss",
		["bgm"]="Set_State_Battle03",
		["idle_type"]=1,
	},
	[110]={
		["resource"]="chapter7",
		["bgm"]="Set_State_GuaJ02",
		["idle_type"]=1,
	},
	[111]={
		["resource"]="chapter6",
		["bgm"]="Set_State_GuaJ04",
		["idle_type"]=1,
	},
	[112]={
		["resource"]="chapter5",
		["bgm"]="Set_State_GuaJ01",
		["idle_type"]=1,
	},
	[113]={
		["resource"]="",
		["bgm"]="Set_State_AXian",
		["idle_type"]=1,
	},
	[114]={
		["resource"]="chapter11",
		["bgm"]="Set_State_GuaJ04",
		["idle_type"]=1,
	},
	[115]={
		["resource"]="",
		["bgm"]="Set_State_Battle01",
		["idle_type"]=1,
	},
	[116]={
		["resource"]="shijie92",
		["bgm"]="Set_State_JiangHu",
		["idle_type"]=1,
	},
	[117]={
		["resource"]="chapter8",
		["bgm"]="Set_State_JiaBan",
		["idle_type"]=2,
	},
	[118]={
		["resource"]="chapter1",
		["bgm"]="Set_State_GuaJ04",
		["idle_type"]=1,
	},
	[119]={
		["resource"]="chapter10",
		["bgm"]="Set_State_GuaJ03",
		["idle_type"]=1,
	},
	[999]={
		["resource"]="xiadaomizong",
		["bgm"]="Set_State_GuaJ01",
		["idle_type"]=1,
	},
	[120]={
		["resource"]="chapter4",
		["bgm"]="Set_State_GuaJ03",
		["idle_type"]=2,
	},
	[121]={
		["resource"]="chapter3",
		["bgm"]="Set_State_GuaJ04",
		["idle_type"]=2,
	},
	[122]={
		["resource"]="chapter9",
		["bgm"]="Set_State_GuaJ02",
		["idle_type"]=2,
	},
	[123]={
		["resource"]="unionwar",
		["bgm"]="Set_State_GongHuiZhan",
		["idle_type"]=1,
	},
	[124]={
		["resource"]="shijie93",
		["bgm"]="Set_State_JiangHu",
		["idle_type"]=1,
	},
	[125]={
		["resource"]="chapter2",
		["bgm"]="Set_State_GuaJ03",
		["idle_type"]=2,
	},
	[126]={
		["resource"]="chapter12",
		["bgm"]="Set_State_GuaJ03",
		["idle_type"]=2,
	},
	[127]={
		["resource"]="chapter13",
		["bgm"]="Set_State_GuaJ03",
		["idle_type"]=2,
	},
	[128]={
		["resource"]="chapter15",
		["bgm"]="Set_State_Battle02",
		["idle_type"]=1,
	},
	[129]={
		["resource"]="chapter16",
		["bgm"]="Set_State_Battle02",
		["idle_type"]=1,
	},
	[130]={
		["resource"]="chapter17",
		["bgm"]="Set_State_Battle02",
		["idle_type"]=1,
	},
	[131]={
		["resource"]="chapter14",
		["bgm"]="Set_State_Battle02",
		["idle_type"]=1,
	},
	[132]={
		["resource"]="shijie94",
		["bgm"]="Set_State_JiangHu",
		["idle_type"]=1,
	},
	[133]={
		["resource"]="wuxingliansai",
		["bgm"]="Set_State_Battle02",
		["idle_type"]=2,
	},
	[134]={
		["resource"]="chapter10001",
		["bgm"]="Set_State_GongHuiZhan",
		["idle_type"]=1,
	},
	[135]={
		["resource"]="qimendunjia",
		["bgm"]="Set_State_GongHuiZhan",
		["idle_type"]=1,
	},
	[136]={
		["resource"]="huashanlunjian",
		["bgm"]="Set_State_Battle02",
		["idle_type"]=2,
	},
	[137]={
		["resource"]="guildhighwar",
		["bgm"]="Set_State_Battle02",
		["idle_type"]=2,
	},
	[140]={
		["resource"]="gujianqitan",
		["bgm"]="Set_State_Cwbz",
		["idle_type"]=1,
	},
	[141]={
		["resource"]="pet_hall",
		["bgm"]="Set_State_ChongWu",
		["idle_type"]=2,
	},
}