return {
	[1001]={
		["team"]=1,
		["name"]="seal_character_name_1",
		["addition2"]={
			["attrs"]={
				{
					1901,
					0.05,
				},
				{
					1903,
					0.05,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_1",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				1,
			},
			["tips"]="seal_character_suittips_1_1",
		},
		["icon"]="icon_fuzhuan_tuwei",
		["quality"]=10,
		["weight"]={
			90,
			10,
			0,
		},
		["main_icon"]="icon_xk_fuzhuan_tuwei",
		["resonance_name"]="突围",
		["story"]="seal_character_story_1",
	},
	[2001]={
		["team"]=1,
		["name"]="seal_character_name_2",
		["addition2"]={
			["attrs"]={
				{
					1901,
					0.08,
				},
				{
					1903,
					0.08,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_2",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				2,
			},
			["tips"]="seal_character_suittips_1_2",
		},
		["icon"]="icon_fuzhuan_tuwei",
		["quality"]=14,
		["weight"]={
			0,
			88,
			12,
		},
		["main_icon"]="icon_xk_fuzhuan_tuwei",
		["resonance_name"]="突围",
		["story"]="seal_character_story_2",
	},
	[2002]={
		["team"]=2,
		["name"]="seal_character_name_4",
		["addition2"]={
			["attrs"]={
				{
					1901,
					0.08,
				},
				{
					1902,
					0.08,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_4",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				4,
			},
			["tips"]="seal_character_suittips_1_4",
		},
		["icon"]="icon_fuzhuan_nuchao",
		["quality"]=14,
		["weight"]={
			0,
			88,
			12,
		},
		["main_icon"]="icon_xk_fuzhuan_nuchao",
		["resonance_name"]="怒潮",
		["story"]="seal_character_story_4",
	},
	[2003]={
		["team"]=3,
		["name"]="seal_character_name_6",
		["addition2"]={
			["attrs"]={
				{
					1902,
					0.15,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_6",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				6,
			},
			["tips"]="seal_character_suittips_1_6",
		},
		["icon"]="icon_fuzhuan_fenghua",
		["quality"]=14,
		["weight"]={
			0,
			88,
			12,
		},
		["main_icon"]="icon_xk_fuzhuan_fenghua",
		["resonance_name"]="风华",
		["story"]="seal_character_story_6",
	},
	[3001]={
		["team"]=1,
		["name"]="seal_character_name_3",
		["addition2"]={
			["attrs"]={
				{
					1901,
					0.1,
				},
				{
					1903,
					0.1,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_3",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				3,
			},
			["tips"]="seal_character_suittips_1_3",
		},
		["icon"]="icon_fuzhuan_buqu",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_buqu",
		["resonance_name"]="突围",
		["story"]="seal_character_story_3",
	},
	[3002]={
		["team"]=2,
		["name"]="seal_character_name_5",
		["addition2"]={
			["attrs"]={
				{
					1901,
					0.1,
				},
				{
					1902,
					0.1,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_5",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				5,
			},
			["tips"]="seal_character_suittips_1_5",
		},
		["icon"]="icon_fuzhuan_nuchao",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_nuchao",
		["resonance_name"]="怒潮",
		["story"]="seal_character_story_5",
	},
	[3003]={
		["team"]=3,
		["name"]="seal_character_name_7",
		["addition2"]={
			["attrs"]={
				{
					1902,
					0.2,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_7",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				7,
			},
			["tips"]="seal_character_suittips_1_7",
		},
		["icon"]="icon_fuzhuan_fenghua",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_fenghua",
		["resonance_name"]="风华",
		["story"]="seal_character_story_7",
	},
	[3004]={
		["team"]=7,
		["name"]="seal_character_name_8",
		["addition2"]={
			["attrs"]={
				{
					915,
					30,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_8",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				8,
			},
			["tips"]="seal_character_suittips_1_8",
		},
		["icon"]="icon_fuzhuan_yingxi",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_yingxi",
		["resonance_name"]="影袭",
		["story"]="seal_character_story_8",
	},
	[3005]={
		["team"]=8,
		["name"]="seal_character_name_9",
		["addition2"]={
			["attrs"]={
				{
					1903,
					0.2,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_9",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				9,
			},
			["tips"]="seal_character_suittips_1_9",
		},
		["icon"]="icon_fuzhuan_aoxue",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_aoxue",
		["resonance_name"]="傲血",
		["story"]="seal_character_story_9",
	},
	[3006]={
		["team"]=9,
		["name"]="seal_character_name_10",
		["addition2"]={
			["attrs"]={
				{
					1904,
					0.05,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_10",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				10,
			},
			["tips"]="seal_character_suittips_1_10",
		},
		["icon"]="icon_fuzhuan_lingyu",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_lingyu",
		["resonance_name"]="领域",
		["story"]="seal_character_story_10",
	},
	[3007]={
		["team"]=10,
		["name"]="seal_character_name_11",
		["addition2"]={
			["attrs"]={
				{
					1901,
					0.15,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_11",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				11,
			},
			["tips"]="seal_character_suittips_1_11",
		},
		["icon"]="icon_fuzhuan_chengfeng",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_chengfeng",
		["resonance_name"]="乘风",
		["story"]="seal_character_story_11",
	},
	[3008]={
		["team"]=12,
		["name"]="seal_character_name_12",
		["addition2"]={
			["attrs"]={
				{
					1902,
					0.1,
				},
				{
					1903,
					0.1,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_12",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				12,
			},
			["tips"]="seal_character_suittips_1_12",
		},
		["icon"]="icon_fuzhuan_buqu",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_buqu",
		["resonance_name"]="不屈",
		["story"]="seal_character_story_12",
	},
	[3009]={
		["team"]=13,
		["name"]="seal_character_name_13",
		["addition2"]={
			["attrs"]={
				{
					1902,
					0.2,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_13",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				13,
			},
			["tips"]="seal_character_suittips_1_13",
		},
		["icon"]="icon_fuzhuan_tonggui",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_tonggui",
		["resonance_name"]="同归",
		["story"]="seal_character_story_13",
	},
	[3010]={
		["team"]=14,
		["name"]="seal_character_name_14",
		["addition2"]={
			["attrs"]={
				{
					1901,
					0.1,
				},
				{
					915,
					20,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_14",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				14,
			},
			["tips"]="seal_character_suittips_1_14",
		},
		["icon"]="icon_fuzhuan_fuze",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_fuze",
		["resonance_name"]="裂风",
		["story"]="seal_character_story_14",
	},
	[3011]={
		["team"]=15,
		["name"]="seal_character_name_15",
		["addition2"]={
			["attrs"]={
				{
					1902,
					0.2,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_15",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				15,
			},
			["tips"]="seal_character_suittips_1_15",
		},
		["icon"]="icon_fuzhuan_weihe",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_weihe",
		["resonance_name"]="威赫",
		["story"]="seal_character_story_15",
	},
	[3012]={
		["team"]=16,
		["name"]="seal_character_name_16",
		["addition2"]={
			["attrs"]={
				{
					1902,
					0.1,
				},
				{
					1901,
					0.05,
				},
			},
			["buffs"]={
			},
			["tips"]="seal_character_suittips_16",
		},
		["addition4"]={
			["attrs"]={
			},
			["buffs"]={
				16,
			},
			["tips"]="seal_character_suittips_1_16",
		},
		["icon"]="icon_fuzhuan_nizhuan",
		["quality"]=19,
		["weight"]={
			0,
			0,
			1,
		},
		["main_icon"]="icon_xk_fuzhuan_nizhuan",
		["resonance_name"]="逆转",
		["story"]="seal_character_story_16",
	},
}