return {
	[1]={
		["CurrencyType"]=104,
		["shopName"]="tid#ShopTypeName_1",
		["moneyGuide"]="",
	},
	[2]={
		["CurrencyType"]=115,
		["shopName"]="tid#ShopTypeName_2",
		["moneyGuide"]="",
	},
	[4]={
		["CurrencyType"]=109,
		["shopName"]="tid#ShopTypeName_4",
		["moneyGuide"]="tid#shop_type_moneyGuide_4",
	},
	[5]={
		["CurrencyType"]=0,
		["shopName"]="tid#ShopTypeName_5",
		["moneyGuide"]="",
	},
	[6]={
		["CurrencyType"]=118,
		["shopName"]="tid#ShopTypeName_6",
		["moneyGuide"]="tid#shop_type_moneyGuide_6",
	},
	[7]={
		["CurrencyType"]=107,
		["shopName"]="tid#ShopTypeName_7",
		["moneyGuide"]="",
	},
	[8]={
		["CurrencyType"]=132,
		["shopName"]="tid#ShopTypeName_8",
		["moneyGuide"]="tid#MoneyGuide_1132",
	},
	[10]={
		["CurrencyType"]=131,
		["shopName"]="tid#ShopTypeName_10",
		["moneyGuide"]="tid#MoneyGuide_1131",
	},
	[11]={
		["CurrencyType"]=136,
		["shopName"]="tid#ShopTypeName_11",
		["moneyGuide"]="tid#MoneyGuide_1136",
	},
	[20]={
		["CurrencyType"]=107,
		["shopName"]="tid#ShopTypeName_11",
		["moneyGuide"]="tid#MoneyGuide_1137",
	},
	[21]={
		["CurrencyType"]=107,
		["shopName"]="tid#ShopTypeName_11",
		["moneyGuide"]="tid#MoneyGuide_1137",
	},
	[22]={
		["CurrencyType"]=107,
		["shopName"]="tid#ShopTypeName_11",
		["moneyGuide"]="tid#MoneyGuide_1138",
	},
	[23]={
		["CurrencyType"]=107,
		["shopName"]="tid#ShopTypeName_11",
		["moneyGuide"]="tid#MoneyGuide_1139",
	},
	[24]={
		["CurrencyType"]=107,
		["shopName"]="tid#ShopTypeName_11",
		["moneyGuide"]="tid#MoneyGuide_1140",
	},
	[25]={
		["CurrencyType"]=0,
		["shopName"]="tid#ShopTypeName_12",
		["moneyGuide"]="",
	},
	[26]={
		["CurrencyType"]=149,
		["shopName"]="tid#ShopTypeName_14",
		["moneyGuide"]="tid#ShopTypeDes_01",
	},
	[27]={
		["CurrencyType"]=107,
		["shopName"]="tid#ShopTypeName_2",
		["moneyGuide"]="tid#MoneyGuide_1137",
	},
	[29]={
		["CurrencyType"]=155,
		["shopName"]="tid#ShopTypeName_29",
		["moneyGuide"]="",
	},
	[30]={
		["CurrencyType"]=0,
		["shopName"]="tid#ShopTypeName_30",
		["moneyGuide"]="",
	},
	[31]={
		["CurrencyType"]=0,
		["shopName"]="tid#ShopTypeName_31",
		["moneyGuide"]="",
	},
	[32]={
		["CurrencyType"]=0,
		["shopName"]="tid#ShopTypeName_32",
		["moneyGuide"]="",
	},
	[33]={
		["CurrencyType"]=163,
		["shopName"]="tid#ShopTypeName_33",
		["moneyGuide"]="tid#MoneyGuide_1163",
	},
	[13]={
		["CurrencyType"]=134,
		["shopName"]="tid#ShopTypeName_13",
		["moneyGuide"]="tid#MoneyGuide_1134",
	},
	[34]={
		["CurrencyType"]=171,
		["shopName"]="tid#ShopTypeName_34",
		["moneyGuide"]="tid#MoneyGuide_1171",
	},
	[35]={
		["CurrencyType"]=172,
		["shopName"]="tid#ShopTypeName_34",
		["moneyGuide"]="tid#MoneyGuide_1172",
	},
}