return {
	[1]={
		[1]={
			["hero_id"]="a_zhaowenzhuo",
			["card_id"]="赵文卓",
			["picture_id"]="",
			["channel_batydance"]="a_zhaowenzhuo_zijie",
			["channel_other"]="a_zhaowenzhuo_other",
			["x_offset"]=-323.7,
		},
		[2]={
			["hero_id"]="a_zengyi",
			["card_id"]="曾毅",
			["picture_id"]="",
			["channel_batydance"]="a_zengyi_zijie",
			["channel_other"]="a_zengyi_other",
			["x_offset"]=-380.0,
		},
		[3]={
			["hero_id"]="q_zwz_zy",
			["card_id"]="合影",
			["picture_id"]="",
			["channel_batydance"]="a_heying_zijie",
			["channel_other"]="a_heying_other",
			["x_offset"]=-323.7,
		},
		[4]={
			["hero_id"]="",
			["card_id"]="",
			["picture_id"]="",
			["channel_batydance"]="moon_shadow/a_yycs_share",
			["channel_other"]="moon_shadow/a_yycs_share",
			["x_offset"]=0.0,
		},
	},
}