return {
	["Martial_boss"]={
		[1]="tid#TextEnum_Martial_boss_1",
		[2]="tid#TextEnum_Martial_boss_2",
		[3]="tid#TextEnum_Martial_boss_3",
	},
	["Martial_ranking"]={
		[1]="tid#TextEnum_Martial_ranking_1",
		[2]="tid#TextEnum_Martial_ranking_2",
		[3]="tid#TextEnum_Martial_ranking_3",
	},
	["Guild_job"]={
		[1]="tid#TextEnum_Guild_job_1",
		[2]="tid#TextEnum_Guild_job_2",
		[3]="tid#TextEnum_Guild_job_3",
		[4]="tid#TextEnum_Guild_job_4",
	},
	["Guild_boss"]={
		[1]="tid#TextEnum_Guild_boss_1",
	},
	["Stage_id"]={
		[12]="tid#TextEnum_Stage_id_12",
		[40]="tid#TextEnum_Stage_id_40",
		[76]="tid#TextEnum_Stage_id_70",
	},
	["money"]={
		[104]="tid#MoneyGuide_104",
		[107]="tid#MoneyGuide_107",
		[109]="tid#MoneyGuide_109",
		[115]="tid#MoneyGuide_115",
		[118]="tid#MoneyGuide_118",
	},
}