return {
	[342]={
		[1]={
			["game_type"]=5,
			["game_id"]=1005,
			["game_name"]="",
			["picture"]="",
			["game_name1"]="浣熊英雄谱",
			["mail_id"]=0,
			["key"]=1,
			["des"]="",
			["frequency"]=0,
			["upper_limit"]=0,
			["reward_1"]={
			},
			["milepost_data"]={
				[0]={
				},
			},
		},
	},
	[360]={
		[1]={
			["game_type"]=5,
			["game_id"]=6001,
			["game_name"]="",
			["picture"]="",
			["game_name1"]="浣熊英雄谱",
			["mail_id"]=0,
			["key"]=1,
			["des"]="tid#XiaoHuanXiongDes_9",
			["frequency"]=0,
			["upper_limit"]=0,
			["reward_1"]={
			},
			["milepost_data"]={
				[0]={
				},
			},
		},
	},
	[387]={
		[2]={
			["game_type"]=4,
			["game_id"]=4002,
			["game_name"]="",
			["picture"]="",
			["game_name1"]="猫鼠游戏",
			["mail_id"]=0,
			["key"]=2,
			["des"]="",
			["frequency"]=3,
			["upper_limit"]=150,
			["reward_1"]={
				{
					103,
					5569,
					1,
				},
			},
			["milepost_data"]={
				[0]={
				},
			},
		},
		[3]={
			["game_type"]=4,
			["game_id"]=4002,
			["game_name"]="",
			["picture"]="",
			["game_name1"]="猫鼠游戏",
			["mail_id"]=0,
			["key"]=3,
			["des"]="",
			["frequency"]=3,
			["upper_limit"]=150,
			["reward_1"]={
				{
					103,
					5569,
					1,
				},
			},
			["milepost_data"]={
				[0]={
				},
			},
		},
	},
}