return {
	[80]={
		["charge_id"]=32,
		["price"]=68,
		["name"]="tid#BattlePassName_1",
		["name1"]="tid#BattlePassName_3",
		["mail_id"]=4,
		["stage_id"]=0,
		["go_type"]={
			27,
		},
	},
	[286]={
		["charge_id"]=2972,
		["price"]=68,
		["name"]="tid#BattlePassName_4",
		["name1"]="tid#BattlePassName_4",
		["mail_id"]=132,
		["stage_id"]=0,
		["go_type"]={
		},
	},
	[309]={
		["charge_id"]=7073,
		["price"]=128,
		["name"]="",
		["name1"]="",
		["mail_id"]=0,
		["stage_id"]=0,
		["go_type"]={
		},
	},
	[368]={
		["charge_id"]=5006,
		["price"]=128,
		["name"]="tid#BattlePassName_5",
		["name1"]="tid#BattlePassName_6",
		["mail_id"]=176,
		["stage_id"]=0,
		["go_type"]={
		},
	},
	[394]={
		["charge_id"]=5394,
		["price"]=128,
		["name"]="",
		["name1"]="",
		["mail_id"]=0,
		["stage_id"]=0,
		["go_type"]={
		},
	},
	[374]={
		["charge_id"]=5514,
		["price"]=128,
		["name"]="",
		["name1"]="",
		["mail_id"]=0,
		["stage_id"]=0,
		["go_type"]={
		},
	},
	[404]={
		["charge_id"]=5581,
		["price"]=128,
		["name"]="",
		["name1"]="",
		["mail_id"]=0,
		["stage_id"]=0,
		["go_type"]={
		},
	},
	[409]={
		["charge_id"]=5702,
		["price"]=128,
		["name"]="",
		["name1"]="",
		["mail_id"]=0,
		["stage_id"]=0,
		["go_type"]={
		},
	},
	[421]={
		["charge_id"]=6035,
		["price"]=128,
		["name"]="",
		["name1"]="",
		["mail_id"]=0,
		["stage_id"]=0,
		["go_type"]={
		},
	},
	[109]={
		["charge_id"]=6603,
		["price"]=128,
		["name"]="tid#BattlePassName_2",
		["name1"]="tid#BattlePassName_4",
		["mail_id"]=5,
		["stage_id"]=0,
		["go_type"]={
			18,
		},
	},
}