---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/2/9 14:24
---


local M = class("SimulateToKenControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        if self.m_model.is_tokens == true then
            self:updateMsg("refresh_data",nil,"TopUpGiftBag.ToKensEntrancPop")
            self:updateMsg("refresh_data",nil,"TopUpGiftBag.ToKensSelectGiftBagPop")
        end
        self:updateMsg("refresh_red_point",nil,"SimulateLift.SimulateLiftMain")
        self:closeView()
    elseif msg == "explain_btn" then
        -- 提示  
        self:openView("Pops.CommonHelpPop", { title = Language:getTextByKey("simulateLeft_text_0057"), content = Language:getTextByKey("tid#MiniGameRewardName_2") })
    elseif msg == "buy_height_royal_btn" then
        -- 购买高级战令
        self.ref_buy_token = true
        local war_order_cfg = self.m_model:get_war_order()
        self:buyForSDK(war_order_cfg.charge_id, function ()
            if self.m_view then
                self.ref_buy_token = true
                self:updateMsg("update_token")
            end
        end)
    elseif msg == "buy" then
        local war_order_cfg = self.m_model:get_war_order()
        self:buyForSDK(war_order_cfg.charge_id, function ()
            if self.m_view then
                self:updateMsg("update_token")
            end
        end)
    elseif msg == "quick_buy_btn" then
        -- 一键领取
        self:getAllRoyalReward(data)
    elseif msg == "get_reward" then
        -- 领取战令奖励
        self:getRoyalReward(data)
    elseif msg == "buy_level_btn" then
        -- 购买未领取的奖励
        local curLv = self.m_model:getShowLv()
        local allXlsxData = self.m_model:get_warrior_cfg()
        local maxLv = table.nums(allXlsxData)
        if curLv >= maxLv then
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("simulateLeft_text_0056"), delay_close = 2})
            return
        end
        local params = {
            token_id = self.m_model.m_openId,
            lv = curLv,
            token_lv = self.m_model.gb_lv,
            vsn = self.m_model.m_version,
            season = self.m_model.m_gb_season,
            callback = function ()
                self:updateMsg("buy",nil, "SimulateLift.SimulateToKen")
                --self:updateMsg("buy")
            end
        }
        self:openView("SimulateLift.SimulateTokenLevelUpPop", params)
    elseif msg == "tips_btn" then
        -- 战令等级感叹号
        local tab_data = self.m_model:get_warrior_cfg()
        local xlsxData = tab_data[1]
        local params = {
            title = Language:getTextByKey("simulateLeft_text_0065"),
            content =  xlsxData.name2,
        }
        self:openView("Pops.CommonHelpPop", params)
    elseif msg == "update_token" then
        --购买战令等级刷新    
        self.m_model.m_data = data
        self.m_model:getNetData("mini_game_index", {}, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                self.m_model:refreshData(response)
                self.m_view:refreshUI()
            end
        end, nil, nil, nil)
        self.m_view:refreshUI()
    end
end

--一键领取皇家犒赏令
function M:getAllRoyalReward()
    local function receivetCallback(response)
        if self:activityOverExamine(response) then
            return
        end
        self.ref_buy_token = true
        RewardUtil:rewardTipsByData(response.reward)
        table.merge(self.m_model.m_data, response)
        self.m_model:refreshData()
        self.m_view:refreshUI()
    end
    local params = {}
    params.vsn = self.m_model.m_version
    self.m_model:getNetData("auto_receive_mini_game", params, receivetCallback)
end

--领取奖励
function M:getRoyalReward(data)
    local function receivetCallback(response)
        if self:activityOverExamine(response) then
            return
        end
        self.ref_buy_token = true
        RewardUtil:rewardTipsByData(response.reward)
        table.merge(self.m_model.m_data, response)
        self.m_model:refreshData()
        self.m_view:refreshUI()
    end
    local params = {}
    params.reward_id = data.id
    params.vsn = self.m_model.m_version
    self.m_model:getNetData("receive_mini_game", params, receivetCallback)
end

--调用sdk充值
function M:buyForSDK(charge_id, callback)
    if self.m_model.is_tokens == true then
        self:buyUseVoucher(charge_id, function ()
            if callback then
                callback()
            end
            self:RefreshOneTagData()
        end)
        return
    end
    if self.timer_id then
        Logger.logWarningAlways(self.timer_id, "-------------IsPay-----------")
        if callback then
            callback()
        end
        return
    end
    self.m_view:lockTouch()
    self.timer_id = self:setOnceTimer(8, function ()
        self.m_view:unlockTouch()
        if callback then
            callback()
        end
        self.timer_id = nil
    end)
    PayUtil:rechargeByChargeId(charge_id, function ()
        if self.m_view then
            if callback then
                callback()
            end
            if self.timer_id then
                self:removeTimer(self.timer_id)
                self.timer_id = nil
            end
            self.m_view:unlockTouch()
            self:RefreshOneTagData()
        end
    end)
end

function M:RefreshOneTagData()
    self.m_model.m_gb_payment_status = 1
    self.m_view:switchUI()
end

--使用代金券购买
function M:buyUseVoucher(data, callback)
    local function receivetCallback(response)
        if callback then
            callback()
        end
        if response and response.reward then
            RewardUtil:rewardTipsByData(response.reward)
        end
    end
    local charge = ConfigManager:getCfgByName("charge")
    local cfg = charge[data]
    if cfg == nil then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0129",data), delay_close = 2})
        return
    end
    local voucher_data = RewardUtil:getProcessRewardData({RewardUtil.REWARD_TYPE_KEYS.VOUCHER,0,0})
    if voucher_data.user_num < cfg.price then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0130",data), delay_close = 2})
        return
    end
    local params = {
        charge_id = data
    }
    self.m_model:getNetData("voucher", params, receivetCallback)
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        --self:closeView("SimulateLift.SimulateLiftMain")
        self:closeView()
        return true
    end
    if response.update == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M