---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---

local M = class("SimulateToKenModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:getData("mini_game_index")
end

function M:onEnter()
    --if self.m_data["end"] == 1 then
    --    return
    --end
    self:refreshData()
    self.m_openId = 286   --self.m_params.open_id
    self.is_tokens = self.m_params.is_token or false
end

function M:refreshData(response)
    if self.m_data == nil then self.m_data = {} end
    if response then
        table.merge(self.m_data, response)
    end
    self.m_version = self.m_data.vsn
    -- 小游戏币数量
    self.m_gbs = self.m_data.gbs
    -- 当期结束时间戳, 为0未开启
    self.m_gb_end_ts = self.m_data.gb_end_ts
    -- 已领免费奖励id数组
    self.m_gb_free_received = self.m_data.gb_free_received
    -- 已领付费奖励id数组
    self.m_gb_pay_received = self.m_data.gb_pay_received
    -- 付费状态   (1开启, 0未开启)
    self.m_gb_payment_status = self.m_data.gb_payment_status
    -- 战令等级  (取minigame_war_order_reward配置的时候作第一层key使用)
    self.m_gb_lv = self.m_data.gb_lv
    -- 是否开启   (1开启, 0未开启)
    self.m_is_gb_open = self.m_data.is_gb_open
    self.m_gb_season = self.m_data.gb_season
end

function M:checkWarInTab(rewards, data)
    for k,v in pairs(rewards) do
        if v[1] == data[1] and v[2] == data[2] then
            return true
        end
    end
    return false
end

function M:checkInRewards(rewards, data)
    for k,v in pairs(rewards) do
        if v[1] == data[1] and v[2] == data[2] then
            v[3] = v[3] + data[3]
        end
    end
    return rewards
end

--战令奖励
function M:getAllReward()
    local war_table = self:get_warrior_cfg()
    local rewards = {}
    for i = 1, #war_table do
        local m_cfg = table.copy(war_table[i])
        if m_cfg then
            local nearestSeason = self:getNearestSeason(m_cfg.fee_incentives)
            for _,itemData in pairs(m_cfg.fee_incentives[nearestSeason]) do
                if self:checkWarInTab(rewards, itemData) == true then
                    self:checkInRewards(rewards, itemData)
                else
                    table.insert( rewards, itemData)
                end
            end
        end
    end
    local function sortFunc(id_one, id_two)
        local bl_1 = (id_one[1] == 101 or id_one[1] == 130) and 1 or 0
        local bl_2 = (id_two[1] == 101 or id_two[1] == 130) and 1 or 0
        return bl_1 > bl_2
    end
    table.sort(rewards, sortFunc)
    return rewards
end

function M:getShowLv()
    local itemData = self:get_warrior_cfg()
    local c_lv = 1
    for i = 1, table.nums(itemData) do
        local c_cfg = itemData[i]
        if self.m_gbs >= c_cfg.condition then
            c_lv = i
        end
    end
    return c_lv
end

--战令进度
function M:getTokenSlider()
    local tab = self:get_warrior_cfg()
    local curLv = self:getShowLv()
    local c_cfg = tab[curLv]
    local n_cfg = tab[curLv+1]
    if n_cfg then
        return (self.m_gbs - c_cfg.condition), (n_cfg.condition - c_cfg.condition)
    else
        if c_cfg then
            return c_cfg.condition, c_cfg.condition
        else
            return 0,0  
        end
    end
    return 0,0
end

--战令表
function M:get_war_order()
    local war_tab = ConfigManager:getCfgByName("war_order")
    if war_tab[self.m_openId] == nil then
        Logger.logError("策划相关配置缺失----openId"..self.m_openId)
    end
    return war_tab[self.m_openId]
end

--战令配置数据
function M:get_warrior_cfg()
    local minigameToKenXlsxData = ConfigManager:getCfgByName("minigame_war_order_reward")
    local version = self.m_version
    if not version then
        return {}
    end
    version = version== 0 and 1 or version
    return minigameToKenXlsxData[version]
end

function M:getReceived(isBuy, id)
    local data = isBuy and self.m_gb_pay_received or self.m_gb_free_received
    for _, itemData in pairs(data) do
        if itemData == id then
            return true
        end
    end
    return false
end

-- 获取策划填的最近的season -- 服务器要求
function M:getNearestSeason(data)
    local tempList = {}
    for serverSeason, itemData in pairs(data) do
        table.insert(tempList, {
            serverSeason = serverSeason,
            itemData = itemData,
        })
    end
    table.sort(tempList, function(itemData1, itemData2) return itemData1.serverSeason < itemData2.serverSeason end)
    local maxItemData = tempList[#tempList]
    local curSeason = 0
    if self.m_gb_season > maxItemData.serverSeason then
        return maxItemData.serverSeason
    else
        for index = 1, #tempList do
            local itemData = tempList[index]
            if itemData.serverSeason == self.m_gb_season then
                return self.m_gb_season
            else
                if self.m_gb_season > itemData.serverSeason then
                    curSeason = itemData.serverSeason
                else
                    break
                end
            end
        end
        return curSeason
    end
    return 0
end

--战令购买可领
function M:getCanHaveReward(m_token_lv)
    local war_table = self:get_warrior_cfg()
    local c_lv = m_token_lv > 0 and m_token_lv or 1
    local rewards = {}
    for i = 1, m_token_lv do
        local m_cfg = table.copy(war_table[i])
        if m_cfg then
            local nearestSeason = self:getNearestSeason(m_cfg.fee_incentives)
            for _, itemData in pairs(m_cfg.fee_incentives[nearestSeason]) do
                if self:checkWarInTab(rewards, itemData) == true then
                    self:checkInRewards(rewards, itemData)
                else
                    table.insert( rewards, itemData)
                end
            end
        end
    end
    local function sortFunc(id_one, id_two)
        local bl_1 = (id_one[1] == 101 or id_one[1] == 130) and 1 or 0
        local bl_2 = (id_two[1] == 101 or id_two[1] == 130) and 1 or 0
        return bl_1 > bl_2
    end
    table.sort(rewards, sortFunc)
    return rewards
end

return M