---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:27
---


local M = class("SimulateToKenView",LikeOO.OOPopBase)
-- 侠客人生模拟器
M.m_uiName = "SimulateLift/SimulateToKen"  -- prefab name
M.m_size_type = 1
M.m_iphoneXAdapter = true

function M:onEnter()
    self:bindUI()
    self:refreshUI()

    self.m_control:setOnceTimer(0.5,function()
        self.m_control:activityOverExamine(self.m_model.m_data)
    end)
end

function M:refreshUI()
    self:setTextByLanKey("text_resetCount", "simulateLeft_text_0005", self.m_model.m_resetCount)
    self.showLv = self.m_model:getShowLv()
    self:updateTime()
    self:refreshBuyToKen()
    local isOpen = self.m_model.m_gb_payment_status == 1
    self:setObjectVisible("loopscroll", (not isOpen))
    self:setObjectVisible("loopscroll_get", isOpen)
    if not isOpen then
        self:createLoopScroll()
    else
        self:createLoopScroll2()
    end
    self:refreshToKenLevelNode()
    local isShowRedDot = UserDataManager:getRedDotByKey("life_reset")
    self:setObjectVisible("img_redDot", isShowRedDot == 1)
end

function M:refreshToKenLevelNode()
    self:setTextByLanKey("dengji_text", "simulateLeft_text_0053")
    self:setText("lv_text", self.m_model:getShowLv())
    self:setTextByLanKey("desc2_text", "tid#MiniGameRewardName_1")
    local c_num, max_num = self.m_model:getTokenSlider()
    self:setTextByLanKey("slider_text", c_num.."/"..max_num)
    local slider_img = self:findSlider("slider_bg")
    local sliderValue = 0
    if max_num > 0 then
        sliderValue = c_num / max_num
    end
    slider_img.value = sliderValue
end

function M:createLoopScroll2()
    local data = self.m_model:get_warrior_cfg()
    if self.m_scroll_view2 == nil then
        local loopscroll = self:findGameObject("loopscroll_get")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self:update_Gift(index, cell_obj, cell_data)
            end,
        }
        self.m_scroll_view2 = LoopScrollViewUtil.new(params)
    else
        self.m_scroll_view2:reloadData(data, true)
    end
end

function M:createLoopScroll()
    local data = self.m_model:get_warrior_cfg()
    if self.m_scroll_view == nil then
        local loopscroll = self:findGameObject("loopscroll")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self:update_Gift(index, cell_obj, cell_data)
            end,
        }
        self.m_scroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_scroll_view:reloadData(data, true)
    end
end

function M:getReward(index)
    self:updateMsg("get_reward", {id = index})
end

function M:updateTime()
    local m_end_ts = self.m_model.m_gb_end_ts
    if m_end_ts and m_end_ts >= 0 then
        local cur_tim = UserDataManager:getServerTime()
        local tim = m_end_ts - cur_tim
        local show_tim = GameUtil:formatTimeBySecond(tim)
        local day, hour, min, sec = GameUtil:getTimeLayoutBySecond(tim)
        local showDayTimer = ConfigManager:getCommonValueById(686) or 4
        self:setObjectVisible("buy_level_btn", day < showDayTimer )
        if day > 0 then
            self:setTextByLanKey("tim_text", "gf_str_0042", day, hour, min, sec)
        else
            self:setTextByLanKey("tim_text", show_tim)
        end
    else
        self:setTextByLanKey("tim_text", " 00:00:00")
    end
end

function M:update_Gift(index, cell_obj, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    local free_data = self.m_model:getReceived(false, index)
    local pay_data = self.m_model:getReceived(true, index)
    local num = luaBehaviour:FindText("lv_title_text")
    num.text = index..Language:getTextByKey("simulateLeft_text_0052")
    local free_obj = luaBehaviour:FindGameObject("free_prent")
    local pay_obj = luaBehaviour:FindGameObject("pay_prent")
    UIUtil.destroyAllChild(free_obj.transform)
    UIUtil.destroyAllChild(pay_obj.transform)
    local function callback(obj, data)
        if free_data == false then
            if self.m_model.m_gbs >= cell_data.condition then
                self:getReward(index)
            end
        end
    end
    local function callback2(obj, data)
        if self.m_model.m_gb_payment_status == 1 and pay_data == false then
            if self.m_model.m_gbs >= cell_data.condition then
                self:getReward(index)
            end
        end
    end
    local can_click = true
    if self.m_model.m_gbs >= cell_data.condition and free_data == false then
        can_click = false
    end
    local pay_click = true
    if self.m_model.m_gbs >= cell_data.condition and pay_data == false and self.m_model.m_pay_status == 1  then
        pay_click = false
    end
    local freeSeason = self.m_model:getNearestSeason(cell_data.free_reward)
    local freeItems = self:creatRewards(free_obj.transform, cell_data.free_reward[freeSeason], true, can_click, callback, 0.8)
    local paySeason = self.m_model:getNearestSeason(cell_data.fee_incentives)
    local payItems = self:creatRewards(pay_obj.transform, cell_data.fee_incentives[paySeason], true, pay_click, callback2, 0.8)
    for i,v in ipairs(freeItems) do
        local ItemluaBehaviour = UIUtil.findLuaBehaviour(v)
        if free_data == false then
            --未领过
            if self.m_model.m_gbs >= cell_data.condition then
                local r_data = RewardUtil:getProcessRewardData(cell_data.free_reward[freeSeason][i])
                GameUtil:creatCommonItemEffect(v, r_data.quality)
            else
                if ItemluaBehaviour then
                    LuaBehaviourUtil.setObjectVisible(ItemluaBehaviour, "lock_image", true)
                end
            end
        else
            --已领过
            if ItemluaBehaviour then
                LuaBehaviourUtil.setObjectVisible(ItemluaBehaviour, "duigoudi_img", true)
            end
        end
    end
    for i,v in ipairs(payItems) do
        local ItemluaBehaviour = UIUtil.findLuaBehaviour(v)
        if index % 5 == 0 or index == 1 then
            local dataTable = cell_data.fee_incentives[paySeason][i]
            local data = RewardUtil:getProcessRewardData(dataTable)
            GameUtil:creatCommonActiveEffect(v, data.quality)
        end
        if  self.m_model.m_is_gb_open == 0 then
            if ItemluaBehaviour then
                LuaBehaviourUtil.setObjectVisible(ItemluaBehaviour, "lock_image", true)
            end
        else
            if pay_data == false then
                --未领过
                if self.m_model.m_gbs >= cell_data.condition and self.m_model.m_gb_payment_status == 1 then
                    local r_data = RewardUtil:getProcessRewardData(cell_data.fee_incentives[paySeason][i])
                    GameUtil:creatCommonItemEffect(v, r_data.quality)
                else
                    if ItemluaBehaviour then
                        LuaBehaviourUtil.setObjectVisible(ItemluaBehaviour, "lock_image", true)
                    end
                end
            else
                if ItemluaBehaviour then
                    LuaBehaviourUtil.setObjectVisible(ItemluaBehaviour, "duigoudi_img", true)
                end
            end
        end
    end
end

function M:creatRewards(reward_node, rewards, is_show_num, is_show_detail, callback, scale, frame_effect)
    local rewards = rewards or {}
    scale = scale or 1
    local itemList = {}
    UIUtil.destroyAllChild(reward_node)
    for k,v in pairs(rewards) do
        local item = GameUtil:createItemElement(v, is_show_num, is_show_detail, callback, frame_effect)
        item.transform:SetParent(reward_node, false)
        table.insert( itemList, item)
        UIUtil.setScale(item.transform, scale)
    end
    return itemList
end

function M:switchUI()
    self:refreshUI()
    if self.m_scroll_view ~= nil then
        local index = self:getTokenSelect()
        self.m_scroll_view:moveToCellIndex(index)
    end
    if self.m_scroll_view2 ~= nil then
        local index = self:getTokenSelect()
        self.m_scroll_view2:moveToCellIndex(index)
    end
end

function M:getTokenSelect()
    local free_index = self.showLv
    local pay_index = self.showLv
    for i = 1 , self.showLv do
        if self:checkCanGet(i, self.m_model.m_gb_free_received) == true then
            free_index = i
            break
        end
    end
    for i = 1 , self.showLv do
        if self:checkCanGet(i, self.m_model.m_gb_pay_received) == true then
            pay_index = i
            break
        end
    end
    if self.m_model.m_gb_payment_status == 1 then
        return math.min(free_index, pay_index)
    else
        return free_index
    end
end

function M:checkCanGet(lv, tab)
    for k,v in pairs(tab) do
        if v == lv then
            return false
        end
    end
    return true
end

function M:refreshBuyToKen()
    local isNeedBuy = (self.m_model.m_gb_payment_status == 0)
    self:setObjectVisible("hight_node", isNeedBuy)
    if not isNeedBuy then
        return
    end
    local war_order_tab = self.m_model:get_war_order()
    if not war_order_tab then
        return
    end
    local show_price = GameUtil:getMoneyTypeNum(war_order_tab.price).. Language:getTextByKey("new_str_0037")
    self:setText("buy_heightRoyal_btn_text", show_price)
    local reward_all = self.m_model:getAllReward()
    local reward_can_get = self.m_model:getCanHaveReward(self.showLv)
    local reward_1 = self:findGameObject("reward_1")
    local reward_2 = self:findGameObject("reward_2")
    if #reward_can_get >= 4 then
        reward_2.transform.pivot = Vector2(0,0.5)
    else
        reward_2.transform.pivot = Vector2(0.5,0.5)
    end
    UIUtil.destroyAllChild(reward_1.transform)
    UIUtil.destroyAllChild(reward_2.transform)
    for i,v in pairs(reward_all) do
        local itemNode = GameUtil:createItemElement(v, true, true)
        UIUtil.setScale(itemNode.transform,0.8)
        itemNode.transform:SetParent(reward_1.transform, false)
    end
    for i,v in pairs(reward_can_get) do
        local itemNode = GameUtil:createItemElement(v, true, true)
        UIUtil.setScale(itemNode.transform,0.8)
        itemNode.transform:SetParent(reward_2.transform, false)
    end
end

function M:bindUI()
    self:setTextByLanKey("common_zl_text", "simulateLeft_text_0035")
    self:setTextByLanKey("common_gj_text", "simulateLeft_text_0036")
    self:setTextByLanKey("desc_text", "simulateLeft_text_0037")
    self:setTextByLanKey("quick_buy_btn_text", "simulateLeft_text_0038")
    self:setTextByLanKey("close_title_text", "simulateLeft_text_0057")
end

function M:destroy()
    self:updateMsg("hide_toKenView", {}, "SimulateLift.SimulateLiftMain")
    M.super.destroy(self)
end

return M
