---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 16:45
---

local M = class("PetardTaskControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_awardInfoBtn" then
        ---- 奖励详情，可领取
        self:openView("PetardActivity.PetardTaskInfo",{
            m_scoreTaskData = self.m_model.m_scoreTaskData,
            m_version = self.m_model.m_version,
            titleName = self.m_model.m_xlsxActivity.name,
        })
    elseif msg == "explain_btn" then
        -- 提示  
        local flowerData = ConfigManager:getCfgByName("flower")
        local versionData = flowerData[self.m_model.m_version]
        self:openView("Pops.CommonHelpPop", { title = self.m_model.m_mainActivityName, content = versionData.des })
    elseif msg == "btn_getBtn" then
        self.m_model:getNetData("double_twelve_receive_quest", data, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                RewardUtil:rewardTipsByData(response.reward)
                EventDispatcher:dipatchEvent("forceRefresh_petardInfoData")
                self.m_view:refreshUI()
            end
        end, nil, nil, nil)
    end
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView("PetardActivity.PetardMain")
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M
