---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 16:09
---

local M = class("PetardTaskModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:refreshData(self.m_params)
    self:getData()
end

function M:refreshData(m_params)
    self.m_activityData = m_params.activityData or {}
    self.m_openId = self.m_activityData.open_id
    self.m_version = m_params.m_version
    self.m_xlsxActivity = m_params.xlsxActivity
    self.m_mainActivityName = m_params.mainActivityName
    
    local serverData = m_params.serverData
    -- 任务
    self.m_taskData = self:trimTaskData(serverData.taskData)
    --任务积分
    self.m_score = serverData.score
    -- 积分任务
    self.m_scoreTaskData = self:trimScoreTaskData(serverData.scoreTaskData)
end

function M:trimScoreTaskData(scoreTaskData)
    local overTaskData = {}
    for i = 1, #scoreTaskData do
        local taskId = scoreTaskData[i]
        overTaskData[taskId] = taskId
    end

    local tempData = {}
    local flower_rewardData = ConfigManager:getCfgByName("flower_reward")
    local versionData = flower_rewardData[self.m_version]
    for id, itemData in pairs(versionData) do
        local isGot = (overTaskData[id] ~= nil)
        table.insert(tempData,{
            id = id,
            xlsxData = itemData,
            isCanGot = (not isGot) and (self.m_score >= itemData.score),
            isGot = isGot,
            -- 未完成
            isUnfinished = (self.m_score < itemData.score),
        })
    end
    table.sort(tempData,function(itemData1, itemData2)
        return itemData1.id < itemData2.id
    end)
    return tempData
end

function M:trimTaskData(serverTaskData)    
    local tempData = {}
    local flower_questData = ConfigManager:getCfgByName("flower_quest")
    local versionData = flower_questData[self.m_version]
    if versionData then
        local curOpenDay = GameUtil:getActityOpenDayCount(self.m_activityData.start_ts)
        local dayTaskData = versionData[curOpenDay] or {}
        for id, itemData in pairs(dayTaskData) do
            local serverData = serverTaskData[tostring(id)]
            if serverData ~= nil then
                tempData[id] = {
                    xlsxData = itemData,
                    progress = serverData.value or 0,
                    -- 领取状态 0不可领取, 1可领取, 2已全部领取完
                    status = serverData.status or 0,
                    id = id,
                }
            end
        end
    end
    table.sort(tempData, function(itemData1,itemData2)
        local sortIndex1 = (itemData1.status == 1) and -1 or itemData1.status
        local sortIndex2 = (itemData2.status == 1) and -1 or itemData2.status
        if sortIndex1 ~= sortIndex2 then
            return sortIndex1 < sortIndex2
        else
            return itemData1.id < itemData2.id
        end
    end)
    return tempData
end

function M:onEnter()

end

-- 展示的奖励    --- 关闭任务详情后需要刷新数据
function M:setAwardData()
    self.awardInfoData = {}
end

function M:setAllTaskData()
    self.allTaskData = {}
end

return M