---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 15:53
---

local M = class("PetardTaskView",LikeOO.OOPopBase)
-- 花火集会
M.m_uiName = "PetardActivity/PetardTask"  -- prefab name
M.m_size_type = 1
M.m_iphoneXAdapter = true

function M:onEnter()
    --EventDispatcher:registerEvent(GlobalConfig.EVENT_KEYS.CLOSE_VIEW, {self, self.addHandler})
    --EventDispatcher:registerEvent(GlobalConfig.EVENT_KEYS.EVERY_DAY_EVENT, {self, self.everyDayRefreshEvent})
    EventDispatcher:registerEvent("petardActivity_everyDayEvent", {self, self.everyDayRefreshEvent})
    self:bindUI()
    self:refreshUI()  
end

function M:refreshUI()
    self:refreshLeftNode()
    self:refreshTaskList()
    self:refreshActivityTimer()
end

function M:refreshActivityTimer()
    local startTimer = self.m_model.m_activityData.start_ts
    local endTimer = self.m_model.m_activityData.end_ts
    local starT = TimeUtil.gmTime(startTimer)
    local endT = TimeUtil.gmTime(endTimer)
    local timerFormat = Language:getTextByKey("castingSword_str_0012", starT.year, starT.month, starT.day,
            endT.year, endT.month, endT.day)
    self:setTextByLanKey("text_timer", "castingSword_str_0011",timerFormat)
end

function M:refreshTaskList()
    -- 任务列表
    local data = self.m_model.m_taskData
    if self.m_taskScroll_view == nil then
        local loopscroll = self:findGameObject("task_loopscroll")
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshTaskItem(cell_obj, cell_data)
            end,
            ui_name = self.m_uiName,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_goBtn" then
                    local xlsxData = cell_data.xlsxData
                    local jumpId = xlsxData.go_type
                    QuickOpenFuncUtil:openFunc(jumpId)
                    self.m_control:closeView("PetardActivity.PetardMain")
                    if (jumpId == 1) or (jumpId == 31) then
                        -- 前往主页, 前往挂机奖励
                        static_rootControl:closeAllViewPop()
                    else
                        self.m_control:closeView()
                    end
                elseif click_name == "btn_getBtn" then
                    -- 领取
                    local params = {version = self.m_model.m_version, quest_id = cell_data.id}
                    self:updateMsg("btn_getBtn", params)
                elseif click_name == "jifen_obj" then
                    -- 点击积分弹出
                    GameUtil:lookInfoTips(self.m_control, {click_transform = click_object.transform, msg = Language:getTextByKey("petard_text_0025")})
                end
            end
        }
        self.m_taskScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_taskScroll_view:reloadData(data, true)
    end
end

function M:refreshTaskItem(cell_obj, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local xlsxData = cell_data.xlsxData
        local curValue = (cell_data.progress > xlsxData.target_value) and xlsxData.target_value or cell_data.progress
        local titleText = Language:getTextByKey(xlsxData.name)
        LuaBehaviourUtil.setText(luaBehaviour, "text_taskTitle", titleText )
        LuaBehaviourUtil.setText(luaBehaviour, "text_progressText", "("..curValue.."/"..xlsxData.target_value..")")
        
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_gotBtnText","petard_text_0012")
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_getBtnText","petard_text_0013")
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_goBtnText","petard_text_0014")
        -- 领取状态 0不可领取, 1可领取, 2已全部领取完
        local status = cell_data.status
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_getBtn", (status == 1))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_gotBtnText",(status == 2))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_goBtn", (status == 0))
        
        ---- 道具花火值
        local isExistProp = xlsxData.score and (xlsxData.score > 0)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "jifen_obj", isExistProp)
        local awardPoint = luaBehaviour:FindGameObject("awardPoint")
        local posX = isExistProp and 241 or 171
        UIUtil.setLocalPosition(awardPoint.transform, posX)
        local transform = awardPoint.transform
        if isExistProp then
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "reward_num_text",xlsxData.score)
        end
        ---- 奖励
        for i = 1, 3 do
            local awardData = xlsxData.reward or {}
            local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData[i] then
                local itemNode = GameUtil:createItemElement(awardData[i], true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
    end
end

function M:refreshLeftNode()
    local allAwardData = self.m_model.awardInfoData
    local showValue = 0
    for i = 1, #self.m_model.m_scoreTaskData do
        local itemData = self.m_model.m_scoreTaskData[i]
        if (not itemData.isGot) then
            showValue = itemData.xlsxData.score
            break
        end
    end
    self:setTextByLanKey("text_taskValue1", "petard_text_0005")
    self:setTextByLanKey("text_taskValue2", self.m_model.m_score)
    --self:setTextByLanKey("text_hintText", "petard_text_0009", showValue)
    local isShowHint = showValue > 0
    self:setObjectVisible("img_scoreRedDotImg", isShowHint and (self.m_model.m_score >= showValue))
    --self:setObjectVisible("text_hintText", isShowHint)
end

function M:everyDayRefreshEvent(event, data)
    -- 刷新
    self.m_model:refreshData(data[self.m_model.m_openId])
    self:refreshUI()
end

function M:bindUI()
    self:setTextByLanKey("close_title_text", self.m_model.m_xlsxActivity.name)
   
end

function M:destroy()
    EventDispatcher:dipatchEvent("petardMainRedDotRefresh")
    EventDispatcher:unRegisterEvent("petardActivity_everyDayEvent", {self, self.everyDayRefreshEvent})
    M.super.destroy(self)
end

return M


