---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/24 15:24
---

local M = class("CastingSwordSinatvControl",LikeOO.OOControlBase)

function M:onEnter()
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_closeBtn" then
        self:closeView()
    elseif msg == "btn_goBtn" then
        local httpLink = nil
        local activeData = ConfigManager:getCfgByName("active")
        for _, itemData in pairs(activeData) do
            if itemData.open_id == self.m_model.m_open_id then
                httpLink = itemData.link
                break
            end
        end
        if not httpLink then
            return
        end
        local url_new = httpLink
        if (self.m_model.m_viewType == 1) then
            -- 江湖大事件跳抖音app
            CS.UnityEngine.Application.OpenURL(url_new)
        else
            -- 光明顶跳内置web浏览器
            SDKUtil:openUrl(url_new)
        end
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M