---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/24 15:25
---

local M = class("CastingSwordSinatvView",LikeOO.OOPopBase)

M.m_uiName = "CastingSwordMeeting/CastingSwordSinatv"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

function M:onEnter()
    self:bindUI()
end

function M:bindUI()
    local applicationId = SDKUtil.sdk_params.applicationId
    local sinatvChannelData = ConfigManager:getCfgByName("channel_id")
    local isShowJumpBtn = false
    local channelData = nil
    for channel, itemData in pairs(sinatvChannelData) do
        -- channel策划填的是包名，没改名字 
        if channel == applicationId then
            channelData = itemData
            break
        end
    end
    -- 是否大事记
    local isBigEvent = (self.m_model.m_viewType == 1)
    if channelData then
        isShowJumpBtn = (channelData.jump == 1)
        if isBigEvent then
            isShowJumpBtn = (channelData.jump1 == 1)
        end
        local xlsxBgName = isBigEvent and channelData.background_1 or channelData.background
        local xlsxBtnName = isBigEvent and channelData.btnName_1 or channelData.btnName
        local img_bg = self:findImage("bg")
        GameUtil:updateResourcesImg(img_bg, "Texture/castingSwordMeeting/".. xlsxBgName)
        local btn_goBtn_Img = self:findImage("btn_goBtn")
        self:setImg(xlsxBtnName,"pub_ui","btn_goBtn")
        self:setObjectVisible("img_logo", (channelData.logo== 1) and (not isBigEvent) )
    end
    self:setObjectVisible("btn_goBtn", isShowJumpBtn)
    local title = isBigEvent and "castingSword_str_0041" or "castingSword_str_0042"
    self:setTextByLanKey("close_title_text", title)
    local redDotName = isBigEvent and "CastingSwordBigEvent" or "CastingSwordLightTop"
    RedPointUtil:saveLocalRedPointFreshTime(redDotName)
end

function M:destroy()
    M.super.destroy(self)
end

return M