---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---

local M = class("SimulateTaskModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:refreshData(self.m_params)
    self:getData()
end

function M:refreshData(m_params)
  
end

function M:onEnter()

end

return M