---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:27
---

local M = class("SimulateTaskView",LikeOO.OOPopBase)
-- 侠客人生模拟器--任务
M.m_uiName = "SimulateLift/SimulateTask"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

function M:onEnter()
    self:bindUI()
    self:refreshUI()
end

function M:refreshUI()
    
end

function M:bindUI()

end

function M:refreshTaskList()
    -- 任务列表
    local data = self.m_model.m_taskData
    if self.m_taskScroll_view == nil then
        local loopscroll = self:findGameObject("task_loopscroll")   
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshTaskItem(cell_obj, cell_data)
            end,
            ui_name = self.m_uiName,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_goBtn" then
                   
                elseif click_name == "jifen_obj" then
                    -- 点击积分弹出
                    --GameUtil:lookInfoTips(self.m_control, {click_transform = click_object.transform, msg = Language:getTextByKey("petard_text_0025")})
                end
            end
        }
        self.m_taskScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_taskScroll_view:reloadData(data, true)
    end
end

function M:refreshTaskItem(cell_obj, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        --local xlsxData = cell_data.xlsxData
        --local curValue = (cell_data.progress > xlsxData.target_value) and xlsxData.target_value or cell_data.progress
        --local titleText = Language:getTextByKey(xlsxData.name)
        --LuaBehaviourUtil.setText(luaBehaviour, "text_taskTitle", titleText )
        --LuaBehaviourUtil.setText(luaBehaviour, "text_progressText", "("..curValue.."/"..xlsxData.target_value..")")
        --
        --LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_gotBtnText","petard_text_0012")
        --LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_getBtnText","petard_text_0013")
        --LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_goBtnText","petard_text_0014")
        ---- 领取状态 0不可领取, 1可领取, 2已全部领取完
        --local status = cell_data.status
        --LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_getBtn", (status == 1))
        --LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_gotBtnText",(status == 2))
        --LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_goBtn", (status == 0))
        --
        ------ 道具花火值
        --local isExistProp = xlsxData.score and (xlsxData.score > 0)
        --LuaBehaviourUtil.setObjectVisible(luaBehaviour, "jifen_obj", isExistProp)
        --local awardPoint = luaBehaviour:FindGameObject("awardPoint")
        --local posX = isExistProp and 241 or 171
        --UIUtil.setLocalPosition(awardPoint.transform, posX)
        --local transform = awardPoint.transform
        --if isExistProp then
        --    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "reward_num_text",xlsxData.score)
        --end
        ------ 奖励
        --for i = 1, 3 do
        --    local awardData = xlsxData.reward or {}
        --    local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
        --    UIUtil.destroyAllChild(reward_node)
        --    if awardData[i] then
        --        local itemNode = GameUtil:createItemElement(awardData[i], true, true)
        --        itemNode.transform:SetParent(reward_node.transform, false)
        --    end
        --end
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M
