---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/2/9 14:24
---


local M = class("SimulateSelectRoleControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_resetBtn" then
        if self.m_model.m_resetCount <= 0 then
            GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("simulateLeft_text_0007"), delay_close = 2})
            return
        end
        local params = {open_id = self.m_model.m_open_id, version = self.m_model.m_version}
        self.m_model:getNetData("reset_role_data", params, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                self.m_model:reduceResetCount()
                self.m_model:refreshData(response)
                self.m_view:refreshUI()
            end
        end, nil, nil, nil)
    elseif msg == "select_role" then
        audio:SendEvtUI("UI_Tab_N5")
        local params = {role_id = data.roleId, version = self.m_model.m_version, open_id = self.m_model.m_open_id}
        self.m_model:getNetData("select_role", params, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                self:openView("SimulateLift.SimulateLiftInfo", {response = response, version = self.m_model.m_version, open_id = self.m_model.m_open_id, isOldLift = false})
                self:closeView()
            end
        end, nil, nil, nil)
    elseif msg == "explain_btn" then
        -- 提示  
        local title_id = self.m_model.m_open_id == 285 and  "simulateLeft_text_0030" or "simulateLeft_text_0068"
        local des_id = self.m_model.m_open_id == 285 and  "tid#ReopenDes_7" or "tid#SwordThym_des1"
        self:openView("Pops.CommonHelpPop", { title = Language:getTextByKey(title_id), content = Language:getTextByKey(des_id) })
    end
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("simulateLeft_text_0039"), delay_close = 2})
        self:closeView()
        return true
    end
    if response.update == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M