---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/28 17:01
---

local M = class("ChinaMobileActivityNode", LikeOO.OOUIbase)
--支付宝红包
M.m_uiName = "GiftBag/ChinaMobileActivityNode"
M.cacheSpineName = ""
function M:onEnter()
    self:showUI(false)
    self.m_end_ts = 0
    self:refreshUI()
    self:bindUI()
end

function M:bindUI()
    self:setTextByLanKey("text_hintText1", "bag_text_0004")
    self:setTextByLanKey("text_hintText2", "bag_text_0005")
end

function M:switchInit(url, callback, id)
    local function callFunc(data)
        if callback then
            callback(data)
        end
        if data and data["end"] == 1 then
            return
        end
        self:refreshUI()
    end
    self.id = id
    self.m_model:initData2(url, callFunc)
end

function M:switchUI(id)
    self.id = id
    self:refreshUI()
end


function M:refreshUI()
    self:showUI(true)
    self.m_end_ts = self.m_model:getActivityEndTime(self.id)
end

function M:showUI(bl)
    local active_item = UserDataManager:getActivesDataByOpenId(416)
    if active_item then
        local time_start = TimeUtil.gmTime(active_item.start_ts)
        local time_end = TimeUtil.gmTime(active_item.end_ts)
        self:setTextByLanKey("time_countdown_text", "new_str_1108", time_start.month, time_start.day, time_end.month, time_end.day)
    end
end

function M:onButtonClick(obj, name)
    if name == "btn_infoBtn" then
        self.m_control:openView("GiftBag.ChinaMobileActivityPop")
    elseif name == "btn_gotBtn" then
        -- 跳转超链接
        local url = nil
        local active_tab = ConfigManager:getCfgByName("active")
        for i, v in pairs(active_tab) do
            if v.open_id == 416 then
                url = v.link
                break
            end
        end
        if url ~= nil then
            local url_new = url
            CS.UnityEngine.Application.OpenURL(url_new)
        end
        M.super.onButtonClick(self, obj, name)
    end
end

function M:destroy()
    M.super.destroy(self)
end


return M