---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/10 14:43
---

local M = class("KongMingLanternNode", LikeOO.OOUIbase)
--夜放孔明灯
M.m_uiName = "GiftBag/KongMingLanternNode"
M.cacheSpineName = ""
M.QUALITY_ITEM = {
    { frame_name = "a_xlqp_hui"  }, --1 灰色
    {frame_name = "a_xlqp_lv"   }, --2 绿色
    {frame_name = "a_xlqp_lan"   }, --3 蓝色
    {frame_name = "a_xlqp_lan"    }, --4 蓝+ 有外框
    {frame_name = "a_xlqp_zi"      }, --5 紫色
    {frame_name = "a_xlqp_jin"     }, --6 金
    {frame_name = "a_xlqp_hong"   }, --7 红
    {frame_name = "a_xlqp_bai" }, --8 白
    {frame_name = "a_xlqp_bai" }, --9 白
    {frame_name = "a_xlqp_bai" }, --10 白
    {frame_name = "a_xlqp_bai" }, --11 白
    {frame_name = "a_xlqp_cai" } --12 彩
}
function M:onEnter()
    EventDispatcher:registerEvent(GlobalConfig.EVENT_KEYS.EVERY_DAY_EVENT, {self, self.everyDayRefreshEvent})
    EventDispatcher:registerEvent("kongMing_setAward", {self, self.kongMingSetAwardEvent})
    self:bindUI()
    self:showUI()
    self:showAnimNode()
end

function M:showAnimNode()
    local kongming_bgAni = self:findGameObject("bgAnim")
    GameUtil:updateSpineLoadSet(kongming_bgAni, "RoleSpine/" .. "wanbaolou_SkeletonData", "idle", 0, true)
end

function M:playKongMingLight()
    audio:SendEvtUI("UI_FKMDeng")
    local lightAnimParent = self:findGameObject("lightAnim")
    local pos = Vector3(-(1632 * 0.5), -(720 * 0.5), 0)
    local lightAnimObj = ResourceUtil:LoadUIGameObject("GiftBag/KongmingLightAniNode", pos, lightAnimParent)
    GameUtil:updateSpineLoadSet(lightAnimObj, "RoleSpine/" .. "kongmingdeng_SkeletonData", "tap", 0, true)
    self:setObjectVisible("lightAnim", true)
    self.m_control:setOnceTimer(3,function()
        if not IsNull(lightAnimObj) then
            U3DUtil:GameObjectDestroy( lightAnimObj )
        end
    end)
end

function M:kongMingSetAwardEvent( eventName, data )
    table.merge(self.m_model.m_kongMingLight_Data, data)
    self:refreshUI()
end

-- 每日刷新
function M:everyDayRefreshEvent()
    local m_kongMingLight_Data = self.m_model.m_kongMingLight_Data.actives[1]
    local endTimer = m_kongMingLight_Data.end_ts
    local serverTimer = UserDataManager:getServerTime()
    if serverTimer > endTimer then
        if self.m_view then
            self.m_view:refreshActiveEndUI()
        end
    else
        self.m_control:refreshCurView()
    end
end

function M:switchInit(url, callback, id)
    local function callFunc(data)
        if callback then
            callback(data)
        end
        if data and data["end"] == 1 then
            return
        end
        self:refreshUI()
    end
    self.id = id
    self.m_model:initData2(url, callFunc)
end

function M:switchUI(id)
    self.id = id
    self:refreshUI()
end

function M:bindUI()
    self:setTextByLanKey("text_awardLookText", "lantern_text_0002")
    self:setTextByLanKey("text_playLanternText", "lantern_text_0003")
end

function M:refreshUI()
    if self.m_model.m_kongMingLight_Data == nil or next(self.m_model.m_kongMingLight_Data) == nil then
        return
    end
    self:showUI()
    if (not self.m_xlsxData) and self.m_model.m_kongMingLight_Data then
        local wishData = ConfigManager:getCfgByName("wish")
        self.m_xlsxData = wishData[self.m_model.m_kongMingLight_Data.wish.version] or {}
    end
    self:setObjectVisible("btn_awardLookBtn", true)
    self:setObjectVisible("btn_wishingBtn", true)
    self:setObjectVisible("btn_playLanternBtn", true)
    if self.m_model.m_kongMingLight_Data then
        self:setTextByLanKey("text_residueCount", "lantern_text_0001", self:getResidueCount())
        self:refreshWishNode()
        self:refreshActivityTimer()
        self:refreshAwardLookNode()
    end

    self:refreshRedDot()
end

function M:refreshRedDot()
    -- 领取愿望
    local wishData = self.m_model.m_kongMingLight_Data.wish.wish
    local isWish = wishData and (table.nums(wishData) > 0)
    local awardNeedCount = self:getAwardNeedCount()
    local isGot = (self.m_model.m_kongMingLight_Data.wish.received == 1)
    -- 有许愿的奖励，且 许愿的奖励所需次数足够， 且 未领取
    self:setObjectVisible("img_gotRedDot", isWish and (awardNeedCount <= 0)  and (not isGot))
    
    -- 许愿
    local flyCount = self:getResidueCount()
    self:setObjectVisible("img_flyRedDot", flyCount > 0)
end

function M:refreshWishNode()
    local wishData = self.m_model.m_kongMingLight_Data.wish.wish
    local isWish = wishData and (table.nums(wishData) > 0)
    self:setObjectVisible("wishingAwardnode", isWish)
    self:setObjectVisible("wishingNode", (not isWish))
    self:setObjectVisible("img_needBg", isWish)
    self:setObjectVisible("img_maskNode", false)
    if isWish then
        local awardNeedCount = self:getAwardNeedCount()
        local awardCountFormat = (awardNeedCount > 0) and Language:getTextByKey("lantern_text_0006", awardNeedCount) or Language:getTextByKey("lantern_text_0009")
        local isGot = (self.m_model.m_kongMingLight_Data.wish.received == 1)
        awardCountFormat = isGot and Language:getTextByKey("lantern_text_0011") or awardCountFormat
        self:setText("text_needText", awardCountFormat)
        --- 显示许愿的奖励
        local data = RewardUtil:getProcessRewardData(wishData)
        local quality_data = self.QUALITY_ITEM[data.quality]
        self:setImg(quality_data.frame_name, "active_ui", "big_reward_bg")
        self:setImg(data.icon_name, data.atlas_name, "big_reward_icon")
        self:setObjectVisible("big_num_bg", data.data_num > 1)
        self:setTextByLanKey("big_reward_num", data.data_num)
        self:setObjectVisible("img_maskNode", isGot)
    end
end

function M:getResidueCount()
    local everyDayCount = self.m_xlsxData.free_time or 0
    local residueCount = everyDayCount - self.m_model.m_kongMingLight_Data.wish.daily_times or 0
    residueCount = residueCount > 0 and residueCount or 0
    return residueCount
end

function M:getAwardNeedCount()
    local wish_timeCount = self.m_xlsxData.wish_time or 0
    local needCount = wish_timeCount - self.m_model.m_kongMingLight_Data.wish.times or 0
    needCount = needCount > 0 and needCount or 0
    return needCount
end

function M:initAwardLookData()
    local rewardData = {}
    local wish_rewardData = ConfigManager:getCfgByName("wish_reward")
    local vsn = self.m_model.m_kongMingLight_Data.wish.version
    versionData = wish_rewardData[vsn] or {}
    for id, itemData in pairs(versionData) do
        table.insert(rewardData, {
            id = id,
            rewardData = itemData.big_reward[1],
        })
    end
    table.sort(rewardData, function(itemData1,itemData2)
        return itemData1.id < itemData2.id
    end)
    self.m_awardLookData = rewardData
end

function M:refreshAwardLookNode()
    if not self.m_awardLookData then
        self:initAwardLookData()
    end
    if self.m_awardLoopScrollView == nil then
        local loopscroll = self:findGameObject("awardScrollView")
        local params = {
            show_data = self.m_awardLookData,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_object, cell_data)
                self:updateTaskItem(index, cell_object, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
            end
        }
        self.m_awardLoopScrollView = LoopScrollViewUtil.new(params)
    else
        self.m_awardLoopScrollView:reloadData(self.m_awardLookData, false)
    end
end

function M:updateTaskItem(index, cell_object, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_object)
    if luaBehaviour then
        local transform = cell_object.transform
        local awardData = cell_data.rewardData
        local reward_node = UIUtil.findRectTransform(transform, "awardNode")
        UIUtil.destroyAllChild(reward_node)
        if awardData then
            local itemNode = GameUtil:createItemElement(awardData, true, true)
            itemNode.transform:SetParent(reward_node.transform, false)
        end
    end
end

function M:refreshActivityTimer()
    local m_kongMingLight_Data = self.m_model.m_kongMingLight_Data.actives[1]
    local startTimer = m_kongMingLight_Data.start_ts
    local endTimer = m_kongMingLight_Data.end_ts
    local starT = TimeUtil.gmTime(startTimer)
    local endT = TimeUtil.gmTime(endTimer)
    local timerFormat = Language:getTextByKey("lantern_text_0007", starT.year, starT.month, starT.day,
            endT.year, endT.month, endT.day)
    self:setTextByLanKey("text_timer", "lantern_text_0008", timerFormat)
end

function M:onButtonClick(obj, name)
    if name == "btn_playLanternBtn" then
        -- 放天灯
        audio:SendEvtUI("UI_Guild_Blessing")
        local wishData = self.m_model.m_kongMingLight_Data.wish.wish
        local isWish = wishData and (table.nums(wishData) > 0)
        if not isWish then
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("lantern_text_0012"), delay_close = 2})
            return
        end
        local residueCount = self:getResidueCount()
        if residueCount <= 0 then
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("lantern_text_0010"), delay_close = 2})
            return 
        end
        local params = {vsn = self.m_model.m_kongMingLight_Data.wish.version}
        self:updateMsg("btn_playLanternBtn", params)
    elseif name == "btn_wishingBtn" then
        -- 能领就领，否则修改愿望
        audio:SendEvtUI("UI_Guild_Blessing")
        if self.m_model.m_kongMingLight_Data and self.m_model.m_kongMingLight_Data.wish.received == 1 then
            --  已领取
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("lantern_text_0011"), delay_close = 2})
            return
        end
        local awardNeedCount = self:getAwardNeedCount()
        if awardNeedCount > 0 then
            local wishData = self.m_model.m_kongMingLight_Data.wish.wish
            local isWish = wishData and (table.nums(wishData) > 0)
            self:openView("GiftBag.KongMingLanternAwardPop", {showType = 1, version = self.m_model.m_kongMingLight_Data.wish.version, wishAward = isWish and wishData or nil })
        else
            local params = {vsn = self.m_model.m_kongMingLight_Data.wish.version}
            self:updateMsg("btn_wishingBtn", params)
        end
    elseif name == "btn_awardLookBtn" then
        audio:SendEvtUI("Play_UI_TresureChest")
        -- 奖励预览
        self:openView("GiftBag.KongMingLanternAwardPop", {showType = 2, version = self.m_model.m_kongMingLight_Data.wish.version, wishAward = nil})
    elseif name == "btn_infoBtn" then
        if not self.m_xlsxData then
            return
        end
        local content = self.m_xlsxData.des
        self:openView("Pops.CommonHelpPop", { title = "lantern_text_0013", content = content })
    end 
end

function M:showUI()
    self:setObjectVisible("btn_awardLookBtn", false)
    self:setObjectVisible("btn_wishingBtn", false)
    self:setObjectVisible("btn_playLanternBtn", false)
end

function M:destroy()
    EventDispatcher:unRegisterEvent(GlobalConfig.EVENT_KEYS.EVERY_DAY_EVENT, {self, self.everyDayRefreshEvent})
    EventDispatcher:unRegisterEvent("kongMing_setAward", {self, self.kongMingSetAwardEvent})
    M.super.destroy(self)
end

return M