---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/19 20:42
---

local M = class("OpenServerRank", LikeOO.OOUIbase)

local RankTypeFormat = {
    "openServerRank_str_0008",
    "openServerRank_str_0009"
}

--侠客争锋
M.m_uiName = "GiftBag/OpenServerRank"
M.cacheSpineName = ""
function M:onEnter()
    self.grayImage = self:findImage("grayImage")
    self.m_tabIndex = 1
    self.m_end_ts = 0
    self:bindUI()
    self:showUI(false)
    self:setTextByLanKey("rank_reward_btn_text", "new_str_0918")
end

function M:bindUI()
    self:setTextByLanKey( "text_tabBtnText1","openServerRank_str_0001")
    self:setTextByLanKey( "text_tabImgText1","openServerRank_str_0001")
    self:setTextByLanKey( "text_tabBtnText2","openServerRank_str_0002")
    self:setTextByLanKey( "text_tabImgText2","openServerRank_str_0002")
    self:setTextByLanKey( "text_tabBtnText3","openServerRank_str_0003")
    self:setTextByLanKey( "text_tabImgText3","openServerRank_str_0003")
    self:setTextByLanKey( "text_tabBtnText4","openServerRank_str_0004")
    self:setTextByLanKey("text_tabImgText4","openServerRank_str_0004")
end

function M:switchInit(url, callback, id)
    local function callFunc(data)
        if callback then
            callback(data)
        end
        if data and data["end"] == 1 then
            return
        end
        self:refreshUI()
    end
    self.id = id
    self.m_model:initData2(url, callFunc)
end

function M:switchUI(id)
    self.id = id
    self.rankType = 1   --- 排行榜类型
    self:refreshUI()
end


function M:refreshUI()
    self:showUI(true)
    if self.m_model.m_hero_battle_curValue == nil then
        return
    end
    --local activityData = self.m_model:checkActiveDataByOpenId(self.m_model.m_hero_battle_openId)              --------------------- 标题，角色立绘也得换
    --self:setTextByLanKey("text_titleText",activityData.name_2)
    -- 1战力，2章节，对应hero_effect表type
    self.combat_num = self.m_model.m_hero_battle_curValue[1]
    self.chapter_id = self.m_model.m_hero_battle_curValue[2]
    local activityData = self.m_model:checkActiveDataByOpenId(self.m_model.m_hero_battle_openId)
    self.m_end_ts = activityData.end_ts
    self.activityType = activityData.open_status
    self.m_version = self.m_model:getSevenDayVersion(self.id)
    self:updateTime()
    self:setSpine()
    self:switchUIByTabBtn()
    self:refreshRedDots()
end

function M:switchUIByTabBtn()
    local index = self.m_tabIndex
    -- 1 最强战力榜，2 最高进度榜， 3 个人战力榜， 4个人进度榜
    local isRank = (index == 1) or (index == 2)
    self:setObjectVisible("rankNode", isRank)
    self:setObjectVisible("progressNode", (not isRank))
    for i = 1, 4 do
        self:setObjectVisible("img_tabBtnImg"..i, index == i)
    end
    if index == 1 then
        if not self.init then
            self.init = true
            self.m_model:setHeroBattleOpenServerMyFightData()
            self.m_model:setHeroBattleOpenServerMyChapterData()
            self.m_model:setHeroBattleOpenServerAllRankData(self.m_model.m_hero_battle_data.top_combat_rank,5)
        end
        local data = self.m_model.m_openServerAllRank_data
        self:refreshRankNode(data.allRankData)
        local myRankNode = self:findGameObject("myRankItem")
        self:updateRankItem(#data.allRankData,myRankNode, data.myRankData)
    elseif index == 2 then
        local data = self.m_model.m_openServerAllProgress_data
        self:refreshRankNode(data.allRankData)
        local myRankNode = self:findGameObject("myRankItem")
        self:updateRankItem(#data.allRankData,myRankNode, data.myRankData)
    elseif index == 3 then
        self:refreshTaskNode(self.m_model.m_openServerMyFight_data)
    elseif index == 4 then
        self:refreshTaskNode(self.m_model.m_openServerMyChapter_data)
    end
end

function M:refreshRedDots()
    for index = 3, 4 do
        local isShowRedDot = false
        local data = (index == 3) and self.m_model.m_openServerMyFight_data or self.m_model.m_openServerMyChapter_data
        for _, itemData in pairs(data) do
            if itemData.isCanGot and (not itemData.isGot) then
                isShowRedDot = true
                break
            end
        end
        self:setObjectVisible("img_tabRedDot"..index, isShowRedDot)
    end
end

function M:refreshTabRedDot()
    local isShowTabRedDot = false
    for index = 3, 4 do
        if isShowTabRedDot then
            break
        end
        local isShowRedDot = false
        local data = (index == 3) and self.m_model.m_openServerMyFight_data or self.m_model.m_openServerMyChapter_data
        for _, itemData in pairs(data) do
            if itemData.isCanGot and (not itemData.isGot) then
                isShowTabRedDot = true
                break
            end
        end
    end
    if not isShowTabRedDot then
        -- 刷新页签上的红点
        self.m_control:refreshUI()
    end
end

function M:refreshTaskNode(taskData)
    if self.m_taskScrollView == nil then
        local loopscroll = self:findGameObject("progress_scroll")
        local params = {
            show_data = taskData,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_object, cell_data)
                self:updateTaskItem(index, cell_object, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_canGotBtn" then
                    if cell_data.isCanGot and (not cell_data.isGot) then
                        local params = {quest_type = cell_data.taskType, quest_id = cell_data.id}
                        self.m_model:getNetData("hero_effect_recv", params, function(response)
                            if response then
                                self.m_control:netCheckEndTips(response)
                                if response["end"] == 1 then
                                    return
                                end
                                local rankType = (self.m_tabIndex == 3) and 1 or 2
                                self.m_model:setGotTaskData(rankType, cell_data.id)
                                cell_data.isGot = true
                                RewardUtil:rewardTipsByData(response.reward)
                                local luaBehaviour = UIUtil.findLuaBehaviour(cell_object)
                                LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_canGotBtnText", "openServerRank_str_0010")
                                local buy_img = luaBehaviour:FindImage("btn_canGotBtn")
                                buy_img.material = self.grayImage.material
                                if (self.m_tabIndex == 3) then
                                    self.m_model:sortData(self.m_model.m_openServerMyFight_data)
                                else
                                    self.m_model:sortData(self.m_model.m_openServerMyChapter_data)
                                end
                                self:refreshUI()
                                self:refreshTabRedDot()
                            end
                        end, nil, nil, nil)
                    end
                end
            end
        }
        self.m_taskScrollView = LoopScrollViewUtil.new(params)
    else
        self.m_taskScrollView:reloadData(taskData, false)
    end
end

function M:updateTaskItem(index, obj, data)
    local luaBehaviour = UIUtil.findLuaBehaviour(obj)
    if luaBehaviour then
        local isBattleTask = (self.m_tabIndex == 3)
        local dataCount = isBattleTask and #self.m_model.m_openServerMyFight_data or #self.m_model.m_openServerMyChapter_data
        local isLastIndex = (dataCount == index)
        local curValue = isBattleTask and self.combat_num or self.chapter_id
        local transform = obj.transform
        local xlsxData = data.xlsxData
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_fight",xlsxData.name)
        -- 奖励
        for i = 1, 3 do
            local awardData = xlsxData.reward or {}
            local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData[i] then
                local itemNode = GameUtil:createItemElement(awardData[i], true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
        local buy_img = luaBehaviour:FindImage("btn_canGotBtn")
        buy_img.material = data.isGot and self.grayImage.material or nil
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_line", (not isLastIndex))
        local curProValue, maxProValue =  curValue, xlsxData.target_value
        if (self.m_tabIndex == 4) then
            -- 章节进度-1，序章不算
            maxProValue = (maxProValue - 1) > 0 and (maxProValue - 1) or maxProValue
            curProValue = curProValue > maxProValue and maxProValue or curProValue
        end
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_progress",curProValue.."/"..maxProValue)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_canGotBtn", data.isCanGot)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_noGotBtn", (not data.isCanGot))
        local btnTextFormat = data.isGot and "openServerRank_str_0010" or "openServerRank_str_0011"
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_canGotBtnText", btnTextFormat)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_noGotBtnText", "openServerRank_str_0016")
    end
end

function M:refreshRankNode(rankData)
    if self.m_rankScrollView == nil then
        local loopscroll = self:findGameObject("rank_scroll")
        local params = {
            show_data = rankData,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_object, cell_data)  
                self:updateRankItem(index, cell_object, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                self.m_control:updateMsg("item_click", {uid = cell_data.user.uid})
            end
        }
        self.m_rankScrollView = LoopScrollViewUtil.new(params)
    else
        self.m_rankScrollView:reloadData(rankData, false)
    end
end

function M:updateRankItem(index, obj, data)
    local luaBehaviour = UIUtil.findLuaBehaviour(obj)
    if luaBehaviour then
        local transform = obj.transform
        local rankIndex = data.rank
        local playerData = data.user
        local listData = (self.m_tabIndex == 1) and self.m_model.m_openServerAllRank_data or self.m_model.m_openServerAllProgress_data
        local dataCount = #listData.allRankData
        local isLastIndex = (index == dataCount)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_rankImg1", (rankIndex == 1))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_rankImg2", (rankIndex == 2))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_rankImg3", (rankIndex == 3))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_rankText", (rankIndex > 3))
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_rankText",rankIndex)   
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_notRankText", (rankIndex <= 0))  
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_notRankText","openServerRank_str_0006")
        local head_node = luaBehaviour:FindGameObject("head_node")
        GameUtil:setUserAvatar(head_node, data.user,false,false,{show_flag = true, scale = 1})
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_name",playerData.name)
        local score = data.score
        local fightFormat =nil
        if (self.m_tabIndex == 2) then
            local chapter_id, stage_id, stage_item = GameUtil:getChapterIdByStageId(score)
            score = stage_item.map_point_name
            fightFormat = RankTypeFormat[self.m_tabIndex] or RankTypeFormat[1]
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_stage", score)
        else
            local textFormat = RankTypeFormat[self.m_tabIndex] or RankTypeFormat[1]
            fightFormat = Language:getTextByKey(textFormat, score)
        end
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_stage", (self.m_tabIndex == 2))
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_fight", fightFormat)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_line", (not isLastIndex))
        -- 奖励
        for i = 1, 3 do
            local awardData = data.awardData or {}
            local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData[i] then
                local itemNode = GameUtil:createItemElement(awardData[i], true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
    end
end

function M:setTabIndex(index,callback)
    if index == self.m_tabIndex then
        return 
    end
    self.m_tabIndex = index
    if callback then
        callback()
    end
end

function M:onButtonClick(obj, name)
    if name == "btn_tabBtn1" then
        self:setTabIndex(1,function()
            self:sendRankData(5)
        end)
    elseif name == "btn_tabBtn2" then
        self:setTabIndex(2,function()
            self:sendRankData(1)
        end)
    elseif name == "btn_tabBtn3" then
        self:setTabIndex(3, function()
            self.m_model:setHeroBattleOpenServerMyFightData()
            self:refreshUI()
        end)
    elseif name == "btn_tabBtn4" then
        self:setTabIndex(4,function()
            self.m_model:setHeroBattleOpenServerMyChapterData()
            self:refreshUI()
        end)
    elseif name == "rank_reward_btn" then
        self:openView("GiftBag.OpenServerRankReward", {versionId = self.m_model.m_hero_battle_version, openType = 1})
    elseif name == "head_node" then
        local myRankData = self.m_model.m_openServerAllRank_data.myRankData
        if myRankData and myRankData.user then
            self:openView("Pops.PlayerInfo", {uid = myRankData.user.uid})
        end
    end
end

function M:sendRankData(rankType)
    local params = { sort = rankType, start = 1, stop = 10 }
    self.m_model:getNetData("show_hero_rank", params, function(response)
        if response then
            if (rankType == 5) then
                self.m_model:setHeroBattleOpenServerAllRankData(response,rankType)
            elseif (rankType == 1) then
                self.m_model:setHeroBattleOpenServerAllProgressData(response,rankType)
            end
            self:refreshUI()
        end
    end, nil, nil, nil)
end

function M:setSpine()
    local cfg = UserDataManager.hero_data:getHeroConfigByCid(505)
    if cfg then
        local icon = cfg.hero_spine
        if self.cacheSpineName == icon then
            return
        else
            self.cacheSpineName = icon
        end
        local play_img = self:findGameObject("hero_spine")
        GameUtil:updateSpineLoadSet(play_img, "RoleSpine/"..self.cacheSpineName, "idle", 0, true)
    end
end

function M:updateTime()
    if self.activityType == 1 then
        if self.m_end_ts and self.m_end_ts > 0 then
            local curTimer = UserDataManager:getServerTime()
            local diffTimer = self.m_end_ts - curTimer
            if diffTimer <= 0 then
                local activityData = self.m_model:checkActiveDataByOpenId(self.m_model.m_hero_battle_openId)
                self.activityType = activityData.open_status
                self:setTextByLanKey("time_text", "openServerRank_str_0015")
                return
            end
            local time_show = GameUtil:formatTimeBySecond(diffTimer)
            self:setTextByLanKey("time_text", "openServerRank_str_0007",time_show)
        else
            self:setTextByLanKey("time_text", "openServerRank_str_0015")
        end
    else
        self:setTextByLanKey("time_text", "openServerRank_str_0015")
    end
end

function M:showUI(bl)
    self:setObjectVisible("hero_spine", bl)
    self:setObjectVisible("timerBg", bl)
end

function M:destroy()
    M.super.destroy(self)
end

return M

