---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/21 10:08
---

local M = class("ProducerGiftBag", LikeOO.OOUIbase)
--制作人赠礼
M.m_uiName = "GiftBag/ProducerGiftBag"
M.cacheSpineName = ""
function M:onEnter()
    self:showUI(false)
    self:setTextByLanKey("producer_btn_text", "producer_btn_tex")
    self.m_end_ts = 0
end

function M:switchInit(url, callback, id)
    local function callFunc(data)
        if callback then
            callback(data)
        end
        if data and data["end"] == 1 then
            return
        end
        self:refreshUI()
    end
    self.id = id
    self.m_model:initData2(url, callFunc)
end

function M:switchUI(id)
    self.id = id
    self:refreshUI()
end

function M:refreshUI()
    self:showUI(true)
    self.m_end_ts = self.m_model:getActivityEndTime(self.id)
    local isGotBtn = self.m_model.producer == 1
    self:setObjectVisible("btn_gotBtn", (not isGotBtn))
    self:updateTime()
end

function M:onButtonClick(obj, name)
    if name == "btn_gotBtn" then
        self:setObjectVisible("btn_gotBtn", false)
        self.m_model:getNetData("producer_recv", {}, function(response)
            if response then
                self.m_control:netCheckEndTips(response)
                if response["end"] == 1 then
                    return
                end
                self.m_control:refreshUI()
                RewardUtil:rewardTipsByData(response.reward)
                self:setObjectVisible("btn_gotBtn", false)
            end
        end, nil, nil, nil)
    end
end

function M:updateTime()
    if self.m_end_ts and self.m_end_ts > 0 then
        local curTimer = UserDataManager:getServerTime()
        local diffTimer = self.m_end_ts - curTimer
        local time_show = GameUtil:formatTimeBySecond(diffTimer)
        self:setTextByLanKey("time_text", "openServerRank_str_0007",time_show)
    else
        self:setTextByLanKey("time_text", "openServerRank_str_0015")
    end
end

function M:showUI(bl)
    self:setObjectVisible("btn_gotBtn", bl)
    self:setObjectVisible("time_text", bl)
end

function M:destroy()
    M.super.destroy(self)
end

return M

