---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/19 20:42
---

local M = class("VersionDashRank", LikeOO.OOUIbase)

--侠客争锋
M.m_uiName = "GiftBag/VersionDashRank"
M.cacheSpineName = ""
function M:onEnter()
    self.grayImage = self:findImage("grayImage")
    self.m_end_ts = 0
    self:bindUI()
    self:showUI(false)
    self:setTextByLanKey("rank_reward_btn_text", "new_str_0918")
end

function M:bindUI()
    self:setTextByLanKey( "text_tabBtnText1","versionDashRank_str_0001")
    self:setTextByLanKey( "text_tabImgText1","versionDashRank_str_0001")
    self:setTextByLanKey( "text_tabBtnText2","versionDashRank_str_0002")
    self:setTextByLanKey( "text_tabImgText2","versionDashRank_str_0002")
    self:setTextByLanKey( "text_tabBtnText3","versionDashRank_str_0003")
    self:setTextByLanKey( "text_tabImgText3","versionDashRank_str_0003")
    self:setTextByLanKey( "text_crossRealmHint","versionDashRank_str_0017")
    self:setTextByLanKey( "text_rankHintText","versionDashRank_str_0018")
end

function M:switchInit(url, callback, id)
    local function callFunc(data)
        if callback then
            callback(data)
        end
        if data and data["end"] == 1 then
            return
        end
        self:refreshUI()
    end
    self.id = id
    self.m_model:initData2(url, callFunc)
end

function M:switchUI(id)
    self.id = id
    self:refreshUI()
end


function M:refreshUI()
    self:showUI(true)
    if self.m_model.m_hero_battle_curValue == nil then
        return
    end
    
    local activityData = self.m_model:checkActiveDataByOpenId(self.m_model.m_hero_battle_openId)
    self.m_end_ts = activityData.end_ts
    self.activityType = activityData.open_status
    self:setTitle(activityData.id)
    if not self.m_tabIndex then
        self.m_tabIndex = 1
        self.m_model:initDashRankTabData(self.m_model.m_hero_battle_version)
        local tabData = self.m_model.m_TabListData[self.m_tabIndex]
        self:sendRankData(tabData.rankType)
    end
    local tabData = self.m_model.m_TabListData[self.m_tabIndex]
    self.cheats_num = (tabData ~= nil) and self.m_model.m_hero_battle_curValue[tabData.taskType] or 0
    self:updateTime()
    self:refreshTabListNode()
    self:refreshContentNode()
    self:setSpine()
end

-- 刷新内容
function M:refreshContentNode()
    local tabData = self.m_model.m_TabListData[self.m_tabIndex]
    -- 1排行，2任务
    local isRank = (tabData.tabType == 1)
    self:setObjectVisible("rankNode", isRank)
    self:setObjectVisible("progressNode", not isRank)
    if isRank then
        self:refreshLoopList()
    else
        self:refreshTaskNode()
    end
    
    -- 排行仅计算从宝箱内完成领取的演武币
    local isShowYanWuHint = isRank and (tabData.rankType == 7)
    self:setObjectVisible( "text_rankHintText", isShowYanWuHint)
end

function M:setTitle(activityId)
    local activityDatas = ConfigManager:getCfgByName("active")
    local curData = activityDatas[activityId]
    if curData then
        self:setTextByLanKey( "text_titleText",curData.name_2)
    end
end

function M:refreshLoopList()
    local data = self.m_model.m_generalRank_data
    -- 是否开启跨服
    local isOpenCrossRealm = (data ~= nil)
    self:setObjectVisible("rankNode", isOpenCrossRealm)
    -- 跨服功能暂未开启
    self:setObjectVisible("text_crossRealmHint", (not isOpenCrossRealm))
    if isOpenCrossRealm then
        local myRankNode = self:findGameObject("myRankItem")
        if data then
            self:refreshRankNode(data.allRankData)
            self:updateRankItem(#data.allRankData,myRankNode, data.myRankData)
        end
    end
end

function M:refreshTabRedDot()
    local isShowTabRedDot = false
    for _, itemData in pairs(self.m_model.m_myDashRankScore_data) do
        if itemData.isCanGot and (not itemData.isGot) then
            isShowTabRedDot = true
            break
        end
    end
    if not isShowTabRedDot then
        -- 刷新页签上的红点
        self.m_control:refreshUI()
    end
end

function M:refreshTaskNode()
    local taskData = self.m_model.m_myDashRankScore_data
    if self.m_taskScrollView == nil then
        local loopscroll = self:findGameObject("progress_scroll")
        local params = {
            show_data = taskData,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_object, cell_data)
                self:updateTaskItem(index, cell_object, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_canGotBtn" then
                    if cell_data.isCanGot and (not cell_data.isGot) then
                        local params = {quest_type = cell_data.taskType, quest_id = cell_data.id}
                        self.m_model:getNetData("hero_effect_recv", params, function(response)
                            if response then
                                self.m_control:netCheckEndTips(response)
                                if response["end"] == 1 then
                                    return
                                end
                                local tabData = self.m_model.m_TabListData[self.m_tabIndex]
                                self.m_model:setGotTaskData(tabData.taskType, cell_data.id)
                                cell_data.isGot = true
                                RewardUtil:rewardTipsByData(response.reward)
                                local luaBehaviour = UIUtil.findLuaBehaviour(cell_object)
                                LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_canGotBtnText", "versionDashRank_str_0010")
                                local buy_img = luaBehaviour:FindImage("btn_canGotBtn")
                                buy_img.material = self.grayImage.material
                                self.m_model:sortData(self.m_model.m_myDashRankScore_data)
                                self:refreshUI()
                                self:refreshTabRedDot()
                            end
                        end, nil, nil, nil)
                    end
                end
            end
        }
        self.m_taskScrollView = LoopScrollViewUtil.new(params)
    else
        self.m_taskScrollView:reloadData(taskData, false)
    end
end

function M:updateTaskItem(index, obj, data)
    local luaBehaviour = UIUtil.findLuaBehaviour(obj)
    if luaBehaviour then
        local isBattleTask = (self.m_tabIndex == 3)
        local dataCount = #self.m_model.m_myDashRankScore_data
        local isLastIndex = (dataCount == index)
        local curValue = self.cheats_num
        local transform = obj.transform
        local xlsxData = data.xlsxData
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_fight",xlsxData.name)
        -- 奖励
        for i = 1, 3 do
            local awardData = xlsxData.reward or {}
            local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData[i] then
                local itemNode = GameUtil:createItemElement(awardData[i], true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
        local buy_img = luaBehaviour:FindImage("btn_canGotBtn")
        buy_img.material = data.isGot and self.grayImage.material or nil
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_line", (not isLastIndex))
        local curProValue, maxProValue =  curValue, xlsxData.target_value
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_progress",curProValue.."/"..maxProValue)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_canGotBtn", data.isCanGot)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_noGotBtn", (not data.isCanGot))
        local btnTextFormat = data.isGot and "versionDashRank_str_0010" or "versionDashRank_str_0011"
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_canGotBtnText", btnTextFormat)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_noGotBtnText", "versionDashRank_str_0016")
    end
end

function M:refreshRankNode(rankData)
    if self.m_rankScrollView == nil then
        local loopscroll = self:findGameObject("rank_scroll")
        local params = {
            show_data = rankData,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_object, cell_data)  
                self:updateRankItem(index, cell_object, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                self.m_control:updateMsg("item_click", {uid = cell_data.user.uid})
            end
        }
        self.m_rankScrollView = LoopScrollViewUtil.new(params)
    else
        self.m_rankScrollView:reloadData(rankData, false)
    end
end

function M:updateRankItem(index, obj, data)
    local luaBehaviour = UIUtil.findLuaBehaviour(obj)
    if luaBehaviour then
        local transform = obj.transform
        local rankIndex = data.rank
        local playerData = data.user
        local listData = self.m_model.m_generalRank_data 
        local dataCount = #listData.allRankData
        local isLastIndex = (index == dataCount)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_rankImg1", (rankIndex == 1))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_rankImg2", (rankIndex == 2))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_rankImg3", (rankIndex == 3))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_rankText", (rankIndex > 3))
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_rankText",rankIndex)   
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_notRankText", (rankIndex <= 0))  
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_notRankText","versionDashRank_str_0006")
        local head_node = luaBehaviour:FindGameObject("head_node")
        GameUtil:setUserAvatar(head_node, data.user,false,false,{show_flag = true, scale = 1})
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_name",playerData.name)
        local score = data.score
        local fightFormat = Language:getTextByKey(data.itemName)
        fightFormat = fightFormat.." "..score
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_stage", false)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_fight", fightFormat)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_line", (not isLastIndex))
        -- 奖励
        for i = 1, 3 do
            local awardData = data.awardData or {}
            local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData[i] then
                local itemNode = GameUtil:createItemElement(awardData[i], true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
    end
end

function M:setTabIndex(index,callback)
    if index == self.m_tabIndex then
        return 
    end
    self.m_tabIndex = index
    if callback then
        callback()
    end
end

function M:onButtonClick(obj, name)
    if name == "rank_reward_btn" then
        self:openView("GiftBag.OpenServerRankReward", {versionId = self.m_model.m_hero_battle_version, openType = 2})
    elseif name == "head_node" then
        if not self.m_model.m_worldRehearsalRank_data then
            return
        end
        local myRankData = self.m_model.m_worldRehearsalRank_data.myRankData
        if myRankData and myRankData.user then
            self:openView("Pops.PlayerInfo", {uid = myRankData.user.uid})
        end
    end
end

function M:sendRankData(rankType)
    local params = { sort = rankType, start = 1, stop = 10 }
    self.m_model:getNetData("show_hero_rank", params, function(response)
        if response then
            self.m_control:netCheckEndTips(response)
            if response["end"] == 1 then
                return
            end
            self.m_model:setGeneralRankData(response,rankType)
            self:refreshUI()
        end
    end, nil, nil, nil)
end

function M:setSpine()
    local heroDatas
    local rank_effectData = ConfigManager:getCfgByName("rank_effect")
    local versionRankAwardData = rank_effectData[self.m_model.m_hero_battle_version]
    local tabData = self.m_model.m_TabListData[self.m_tabIndex]
    local rankType = tabData.rankType
    local curVersionRankAwardData = versionRankAwardData[rankType] or {}
    
    if curVersionRankAwardData then
        for _, itemData in pairs(curVersionRankAwardData) do
            -- 角色和排行榜类型有关
            if itemData.hero_id then
                local tempHeroData = itemData.hero_id[1]
                if tempHeroData then
                    heroDatas = tempHeroData
                end
            end
            break
        end
    end

    if heroDatas then
        local reward_data = RewardUtil:getProcessRewardData(heroDatas)
        if reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT then
            local cfg = UserDataManager.hero_data:getHeroConfigByCid(reward_data.data_id)
            if cfg then
                local icon = cfg.hero_spine
                if self.cacheSpineName == icon then
                    return
                else
                    self.cacheSpineName = icon
                end

            end
        elseif reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
            local cur_skin_cfg = ConfigManager:getHeroSkinCfg(reward_data.data_id)
            local icon = cur_skin_cfg.hero_spine
            if self.cacheSpineName == icon then
                return
            else
                self.cacheSpineName = icon
            end
        end
        local play_img = self:findGameObject("hero_spine")
        GameUtil:updateSpineLoadSet(play_img, "RoleSpine/" .. self.cacheSpineName, "idle", 0, true)
        self:setObjectVisible("hero_spine", true)
    end
end

function M:updateTime()
    if self.activityType == 1 then
        if self.m_end_ts and self.m_end_ts > 0 then
            local curTimer = UserDataManager:getServerTime()
            local diffTimer = self.m_end_ts - curTimer
            if diffTimer <= 0 then
                local activityData = self.m_model:checkActiveDataByOpenId(self.m_model.m_hero_battle_openId)
                self.activityType = activityData.open_status
                self:setTextByLanKey("time_text", "versionDashRank_str_0015")
                return
            end
            local time_show = GameUtil:formatTimeBySecond(diffTimer)
            self:setTextByLanKey("time_text", "versionDashRank_str_0007",time_show)
        else
            self:setTextByLanKey("time_text", "versionDashRank_str_0015")
        end
    else
        self:setTextByLanKey("time_text", "versionDashRank_str_0015")
    end
end

function M:showUI(bl)
    self:setObjectVisible("hero_spine", bl)
    self:setObjectVisible("timerBg", bl)
end

function M:refreshTabListNode()
    if not self.m_model.m_TabListData then
        self.m_model:initDashRankTabData(self.m_model.m_hero_battle_version)
    end
    if self.m_tabLoopScrollView == nil then
        local loopscroll = self:findGameObject("tabList")
        local params = {
            show_data = self.m_model.m_TabListData,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_object, cell_data)
                self:updateTabItem(index, cell_object, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_tabBtn" then
                    if cell_data.tabType == 1 then
                        self:setTabIndex(index,function()
                            self:sendRankData(cell_data.rankType)
                        end)
                    elseif cell_data.tabType == 2 then
                        self:setTabIndex(index,function()
                            self.m_model:setMyDashRankScoreData(cell_data.taskType)
                            self:refreshUI()
                        end)
                    end
                end
            end
        }
        self.m_tabLoopScrollView = LoopScrollViewUtil.new(params)
    else
        self.m_tabLoopScrollView:reloadData(self.m_model.m_TabListData, false)
    end
end

function M:updateTabItem(index, cell_object, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_object)
    if luaBehaviour then
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_tabBtnText", cell_data.name)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_tabImgText", cell_data.name)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_tabBtnImg",  (self.m_tabIndex == index))
        local isShowRedDot = false
        if cell_data.tabType == 2 then
            local m_hero_battle_data = self.m_model.m_hero_battle_data
            local serverTaskData = m_hero_battle_data.hero_rank.quests[tostring(cell_data.taskType)]
            local taskXlsxData = ConfigManager:getCfgByName("hero_effect")
            local taskVersionData = taskXlsxData[self.m_model.m_hero_battle_version]
            local taskTypeRankData = taskVersionData[cell_data.taskType]
            for id, itemData in pairs(taskTypeRankData) do
                local isGotTask = self.m_model:isGotTask(id, serverTaskData)
                if (serverTaskData.value >= itemData.target_value) and (not isGotTask) then
                    isShowRedDot = true
                end
            end
        end
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_redDot", isShowRedDot)
    end
end


function M:destroy()
    M.super.destroy(self)
end

return M

