---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/2/9 14:24
---


local M = class("SimulateLiftMainControl",LikeOO.OOControlBase)

function M:onEnter()
    self.m_timer_id = self:setTimer(1, handler(self, self.updateTime))
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:updateMsg("common_refresh", nil, "parent")
        self:closeView()
    elseif msg == "explain_btn" then
        -- 提示  
        local title_id = self.m_model.m_open_id == 285 and  "simulateLeft_text_0030" or "simulateLeft_text_0068"
        local des_id = self.m_model.m_open_id == 285 and  "tid#ReopenDes_7" or "tid#SwordThym_des1"
        self:openView("Pops.CommonHelpPop", { title = Language:getTextByKey(title_id), content = Language:getTextByKey(des_id) })
    elseif msg == "btn_rinseCardBtn" then
        -- 侠客洗牌
        if self.m_model.m_finish == 0 then
            self:openView("SimulateLift.SimulateLiftInfo", {response = self.m_model.m_data, version = self.m_model.m_version, open_id = self.m_model.m_open_id, isOldLift = true, reset_times = self.m_model.m_reset_times})
        else
            self:againNewLife()
        end
    elseif msg == "btn_outcomeBtn" then
        -- 结局
        self:openView("SimulateLift.SimulateOutCome", {open_id = self.m_model.m_open_id, version = self.m_model.m_version})
    elseif msg == "btn_tokenBtn" then
        -- 战令
        self:openView("SimulateLift.SimulateToKen", {is_token = false})
    elseif msg == "refresh_lifeData" then
        -- 刷新封面数据
        self.m_model:refreshData(data.response)
        if data.isAgainStart then
            self:updateMsg("btn_rinseCardBtn",{})
        end
        self.m_view:refreshUI()
    elseif msg == "again_new" then
        -- 重新开始
        self:againNewLife()
    elseif msg == "refresh_finishValue" then
        self.m_model.m_finish = 1
        self.m_model.m_data.finish = 1
    elseif msg == "hide_toKenView" then
        self.m_view:refreshUI()
    elseif msg == "end_time" then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:updateMsg("common_refresh",nil,"parent")
        static_rootControl:closeAllViewPop();
    elseif msg == "refresh_red_point" then
        self.m_view:refreshUI()
    end
end

function M:againNewLife()
    self.m_model.m_finish = 1
    if self.m_model.m_surplusCount <= 0 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("simulateLeft_text_0001"), delay_close = 2})
        return
    end
    self:openView("SimulateLift.SimulateSelectRole", {open_id = self.m_model.m_open_id, version = self.m_model.m_version, reset_times = self.m_model.m_reset_times})
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    if response.update == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

--计时器
function M:updateTime()
    local remain_time = self.m_model:getEndTs()
    if remain_time <= 0 then
        self:updateMsg("end_time")
    end
end

function M:destroy()
    self:removeTimer(self.m_timer_id)
    M.super.destroy(self)
end

return M