---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---

local M = class("SimulateLiftMainModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self.m_open_id = self.m_params.open_id or 285
    self:getData("game_index", {open_id = self.m_open_id})
end

function M:onEnter()
    self.m_act_data = UserDataManager:getActivesDataByOpenId(self.m_open_id)
    self:refreshData(self.m_data)
end

function M:modifyData(m_data)
    table.merge(self.m_data, m_data)
end

function M:refreshData(m_data)
    self.m_data = m_data
    if m_data["end"] == 1 then
        return
    end
    self.m_version = m_data.version
    -- 还剩多少次可使用次数
    self.m_surplusCount = m_data.times + m_data.pay_times
    self.m_role_id = m_data.role_id
    -- 属性值
    self.m_attrs = m_data.attrs
    self.m_is_dead = m_data.is_dead
    -- 0这一局游戏未结束 1已结束
    self.m_finish = m_data.finish
    -- 可选的角色, 当前值有数据时要先让玩家选角色 {role_id: {1:2, 2:5}}  {角色id: 当前角色随到的属性}
    self.m_role_options = m_data.role_options
    -- 可选的天赋数据 [talent_id1, talent_id2, ... talent_id10]
    self.m_talent_options = m_data.talent_options
    -- 上局继承的天赋数据 [talent_id1]
    self.m_talent_inherit = m_data.talent_inherit
    
    -- 玩家的天赋数据 [talent_id1, talent_id2]
    self.m_talents = m_data.talents
    -- 详细成长日志 [{age:年龄, event_id:触发的事件id, choice:选项id,is_dead:是否死亡, revive:是否复活, choice:选项id}]
    self.m_growth_log = m_data.growth_log
    
    -- 历史最高年龄
    self.m_max_age = m_data.max_age
    -- 历史最高分数
    self.m_max_score = m_data.max_score
    
    -- 本局已重置次数
    self.m_reset_times = m_data.reset_times
end

function M:getEndTs()
    if self.m_act_data and self.m_act_data.end_ts then
        return self.m_act_data.end_ts - UserDataManager:getServerTime() + 1
    end
    return 0
end
return M