---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:24
---


local M = class("SimulateSpecialEventControl",LikeOO.OOControlBase)

function M:onEnter()
    audio:SendEvtUI("Play_UI_Popup_2")
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:randomEvent()
    elseif msg == "btn_closeBtn" then
        self:randomEvent()
    elseif msg == "btn_selectBtn_1" then
        self:selectEvent(1)
    elseif msg == "btn_selectBtn_2" then
        self:selectEvent(2)
    elseif msg == "btn_selectBtn_3" then
        self:selectEvent(3)
    elseif msg == "btn_selectBtn_4" then
        self:selectEvent(4)
    end
end

function M:randomEvent()
    local allCount = table.nums(self.m_model.m_eventContents)
    local index = math.random(1, allCount)
    self:selectEvent(index)
end

function M:selectEvent(index)
    local params = {open_id = self.m_model.m_open_id, version = self.m_model.m_version, choice_id = index }
    self.m_model:getNetData("select_choice", params, function(response)
        if response then
            if self:activityOverExamine(response) then
                return
            end
            self:updateMsg("refresh_lifeData",{response = response, serverIndex = self.m_model.m_serverIndex},"SimulateLift.SimulateLiftInfo")
            self:closeView()
        end
    end, nil, nil, nil)
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    if response.update == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M