---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---

local M = class("SimulateSpecialEventModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:refreshData()
    self:getData()
end

function M:refreshData()
    self.m_eventId = self.m_params.eventId
    self.m_open_id = self.m_params.open_id
    self.m_version = self.m_params.version
    self.m_serverIndex = self.m_params.serverIndex
    local eventXlsxData = ConfigManager:getCfgByName("reopen_events")
    local curEventData = eventXlsxData[self.m_eventId]
    self.m_title = curEventData.tittle_text
    self.m_eventContents = curEventData.option_text
end

function M:onEnter()

end

return M