---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---

local M = class("FlowerGivePopModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:initData()
    self:getData()
end

function M:initData()
    self.m_existFlowerCount = self.m_params.existFlowerCount
    self.m_playerId = self.m_params.playerId
    self.m_tips_text_num = self.m_params.tips_num or 0
    --self.m_itemAwardData = {103,5397,1}
    self.m_itemAwardData = self:getFlowerReward()
    self.m_itemUnit = RewardUtil:getProcessRewardData(self.m_itemAwardData)
    self.m_use_num = 0
end

function M:addUseNum(value)
    local new_count = self.m_use_num + value
    self.m_use_num = math.min(math.max(1,new_count),self:getMaxNum())
end

function M:setUseNum(m_use_num)
    self.m_use_num = m_use_num
end

function M:getUseNum()
    return self.m_use_num
end

function M:getMaxNum()
    return self.m_itemUnit.user_num
end

--获取赠送道具id
function M:getFlowerReward()
    local flower_festival = ConfigManager:getCfgByName("flower_festival")
    local activityData = UserDataManager:getActivesDataByOpenId(291)
    Logger.logError(flower_festival,"flower_festival~~~~~~~~~~~~~~~~~~~")
    return flower_festival[activityData.version].item_id1[1]
end

function M:onEnter()

end

return M