---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/24 11:02
---

local M = class("CastingSwordShareInfoControl",LikeOO.OOControlBase)

function M:onEnter()
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_closeBtn" then
        self:closeView()
    elseif msg == "share_pop" then
        self.m_view:ShareShow(false)
        local show_call = function()
            self.m_view:ShareShow(true)
        end
        self:openView("SharePictureNoLogo", {picture_callback = show_call})
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M