-- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/11 20:36
---

local M = class("CastingSwordShareInfoView",LikeOO.OOPopBase)

M.m_uiName = "CastingSwordMeeting/CastingSwordShareInfo"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

function M:onEnter()
    self:bindUI()
    self:refreshUI()
    self:updateMsg("share_pop")
end

function M:bindUI()
    self:setTextByLanKey("close_title_text", "castingSword_str_0039")
    self:setTextByLanKey("text_hintText", "castingSword_str_0027")
    local userName = UserDataManager.user_data:getUserStatusDataByKey("name")
    self:setTextByLanKey("text_myName", "castingSword_str_0026", userName)
    local head_node = self:findGameObject("head_node")
    local avatar = UserDataManager.user_data:getUserStatusDataByKey("avatar")
    local frame = UserDataManager.user_data:getUserStatusDataByKey("frame")
    GameUtil:setUserAvatar(head_node, {avatar = avatar, frame = frame}, false)
    -- 官方包才有
    local isOfficialBag = false
    if SDKUtil.is_gmsdk then
        local bundleid = SDKUtil.sdk_params.applicationId or ""
        if bundleid == "com.hermes.wl" then
            -- 是官方包
            isOfficialBag = true
        end
    end
    self:setObjectVisible("img_QRcode", isOfficialBag)
    self:setObjectVisible("hintNode", (not isOfficialBag))
end

function M:refreshUI()
    
end

function M:ShareShow(flag)
    self:setObjectVisible("CommonCloseNode", flag)
end

function M:destroy()
    EventDispatcher:dipatchEvent("refresh_castingSwordShareTask")
    M.super.destroy(self)
end

return M