return {
    ["battle_buff"] = "1",
    ["battle_common"] = "1",
    ["battle_deployment"] = "1",
    ["battle_equip_detail"] = "1",
    ["battle_equip_hero_skill"] = "1",
    ["battle_equip_heroes"] = "1",
    ["battle_heirloom"] = "1",
    ["battle_hero_detail"] = "1",
    ["battle_hero_enumeration"] = "1",
    ["battle_hero_evolution"] = "1",
    ["battle_hero_quality"] = "1",
    ["battle_hero_rank"] = "1",
    ["battle_hero_skin"] = "1",
    ["battle_hero_upgrade"] = "1",
    ["battle_legend"] = "1",
    ["battle_legend_battle"] = "1",
    ["battle_legend_stage"] = "1",
    ["battle_mystic"] = "1",
    ["battle_mystic_buff"] = "1",
    ["battle_raid_open"] = "1",
    ["battle_random_seed"] = "1",
    ["battle_scene_config"] = "1",
    ["battle_scene_friction"] = "1",
    ["battle_skill_detail"] = "1",
    ["battle_stage"] = "1",
    ["battle_treasure_config"] = "1",
}
