return
{
	["enemyWaitTime"] = 0,
	["origin"] = 
	{
		["y"] = 1024,
		["z"] = 0,
		["x"] = 0,
	},
	["selfBasePos"] = 0,
	["enemyCurve"] = "line",
	["selfMoveTimer"] = 0,
	["destination"] = 
	{
		["y"] = 1024,
		["z"] = 0,
		["x"] = 0,
	},
	["enemyBasePos"] = 1024,
	["enemyDistance"] = 0,
	["damageStart"] = 0,
	["enemyMoveTimer"] = 0,
	["originParent"] = "Xiong",
	["destinationParent"] = "Xiong",
	["selfWaitTime"] = 0,
	["finishWaitTime"] = 2048,
	["selfDistance"] = 0,
	["prefab"] = "W_Heh_Skill1_Line_001",
	["hitEffect"] = "W_Heh_Skill1_Hit",
	["selfCurve"] = "line",
	["bufid"] = "nil",
	["damageInterval"] = 0,
	["imprison"] = false,
	["count"] = 
	{
		["ignoreSummon"] = false,
		["targetNoRepeat"] = false,
		["isFixPoint"] = false,
		["selectLast"] = false,
		["areaRadius"] = 0,
		["forceSelect"] = false,
		["area"] = "all",
		["areaWidth"] = 0,
		["useSelf"] = false,
		["areaAngle"] = 0,
		["campRace"] = "not",
		["areaHeight"] = 0,
		["profession"] = "all",
		["gender"] = "man",
		["fixpoint"] = "enemyBackCenter",
		["pos"] = "not",
		["priority"] = false,
		["count"] = "one",
		["camp"] = "friend",
		["posIndex"] = "all",
	},
	["fireTime"] = 358,
	["damage"] = 0,
}