return
{
	["selectDis"] = "number",
	["distance"] = 2048,
	["moveType"] = "MoveBlink",
	["useSceneDir"] = false,
	["isSelectTarget"] = true,
	["moveOrder"] = "order",
	["targetPos"] = "back",
	["isTargetPoint"] = false,
	["bufid"] = 0,
	["isAnewEnemy"] = false,
	["effect"] = "nil",
	["faceToTarget"] = false,
	["speed"] = 0,
	["ignoreArea"] = false,
	["needBack"] = false,
	["curveMove"] = 
	{
		["move"] = false,
	},
	["dirToBoss"] = false,
	["count"] = 
	{
		["ignoreSummon"] = false,
		["targetNoRepeat"] = false,
		["isFixPoint"] = false,
		["selectLast"] = false,
		["areaRadius"] = 0,
		["forceSelect"] = false,
		["area"] = "all",
		["areaWidth"] = 0,
		["campRace"] = "not",
		["areaHeight"] = 0,
		["profession"] = "all",
		["areaAngle"] = 0,
		["fixpoint"] = "enemyBackCenter",
		["pos"] = "not",
		["priority"] = false,
		["count"] = "one",
		["camp"] = "friendExceptSelf",
		["posIndex"] = "all",
	},
	["endAnimName"] = "nil",
	["isDirZero"] = false,
}