return
{
	["sendForData"] = 
	{
		["fixValue"] = 0,
		["summonName"] = 3091,
		["targetPos"] = "Up",
		["offset"] = 
		{
			["y"] = 0,
			["z"] = 0,
			["x"] = 0,
		},
		["aiType"] = "ShootThenStop",
		["distance"] = 0,
		["is_border"] = false,
		["is_sign"] = true,
		["alwaysfollow"] = true,
		["id"] = 0,
		["follow"] = true,
		["hpType"] = "hpBase",
		["count"] = 
		{
			["ignoreSummon"] = false,
			["targetNoRepeat"] = false,
			["isFixPoint"] = false,
			["selectLast"] = false,
			["areaRadius"] = 0,
			["forceSelect"] = false,
			["area"] = "all",
			["areaWidth"] = 0,
			["campRace"] = "not",
			["areaHeight"] = 0,
			["profession"] = "all",
			["areaAngle"] = 0,
			["fixpoint"] = "enemyBackCenter",
			["pos"] = "not",
			["priority"] = false,
			["count"] = "one",
			["camp"] = "self",
			["posIndex"] = "all",
		},
		["percentValue"] = 0,
		["summonType"] = "special",
	},
	["move_data"] = 
	{
		["eventName"] = "AttackMove",
		["selectDis"] = "number",
		["distance"] = 717,
		["triggerTime"] = 0,
		["moveType"] = "MoveGeneral",
		["useSceneDir"] = false,
		["isSelectTarget"] = false,
		["moveOrder"] = "order",
		["targetPos"] = "front",
		["isTargetPoint"] = false,
		["bufid"] = 0,
		["isAnewEnemy"] = false,
		["effect"] = "nil",
		["faceToTarget"] = false,
		["speed"] = 0,
		["ignoreArea"] = false,
		["needBack"] = false,
		["curveMove"] = 
		{
			["curveDistanceType"] = "targetDistance",
			["curveMoveDistance"] = 0,
			["curveMoveType"] = "line",
			["curveMoveTime"] = 246,
			["move"] = true,
		},
		["dirToBoss"] = false,
		["count"] = 
		{
			["ignoreSummon"] = false,
			["targetNoRepeat"] = false,
			["isFixPoint"] = false,
			["selectLast"] = false,
			["areaRadius"] = 0,
			["forceSelect"] = false,
			["area"] = "all",
			["areaWidth"] = 0,
			["useSelf"] = false,
			["campRace"] = "not",
			["areaHeight"] = 0,
			["profession"] = "all",
			["areaAngle"] = 0,
			["fixpoint"] = "enemyBackCenter",
			["pos"] = "not",
			["priority"] = false,
			["count"] = "all",
			["camp"] = "enemy",
			["posIndex"] = "all",
		},
		["endAnimName"] = "nil",
		["isDirZero"] = false,
	},
}