---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/11 14:58
---

local M = class("CastingSwordTaskControl",LikeOO.OOControlBase)

function M:onEnter()
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_examine" then
        -- 打开铸剑奖励
        self:openView("CastingSwordMeeting.CastingSwordTaskInfo",{
            m_allAwardsData = self.m_model.m_allAwardsData,
            m_allPersonAwardsData = self.m_model.m_allPersonAwardsData,
            m_score_done = self.m_model.m_score_done,
            m_person_score_done = self.m_model.m_person_score_done,
            m_score = self.m_model.m_score,
            m_self_score = self.m_model.m_self_score,
            m_version = self.m_model.m_version,
        })
    elseif msg == "canGotAward_btn1" then
        -- 领取
        self:gotAwardSend(1)
    elseif msg == "canGotAward_btn2" then
        self:gotAwardSend(2)
    elseif msg == "canGotAward_btn3" then
        self:gotAwardSend(3)
    elseif msg == "canGotAward_btn4" then
        self:gotAwardSend(4)
    elseif msg == "box_click1" then
        -- 查看
        self:lookAward(1, data)
    elseif msg == "box_click2" then
        self:lookAward(2, data)
    elseif msg == "box_click3" then
        self:lookAward(3, data)
    elseif msg == "box_click4" then
        self:lookAward(4, data)
    elseif msg == "refresh_castingSwordGotAward" then
        self.m_model:setScoreDone(data.score_done)
        self.m_view:refreshBottomNode()
    elseif msg == "btn_goBtn" then
        -- 每日跳转
        local curDayIndex = self.m_model:getActityOpenDay()
        curDayIndex = math.floor(curDayIndex)
        curDayIndex = curDayIndex <= 0 and 1 or curDayIndex
        local cell_data = self.m_model.m_taskData.dayTaskData[curDayIndex] or {}
        local xlsxData = cell_data.xlsxData
        if xlsxData then
            local jumpId = xlsxData.go_type
            QuickOpenFuncUtil:openFunc(jumpId)
            if (jumpId == 1) or (jumpId == 31) then
                -- 前往主页, 前往挂机奖励
                static_rootControl:closeAllViewPop()
            else
                self:closeView()
            end
        end
    elseif msg == "btn_getBtn" then
        -- 每日领取
        local curDayIndex = self.m_model:getActityOpenDay()
        curDayIndex = math.floor(curDayIndex)
        curDayIndex = curDayIndex <= 0 and 1 or curDayIndex
        local cell_data = self.m_model.m_taskData.dayTaskData[curDayIndex] or {}
        local params = {vsn = self.m_model.m_version, quest_id = cell_data.id}
        self.m_model:getNetData("sword_recv_quest_reward", params, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                RewardUtil:rewardTipsByData(response.reward)
                self.m_model:amendTaskData(cell_data.id)
                self.m_view:setObjectVisible("btn_gotBtn", true)
                self.m_view:setObjectVisible("btn_getBtn", false)
                self.m_model:refreshActivityData(response)
                self.m_view:refreshUI()
            end
        end, nil, nil, nil)
    elseif msg == "jifen_obj" then
        -- 点击每日积分img弹出
        local click_object = self.m_view:findGameObject("jifen_obj")
        GameUtil:lookInfoTips(self, {click_transform = click_object.transform, msg = Language:getTextByKey("castingSword_str_0046")})
    elseif msg == "btn_hintBtn" then
        local sword_Data = ConfigManager:getCfgByName("sword")
        local versionData = sword_Data[self.m_model.m_version]
        local params = {}
        local activityName = ""
        local activeData = ConfigManager:getCfgByName("active")
        for _, itemData in pairs(activeData) do
            if itemData.open_id == self.m_model.m_activityData.open_id then
                activityName = itemData.name
                break
            end
        end
        params.title = activityName
        params.content = versionData.des
        self:openView("Pops.CommonHelpPop", params)
    end
end

function M:lookAward(index, data)
    local awardData = self.m_model.m_allAwardsData[index]
    local xlsxData = awardData.xlsxData
    local rewards = xlsxData.reward
    self:openView("Pops.LookRewardTips",{rewards = rewards, click_transform = data.click_transform, show_check_mark = false})
end

function M:gotAwardSend(index)
    local params = {vsn = self.m_model.m_version, score_id = index, type = 0}
    self.m_model:getNetData("sword_recv_score_reward", params, function(response)
        if response then
            if self:activityOverExamine(response) then
                return
            end
            RewardUtil:rewardTipsByData(response.reward)
            self.m_model:setScoreDone(response.score_done)
            self.m_view:refreshBottomNode()
        end
    end, nil, nil, nil)
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:heroDetailPop(index, cell_data)

end

function M:destroy()
    M.super.destroy(self)
end

return M
