---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/11 15:17
---
local M = class("CastingSwordTaskModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self.m_openId = self.m_params.open_id
    self.m_version = self.m_params.version
    self.m_activityData = self.m_params.actives[1]
    self:refreshActivityData(self.m_params)
    self:getData()
end

function M:setScoreDone(score_done)
    local tempData = {}
    for i = 1, #score_done do
        local index = score_done[i]
        tempData[index] = index
    end
    self.m_score_done = tempData
end

function M:setPersonScoreDone(person_score_done)
    local tempData = {}
    for i = 1, #person_score_done do
        local index = person_score_done[i]
        tempData[index] = index
    end
    self.m_person_score_done = tempData
end

function M:refreshActivityData(response)
    self.m_score = response.score
    self.m_self_score = response.self_score
    self.m_quests_data = response.quests
    -- 领取过得玄铁目标宝箱
    if response.score_done then
        self:setScoreDone(response.score_done)
    end
    if response.score_person_done then
        self:setPersonScoreDone(response.score_person_done)
    end
    self:setAllTaskData()   -- self.m_taskData
    self:setAllAwardsData() -- self.m_allAwardsData
    self:setPersonAwardsData() -- self.m_allPersonAwardsData
    self:setAwardState()    -- self.m_curAwardIndex
end

function M:onEnter()

end

function M:setAllTaskData()
    local sword_questData = ConfigManager:getCfgByName("sword_quest")
    local versionRankAwardData = sword_questData[self.m_version] or {}
    local tempData = {
        dayTaskData = {},
        allTaskData = {},
    }
    for id, itemData in pairs(versionRankAwardData) do
        if (itemData.sort == 1) then
            local curServerData = self.m_quests_data[tostring(id)] or {}
            if (itemData.type == 2) then
                -- 每期任务 
                table.insert(tempData.allTaskData, {
                    xlsxData = itemData,
                    serverData = curServerData,
                    id = id,
                })
            elseif (itemData.type == 1) then
                --每日任务 (key是天数)
                tempData.dayTaskData[itemData.day] = {
                    xlsxData = itemData,
                    serverData = curServerData,
                    id = id,
                }
            end
        end
    end
    table.sort(tempData.allTaskData, function(itemData1, itemData2)
        local gotId1 = self:getSortIndex(itemData1.serverData.status)
        local gotId2 = self:getSortIndex(itemData2.serverData.status)
        if gotId1 ~= gotId2 then
            return gotId1 < gotId2
        else
            return itemData1.id < itemData2.id
        end
    end)
    self.m_taskData = tempData
end

function M:getSortIndex(status)
    --0: 未完成,1：已完成，2：已领取
    -- 返回的顺序是1已完成，2未完成，3已领取
    if status == 0 then
        return 2
    elseif status == 1 then
        return 1
    elseif status == 2 then
        return 3
    end
    return 4
end

-- 完成任务修改
function M:amendTaskData(id)
    for _, itemData in pairs(self.m_taskData.allTaskData) do
        if itemData.id == id then
            itemData.serverData.status = 2
            break
        end
    end
end

function M:getActityOpenDay()
    local serverTimer = UserDataManager:getServerTime()
    local startTimer = self.m_activityData.start_ts
    --local residueTimer = serverTimer - startTimer
    --local openDayCount = math.floor(residueTimer / (24*60*60))
    local openDayCount = GameUtil:NumberOfDaysIntervalDay(startTimer,serverTimer)
    return math.floor(openDayCount)
end

function M:setAllAwardsData()
    local sword_questData = ConfigManager:getCfgByName("sword_reward")
    local versionRankAwardData = sword_questData[self.m_version] or {}
    self.m_allAwardsData = {}
    for id, itemData in ipairs(versionRankAwardData) do
        self.m_allAwardsData[id] = {
            xlsxData = itemData,
            id = id,
        }
    end
end

function M:setPersonAwardsData()
    local sword_questData = ConfigManager:getCfgByName("sword_person_reward")
    local versionRankAwardData = sword_questData[self.m_version] or {}
    self.m_allPersonAwardsData = {}
    for id, itemData in ipairs(versionRankAwardData) do
        self.m_allPersonAwardsData[id] = {
            xlsxData = itemData,
            id = id,
        }

    end
end

function M:setAwardState()
    self.m_curAwardIndex = 1
    for id, itemData in ipairs(self.m_allAwardsData) do
        if self.m_score >= itemData.xlsxData.score then
            self.m_curAwardIndex = id + 1
        end
    end
    self.m_curAwardIndex = self.m_curAwardIndex > 4 and 4 or self.m_curAwardIndex
end

return M

