---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/10 15:36
---

local M = class("KongMingLanternAwardPopModel", LikeOO.OODataBase)

M.point = {}

function M:onCreate()
    -- 1 许愿，2 奖励预览
    self.m_showType = self.m_params.showType 
    self.m_version = self.m_params.version
    self.m_wishAward = self.m_params.wishAward
    self:setSelectId(-1)
    self:getData()
end

function M:setSelectId(id)
    self.m_selectId = id
end

function M:getRewardsData()
    local tempData = {}
    if self.m_showType == 1 then
        local tempList = {}
        local wishData = ConfigManager:getCfgByName("wish")
        versionData = wishData[self.m_version] or {}
        for index, itemData in pairs(versionData.wish_reward) do
            tempList[index] = {
                awardData = itemData,
                weight = 0,
            }
        end
        return tempList
    else
        local tempList = {}
        local wish_rewardData = ConfigManager:getCfgByName("wish_reward")
        versionData = wish_rewardData[self.m_version] or {}
        for index, itemData in pairs(versionData) do
            tempList[index] = {
                awardData = itemData.big_reward[1],
                weight = itemData.show_weight,
            }
        end
        return tempList 
    end
end

function M:onEnter()

end

return M