---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/10 15:36
---

local M = class("KongMingLanternAwardPopView", LikeOO.OOPopBase)

M.m_uiName = "GiftBag/KongMingLanternAwardPop"
M.m_size_type = 2
function M:onEnter()
    self.m_selectItemObj = nil
    self:refreshUI()
end

function M:refreshUI()
    local isWith = self.m_model.m_showType == 1
    self:setObjectVisible("set_obj", isWith)
    local titleName = isWith and "lantern_text_0004" or "lantern_text_0002"
    self:setTextByLanKey("common_title_text", titleName)
    self:setTextByLanKey("text_gotText", "lantern_text_0005")
    
    self:refreshList()
end

function M:refreshList()
    local data = self.m_model:getRewardsData()
    if self.m_scroll_view == nil then
        local loopscroll = self:findGameObject("list_scroll")
        local params = {
            show_data = data,
            one_line_count = 7,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshItem(index, cell_obj, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "infoBtn" then
                    local awardData = RewardUtil:getProcessRewardData(cell_data.awardData)
                    local data_type = awardData.data_type
                    if data_type == RewardUtil.REWARD_TYPE_KEYS.EQUIPS then
                        if awardData.oid then
                            static_rootControl:openView("HeroInfo.EquipmentPop", {equip_id = awardData.oid})
                        else
                            static_rootControl:openView("HeroInfo.EquipmentPop", {equip_cfg_id = awardData.data_id, look_model = 3})
                        end
                    elseif data_type == RewardUtil.REWARD_TYPE_KEYS.ITEM then
                        static_rootControl:openView("Item.ItemDetail", {show_data = awardData, display = true}, nil, true)
                    elseif data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT or data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS_EXT then
                        static_rootControl:openView("Pops.HeroLookInfo", {hero_id = awardData.data_id, is_new = false})
                    elseif data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
                        static_rootControl:openView("Pops.HeroSkinLookInfo", {is_new = false, skin_id = awardData.data_id})
                    elseif data_type == RewardUtil.REWARD_TYPE_KEYS.MYSTIC then
                        static_rootControl:openView("SutraDepository.DepositoryPop", {oid = awardData.data_id, mode = 2})
                    elseif data_type == RewardUtil.REWARD_TYPE_KEYS.TITLE then
                        static_rootControl:openView("Title.TitleDetail", {show_data = awardData, display = true})
                    else
                        static_rootControl:openView("Pops.CommonItemTipsPop", {data = awardData, target_obj = cell_object})
                    end
                end
            end
        }
        self.m_scroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_scroll_view:reloadData(data)
    end
end

function M:switchSelectId(id, cell_obj)
    if (self.m_model.m_selectId > 0) and (not IsNull(self.selectItem)) then
        local luaBehaviour = UIUtil.findLuaBehaviour(self.selectItem)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "light_img", false)
    end
    self.m_model:setSelectId(id)
    self.selectItem = cell_obj
    local luaBehaviour = UIUtil.findLuaBehaviour(self.selectItem)
    LuaBehaviourUtil.setObjectVisible(luaBehaviour, "light_img", true)
end

function M:refreshItem(index, cell_obj, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local isShowWeight = (self.m_model.m_showType == 2)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "probability_text", isShowWeight)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "itemBg", isShowWeight)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "infoBtn", (not isShowWeight))
        if not isShowWeight then
            GameUtil:updateItemElement(cell_obj, cell_data.awardData, true, false,function()
                local params = {vsn = self.m_model.m_version, index = (index - 1)}
                self.m_model:getNetData("set_wish", params, function(response)
                    if response then
                        if response["end"] == 1 then
                            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
                            return
                        end
                        EventDispatcher:dipatchEvent("kongMing_setAward", response)
                        if not IsNull(self.m_selectItemObj) then
                            self.m_selectItemObj:SetActive(false)
                        end
                        self.m_selectItemObj = luaBehaviour:FindGameObject("selectNode")
                        self.m_selectItemObj:SetActive(true)
                        audio:SendEvtUI("Play_UI_Selected")
                    end
                end, nil, nil, nil)
            end)
            if self.m_model.m_wishAward then
                local isSelectAward = true
                for index, itemData in pairs(self.m_model.m_wishAward) do
                    if not isSelectAward then
                        break
                    end
                    isSelectAward = (cell_data.awardData[index] == itemData)
                end
                if isSelectAward then
                    self.m_selectItemObj = luaBehaviour:FindGameObject("selectNode")
                    self.m_selectItemObj:SetActive(true)
                end
            end
        else
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour,"probability_text", cell_data.weight .. "%") 
            GameUtil:updateItemElement(cell_obj, cell_data.awardData, true, true)
        end
    end
end

return M














