---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/21 10:58
---

local M = class("OpenServerRankRewardModel", LikeOO.OODataBase)

local __TAB_BTN_NODE = {
    {btn_key = "tog_1", text_key = "tog_1_text", tabIndex = 1, rankType1 = 5, rankType2 = 7}, --战力榜 -- 巅峰榜
    {btn_key = "tog_2", text_key = "tog_2_text", tabIndex = 2, rankType1 = 1, rankType2 = 8}, --关卡榜 -- 秘籍榜
}

function M:onCreate()
    M.super.onCreate(self)
    self.m_open_tab_index = __TAB_BTN_NODE[1].tabIndex
    self.m_versionId = self.m_params.versionId or 1
    --1侠客争锋，2赛季冲榜
    self.m_openType = self.m_params.openType or 1
    self:setRankData()
    self:setDashRankTabData()
    self.dataCountList = {}
    for index, itemData in pairs(self.m_rankAwards_data) do
        self.dataCountList[index] = #itemData
    end
    self:getData()
end

function M:onEnter()

end

function M:setRankData()
    if not self.m_rankAwards_data then
        self.m_rankAwards_data = {}
        local configName = (self.m_openType == 1) and "rank_effect" or "rank_effect"
        local game_street_rank_cfg = ConfigManager:getCfgByName(configName)
        local cfgData = game_street_rank_cfg[self.m_versionId]
        for rankType, typeItemData in pairs(cfgData) do
            if not self.m_rankAwards_data[rankType] then
                self.m_rankAwards_data[rankType] = {}
            end
            for id, itemData in pairs(typeItemData) do
                table.insert(self.m_rankAwards_data[rankType], {
                    id = id,
                    rank = itemData.rank,
                    daily_rewards = itemData.reward,
                    order = itemData.order,
                    tab_name = itemData.tab_name,
                    type = itemData.type,
                })
            end
            table.sort(self.m_rankAwards_data[rankType], function(itemData1, itemData2)
                return itemData1.id < itemData2.id
            end)
        end 
    end
end

-- 设置赛季冲榜按钮信息
function M:setDashRankTabData()
    local tempList = {}
    for _, itemData in pairs(self.m_rankAwards_data) do
        local itemOneData = itemData[1]
        table.insert(tempList, {
            taskType = itemOneData.type,
            order = itemOneData.order,
            name = itemOneData.tab_name,
        })
    end
    self.m_TabListData = tempList
end
return M
