---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/21 10:55
---

local M = class("OpenServerRankRewardView",LikeOO.OOPopBase)

M.m_uiName = "GiftBag/OpenServerRankReward"
M.m_size_type = 2

function M:onEnter()
    self:setTextByLanKey("tog_1_text", "openServerRank_str_0013")
    self:setTextByLanKey("tog_2_text", "openServerRank_str_0014")
    self:setTextByLanKey("common_title_text", "openServerRank_str_0012")
    self.m_toggle_btns = {}
    --for k,v in pairs(self.m_model:getTabBtnNode()) do
    --    local tabTextFormat = v["show_text"..self.m_model.m_openType]
    --    self:setTextByLanKey(v.text_key, tabTextFormat)
    --    local tog_btn = self:findToggle(v.btn_key)
    --    self.m_toggle_btns[k] = tog_btn
    --    UIUtil.addToggleListener(tog_btn, function(is_on)
    --        if is_on then
    --            self.m_model.m_open_tab_index = k
    --            self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_1)
    --            self:refreshUI()
    --        else
    --            self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_5)
    --        end
    --    end,nil,self.m_uiName)
    --    if k == self.m_model.m_open_tab_index then
    --        tog_btn.isOn = true
    --        self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_1)
    --    else
    --        self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_5)
    --    end
    --    self:setObjectVisible(v.red_point_img, false)
    --end
    self:refreshUI()
end

function M:refreshUI()
    self:updateRankLoopScroll()
    self:refreshTabListNode()
end

--[[
	创建排行列表
]]
function M:updateRankLoopScroll()
    --local tabBtnConfig = self.m_model:getTabBtnNode()
    local tabItemData = self.m_model.m_TabListData[self.m_model.m_open_tab_index]
    local data = self.m_model.m_rankAwards_data[tabItemData.taskType]
    local max_index = #data
    self:setObjectVisible("common_tips_node", #data == 0)
    if self.m_rank_loop_scroll_view == nil then
        local loopscroll = self:findGameObject("rank_loopscroll")
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_object, cell_data)
                self:updateRankScrollViewCell(index, cell_object, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                self:updateMsg(click_name, {id = index, cell_data = cell_data})
            end
        }
        self.m_rank_loop_scroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_rank_loop_scroll_view:reloadData(data, false)
    end
end

--Scroll内cell的回调
function M:updateRankScrollViewCell(index, cell_object, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_object)
    local reward = cell_data.daily_rewards or {} 	-- 奖励
    local reward_node = luaBehaviour:FindRectTransform("reward_node")
    GameUtil:createRewards(reward_node, reward, true, true, nil, 1)
    local rank = cell_data.rank or {}
    local first_rank = rank[1] or 0
    local second_rank = rank[2] or 0

    local top_three_flag = first_rank > 0 and first_rank < 2
    LuaBehaviourUtil.setObjectVisible(luaBehaviour, "top_three_rank_img", top_three_flag)
    LuaBehaviourUtil.setObjectVisible(luaBehaviour, "rank_bg", not top_three_flag)
    local top_three_item = GlobalConfig.RANK_TOP_THREE_IMG[first_rank]
    if top_three_item and top_three_flag then
        LuaBehaviourUtil.setImg(luaBehaviour,"top_three_rank_img", top_three_item.rank, top_three_item.atlas)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "rank_text", "")
    else
        local max_index = self.m_model.dataCountList[self.m_model.m_open_tab_index]
        if index == max_index then
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "rank_text", "new_str_0894", first_rank)
        else
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "rank_text", first_rank .. "-" .. second_rank)
        end
    end
end

function M:refreshTabListNode()
    if self.m_tabLoopScrollView == nil then
        local loopscroll = self:findGameObject("tab_scroll")
        local params = {
            show_data = self.m_model.m_TabListData,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_object, cell_data)
                self:updateTabItem(index, cell_object, cell_data)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_bgBtn" then
                    self.m_model.m_open_tab_index = index
                    self:refreshUI()
                end
            end
        }
        self.m_tabLoopScrollView = LoopScrollViewUtil.new(params)
    else
        self.m_tabLoopScrollView:reloadData(self.m_model.m_TabListData, false)
    end
end

function M:updateTabItem(index, cell_object, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_object)
    if luaBehaviour then
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_name", cell_data.name)
        local isSelectItem = (self.m_model.m_open_tab_index == index)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_SelectImg", isSelectItem)
        local textColor = isSelectItem and GlobalConfig.COMMON_COLLOR.COMMON_TOGGLE_FOCUS or GlobalConfig.COMMON_COLLOR.COMMON_TOGGLE
        LuaBehaviourUtil.setTextColor(luaBehaviour, "text_name", textColor)
    end
end

return M