---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:27
---

local M = class("SimulateOutComeView",LikeOO.OOPopBase)
-- 侠客人生模拟器--结局统计界面
M.m_uiName = "SimulateLift/SimulateOutCome"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

function M:onEnter()
    self:bindUI()
    self:refreshUI()
end

function M:refreshUI()
    self:refreshList()
    self:setText("text_progressText1", self.m_model.curEndCount .. "/" .. self.m_model.allEndCount)
    self:setText("text_progressText2", self.m_model.curEggEventCount .. "/" .. self.m_model.allEggEventCount)
    self:setObjectVisible("btn_tabBtn2", self.m_model.m_openId == 285)
end

function M:refreshList()
    for index = 1, 2 do
        local isSelect = (self.m_model.m_selectIndex == index)
        self:setObjectVisible("img_selectImg"..index, isSelect)
        local curColor = isSelect and Color( 121/255, 86/255, 45/255) or Color( 153/255, 187/255, 209/255)
        local contentText = self:findText("text_contentText"..index)
        contentText.color = curColor
        local progressText = self:findText("text_progressText"..index)
        progressText.color = curColor
    end
    local isOutCome = (self.m_model.m_selectIndex == 1)
    self:setObjectVisible("outComeNode", isOutCome)
    self:setObjectVisible("eggNode", (not isOutCome))
    if isOutCome then
        self:createOutcomeLoopScroll()
    else
        self:createEggLoopScroll()
    end
end

function M:bindUI()
    self:setTextByLanKey("text_contentText1", "simulateLeft_text_0003")
    self:setTextByLanKey("text_contentText2", "simulateLeft_text_0051") 
end

function M:createOutcomeLoopScroll()
    local data = self.m_model.endListData
    if self.m_endScroll_view == nil then
        local loopscroll = self:findGameObject("outcomeLoopscroll")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self:update_outcomeGift(cell_obj, cell_data, index)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name) -- 点击回调
                
            end
        }
        self.m_endScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_endScroll_view:reloadData(data)
    end
end
function M:update_outcomeGift(cell_obj, cell_data, index)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_contentText", cell_data.value)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_showImg", (not cell_data.isEmpty))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_hideImg", cell_data.isEmpty)
    end
end

function M:createEggLoopScroll()
    local data = self.m_model.eventListData
    if self.m_eggScroll_view == nil then
        local loopscroll = self:findGameObject("eggLoopscroll")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self:update_eggGift(cell_obj, cell_data, index)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name) -- 点击回调

            end
        }
        self.m_eggScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_eggScroll_view:reloadData(data)
    end
end
function M:update_eggGift(cell_obj, cell_data, index)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_contentText", cell_data.value)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_showImg", (not cell_data.isEmpty))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_hideImg", cell_data.isEmpty)
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M
