---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/21 12:46
---@class FlowerServerRankRewardControl:OOControlBase
local M = class("FlowerServerRankRewardControl",LikeOO.OOControlBase)

function M:onEnter()

end

function M:onHandle(msg , data)
    if msg == 99999 then    -- 返回
        self:closeView()
    end
end

return M
