---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/21 10:58
---
---@class FlowerServerRankRewardModel:OODataBase
local M = class("FlowerServerRankRewardModel", LikeOO.OODataBase)

local __TAB_BTN_NODE = {
    {btn_key = "tog_1", configName = "flower_rank_reward", text_key = "tog_1_text", tabIndex = 1, tab_name = "flower_text_0054"}, 
    {btn_key = "tog_2", configName = "flower_guild_reward", text_key = "tog_2_text", tabIndex = 2, tab_name = "flower_text_0055"}, 
}

function M:onCreate()
    M.super.onCreate(self)
    self.tab=true
    if self.m_params.is_rta_rank_rewards then
        __TAB_BTN_NODE = {
            {btn_key = "tog_1", configName = "rta_rank_award", text_key = "tog_1_text", tabIndex = 1, tab_name = "flower_text_0054"},
        }

        self.tab=false
    end
    self.m_open_tab_index = __TAB_BTN_NODE[1].tabIndex
    self.m_TabListData = __TAB_BTN_NODE
    self.m_versionId = self.m_params.version or 1
    self:setRankData()
    --self:setDashRankTabData()
    self.dataCountList = {}
    for index, itemData in pairs(self.m_rankAwards_data) do
        self.dataCountList[index] = #itemData
    end
    self:getData()
end

function M:onEnter()

end

function M:setRankData()
    if not self.m_rankAwards_data then
        self.m_rankAwards_data = {}
        for index = 1, table.nums(__TAB_BTN_NODE) do
            local itemData =  __TAB_BTN_NODE[index]
            local configXlsxData = ConfigManager:getCfgByName(itemData.configName)
            local cfgData = configXlsxData[self.m_versionId]
            if not self.m_rankAwards_data[index] then
                self.m_rankAwards_data[index] = {}
            end
            if self.m_params.is_rta_rank_rewards then
                cfgData=cfgData[self.m_params.tier]

                local pairsByKeys=function(t)
                    local a={}
                    for i in pairs(t) do
                        a[#a+1]=i
                    end
                    table.sort(a)
                    local j=0
                    return function()
                        j=j+1
                        return a[j],t[a[j]]
                    end
                end

                for rank, itemData in pairsByKeys(cfgData) do
                    local _rank=rank
                    if itemData.rank_dis[2]==3 then
                        table.insert(self.m_rankAwards_data[index], {
                            rank = {[1]=2},
                            award = itemData.awards,
                        })
                        table.insert(self.m_rankAwards_data[index], {
                            rank = {[1]=3},
                            award = itemData.awards,
                        })
                    else
                        table.insert(self.m_rankAwards_data[index], {
                            rank = itemData.rank_dis,
                            award = itemData.awards,
                        })
                    end

                end
            else
                for _, itemData in pairs(cfgData) do
                    table.insert(self.m_rankAwards_data[index], {
                        rank = itemData.rank,
                        award = itemData.rank_rewards,
                    })
                end
            end

            Logger.logWarning(self.m_rankAwards_data)
        end
    end
end

return M
