---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 16:45
---

local M = class("FlowerGiftBagControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
    self:updateTime()
    self.m_timer_id = self:setTimer(1,handler(self,self.updateTime))
end

function M:onHandle(msg , data)
    if msg == 99999 then
        if self.m_model.is_tokens == true then
            self:updateMsg("refresh_data",nil,"TopUpGiftBag.ToKensSelectGiftBagPop")
        end
        self:closeView()
    elseif msg == "explain_btn" then
        -- 提示  
        local flowerData = ConfigManager:getCfgByName("flower_festival")
        local versionData = flowerData[self.m_model.m_version]
        local mainActiveData = self.m_model:getXlsxActivityByOpenId(self.m_model.m_open_id, true)
        self:openView("Pops.CommonHelpPop", { title = Language:getTextByKey(mainActiveData.name), content = Language:getTextByKey(versionData.flower_des) })
    elseif msg == "refresh_data" then
        local function netCallback(response)
            if response.update then
                GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("new_str_0558"), delay_close = 2})
                self:closeView()
                return
            end
            if response["end"] then
                GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("new_str_0558"), delay_close = 2})
                self:closeView()
                return
            end
            self.m_model:initData(response)
            self.m_view:refreshUI()
        end
        local param = {}
        param.open_id = self.m_model.m_params.openId
        param.vsn = self.m_model.m_params.version
        self.m_model:getNetData("active_common_gift_index", param, netCallback)
    elseif msg == "get_free_ladder_gift" then --免费阶梯礼包
        self:getFreeLadderGift(data)
    elseif msg == "buy" then
        self:buyForSDK(data)
    end
end


--使用代金券购买
function M:buyUseVoucher(data, callback)
    local function receivetCallback(response)
        if callback then
            callback()
        end
        if response and response.reward then
            RewardUtil:rewardTipsByData(response.reward)
        end
    end
    local charge = ConfigManager:getCfgByName("charge")
    local cfg = charge[data]
    if cfg == nil then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0129",data), delay_close = 2})
        return
    end
    local voucher_data = RewardUtil:getProcessRewardData({RewardUtil.REWARD_TYPE_KEYS.VOUCHER,0,0})
    if voucher_data.user_num < cfg.price then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0130",data), delay_close = 2})
        return
    end
    local params = {
        charge_id = data
    }
    self.m_model:getNetData("voucher", params, receivetCallback)
end


--调用sdk充值
function M:buyForSDK(charge_id)
    audio:SendEvtUI("UI_Pay")
    if self.m_model.is_tokens == true then
        self:buyUseVoucher(charge_id, function ()
            self:RefreshOneTagData()
        end)
        return
    end
    if self.timer_id then
        Logger.logWarningAlways(self.timer_id, "-------------IsPay-----------")
        return
    end
    self.m_view:lockTouch()
    self.timer_id = self:setOnceTimer(8, function ()
        self.m_view:unlockTouch()
        self.timer_id = nil
    end)
    PayUtil:rechargeByChargeId(charge_id, function ()
        if self.m_view then
            self.m_view:unlockTouch()
            if self.timer_id then
                self:removeTimer(self.timer_id)
                self.timer_id = nil
            end
            self:RefreshOneTagData()
        end
    end)
end

--免费阶梯礼包
function M:getFreeLadderGift(data)
    local function receivetCallback(response)
        if response then
            if response.update then
                GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("new_str_0558"), delay_close = 2})
                self:closeView()
                return
            end
            if response["end"] then
                GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("new_str_0558"), delay_close = 2})
                self:closeView()
                return
            end
            if response.gifts_data then
                table.merge(self.m_model.m_gifts_data, response.gifts_data)
            end
            RewardUtil:rewardTipsByData(response.reward)
            self.m_view:refreshUI()
        end
    end
    local params = {}
    params.vsn = self.m_model.m_version
    params.place = data.id
    params.open_id = self.m_model.m_open_id
    params.paper_id = self.m_model.cur_page
    self.m_model:getNetData("active_common_gift_buy", params, receivetCallback)
end

--付费后的整体刷新
function M:RefreshOneTagData()
    self:updateMsg("refresh_data")
end

function M:updateTime()
    self.m_view:updateTime()
end

function M:destroy()
    self:removeTimer(self.m_timer_id)
    M.super.destroy(self)
end

return M
