---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/8 16:14
---

local M = class("PetardMainControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        if not self.m_model.m_isEnter then
            return
        end
        self:closeView()
    elseif msg == "btn_openBtn1" then
        -- 签到有礼
        self:openViewByIndex(2)
    elseif msg == "btn_openBtn2" then
        -- 花火集会
        self:openViewByIndex(3)
    elseif msg == "btn_openBtn3" then
        -- 花火商店 
        self:openViewByIndex(4)
    elseif msg == "btn_openBtn4" then
        -- 返现礼包
        self:openViewByIndex(5)
    elseif msg == "explain_btn" then
        -- 提示  
        local flowerData = ConfigManager:getCfgByName("flower")
        local versionData = flowerData[self.m_model.m_version] 
        local name = self.m_model.petardAactivityDatas[221].xlsxActivity.name or ""
        self:openView("Pops.CommonHelpPop", { title = name, content = versionData.des })
    elseif msg == "everyDayrefresh" then
        self.m_model:getNetData("double_twelve_index", data, function(response)
            if response then
                if response["end"] == 1 then
                    GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
                    return
                end
                self.m_model:everyDayRefresh(response)
                self.m_view:refreshAllRedDot()
                EventDispatcher:dipatchEvent("petardActivity_everyDayEvent", self.m_model.petardAactivityDatas)
            end
        end, nil, nil, nil)
    elseif msg == "refreshAllRedDot" then
        --Logger.logError("shuax-------------")
        self.m_view:refreshAllRedDot()
    end
end

function M:openViewByIndex(index)
    if not self.m_model.m_isEnter then
        return
    end
    if not self.m_model.petardAactivityDatas then
        return
    end
    local itenConfig = self.m_model.m_tabConfig
    if not itenConfig[index] then
        return
    end
    local openId = (itenConfig[index].open_id)
    if not self.m_model.petardAactivityDatas[openId] then
        return
    end
    local itemActivityData = self.m_model.petardAactivityDatas[openId]
    if index == 2 then
        self:openView("PetardActivity.PetardSevenDayLogin", itemActivityData)
    elseif index == 3 then
        self:openView("PetardActivity.PetardTask", itemActivityData)
    elseif index == 4 then
        self:openView("PetardActivity.PetardShop", itemActivityData)
    elseif index == 5 then
        self:openView("PetardActivity.PetardGiftBagNew", {openId = openId, version = self.m_model.m_version})
    end
end

function M:testOpenByActivityTimer()
    -- 时间不准，直接刷新
    self:updateMsg("common_refresh", nil, "parent")
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M