---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/12/6 16:20
---

local M = class("PetardMainAnimNode", LikeOO.OOUIbase)
--侠客争锋
M.m_uiName = "PetardActivity/PetardMainAnimNode"
M.cacheSpineName = ""


local AnimName = {
    BgName = "BGyanhua_SkeletonData",
    NpcName = "Axian_SkeletonData",
    MaxBgName = "BGmain_SkeletonData",
}

function M:onEnter()
    local allTimer = 5.67
    local npcTimer = 2.66
    local npcBgTimer = 2.26
    self.m_model.m_isEnter = false
    local petard_bgAni = self:findGameObject("anim1")
    local petard_npcAni = self:findGameObject("anim2")
    local petard_maxBgAni = self:findGameObject("anim3")
    -- 点火          
    GameUtil:updateSpineLoadSet(petard_bgAni, "RoleSpine/" .. AnimName.BgName, "idle", 0, true)
    GameUtil:updateSpineLoadSet(petard_npcAni, "RoleSpine/" .. AnimName.NpcName, "animation_long", 0, true)
    GameUtil:updateSpineLoadSet(petard_maxBgAni, "RoleSpine/" .. AnimName.MaxBgName, "idle", 0, true)
    self.m_control:setOnceTimer(npcBgTimer,function()
        self:setObjectVisible("anim1", false)
    end)
    self.m_control:setOnceTimer(npcTimer,function()
        self:setObjectVisible("anim2", false)
    end)
    self.m_control:setOnceTimer(allTimer,function()
        self.m_model.m_isEnter = true
        self:setObjectVisible("anim3", false)
    end)
end

function M:destroy()
    M.super.destroy(self)
end

return M