---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/12/13 16:29
---

local __PrefabPath = "QiMenDunJia/sceneObject/"

-- 奇门遁甲 格子管理类
---@class QiMenDunJiaGridMgr @
local M = class("QiMenDunJiaGridMgr")

function M:init(parentModel)
    self:initAllObjInfo()       
    self.parentModel = parentModel
    -- 走过的地块
    self:refreshWalkGrids(parentModel.serverMapData.passed)
    -- prefabPath
    -- 地图id
    self.map_id = self.parentModel.map_id
    -- 当前玩家格子id
    local curPlayerGridId = self.parentModel.playerGridId
    -- 查看时的格子id
    self.lookGridId = curPlayerGridId
    -- 超过x范围刷新脚下格子
    self.refreshRadius = 3
    -- 上一次刷新格子记录的格子id
    --self.lastRefreshGridId = curPlayerGridId
    -- 显示格子的范围
    self.showGridRadius = self.refreshRadius * 2
    -- 格子预制体
    self.viewGridObjCount = self.showGridRadius * self.showGridRadius
    -- 记录显示的格子对象集合
    self.showGridObjInfoList = {}
    
    -- [index]:gridId
    self.viewGridObjIdList = {}
    self.viewGridObjPool = nil
    self:initGridObjPool()      -- self.viewGridObjPool
    
    self:initGridsData()        -- self.gridUnitList
    self:refreshGridInfo(false, curPlayerGridId, true)
end

-- 刷新走过的格子数据
function M:refreshWalkGrids(passed)
    if not self.walkGridIds then
        self.walkGridIds = {}
    end
    for _, gridId in pairs(passed) do
        self.walkGridIds[gridId] = gridId
    end
    self.parentModel:refreshServerMapData({passed = self.walkGridIds})
end

-- 刷新单个走过的格子数据
function M:setWalkGridIdsByGridId(gridId)
    self.walkGridIds[gridId] = gridId
    self.parentModel:refreshServerMapData({passed = self.walkGridIds})
end

function M:isGridWalk(gridId)
    return (self.walkGridIds[gridId] ~= nil)
end

-- 初始化和模型有关的        ---- 暂时写这里，之后扔出去
function M:initAllObjInfo()
    --模型池子的luabehaviour
    --local allModelPoolObj = U3DUtil:GameObject_Find("AllModelPool")
    --local gridModelPoolObj = allModelPoolObj.transform:Find("gridModelPool")
    --self.gridModelPoolTrans = gridModelPoolObj.transform

    -- 池子
    local allPoolObj = U3DUtil:GameObject_Find("AllPool")
    self.gridPoolTrans = allPoolObj.transform:Find("gridPool")
    
    -- 场景
    local sceneObj = U3DUtil:GameObject_Find("qimendunjiascene_data")
    self.gridGroupTrans = sceneObj.transform:Find("gridGroup")
end

function M:initGridObjPool()
    if (not self.gridGroupTrans) then
        return
    end
    if not self.viewGridObjPool then
        self.viewGridObjPool = {}
        local gve_massifData = ConfigManager:getCfgByName("gve_massif")
        for id, itemData in pairs(gve_massifData) do
            --- 类型是地块
            if itemData.type == 1 then
                for index = 1, self.viewGridObjCount do
                    local gridName = itemData.building_model
                    local itemGridObj = self:createGridObjByGridModelType(gridName)
                    if not self.viewGridObjPool[id] then
                        self.viewGridObjPool[id] = {}
                    end
                    local curGridPool = self.viewGridObjPool[id]
                    curGridPool[index] = itemGridObj
                    -- 动态创建的需要添加点击事件
                    self:setGridObjClickEvent(itemGridObj, true)
                end
            end
        end
    end
end

-- 获取当前半径范围内的所有不为空的格子id
function M:getCurRadiusGridIds(centreGridId)
    -- showGridRadius
    local centerGridData = self.gridUnitList[centreGridId]
    if not centerGridData then
        return {}
    end
    local curWidth = centerGridData.w_pos
    local curHeight = centerGridData.h_pos
    local widthList = {}
    local heightList = {}
    for tempW = -(self.showGridRadius), self.showGridRadius, 1 do
        for tempH = -(self.showGridRadius), self.showGridRadius, 1 do
            local targetW = curWidth + tempW
            local targetH = curHeight + tempH
            if (targetW >= 0) and (targetH >= 0) then
                if not widthList[targetW] then
                    widthList[targetW] = targetW
                end
                if not heightList[targetH] then
                    heightList[targetH] = targetH
                end
            end
        end
    end
    local showRefreshGridIds = {}
    for _, tempWidth in pairs(widthList) do
        for _, tempHeight in pairs(heightList) do
            local gridId = self:getGridIDByWidthAndHeight(tempWidth, tempHeight)
            if (self.gridUnitList[gridId] ~= nil) and (self.gridUnitList[gridId].m_gridType ~= GlobalConfig.GridType.Empty) then
                showRefreshGridIds[gridId] = gridId
            end
        end
    end
    return showRefreshGridIds
end

-- 刷新格子信息   (通过中心格子id同步格子)
-- （先让玩家走过去，再调格子刷新）     
-- isNotLimit 是否不启用 刷新限制
function M:refreshGridInfo(isCameraRefresh, centreGridId, isNotLimit)
    ---- 超过x范围刷新脚下格子
    --self.refreshRadius = 5
    ---- 上一次刷新格子记录的格子id
    --self.lastRefreshGridId = self.curPlayerGridId
    local centerGridData = self.gridUnitList[centreGridId]
    if not centerGridData then
        return
    end
    --local lastRefreshHintGridData = self.gridUnitList[self.lastRefreshGridId]
    --if not lastRefreshHintGridData then
    --    return
    --end
    self.lookGridId = centreGridId
    --Logger.logError("刷新地块总接口参数===%%%%%%====lookGridId = "..self.lookGridId..", PlayerGridId = "..self.parentModel.playerGridId..", 服务器的数据格子是==="..self.parentModel.serverMapData.cell_id)
    if not isNotLimit then
        --local offsetWidth = math.abs(centerGridData.w_pos) - math.abs(lastRefreshHintGridData.w_pos)
        --offsetWidth = math.abs(offsetWidth)
        --local offsetHeight = math.abs(centerGridData.h_pos) - math.abs(lastRefreshHintGridData.h_pos)
        --offsetHeight = math.abs(offsetHeight)
        --local offsetDis = (offsetWidth > offsetHeight) and offsetWidth or offsetHeight
        --if offsetDis <= self.refreshRadius then
        --    return
        --end
    end
    -- 判断格子间距离，超过一定范围后刷新周围格子
    --self.lastRefreshGridId = centreGridId

    -- 刷新可视范围6+1格子条件（除怪物格子）
    local centerGridType = centerGridData.m_gridType
    if centerGridType and (not isCameraRefresh) then
        if (centerGridType ~= GlobalConfig.GridType.Normal) and (centerGridType ~= GlobalConfig.GridType.Empty) and
                (centerGridType ~= GlobalConfig.GridType.GiftBag) and (centerGridType ~= GlobalConfig.GridType.BirthPoint) and (centerGridType ~= GlobalConfig.GridType.Dependency)  then
            return
        end
    end
    
    local showRefreshGridIds = self:getCurRadiusGridIds(centreGridId)
    -- 刷新可视范围6+1格子的显示属性 (只处理不可见的格子数据)
    local allShowGrids = {}
    if (not isCameraRefresh) then
        local aroundGridUnits,_ = self.parentModel:getAroundGridUnit(centerGridData)
        for _, itemData in pairs(aroundGridUnits) do
            if not itemData.m_isWalk then
                allShowGrids[itemData.m_gridId] = itemData.m_gridId
            end
        end
        if not centerGridData.m_isWalk then
            allShowGrids[centreGridId] = centreGridId
        end
    end
    local showGridCount = table.nums(self.showGridObjInfoList)
    if showGridCount > 0 then
        --- 判断当前格子Id存不存在，存在的话 未探索改为 已探索，不可见格子就隐藏
        for id, _ in pairs(self.showGridObjInfoList) do
            -- 隐藏不可见格子
            if not showRefreshGridIds[id] then
                local curGridInfo = self.showGridObjInfoList[id]
                self:setGridObjByGridModelType(curGridInfo.gridModelType, curGridInfo.gridObj)
                self.showGridObjInfoList[id] = nil
            end
            -- 修改格子属性（未探索 改为 已探索）
            if (not isCameraRefresh) and centerGridData.m_isWalk then
                if allShowGrids[id] then
                    -- 移除格子模型
                    local curGridInfo = self.showGridObjInfoList[id]
                    self:setGridObjByGridModelType(curGridInfo.gridModelType, curGridInfo.gridObj)
                    self.showGridObjInfoList[id] = nil
                    -- 修改格子属性
                    self:setShowGridData(id)
                end
            end
        end
    end
    for gridId, _ in pairs(showRefreshGridIds) do
        if not self.showGridObjInfoList[gridId] then
            local gridUnit = self.gridUnitList[gridId]
            if gridUnit.m_gridType ~= GlobalConfig.GridType.Empty then
                local gridModelType = gridUnit.m_gridModelType  --gridUnit.m_isWalk and gridUnit.m_gridModelType or gridUnit.m_blackModelTypeId            -- 不展示黑色地块
                local gridObj = self:getGridObjByGridModelType(gridUnit, self.gridGroupTrans)
                self.showGridObjInfoList[gridId] = {
                    id = gridId,
                    gridModelType = gridModelType,
                    gridObj = gridObj,
                }
                self:setGridObjPosByGridId(gridObj, gridId)
            end
        end
    end
    
    -- 刷新怪物，宝箱，铸剑台
    self:refreshMapInfoData(showRefreshGridIds)   
end

-- 刷新可视范围6+1格子的显示属性
function M:setShowGridData(gridId)
    local gridUnit = self:getGridUnitById(gridId)
    self:setWalkGridIdsByGridId(gridId)
    local serverGridData = self.serverGridsData[tostring(gridId)] or nil
    local isWalk = (self.walkGridIds[gridId] ~= nil)
    gridUnit:refreshGridData(serverGridData, isWalk)
    self.parentModel:refreshAStarGridData(gridUnit.w_pos, gridUnit.h_pos, serverGridData, isWalk)
end

-- 刷新单个格子信息
function M:refreshGridData(gridId, serverCell)
    self.serverGridsData[tostring(gridId)] = serverCell
    self.parentModel:refreshServerMapData({cells = self.serverGridsData})
    local gridUnit = self:getGridUnitById(gridId)
    local serverGridData = self.serverGridsData[tostring(gridId)] or nil
    local isWalk = (self.walkGridIds[gridId] ~= nil)
    gridUnit:refreshGridData(serverGridData, isWalk)
    self.parentModel:refreshAStarGridData(gridUnit.w_pos, gridUnit.h_pos, serverGridData, isWalk)
    return gridUnit
end

    -- 返回可视范围内的怪物格子，宝箱格子     
function M:refreshMapInfoData(showRefreshGridIds)
    local groundGoods = {
        monsterGrids = {},  giftBagGrids = {}, swordDesks = {},
        forceStatues = {},  leagueGrids = {},  shopGrids = {},
        wuzhuangs = {}, pillars = {},
    }
    for gridId, _ in pairs(showRefreshGridIds) do
        -- 这里生成建筑物要注意关联格子，
        local tempUnit = self.gridUnitList[gridId]
        local relationGridId = tempUnit.m_relationGridId
        local gridUnit = (relationGridId > 0) and self.gridUnitList[relationGridId] or tempUnit
        if gridUnit and (gridUnit.m_gridType ~= GlobalConfig.GridType.Empty) and (gridUnit.m_gridId ~= self.parentModel.playerGridId) then
            local curGridId = gridUnit.m_gridId
            -- 走过 或者 策划配表的显示模型
            if gridUnit.m_isWalk or gridUnit.m_isShowModel then
                if (gridUnit.m_gridType == GlobalConfig.GridType.Monster) then
                    groundGoods.monsterGrids[curGridId] = curGridId
                    if gridUnit.m_wuzhuangSign then
                        --TODO 特殊处理了八卦阵，含有八卦阵数据的怪物类型, 脚下显示八卦阵
                        groundGoods.wuzhuangs[curGridId] = curGridId
                    end
                elseif (gridUnit.m_gridType == GlobalConfig.GridType.GiftBag) then
                    groundGoods.giftBagGrids[curGridId] = curGridId
                elseif (gridUnit.m_gridType == GlobalConfig.GridType.SwordDesk) then
                    groundGoods.swordDesks[curGridId] = curGridId
                elseif (gridUnit.m_gridType == GlobalConfig.GridType.ForceStatue) then
                    groundGoods.forceStatues[curGridId] = curGridId
                elseif (gridUnit.m_gridType == GlobalConfig.GridType.League) then
                    groundGoods.leagueGrids[curGridId] = curGridId
                elseif (gridUnit.m_gridType == GlobalConfig.GridType.Shop) then
                    groundGoods.shopGrids[curGridId] = curGridId
                elseif (gridUnit.m_gridType == GlobalConfig.GridType.Wuzhuang) then
                    groundGoods.wuzhuangs[curGridId] = curGridId
                elseif (gridUnit.m_gridType == GlobalConfig.GridType.Pillar) then
                    groundGoods.pillars[curGridId] = curGridId
                end
            end
        end
    end
    self.parentModel:refreshMapInfo(groundGoods)
end

    -- 往池子里放格子
function M:setGridObjByGridModelType(gridModelType, gridObj)                    
    if table.nums(self.viewGridObjPool[gridModelType]) > self.viewGridObjCount then
        self:setGridObjClickEvent(gridObj, false)
        local gve_massifData = ConfigManager:getCfgByName("gve_massif")
        local gridXlsxData = gve_massifData[gridModelType] or {}
        local gridModelName = gridXlsxData.building_model
        U3DUtil:DestroyAndBundle(gridObj, gridModelName, nil, 0)
        return
    end
    gridObj:SetActive(false)
    table.insert(self.viewGridObjPool[gridModelType], gridObj)
end

-- 从池子里拿格子
function M:getGridObjByGridModelType(gridUnit, parentTrans)         
    if not gridUnit then
        return nil
    end
    local gridModelType = gridUnit.m_gridModelType  --gridUnit.m_isWalk and gridUnit.m_gridModelType or gridUnit.m_blackModelTypeId
    local gridModelName = gridUnit.m_gridModelName --gridUnit.m_isWalk and gridUnit.m_gridModelName or gridUnit.m_blackModelName        -- 不展示黑色地块
    local gridObj = nil
    if table.nums(self.viewGridObjPool[gridModelType]) <= 0 then
        gridObj = self:createGridObjByGridModelType(gridModelName)
        -- 动态创建的需要添加点击事件
        self:setGridObjClickEvent(gridObj, true)
    else
        gridObj = table.remove(self.viewGridObjPool[gridModelType])
    end
    gridObj.transform:SetParent(parentTrans,false)
    gridObj.name = "grid_"..gridModelType .. "_" .. gridUnit.w_pos .. "_" .. gridUnit.h_pos
    gridObj:SetActive(true)
    return gridObj
end

-- 设置格子的点击事件(对象，是否设置点击事件)
function M:setGridObjClickEvent(gridObj, isSet)
    local mouseListener = gridObj:GetComponent("GameObjectMouseEventListener")
    if not mouseListener then
        return
    end
    if isSet then
        mouseListener.onClick = function()
            if IsNull(gridObj) then
                return
            end
            local strTab = string.split( gridObj.name,'_' )
            local gridWidth = tonumber(strTab[3])
            local gridHeight = tonumber(strTab[4])
            self.parentModel:ClickObjEvent(gridWidth, gridHeight, "gridGroup", nil)
        end
    else
        mouseListener.onClick = nil
    end
end

-- 点到格子
function M:ClickGridEvent(gridType, gridWidth, gridHeight, overEvent)
    
end

function M:createGridObjByGridModelType(gridModelName) 
    local obj = ResourceUtil:GetUIItem("QiMenDunJia/sceneObject/"..gridModelName, self.gridPoolTrans.gameObject, "ui_prefabs")
    local itemGridTrans = obj.transform
    itemGridTrans.localPosition = Vector3.zero
    obj:SetActive(false)
    return obj
end

function M:setGridObjPosByGridId(gridObj, gridId)
    if IsNull(gridObj) then
        return
    end
    local gridUnit = self.gridUnitList[gridId]
    if not gridUnit then
        gridObj:SetActive(false)
        return
    end
    gridObj.transform.localPosition = Vector3(gridUnit.m_posX, gridUnit.m_posY, gridUnit.m_posZ)
end

-- 初始化格子数据
function M:initGridsData()
    self.gridUnitList = {}
    self.serverGridsData = self.parentModel.serverMapData.cells
    local local_mapData = require("Battle.Data.QiMenDunJia."..tostring(self.map_id));       
    --宽度
    local max_w = #local_mapData[0];
    --高度
    local max_h = #local_mapData;
    local gridUnitCls = require("Battle.Sce.QiMenDunJia.QiMenDunJiaGridUnit")
    for curWidth = 0, max_w do
        for curHeight = 0, max_h do
            -- 地图编辑器生成的数据是高在前
            local placeGridData = local_mapData[curHeight][curWidth] 
            local gridId = self:getGridIDByWidthAndHeight(curWidth,curHeight)
            local girdUnit = gridUnitCls.new()
            girdUnit:init(gridId, placeGridData, curWidth, curHeight)
            local serverGridData = self.serverGridsData[tostring(gridId)] or nil
            girdUnit:refreshGridData(serverGridData, (self.walkGridIds[gridId] ~= nil))
            self:setGridRelation(placeGridData, girdUnit)
            self:setMonsterRefreshGridRelation(girdUnit)
            self.gridUnitList[girdUnit.m_gridId] = girdUnit
        end
    end
    
    local centerGridData = self.gridUnitList[self.parentModel.playerGridId]
    -- 初始化将所在范围6个格子属性全部修改掉
    local aroundGridUnits,_ = self.parentModel:getAroundGridUnit(centerGridData)
    for _, itemUnit in pairs(aroundGridUnits) do
        if self.gridUnitList[itemUnit.m_gridId] then
            local girdUnit = self.gridUnitList[itemUnit.m_gridId]
            self.walkGridIds[girdUnit.m_gridId] = girdUnit.m_gridId
            local serverGridData = self.serverGridsData[tostring(itemUnit.m_gridId)] or nil
            girdUnit:refreshGridData(serverGridData, true)
            self.parentModel:refreshAStarGridData(itemUnit.w_pos, itemUnit.h_pos, serverGridData, true)
        end
    end
end

-- 设置八卦阵--柱子类格子关联
function M:setMonsterRefreshGridRelation(girdUnit)
    local mapConfig = self.parentModel.config
    if (mapConfig == nil) or (table.nums(mapConfig) <= 0) then
        return
    end
    local curGridId = girdUnit.m_gridId
    if mapConfig[curGridId] == nil then
        return
    end
    local curGridConfig = mapConfig[curGridId]
    local monsterRelationList = curGridConfig.monsterRelationList
    if (not monsterRelationList) or (monsterRelationList == "") then
        return
    end
    local monsterRelationInfoList = string.split(monsterRelationList, "|")
    if not monsterRelationInfoList[1] then
        return
    end
    if table.nums(monsterRelationInfoList) > 1 then
        girdUnit:setWuzhuangSign(true)
    else
        local itemInfo = monsterRelationInfoList[1]
        local relationGridData = string.split(itemInfo, "_")
        local tempGridId = self:getGridIDByWidthAndHeight(tonumber(relationGridData[1]), tonumber(relationGridData[2]))
        girdUnit:setMonsterRefreshGridId(tempGridId)
    end 
end

-- 设置格子关联
function M:setGridRelation(placeGridData, girdUnit)
    if (not placeGridData) or (not girdUnit) then
        return
    end
    --if girdUnit.m_gridType ~= GlobalConfig.GridType.Dependency then
    --    return
    --end
    local relationInfo = placeGridData.relationList
    if not relationInfo or relationInfo == "" then
        return
    end
    local relationInfoList = string.split(relationInfo, "|")
    if not relationInfoList[1] then
        return
    end
    local listCount = table.nums(relationInfoList)
    if listCount > 1 then
        -- 母格子
        local childList = {}
        for index = 1, listCount do
            local itemInfo = relationInfoList[index]
            local relationGridId = self:getGridIdByOneGridStrInfo(itemInfo)
            if relationGridId > 0 then
                childList[relationGridId] = relationGridId
            end
        end
        girdUnit:setRelationGridlist(childList)
        girdUnit:setRelationGridId(girdUnit.m_gridId)
    else
        -- 子格子
        local relationGridId = self:getGridIdByOneGridStrInfo(relationInfoList[1])
        if relationGridId > 0 then
            girdUnit:setRelationGridId(relationGridId)
        end
    end
end

-- 获取格子，通过格子string信息("2_2")
function M:getGridIdByOneGridStrInfo(gridStrInfo)
    local relationGridData = string.split(gridStrInfo, "_")
    if (not relationGridData) or (table.nums(relationGridData) < 2) then
        return -1
    end
    return self:getGridIDByWidthAndHeight(tonumber(relationGridData[1]), tonumber(relationGridData[2]))
end

--disable
function M:disable(  )

end

--销毁
function M:destroy()
    local gve_massifData = ConfigManager:getCfgByName("gve_massif")
    if self.viewGridObjPool then
        for gridModelType, itemGridPool in pairs(self.viewGridObjPool) do
            local gridXlsxData = gve_massifData[gridModelType] or {}
            local gridModelName = gridXlsxData.building_model
            if gridModelName then
                for _, gridObj in pairs(itemGridPool) do
                    if not IsNull(gridObj) then
                        self:setGridObjClickEvent(gridObj, false)
                        U3DUtil:DestroyAndBundle(gridObj,__PrefabPath..gridModelName,nil,0)
                    end
                end
            end
        end 
    end
    self.viewGridObjPool = nil

    if self.showGridObjInfoList then
        for _, itemData in pairs(self.showGridObjInfoList) do
            local gridModelType = itemData.gridModelType
            local gridXlsxData = gve_massifData[gridModelType] or {}
            local gridModelName = gridXlsxData.building_model
            if (not IsNull(itemData.gridObj)) and gridModelName then
                self:setGridObjClickEvent(itemData.gridObj, false)
                U3DUtil:DestroyAndBundle(itemData.gridObj,__PrefabPath..gridModelName,nil,0)
            end
        end
    end
    self.showGridObjInfoList = nil
    self.walkGridIds = nil
    for _, itemData in pairs(self.gridUnitList) do
        itemData:destroy()
    end
    self.gridUnitList = nil
end

-- 获得id     -- infoToID
function M:getGridIDByWidthAndHeight( w, h )
    --  110001 0001 0001
    return tonumber(self.map_id) * 100000000 + w * 10000 + h
end

--获取格子数据        -- getCellData
function M:getGridUnitById( cell_id )
    return self.gridUnitList[cell_id] or nil
end

return M