---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---

local M = class("FlowerSecondPopModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:refreshData()
    self:getData()
end

function M:refreshData()
    self.m_flowerName = self.m_params.name 
    self.m_callBack = self.m_params.callBack
    self.m_noPopHint = false
end

function M:switchNoPopHint()
    self.m_noPopHint = not self.m_noPopHint
end

function M:onEnter()

end

return M