---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
---

local M = class("FlowerSecondPopView",LikeOO.OOPopBase)
-- 花花连连看二级确认框
M.m_uiName = "FlowerFestival/FlowerSecondPop"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

function M:onEnter()
    self:bindUI()
    self:refreshUI()
end

function M:refreshUI()
    self:setTextByLanKey("tips_text", "flower_text_0012", self.m_model.m_flowerName)
    self:setObjectVisible("img_duiGou", self.m_model.m_noPopHint)
end

function M:bindUI()
    self:setTextByLanKey("common_title_text", "new_str_0005")
    self:setTextByLanKey("hint_text", "new_str_0910")
    self:setTextByLanKey("text_cancel", "new_str_0007")
    self:setTextByLanKey("text_ok", "new_str_0006")
end

function M:destroy()
    M.super.destroy(self)
end

return M
