---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wt.
--- DateTime: 2021/12/3 14:48
---
--- 职业
---@class Profression
---@field player PlayerModel
local M = class("Profression")

function M:init(player,data)
    self.player = player;
    self.config_param = data;
end

--获取参数
function M:getParam(index, default)
    return self.config_param[index] or default
end

--游戏开始时
function M:gameStart()
    
end

--更新
function M:update( dt )
    
end

--攻击时
function M:Attack( attackData )
    
end

--被攻击时
function M:BeHit( attackData )
    
end

--被攻击结束时
function M:BeHitOver()
    
end

--死亡前攻击
function M:attackBeforeDead( damage )
    return damage;
end

--释放大招开始
function M:skill3Start()
    
end

--释放大招结束
function M:skill3Over()
    
end

--游戏结束时
function M:gameOver()
    
end

return M;