---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/2/9 14:24
---


local M = class("SimulateLiftInfoControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        local isCanJumpResult = self.m_model.m_isCanJumpResult
        if isCanJumpResult then
            self.m_view:setAwardInfo()
        end
        self:updateMsg("refresh_red_point",nil,"SimulateLift.SimulateLiftMain")
        self:closeView()
    elseif msg == "explain_btn" then
        -- 提示  
        local title_id = self.m_model.m_open_id == 285 and  "simulateLeft_text_0030" or "simulateLeft_text_0068"
        local des_id = self.m_model.m_open_id == 285 and  "tid#ReopenDes_7" or "tid#SwordThym_des1"
        self:openView("Pops.CommonHelpPop", { title = Language:getTextByKey(title_id), content = Language:getTextByKey(des_id) })
    elseif msg == "btn_lotteryBtn" then
        -- 点击属性十连
        self:switchStage()
    elseif msg == "btn_goBtn" then
        -- 开始人生 -- 选择天赋
        if self.m_model:isCanSelect() then
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("simulateLeft_text_0016"), delay_close = 2})
            return
        end
        local talents = {}
        local m_talent = self.m_model.m_talent
        for _, index in pairs(self.m_model.m_selectList) do
            table.insert(talents, m_talent[index])
        end
        local params = {open_id = self.m_model.m_open_id, version = self.m_model.m_version, talents = talents}
        self.m_model:getNetData("select_talents", params, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                self.m_model:initLifeData(response.growth_log, response.role_id)
                self.m_model:switchLifeData(response)
                self:switchStage(true)
                self:updateMsg("refresh_lifeData",{response = response},"SimulateLift.SimulateLiftMain")
            end
        end, nil, nil, nil)
    elseif msg == "btn_restartBtn" then
        -- 重新开始
        self:updateMsg("again_new",{},"SimulateLift.SimulateLiftMain")
        self:closeView()
    elseif msg == "btn_inheritBtn" then
        -- 我要继承
        self:openView("SimulateLift.SimulateTalentInherit", {talents = self.m_model.m_data.talents,open_id = self.m_model.m_open_id, version = self.m_model.m_version})
    elseif msg == "btn_autoSelectBtn" then
        -- 自动播放
        if not self.m_model.m_isCanPress then
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("simulateLeft_text_0059"), delay_close = 2})
            return
        end
        self.m_model:switchAutoPlay()
        self.m_view:autoPlayLift()
        self.m_model.m_isCanPress = false
        local cdTimer = ConfigManager:getCommonValueById(668) or 1
        self:setOnceTimer(cdTimer + 1, function()
            self.m_model.m_isCanPress = true
        end)
    elseif msg == "liftBg" then
        -- 手动播放
        self.m_view:notAutoRefshList()
    elseif msg == "btn_jumpEnd" then
        -- 查看结局
        self.m_view:lockTouch()
        self.m_view:showCloud(function()
            self.m_view:unlockTouch()
            self:jumpLiftResult()
        end)
        self:setOnceTimer(8, function()
            self.m_view:unlockTouch()
        end)
    elseif msg == "refresh_lifeData" then
        -- 服务器下行的是所有的生涯日志数据，需要排除一下展示过的
        self.m_model:initLifeData(data.response.growth_log, data.response.role_id, data.response.front_index)
        self.m_view:refreshItemLiftList()
        self:updateMsg("refresh_lifeData",{response = data.response},"SimulateLift.SimulateLiftMain")
    elseif msg == "btn_shareBtn" then
        self.m_view:showShareNode()
        -- 分享
        local show_call = function()
            self.m_view:hideShereNode()
        end
        self:openView("SharePictureNoLogo", {picture_callback = show_call})
    end
end

-- 同步生涯日志
function M:detectionLifeParams(islifeOver)
    if not islifeOver then
        -- 每5次向服务器发送一次消息
        local isCanSend = self.m_model:addLifePlayCount()
        if not isCanSend then
            return
        end
    end
    -- 播放到哪个事件
    local liftData = self.m_model.liftData
    local allLiftData = table.nums(liftData)
    if allLiftData <= 0 then
        return
    end
    local lastLiftData = liftData[allLiftData]
    local contents = lastLiftData.contents
    if not contents then
        return
    end
    local allContentsCount = table.nums(contents)
    local lastContent = contents[allContentsCount]
    local serverIndex = lastContent.serverIndex
    local params = {open_id = self.m_model.m_open_id, version = self.m_model.m_version, index = serverIndex}
    self.m_model:getNetData("update_front_index", params, function(response)
        if response then
            if self:activityOverExamine(response) then
                return
            end
            local isFinish = (response.finish == 1)
            if isFinish and table.nums(response.reward) <= 0 then
                return
            end
            self.m_model:endAwardInfo(response)
            if isFinish then
                self:updateMsg("refresh_finishValue",{},"SimulateLift.SimulateLiftMain")
            end
        end
    end, nil, nil, nil)
end

function M:showNewColorEggPopWindow(eventId, newEggProgress)
    if (not eventId) or (not newEggProgress) then
        return
    end
    if eventId <=0 then
        return
    end
    local eventsData = ConfigManager:getCfgByName("reopen_events")
    local itemEventXlsxData = eventsData[eventId]
    self.m_view:popWindow( Language:getTextByKey(itemEventXlsxData.title_special), 1, newEggProgress)
end

function M:jumpLiftResult()
    self.m_model:jumpLiftResult()
    self.m_view:refreshUI()
end

function M:switchStage()
    self.m_model:switchStage()
    self.m_view:refreshUI()
end

function M:popInteractEvent(eventId, serverIndex)
    self:openView("SimulateLift.SimulateSpecialEvent", {eventId = eventId,open_id = self.m_model.m_open_id, version = self.m_model.m_version, serverIndex = serverIndex})
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    if response.update == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M