---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---

local M = class("SimulateLiftInfoModel", LikeOO.OODataBase)

local LiftStage = {
    Start = 1,
    SelectTalent = 2, 
    LiftLog = 3,
    End = 4,
}

function M:onCreate()
    M.super.onCreate(self)
    self:initData()
    self:getData()
    self.colorEggEventIdList = {}
    self.m_isCanPress = true
end

function M:addColorEggId(eventId)
    if self.colorEggEventIdList[eventId] == nil then
        self.colorEggEventIdList[eventId] = eventId
        return true
    end
    return false
end

function M:modifyData(m_data)
    table.merge(self.m_data, m_data)
    ----------------------------------------------------------- 修改部分数据
end

function M:initData()
    local isOldLift = self.m_params.isOldLift or false
    self.liftPool = {}
    self.liftData = {}
    self.m_liftStages = LiftStage
    self.m_qualityColourValues = GlobalConfig.SimulateQualityColourValues
    self.m_qualityValues = GlobalConfig.SimulateQualityValues
    self.m_stage = isOldLift and self.m_liftStages.LiftLog or self.m_liftStages.Start
    self.m_allCount = ConfigManager:getCommonValueById(662) or 3
    self.m_selectList = {}
    self.m_isAutoPlay = false
    self.m_isCanJumpResult = false
    self.m_open_id = self.m_params.open_id
    self.m_version = self.m_params.version
    self.m_talentValues = GlobalConfig.SimulateTalentValues
    -- 每5次向服务器发送一次消息
    self.lifePlayCount = 0

    local response = self.m_params.response
    self.m_talent = response.talent_options
    self:switchLifeData(response)
end

function M:switchLifeData(response)
    if (not response.talents) or (not response.growth_log) then
        return
    end
    -- 服务器下发的天赋数据
    self.m_data = response
    -- 继续打印生活日志
    if self.m_stage == self.m_liftStages.LiftLog then
        self:initLifeData( response.growth_log, response.role_id, response.front_index)
    end
end

function M:getAttributeLevel(isGameOver, attributeValue)
    local configValue = isGameOver and 673 or 650
    local attributeScope = ConfigManager:getCommonValueById(configValue) or {}
    if table.nums(attributeScope) <= 0 then
        return 5
    end
    if attributeValue < attributeScope[1] then
        return 5
    elseif (attributeValue >= attributeScope[1] ) and (attributeValue <= attributeScope[2]) then
        return 4
    elseif (attributeValue > attributeScope[2] ) and (attributeValue <= attributeScope[3]) then
        return 3
    elseif (attributeValue > attributeScope[3] ) and (attributeValue <= attributeScope[4]) then
        return 2
    elseif attributeValue > attributeScope[4] then
        return 1
    end
    return 5
end

function M:addLifePlayCount()
    self.lifePlayCount = self.lifePlayCount + 1
    if self.lifePlayCount >= 5 then
        self.lifePlayCount = 0
        return true
    end
    return false
end

-- 跳转到结果界面（有些数据要重置）
function M:jumpLiftResult()
    self.m_stage = self.m_liftStages.End
    self.m_isCanJumpResult = false
end

function M:setCanJumpResult(isCanJumpResult)
    self.m_isCanJumpResult = isCanJumpResult
end

function M:switchAutoPlay()
    self.m_isAutoPlay = (not self.m_isAutoPlay)
end

function M:endAwardInfo(data)
    local awardInfos = {}
    local serverAwardInfos = {}
    if data.reward and table.nums(data.reward) > 0 then
        local tempReward = {}
        RewardUtil:processReward(tempReward, data.reward)
        for index = 1, #tempReward do
            local tempAward = tempReward[index]
            local itemAward = RewardUtil:getProcessRewardData(tempAward)
            table.insert(awardInfos, {
                awardData = itemAward, 
                awardType = 1,
            })
            table.insert(serverAwardInfos, tempAward)
        end
    end
    if data.ending_reward and table.nums(data.ending_reward) > 0 then
        local tempReward = {}
        RewardUtil:processReward(tempReward, data.ending_reward)
        for index = 1, #tempReward do
            local tempAward = tempReward[index]
            local itemAward = RewardUtil:getProcessRewardData(tempAward)
            table.insert(awardInfos, {
                awardData = itemAward,
                awardType = 2,
            })
            table.insert(serverAwardInfos, tempAward)
        end
    end
    if data.egg_reward and table.nums(data.egg_reward) > 0 then
        local tempReward = {}
        RewardUtil:processReward(tempReward, data.egg_reward)
        for index = 1, #tempReward do
            local tempAward = tempReward[index]
            local itemAward = RewardUtil:getProcessRewardData(tempAward)
            table.insert(awardInfos, {
                awardData = itemAward,
                awardType = 3,
            })
            table.insert(serverAwardInfos, tempAward)
        end
    end
    self.endAwardInfoData = {
        awardInfos = awardInfos,
        serverAwardInfos = serverAwardInfos,
        ending_data = data.ending_data,
        finish = data.finish or 1,
        front_index = data.front_index,
        cur_score = data.cur_score,
    }
end

function M:closeAutoPlay()
    self.m_isAutoPlay = false
end

function M:switchStage()
    if self.m_stage == self.m_liftStages.End then
        return
    end
    self.m_stage = self.m_stage + 1
end

function M:initLifeData(lifeServerData, roleId, serverSaveIndex)
    serverSaveIndex = serverSaveIndex and serverSaveIndex or 1
    serverSaveIndex = serverSaveIndex == 0 and 1 or serverSaveIndex
    self.m_roleId = roleId
    local serverData = {}
    local eventsData = ConfigManager:getCfgByName("reopen_events")
    local effectsData = ConfigManager:getCfgByName("reopen_effects")
    local talentData = ConfigManager:getCfgByName("reopen_talent")
    -- 整理服务器数据
    for index = 1, table.nums(lifeServerData) do
        local isAdd = true-- index >= serverSaveIndex
        --if serverSaveIndex > 1 then
        --    -- 1为0岁，其他时候为可互动事件开头，需排除
        --    isAdd = index > serverSaveIndex
        --end
        if isAdd then
            local itemServerData = lifeServerData[index]
            -- 添加事件日志
            if itemServerData.event_effects and table.nums(itemServerData.event_effects) > 0 then
                -- 有效果
                -- 事件 武林动荡，事件event表text    xx+2effect表 description
                local eventCount = table.nums(itemServerData.event_effects)
                if eventCount > 0 then
                    for j = 1, eventCount do
                        local itemEvent = itemServerData.event_effects[j]
                        -- 通过事件，获得天赋
                        if itemEvent.talent_add then
                            local content = ""
                            local talent_add = itemEvent.talent_add
                            for talentAddIndex = 1, table.nums(talent_add) do
                                local talentAddId = talent_add[talentAddIndex]
                                local talentXlsxData = talentData[talentAddId]
                                content = content .. Language:getTextByKey("simulateLeft_text_0048", talentXlsxData.name)
                            end
                            table.insert(serverData,{
                                age = itemServerData.age,
                                attrs = itemServerData.res_attrs,
                                content = content,
                                choice = itemServerData.choice,
                                eventId = -1,
                                serverIndex = index,
                            })
                        end
                        -- 添加事件
                        if itemEvent.event_id then
                            local itemEventData = eventsData[itemEvent.event_id]
                            if itemEventData then
                                local effectXlsxData = effectsData[itemEvent.effect_id] or {}
                                local eventId = (itemEventData.type2 == 1) and itemEvent.event_id or -1
                                local content = ""
                                local heightEventId = -1
                                if (eventId > 0) then
                                    -- 互动事件
                                    local choice = itemServerData.choice    -- 选项
                                    local text_info = itemEventData.option_text[choice]
                                    local infoName1 = Language:getTextByKey(text_info) or ""
                                    local infoName2 = Language:getTextByKey(effectXlsxData.text) or ""
                                    content = Language:getTextByKey("simulateLeft_text_0046", infoName1, infoName2)
                                    content = Language:getTextByKey("simulateLeft_text_0046", Language:getTextByKey(itemEventData.tittle_text), content)
                                else
                                    -- 一般事件
                                    local infoName1 = Language:getTextByKey(itemEventData.text) or ""
                                    local infoName2 = ""
                                    if effectXlsxData and effectXlsxData.text then
                                        infoName2 = Language:getTextByKey(effectXlsxData.text) or ""
                                    end
                                    content = Language:getTextByKey("simulateLeft_text_0046", infoName1, infoName2)
                                    heightEventId = itemEvent.event_id
                                end
                                table.insert(serverData,{
                                    age = itemServerData.age,
                                    attrs = itemServerData.res_attrs,
                                    content = content,
                                    choice = itemServerData.choice,
                                    eventId = heightEventId,
                                    serverIndex = index,
                                })
                            end
                        end
                    end
                end
            else
                -- 没效果
                local itemEventData = eventsData[itemServerData.event_id]
                -- type2 == 1 是互动型事件
                if itemEventData then
                    local interactEventId = (itemEventData.type2 == 1) and itemServerData.event_id or -1
                    local content = ""
                    if (interactEventId > 0) then
                        local choice = itemServerData.choice    -- 选项
                        local text_info = itemEventData.option_text[choice]
                        content = Language:getTextByKey(text_info)
                    else
                        content = Language:getTextByKey(itemEventData.text)
                    end
                    table.insert(serverData,{
                        age = itemServerData.age,
                        attrs = itemServerData.res_attrs,
                        content = content,
                        choice = itemServerData.choice,
                        eventId = itemServerData.event_id,
                        serverIndex = index,
                        isColorEgg = itemServerData.is_new_egg,
                    })
                end
            end
            -- 复活相关
            --if itemServerData.revive then
            --    table.insert(serverData,{
            --        age = itemServerData.age,
            --        attrs = itemServerData.res_attrs,
            --        content = Language:getTextByKey("simulateLeft_text_0054"),
            --        choice = itemServerData.choice,
            --        eventId = -1,
            --        serverIndex = index,
            --    })
            --end
            -- 添加天赋日志
            if itemServerData.talent_effects and table.nums(itemServerData.talent_effects) > 0 then
                local talentCount = table.nums(itemServerData.talent_effects)
                if talentCount > 0 then
                    for j = 1, talentCount do
                        local itemTalent = itemServerData.talent_effects[j]
                        if itemTalent.effect_id then
                            -- 天赋   --发动天赋【talent表-name】，effect表-description
                            local effectXlsxData = effectsData[itemTalent.effect_id] or {}
                            if itemTalent.talent_id then
                                local itemTalentData = talentData[itemTalent.talent_id] or {}
                                local content = ""
                                local tempContent = ""
                                if itemTalent.talent_change then
                                    local talent_change = itemTalent.talent_change
                                    local talentDesList = {}
                                    for talentIndex = 1, table.nums(talent_change) do
                                        local ItemtalentChangeId = talent_change[talentIndex]
                                        local talentItemData = talentData[ItemtalentChangeId]
                                        local talentName = Language:getTextByKey("simulateLeft_text_0048", Language:getTextByKey(talentItemData.name))
                                        tempContent = tempContent .. talentName
                                        table.insert(talentDesList, talentName .."："..Language:getTextByKey(talentItemData.description))
                                    end
                                    content = Language:getTextByKey("simulateLeft_text_0047", Language:getTextByKey(itemTalentData.name), tempContent)
                                    for desListIndex = 1, table.nums(talentDesList) do
                                        local desItem = talentDesList[desListIndex]
                                        content = content .. "\n" .. desItem
                                    end
                                else
                                    content = Language:getTextByKey("simulateLeft_text_0045", Language:getTextByKey(itemTalentData.name), Language:getTextByKey(effectXlsxData.text))
                                end
                                table.insert(serverData,{
                                    age = itemServerData.age,
                                    attrs = itemServerData.res_attrs,
                                    content = content,
                                    choice = itemServerData.choice,
                                    eventId = -1,
                                    serverIndex = index,
                                })
                            end
                        end
                    end
                end
            end
        end
    end
    
    self.liftPool = {}
    -- 从0岁开始
    local ageIndex = 0
    local age = 0           
    local tempData = {}
    local eventIds = {}
    local colorEggEvent = {} 
    local maxDataCount = table.nums(serverData)
    for index = 1, maxDataCount do
        local itemData = serverData[index]
        local serverAge = itemData.age
        local serverContent = itemData.content
        local attrs = itemData.attrs
        local choice = itemData.choice
        local eventId = itemData.eventId
        local serverIndex = itemData.serverIndex
        local isColorEgg = itemData.isColorEgg or -1
        if index == 1 then
            age = serverAge
        end
        if age ~= serverAge then
            table.insert(self.liftPool, {
                age = age,
                roleId = self.m_roleId,
                contents = tempData,
                choice = choice,
                eventIds = eventIds,
                colorEggEvent = colorEggEvent,
            })
            -- 下一岁
            ageIndex = 1
            age = serverAge
            tempData = {}
            -- {该年龄的第几条，服务器内容Index，内容}, {该年龄的第几条，服务器内容Index，内容}
            table.insert(tempData, {ageIndex = ageIndex, serverIndex = serverIndex, content = serverContent, attrs = attrs})
            table.insert(eventIds, eventId)
            table.insert(colorEggEvent, isColorEgg )
        else
            ageIndex = ageIndex + 1
            -- {该年龄的第几条，服务器内容Index，内容}, {该年龄的第几条，服务器内容Index，内容}
            table.insert(tempData, {ageIndex = ageIndex, serverIndex = serverIndex, content = serverContent, attrs = attrs})
            table.insert(eventIds, eventId)
            table.insert(colorEggEvent, isColorEgg )
        end
        if (index == maxDataCount) then
            table.insert(self.liftPool, {
                age = age,
                roleId = self.m_roleId,
                contents = tempData,
                choice = choice,
                eventIds = eventIds,
                colorEggEvent = colorEggEvent,
            })
        end
    end
    for i = 1, serverSaveIndex do
        self:modeifyLiftData()
    end
end

-- 修改生涯展示信息(每次一条)   -2 结束，-1 继续下一条，>0 弹事件框(return事件id)
function M:modeifyLiftData()
    if table.nums(self.liftPool) <= 0 then
        return -2, -1
    end
    if not self.liftData then
        self.liftData = {}
    end
    local tempData = table.remove(self.liftPool,1)
    
    -- 如果是最后一条，判断是不是 互动型事件
    local lifePoolCount = table.nums(self.liftPool)
    if lifePoolCount <= 0 then
        local tempLife = tempData
        local tempContentsCount = table.nums(tempLife.contents)
        if (tempContentsCount <= 1) and (tempContentsCount > 0) then
            local eventId = tempLife.eventIds[1]
            local content = tempLife.contents[1]
            if eventId and eventId > 0 then
                local eventsData = ConfigManager:getCfgByName("reopen_events")
                local itemEventXlsxData = eventsData[eventId] or {}
                if itemEventXlsxData.type2 == 1 then
                    if (not tempLife.choice) or (tempLife.choice and tempLife.choice == 0) then
                        return eventId, content.serverIndex
                    end
                end
            end            
        end
    end
    
    local age = tempData.age
    local contents = tempData.contents
    local eventIds = tempData.eventIds
    local colorEggEvent = tempData.colorEggEvent
    local remove_index = 1
    --只有在同一年纪同时出现天赋和互动事件的时候，判断第一个事件是不是没互动过的事件，如果是则不能移除第一个事件，要去移除第二个
    if #eventIds > 1 then
        for i = 1, #eventIds do
            local eventId = eventIds[i]
            local eventsData = ConfigManager:getCfgByName("reopen_events") or {}
            local itemEventXlsxData = eventsData[eventId] or {}
            if next(itemEventXlsxData) == nil or itemEventXlsxData.type2 == nil or itemEventXlsxData.type2 ~= 1 then
                remove_index = i
                break
            end
        end
    end
    remove_index = math.min(#contents, remove_index)
    local firstContent = table.remove(contents, remove_index)
    local firstEventId = table.remove(eventIds, remove_index)
    local firstColorEggEvent = table.remove(colorEggEvent, remove_index)
    if table.nums(self.liftData) <= 0 then
        -- 第一次存
        -- 格式{年龄，角色，{该年龄的第几条，服务器内容Index，内容}, {该年龄的第几条，服务器内容Index，内容}}
        table.insert(self.liftData, {
            age = age,
            roleId = self.m_roleId,
            contents = {firstContent},
            eventIds = {firstEventId},
            colorEggEvent = {firstColorEggEvent},
        })
        if table.nums(contents) > 0 then
            table.insert(self.liftPool, 1,{age = age, contents = contents, eventIds = eventIds, colorEggEvent = colorEggEvent})
        end
        return -1,-1
    end
    -- 继续存
    local curAllCount = table.nums(self.liftData)
    local lastData = self.liftData[curAllCount]
    local curAge = lastData.age
    if (age == curAge) then
        -- 同年龄的存
        -- 格式{年龄，角色，{该年龄的第几条，服务器内容Index，内容}, {该年龄的第几条，服务器内容Index，内容}}
        table.insert(lastData.contents, firstContent)
        table.insert(lastData.eventIds, firstEventId)
        table.insert(lastData.colorEggEvent, firstColorEggEvent)
    else
        -- 不同年龄
        -- 格式{年龄，角色，{该年龄的第几条，服务器内容Index，内容}, {该年龄的第几条，服务器内容Index，内容}}
        table.insert(self.liftData, {
            age = age,
            roleId = self.m_roleId,
            contents = {firstContent},
            eventIds = {firstEventId},
            colorEggEvent = {firstColorEggEvent},
        })
    end
    if table.nums(contents) > 0 then
        -- 只取了一条，其他的塞回去
        table.insert(self.liftPool, 1,{age = age, contents = contents, eventIds = eventIds, colorEggEvent = colorEggEvent})
    end
    return -1,-1
end

-- 获取投胎时玩家的属性
function M:getSelectTalentInfo()
    local attrs = self.m_params.response.attrs
    local tempAttrs = {}
    if attrs then
        for id, value in pairs(attrs) do
            table.insert(tempAttrs,{
                id = id,
                value = value,
            })
        end
        table.sort(tempAttrs, function(itemData1,itemData2) return itemData1.id < itemData2.id end)
    end
    return tempAttrs, 0
end

-- 获取最后一条的属性，年龄，事件id，新彩蛋进度(-1表示不是彩蛋)
function M:getLastLifeInfo()
    local liftData = self.liftData
    local curAgeLifeData = liftData[table.nums(liftData)]
    if not curAgeLifeData then
        return nil, nil
    end
    local contents = curAgeLifeData.contents
    local colorEggEvent = curAgeLifeData.colorEggEvent
    local eventIds = curAgeLifeData.eventIds
    local lastLifeData = contents[table.nums(contents)]
    local attrs = lastLifeData.attrs
    local tempAttrs = {}
    for id, value in pairs(attrs) do
        table.insert(tempAttrs,{
            id = id,
            value = value,
        })
    end
    table.sort(tempAttrs, function(itemData1,itemData2) return itemData1.id < itemData2.id end)
    local lastColorEggEvent = colorEggEvent[table.nums(colorEggEvent)]
    local eventId = lastColorEggEvent > 0 and eventIds[table.nums(eventIds)] or -1
    return tempAttrs, curAgeLifeData.age, eventId, lastColorEggEvent
end

function M:isCanSelect()
    return (table.nums(self.m_selectList) < self.m_allCount)
end

function M:modifySelectCount(index)
    if self.m_selectList[index] ~= nil then
        self.m_selectList[index] = nil
    else
        if not self:isCanSelect() then
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("simulateLeft_text_0014"), delay_close = 2})
            return false
        end
        self.m_selectList[index] = index
    end
    return (self.m_selectList[index] ~= nil)
end

function M:onEnter()

end

return M