---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/10 15:36
---

local M = class("FulwinArenaInvitePopView", LikeOO.OOPopBase)

M.m_uiName = "FulwinArena/FulwinArenaInvitePop"
M.m_size_type = 2
function M:onEnter()
    self:setTextByLanKey("text_title", "fylt_str_0012")
    
    self.m_selectItemObj = nil
    self:refreshUI()
    self:bindUI()
end

function M:refreshUI()
    self:setObjectVisible("img_justice", self.m_model.m_isJustice)
    self:setObjectVisible("img_one", self.m_model.m_selectPeopleCount == 1)
    self:setObjectVisible("img_three", self.m_model.m_selectPeopleCount == 3)
    local playerInfoNode1 = self:findGameObject("playerInfoNode1")
    self:setPlayerNode(playerInfoNode1, true)
    
    local isExistRival = self.m_model.m_rivalData ~= nil
    if isExistRival then
        local playerInfoNode2 = self:findGameObject("playerInfoNode2")
        self:setPlayerNode(playerInfoNode2, false)
    end
    self:setObjectVisible("playerInfoNode2", isExistRival)
    self:setObjectVisible("addPlayerNode", (not isExistRival))
end

function M:setPlayerNode(playerNode, isCurPlayer)
    if IsNull(playerNode) then
        return
    end
    local luaBehaviour = UIUtil.findLuaBehaviour(playerNode)
    if not luaBehaviour then
        return
    end
    local head_node = luaBehaviour:FindGameObject("head_node")
    local userName = nil
    local zfljArenaRank = 0
    local txywArenaRank = 0
    if isCurPlayer then
        local user_data = UserDataManager.user_data.user_status
        GameUtil:setUserAvatar(head_node, user_data, false)
        userName = UserDataManager.user_data:getUserStatusDataByKey("name")
        zfljArenaRank = self.m_model.m_myZfljRank
        txywArenaRank = self.m_model.m_myTxywRank
    else
        local userInfo = self.m_model.m_rivalData
        local user = userInfo.user
        GameUtil:setUserAvatar(head_node, user, false)
        userName = user.name
        zfljArenaRank = userInfo.arena_rank
        txywArenaRank = userInfo.high_arena_rank
    end
    LuaBehaviourUtil.setText(luaBehaviour, "text_name", userName)
    zfljArenaRank = zfljArenaRank > 0 and zfljArenaRank or Language:getTextByKey("fylt_str_0039")
    --LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_arena", "fylt_str_0035", zfljArenaRank)
    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_arena", "")
    txywArenaRank = txywArenaRank <= 0 and 999999 or txywArenaRank
    local cfg = ConfigManager:getHighArenaCfgByRank(txywArenaRank)
    --txywArenaRank = txywArenaRank >= 0 and txywArenaRank or Language:getTextByKey("fylt_str_0037")
    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_grading", "fylt_str_0036", Language:getTextByKey(cfg.division_name ))
end

function M:bindUI()
    self:setTextByLanKey("common_title_text", "fylt_str_0017")
    self:setTextByLanKey("text_team", "fylt_str_0013")
    self:setTextByLanKey("text_teamIndex1", "fylt_str_0014")
    self:setTextByLanKey("text_teamIndex2", "fylt_str_0015")
    self:setTextByLanKey("text_justice", "fylt_str_0016")
end

return M














