---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:24
---


local M = class("FlowerGiveRankControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_logBtn" then
        
    elseif msg == "btn_rankBtn" then
        
    elseif msg == "close_img" then
        self:closeView()
    elseif msg == "refresh_flowerEvent" then
        self.m_model:getNetData("self_flower_rank", {vsn = self.m_model.m_version, start = 1, stop = 30}, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                self.m_model:refreshData(response)
                self.m_view:refreshUI()
            end
        end, nil, nil, nil)
    end
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    if response.update == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M