---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---

local M = class("FlowerGiveRankModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self.m_version = self.m_params.version
    self.m_selectIndex = 0
    self:getData("self_flower_rank", {vsn = self.m_version, start = 1, stop = 30})
end

function M:modifySelectIndex(index)
    self.m_selectIndex = index
end

function M:refreshData(data)
    self.m_data = data
    self.m_rankData = self.m_data.ranks
    self.m_logs = self.m_data.logs
end

function M:onEnter()
    self:refreshData(self.m_data)
end

return M