---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
---

local M = class("FlowerGiveRankView",LikeOO.OOPopBase)
-- 花花赠送榜
M.m_uiName = "FlowerFestival/FlowerGiveRank"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

local __TAB_BTN_NODE = {
    {btn_key = "tog_1", text_key = "tog_1_text", show_text = "flower_text_0001" }, 
    {btn_key = "tog_2", text_key = "tog_2_text", show_text = "flower_text_0002" }, 
}

function M:onEnter()
    self.m_toggle_btns = {}
    for k,v in pairs(__TAB_BTN_NODE) do
        self:setTextByLanKey(v.text_key, v.show_text)
        local tog_btn = self:findToggle(v.btn_key)
        self.m_toggle_btns[k] = tog_btn
        UIUtil.addToggleListener(tog_btn, function(is_on) self:switchTabUpdate(is_on, k) end,nil,self.m_uiName)
        if k == 1 then
            tog_btn.isOn = true
        end
    end

    self:bindUI()
    --self:refreshUI()
end

function M:switchTabUpdate(is_on, index)
    local selectIndex = self.m_model.m_selectIndex
    if selectIndex == index then
        return
    end
    if index <= 0 then
        return
    end
    self.m_model:modifySelectIndex(index)
    selectIndex = self.m_model.m_selectIndex
    local isGiveRank = 1 == selectIndex
    self:setObjectVisible("giveNode", isGiveRank)
    self:setObjectVisible("logNode", (not isGiveRank))
    self:setTextByLanKey("common_title_text", isGiveRank and "flower_text_0007" or "flower_text_0008" )
    if isGiveRank then
        local isShowList = table.nums(self.m_model.m_rankData) > 0
        self:setObjectVisible("giveLoopscroll", isShowList)
        self:setObjectVisible("CommonTipsNode", (not isShowList))
        if isShowList then
            self:createGiveLoopScroll()
        end
    else
        local isShowList = table.nums(self.m_model.m_logs) > 0
        self:setObjectVisible("logLoopscroll", isShowList)
        self:setObjectVisible("CommonTipsNode", (not isShowList))
        if isShowList then
            self:createLogLoopScroll()
        end
    end

    for k,v in pairs(__TAB_BTN_NODE) do
        if selectIndex == k then
            self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_25)
        else
            self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_24)
        end
    end
end

function M:refreshUI()
    self:switchTabUpdate(nil, self.m_model.m_selectIndex)
end

function M:bindUI()
    self:setTextByLanKey("text_topRankName", "flower_text_0062")
    self:setTextByLanKey("text_topPlayerName", "flower_text_0063")
    self:setTextByLanKey("text_topItemName", "flower_text_0064")
    self:setTextByLanKey("common_no_have_text", "flower_text_0066")
end

function M:createGiveLoopScroll()
    local data = self.m_model.m_rankData
    if self.m_giveScroll_view == nil then
        local loopscroll = self:findGameObject("giveLoopscroll")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self:update_GiveItem(cell_obj, cell_data, index)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name) -- 点击回调
                if click_name == "btn_getBtn" then
                  -- 回赠按钮
                    audio:SendEvtUI("UI_Popup_N1")
                    self.m_control:openView("FlowerFestival.FlowerGivePop", {playerId = cell_data.user.uid, existFlowerCount = cell_data.score,tips_num = 1})
                end
            end
        }
        self.m_giveScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_giveScroll_view:reloadData(data)
    end
end

function M:update_LogItem(cell_obj, cell_data, index)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local userInfo = cell_data.user
        local head_node = luaBehaviour:FindGameObject("head_node")
        GameUtil:setUserAvatar(head_node, userInfo,false,false,false)
        local title_id = userInfo.title
        if title_id and title_id ~= 0 then
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "head_title_img1", true)
            local title_obj = luaBehaviour:FindGameObject("head_title_img1")
            local name_img = luaBehaviour:FindImage("head_title_img1")
            local cfg = UserDataManager.title_data:getTitleConfigById(title_id)
            if cfg and name_img and title_obj then
                name_img.enabled = true
                GameUtil:setTextureLoadTitleLanImgText(name_img, cfg.icon) -- 设置称号图片
                name_img:SetNativeSize()
                UIUtil.setScale(title_obj.transform, 0.6)
            end
            UIUtil.destroyAllChild(name_img.gameObject.transform)
            if cfg.title_effect and cfg.title_effect ~= "" then
                name_img.enabled = false
                ResourceUtil:GetUIEffectItem("Headtitle/" .. cfg.title_effect, name_img.gameObject)
            end
        else
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "head_title_img1", false)
        end
        LuaBehaviourUtil.setText(luaBehaviour, "text_name", userInfo.name )
        local itemUnit = RewardUtil:getProcessRewardData(cell_data.gifts[1])
        local logFormat = Language:getTextByKey("flower_text_0003", itemUnit.data_num, itemUnit.name)
        LuaBehaviourUtil.setText(luaBehaviour, "text_giveLog", logFormat )
        local sendTimer = TimeUtil.gmTime(cell_data.time)
        local timerFormat = Language:getTextByKey("flower_text_0061", sendTimer.year, sendTimer.month, sendTimer.day,
                sendTimer.hour, sendTimer.min, sendTimer.sec)
        LuaBehaviourUtil.setText(luaBehaviour, "text_timer", timerFormat )
    end
end

function M:createLogLoopScroll()
    local data = self.m_model.m_logs
    if self.m_logScroll_view == nil then
        local loopscroll = self:findGameObject("logLoopscroll")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self:update_LogItem(cell_obj, cell_data, index)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name) -- 点击回调
               
            end
        }
        self.m_logScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_logScroll_view:reloadData(data)
    end
end

function M:update_GiveItem(cell_obj, cell_data, index)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local curRank = cell_data.rank
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "rank_bg", curRank > 3)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_rank1", curRank == 1)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_rank2", curRank == 2)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_rank3", curRank == 3)
        LuaBehaviourUtil.setText(luaBehaviour, "text_rank", curRank )
        local userInfo = cell_data.user
        LuaBehaviourUtil.setText(luaBehaviour, "text_name", userInfo.name )
        LuaBehaviourUtil.setText(luaBehaviour, "text_flowerCount", cell_data.score )
        local head_node = luaBehaviour:FindGameObject("head_node")
        GameUtil:setUserAvatar(head_node, userInfo,false,false,false)
        local title_id = userInfo.title
        if title_id and title_id ~= 0 then
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "head_title_img1", true)
            local title_obj = luaBehaviour:FindGameObject("head_title_img1")
            local name_img = luaBehaviour:FindImage("head_title_img1")
            local cfg = UserDataManager.title_data:getTitleConfigById(title_id)
            if cfg and name_img and title_obj then
                name_img.enabled = true
                GameUtil:setTextureLoadTitleLanImgText(name_img, cfg.icon) -- 设置称号图片
                name_img:SetNativeSize()
                UIUtil.setScale(title_obj.transform, 0.6)
            end
            UIUtil.destroyAllChild(name_img.gameObject.transform)
            if cfg.title_effect and cfg.title_effect ~= "" then
                name_img.enabled = false
                ResourceUtil:GetUIEffectItem("Headtitle/" .. cfg.title_effect, name_img.gameObject)
            end
        else
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "head_title_img1", false)
        end
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_getBtnText", "flower_text_0004" )
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M
