---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/8 16:17
---
local M = class("FlowerMainModel", LikeOO.OODataBase)
---
local __TAB_BTN_NODE = {            --- 顺序不能乱
    {open_id = 290,redDotIndex = 1, isRechargeAct = false, lua_name = "FlowerFestival.FlowerLinkGame"}, -- 曲水流觞 连连看
    {open_id = 291,redDotIndex = 2, isRechargeAct = false, lua_name = "FlowerFestival.FlowerAllRank"}, -- 花团锦簇
    {open_id = 292,redDotIndex = 3, isRechargeAct = true, lua_name = "FlowerFestival.FlowerGiftBag"}, -- 花朝集市
    {open_id = 293,redDotIndex = 4, isRechargeAct = false, lua_name = "FlowerFestival.FlowerExchange"}, -- 花朝兑换
}

function M:onCreate()
    M.super.onCreate(self)
    self.m_tabConfig = __TAB_BTN_NODE
    self.m_parentOpenId = self.m_params.open_id
    self:getData("flower_festival")
end

function M:onEnter()
    self.m_version = self.m_data.vsn
end

function M:switchData(tempTable)
    table.merge(self.m_data, tempTable)
end

-- 每日刷新
function M:everyDayRefresh()
    --self:refreshActivityDatas()
end

-- 活动是否开启中
function M:isOpenActiveByOpenId(openId, isRechargeAct, isShowEnter)
    local activityData = nil
    if isRechargeAct then
        activityData = UserDataManager:getActivesRechargeDataByOpenId(openId)
    else
        activityData = UserDataManager:getActivesDataByOpenId(openId)
    end
    if not activityData then
        return false
    end
    --local startTimer = activityData.start_ts
    if isShowEnter then
        local endTimer = activityData.end_ts
        local curTimer = UserDataManager:getServerTime()
        return curTimer <= endTimer
    else
        local endTimer = activityData.show_start_ts
        local curTimer = UserDataManager:getServerTime()
        return curTimer <= endTimer
    end
end

function M:getXlsxActivityByOpenId(openId, isRechargeActivity)
    local xlsxName = isRechargeActivity and "active_recharge" or "active"
    local active = ConfigManager:getCfgByName(xlsxName)
    for _,itemData in pairs(active) do
        if (itemData.version == self.m_version) and (openId == itemData.open_id) then
            return itemData
        end
    end
    return nil
end

return M