---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/8 16:18
---

local M = class("FlowerMainView",LikeOO.OOPopBase)

M.m_uiName = "FlowerFestival/FlowerMain"  -- prefab name
M.m_size_type = 1
M.m_iphoneXAdapter = true

function M:onEnter()
    self.tab_Node = self.m_model.m_tabConfig
    self:bindUI()
    self:refreshUI()
    RedPointUtil:saveLocalRedPointFreshTime("flower_mainRedDot")
end

function M:refreshUI()
    self:refreshActivityTimer()
    self:refreshAllRedDot()
end

function M:refreshActivityTimer()
    local activityData = UserDataManager:getActivesDataByOpenId(self.m_model.m_parentOpenId)
    local startTimer =activityData.start_ts
    local endTimer = activityData.end_ts
    local starT = TimeUtil.gmTime(startTimer)
    local endT = TimeUtil.gmTime(endTimer)
    local timerFormat = Language:getTextByKey("castingSword_str_0012", starT.year, starT.month, starT.day,
            endT.year, endT.month, endT.day)
    self:setTextByLanKey("text_timer", "flower_text_0052",timerFormat)
end

function M:bindUI()           
    for _, itemData in pairs(self.m_model.m_tabConfig) do
        local index = itemData.redDotIndex
        local activeXlsxData = self.m_model:getXlsxActivityByOpenId(itemData.open_id, itemData.isRechargeAct)
        self:setTextByLanKey("text_tabBtnText"..index, activeXlsxData.name)
    end
    local mainActiveData = self.m_model:getXlsxActivityByOpenId(self.m_model.m_parentOpenId, false)
    self:setTextByLanKey("close_title_text", mainActiveData.name)
end

function M:refreshAllRedDot()
    for _, itemData in pairs(self.m_model.m_tabConfig) do
        local red_point_img = self:findGameObject("red_point"..itemData.redDotIndex)
        if red_point_img then
            local openId = itemData.open_id
            local isShowRedDot = false
            if openId == 290 then
                local taskDatas = self.m_model.m_data.quests
                if taskDatas then
                    for _, taskItemData in pairs(taskDatas) do
                        if taskItemData.status == 1 then
                            isShowRedDot = true
                            break
                        end
                    end
                end
                if not isShowRedDot then
                    local login_data = self.m_model.m_data.login_data
                    if login_data then
                        isShowRedDot = login_data <= 0
                    end
                end
            elseif openId == 291 then
            elseif openId == 292 then
                local common_giftList = UserDataManager:getRedDotByKey("common_gift")
                if type(common_giftList) ~= "number" then
                    for _, giftData in pairs(common_giftList) do
                        if giftData[1] == openId and giftData[2] == self.m_model.m_version then
                            isShowRedDot = true
                        end
                    end
                end
            elseif openId == 293 then
                isShowRedDot = RedPointUtil:localRedPointJudge("flower_mainRedDot")
            end
            red_point_img:SetActive(isShowRedDot)
        end
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M