---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/28 20:20
---

local M = class("ChinaMobileActivityPopView", LikeOO.OOPopBase)

M.m_uiName = "GiftBag/ChinaMobileActivityPop"
M.m_size_type = 2
-- 支付宝红包活动介绍
function M:onEnter()
end

function M:refreshUI()
end


return M