---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 16:45
---

local M = class("FlowerLinkGameControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "click_lineGameBtnEvent" then
        self:clickLineGameBtn(data.index)
    elseif msg == "got_awardEvent" then
        self:gotLineAwardByAwardId(data.rewardId)
    elseif msg == "everyDay_sign" then
        -- 签到
        self:everyDaySign(data.day)
    elseif msg == "item_buyEvent" then
        -- 购买
        self:buyEvent(data.day)
    elseif msg == "item_taskEvent" then
        -- 任务
        self:overTaskEvent(data.quest_id)
    elseif msg == "jump_Event" then
        QuickOpenFuncUtil:openFunc(data.jumpId)
        self:closeView("FlowerFestival.FlowerMain")
        self:closeView()
    elseif msg == "explain_btn" then
        -- 提示  
        local openId = self.m_model.m_openId
        local lianliankanData = ConfigManager:getCfgByName("lianliankan")
        local openIdData = lianliankanData[openId]
        local versionData = openIdData[self.m_model.m_version]
        local mainActiveData = self.m_model:getXlsxActivityByOpenId(openId, false)
        self:openView("Pops.CommonHelpPop", { title = Language:getTextByKey(mainActiveData.name), content = Language:getTextByKey(versionData.flower_des) })
    elseif msg == "btn_flowerItemBtn1" then
        local flowerItemDatas = self.m_model.m_flowerItemDatas
        local itemUnit1 = RewardUtil:getProcessRewardData(flowerItemDatas[1])
        GameUtil:lookInfoTips(self, {click_transform = data.transform, msg = itemUnit1.story})
    elseif msg == "btn_flowerItemBtn2" then
        local flowerItemDatas = self.m_model.m_flowerItemDatas
        local itemUnit1 = RewardUtil:getProcessRewardData(flowerItemDatas[2])
        GameUtil:lookInfoTips(self, {click_transform = data.transform, msg = itemUnit1.story})
    elseif msg == "btn_flowerItemBtn3" then
        local flowerItemDatas = self.m_model.m_flowerItemDatas
        local itemUnit1 = RewardUtil:getProcessRewardData(flowerItemDatas[3])
        GameUtil:lookInfoTips(self, {click_transform = data.transform, msg = itemUnit1.story})
    elseif msg == "everyDayRefreshEvent" then
        self.m_model:getNetData("common_quest_index",{open_id = self.m_model.m_openId, vsn = self.m_model.m_version}, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                self.m_model:switchData(response)
                self.m_model:refreshDatas()
                self.m_view:refreshUI()
            end
        end, nil, nil, nil)
    end
end

function M:overTaskEvent(quest_id)
    local params = {open_id = self.m_model.m_openId, vsn = self.m_model.m_version, quest_id = quest_id}
    self.m_model:getNetData("common_quest_recv_task", params, function(response)
        if response then
            if self:activityOverExamine(response) then
                return
            end
            RewardUtil:rewardTipsByData(response.reward)
            self:updateMsg("everyDayRefreshEvent", nil)
        end
    end, nil, nil, nil)
end

function M:buyEvent(day)
    local params = {open_id = self.m_model.m_openId, vsn = self.m_model.m_version, day = day}
    self.m_model:getNetData("common_quest_buy", params, function(response)
        if response then
            if self:activityOverExamine(response) then
                return
            end
            RewardUtil:rewardTipsByData(response.reward)
            self.m_model:switchTaskData({shop_data = response.shop_data})
            self.m_model:refreshTaskData()
            self.m_view:refreshTaskList()
        end
    end, nil, nil, nil)
end

function M:everyDaySign(day)
    local params = {open_id = self.m_model.m_openId, vsn = self.m_model.m_version, day = day}
    self.m_model:getNetData("common_quest_recv_login", params, function(response)
        if response then
            if self:activityOverExamine(response) then
                return
            end
            RewardUtil:rewardTipsByData(response.reward)
            self.m_model:switchTaskData({login_data = response.login_data})
            self.m_model:refreshTaskData()
            self.m_view:refreshTaskList()
        end
    end, nil, nil, nil)
end

function M:gotLineAwardByAwardId(index)
    if not self.m_model.m_awardLockData[index] then
        return
    end
    if self.m_model.m_awardLockData[index].isGot then
        return
    end
    local params = {open_id = self.m_model.m_openId, vsn = self.m_model.m_version, reward_id = index}
    self.m_model:getNetData("common_quest_recv", params, function(response)
        if response then
            audio:SendEvtUI("UI_Tab_N7")
            if self:activityOverExamine(response) then
                return
            end
            RewardUtil:rewardTipsByData(response.reward)
            self.m_model:setUnLockData(response.unlock)
            self.m_model:setLockAward(response.recv)
            self.m_view:refreshLeftNode()
        end
    end, nil, nil, nil)
end

function M:clickLineGameBtn(index)
    local isCanUnlock = self.m_model:isCanActiveFlowerByGridId(index)
    if isCanUnlock then
        -- 可解锁，刷新
        local isPopWindow = RedPointUtil:localRedPointJudge("flower_lineGame_everyDayPopHint")
        if isPopWindow then
            -- 弹出二级确认框
            local gridInfoData = self.m_model.m_unLockData[index]
            local itemXlsxData = gridInfoData.xlsxData.item
            local awardUnit = RewardUtil:getProcessRewardData(itemXlsxData[1])
            self:openView("FlowerFestival.FlowerSecondPop", {name = awardUnit.name, callBack = function()
                self:activeGridByGridId(index)
            end})
        else
            -- 不弹窗，直接激活格子
            self:activeGridByGridId(index)
        end
    else
        -- 不可解锁， 提示
        local gridInfoData = self.m_model.m_unLockData[index]
        local itemXlsxData = gridInfoData.xlsxData.item
        local awardUnit = RewardUtil:getProcessRewardData(itemXlsxData[1])
        GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("flower_text_0011", awardUnit.name), delay_close = 2})
    end
end

function M:activeGridByGridId(gridId)
    local params = {open_id = self.m_model.m_openId, vsn = self.m_model.m_version, map_id = gridId}
    self.m_model:getNetData("common_quest_unlock", params, function(response)
        if response then
            audio:SendEvtUI("UI_DJGZi")
            if self:activityOverExamine(response) then
                return
            end
            self.m_model:setUnLockData(response.unlock)
            self.m_model:setLockAward(response.recv)
            self.m_view:refreshLeftNode()
        end
    end, nil, nil, nil)
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView("PetardActivity.PetardMain")
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M
