---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 16:09
---

local M = class("FlowerLinkGameModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self.m_version = self.m_params.version or 1
    self.m_openId = self.m_params.openId or 290
    self:getData("common_quest_index",{open_id = self.m_openId, vsn = self.m_version})
    self.m_flowerItemDatas = {
        {103,5399,1},
        {103,5400,1},
        {103,5401,1},
    }
    self.m_showEftList = {}
end

function M:setShowEftListData(index)
    self.m_showEftList[index] = index
end

function M:refreshLeftData(m_data)
    self:setUnLockData(m_data.unlock)
    self:setLockAward(m_data.recv)
end

function M:switchData(tempTable)
    table.merge(self.m_data, tempTable)
end

function M:onEnter()
    self:refreshLeftData(self.m_data)
    self:refreshTaskData()
end

function M:refreshDatas()
    self:refreshLeftData(self.m_data)
    self:refreshTaskData()
end

-- 活动开启了几天
function M:getActityOpenDayCount()
    local serverTimer = UserDataManager:getServerTime()
    local activityData = UserDataManager:getActivesDataByOpenId(self.m_openId)
    local startTimer = activityData.start_ts
    local openDayCount = GameUtil:NumberOfDaysIntervalDay(startTimer,serverTimer)
    openDayCount = math.floor(openDayCount)
    openDayCount = openDayCount <= 0 and 1 or openDayCount
    return openDayCount
end

function M:getXlsxActivityByOpenId(openId, isRechargeActivity)
    local xlsxName = isRechargeActivity and "active_recharge" or "active"
    local active = ConfigManager:getCfgByName(xlsxName)
    for _,itemData in pairs(active) do
        if (itemData.version == self.m_version) and (openId == itemData.open_id) then
            return itemData
        end
    end
    return nil
end

function M:switchTaskData(tempTable)
    table.merge(self.m_data, tempTable)
end

function M:refreshTaskData()
    local m_data = self.m_data
    local tempShopData = {}
    for strDay, data in pairs(m_data.shop_data) do
        local serverDay = tonumber(strDay)
        tempShopData[serverDay] = data
    end
   
    local tempTaskData = {}
    for strId, itemData in pairs(m_data.quests) do
        local taskId = tonumber(strId)
        tempTaskData[taskId] = itemData
    end
    
    self.taskData = {}
    -- type 1每日签到，2购买，3任务
    local loginXlsxData = ConfigManager:getCfgByName("lianliankan_quest_login")
    local openIdLoginXlsxData = loginXlsxData[self.m_openId] or {}
    local versionLoginXlsxData = openIdLoginXlsxData[self.m_version] or {}
    local openDay = self:getActityOpenDayCount()
    if versionLoginXlsxData[openDay] then
        local dayXlsxData = versionLoginXlsxData[openDay]
        local isGot = m_data.login_data > 0
        table.insert(self.taskData, {
            taskType = 1,
            itemXlsxData = dayXlsxData,
            isGot = isGot,
            day = openDay,
            sortIndex = isGot and -10 or 10
        })
    end
    local shopXlsxData = ConfigManager:getCfgByName("lianliankan_quest_shop")
    local openIdShopXlsxData = shopXlsxData[self.m_openId] or {}
    local versionShopXlsxData = openIdShopXlsxData[self.m_version] or {}
    if versionShopXlsxData[openDay] then
        local dayXlsxData = versionShopXlsxData[openDay]
        local buyCount = tempShopData[openDay] or 0
        table.insert(self.taskData, {
            taskType = 2,
            itemXlsxData = dayXlsxData,
            buyCount = buyCount,
            day = openDay,
            sortIndex = (buyCount >= dayXlsxData.time) and -5 or 5
        })
    end
    local questXlsxData = ConfigManager:getCfgByName("lianliankan_quest")
    local openIdQuestXlsxData = questXlsxData[self.m_openId] or {}
    local versionQuestXlsxData = openIdQuestXlsxData[self.m_version] or {}
    for id, itemData in pairs(versionQuestXlsxData) do
        if itemData.day == openDay then
            local serverTaskData = tempTaskData[id] or {}
            local curProgress = serverTaskData.value or 0
            local status =  serverTaskData.status or 0
            local sortIndex = 0
            if status == 1 then
                sortIndex = 1
            elseif status == 2 then
                sortIndex = -1
            end
            table.insert(self.taskData, {
                taskType = 3,
                itemXlsxData = itemData,
                id = id,
                curProgress = curProgress,
                status = status,
                sortIndex = sortIndex,
            })
        end
    end
    table.sort(self.taskData, function(itemData1, itemData2)
        if itemData1.sortIndex ~= itemData2.sortIndex then
            return itemData1.sortIndex > itemData2.sortIndex
        end
    end)
end

function M:isCanActiveFlowerByGridId(gridId)
    local gridInfoData = self.m_unLockData[gridId]
    local item = gridInfoData.xlsxData.item
    if item and item[1] then
        local itemXlsxData = item[1] or {}
        local itemInfo = RewardUtil:getProcessRewardData(itemXlsxData)
        return itemInfo.user_num >= itemInfo.data_num
    end
    return false
end

-- 检查可解锁奖励数据
function M:examineAwardkDataByAwardId(awardId)
    if not awardId then
        return false
    end
    local awardXlsxData = ConfigManager:getCfgByName("lianliankan_reward")
    local openIdXlsxData = awardXlsxData[self.m_openId] or {}
    local versionXlsxData = openIdXlsxData[self.m_version] or {}
    local itemData = versionXlsxData[awardId]
    local open_condition = itemData.open_condition
    for index = 1, table.nums(open_condition) do
        local gridId = open_condition[index]
        if not self.m_unLockData[gridId].isGot then
            return false
        end
    end
    return true
end

function M:setLockAward(recv)
    local tempList = {}
    local awardXlsxData = ConfigManager:getCfgByName("lianliankan_reward")
    local openIdXlsxData = awardXlsxData[self.m_openId] or {}
    local versionXlsxData = openIdXlsxData[self.m_version] or {}
    for strId, itemXlsxData in pairs(versionXlsxData) do
        local id = tonumber(strId)
        tempList[id] = {
            id = id,
            xlsxData = itemXlsxData.reward[1],
            isGot = false,
        }
    end
    for index = 1, table.nums(recv) do
        local id = recv[index]
        if tempList[id] ~= nil then
            tempList[id].isGot = true
        end
    end
    self.m_awardLockData = tempList
end

function M:setUnLockData(unlocks)
    local tempList = {}
    for index = 1, table.nums(unlocks) do
        local gridId = unlocks[index]
        tempList[gridId] = gridId
    end
    local mapXlsxData = ConfigManager:getCfgByName("lianliankan_map")
    local openIdXlsxData = mapXlsxData[self.m_openId] or {}
    local versionXlsxData = openIdXlsxData[self.m_version] or {}
    local returnList = {}
    for index = 1, 16 do
        returnList[index] = {
            index = index,
            isGot = tempList[index] ~= nil,
            xlsxData = versionXlsxData[index],
        }
    end
    self.m_unLockData = returnList
end

return M