---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 15:53
---

local M = class("FlowerLinkGameView",LikeOO.OOPopBase)
-- 花花节 连连看
M.m_uiName = "FlowerFestival/FlowerLinkGame"  -- prefab name
M.m_size_type = 1
M.m_iphoneXAdapter = true

function M:onEnter()
    EventDispatcher:registerEvent(GlobalConfig.EVENT_KEYS.EVERY_DAY_EVENT, {self, self.everyDayRefreshEvent})
    self:bindUI()
    self:refreshUI()
    self.m_attr_node = GameUtil:commonAttrNode(self.m_control, {item_id = 5397})
end

function M:everyDayRefreshEvent()
    self:updateMsg("everyDayRefreshEvent", nil)
end

function M:refreshUI()
    self:refreshLeftNode()
    self:refreshTaskList()
end

function M:refreshLeftNode()
    self:refreshLineGameNode()
    self:refreshTopItemInfo()
    self:refreshLineGameAwardInfo()
end

function M:refreshLineGameAwardInfo()
    local allLineGameAwardData = self.m_model.m_awardLockData
    for _, itemData in pairs(allLineGameAwardData) do
        local index = itemData.id
        local awardXlsxData = itemData.xlsxData
        local isGot = itemData.isGot
        local awardNode = self:findGameObject("awardNode"..index)
        local luaBehaviour = UIUtil.findLuaBehaviour(awardNode)
        if luaBehaviour then
            local awardUnit = RewardUtil:getProcessRewardData(awardXlsxData)
            local awardItemNode = luaBehaviour:FindGameObject("ItemNode")
            GameUtil:updateItemElementByData(awardItemNode, awardUnit, true, false, function ()
                if isGot then
                   return 
                end
                local isCanGot = self.m_model:examineAwardkDataByAwardId(index)
                if isCanGot then
                    self:updateMsg("got_awardEvent", {rewardId = index})
                else
                    GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("flower_text_0013"), delay_close = 2})
                end
            end)
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "duigou_img", isGot)
            if isGot then
                LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_duigou", isGot)
            else
                local isCanGot = self.m_model:examineAwardkDataByAwardId(index)
                LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_duigou", (not isCanGot))
                if isCanGot then
                    self:showItemAwardEft(luaBehaviour, index)
                end
            end
            local btn_duigou = luaBehaviour:FindGameObject("btn_duigou")
            UIUtil.setButtonClick(
                    btn_duigou.transform,
                    function()
                        for _, itemBtnData in pairs(self.m_model.m_awardLockData) do
                            if itemBtnData.id == index then
                                if not itemBtnData.isGot then
                                    GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("flower_text_0013"), delay_close = 2})
                                end
                            end
                        end
                    end
            )
        end
    end
end

function M:showItemAwardEft(luaBehaviour, index)
    if self.m_model.m_showEftList[index] then
        return
    end
    self.m_model:setShowEftListData(index)
    LuaBehaviourUtil.setObjectVisible(luaBehaviour, "eft_showAward", true)
    self.m_control:setOnceTimer(1,function()
        local eftNode = luaBehaviour:FindGameObject("eft_showAward")
        if not IsNull(eftNode) then
            eftNode:SetActive(false)
        end
    end)
end

function M:refreshTopItemInfo()
    local flowerItemDatas = self.m_model.m_flowerItemDatas
    local itemUnit1 = RewardUtil:getProcessRewardData(flowerItemDatas[1])
    self:setText("text_flowerCount1", itemUnit1.user_num)
    local itemUnit2 = RewardUtil:getProcessRewardData(flowerItemDatas[2])
    self:setText("text_flowerCount2", itemUnit2.user_num)
    local itemUnit3 = RewardUtil:getProcessRewardData(flowerItemDatas[3])
    self:setText("text_flowerCount3", itemUnit3.user_num)
end

function M:refreshLineGameNode()
    -- 花的图片
    local flowerDatas = self.m_model.m_unLockData
    for _, itemData in pairs(flowerDatas) do
        local gridId = itemData.index
        local isGot = itemData.isGot
        local activeType = isGot and 2 or 1
        local xlsxData = itemData.xlsxData
        local itemXlsxData = xlsxData.item[1]
        local itemUnit = RewardUtil:getProcessRewardData(itemXlsxData)
        local flowerLineNode = self:findGameObject("flowerLineNode"..gridId)
        local luaBehaviour = UIUtil.findLuaBehaviour(flowerLineNode)
        local img_flower = luaBehaviour:FindImage("img_flower")
        GameUtil:updateResourcesImg(img_flower, "Texture/flowerFestival/".."flower_"..activeType.."_"..itemUnit.data_id)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "Img_showLine", isGot)
    end
end

function M:refreshTaskList()
    -- 任务列表
    local data = self.m_model.taskData
    if self.m_taskScroll_view == nil then
        local loopscroll = self:findGameObject("task_loopscroll")
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshTaskItem(cell_obj, cell_data,false)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_canGotBtn" then
                    local taskType = cell_data.taskType
                    if taskType == 1 then
                        -- 每日登陆
                        self:updateMsg("everyDay_sign", {day = cell_data.day})
                    elseif taskType == 2 then
                        -- 每日限购
                        self:updateMsg("item_buyEvent", {day = cell_data.day})
                    elseif taskType == 3 then
                        -- 任务
                        if cell_data.status == 0 then
                            self:updateMsg("jump_Event", {jumpId = cell_data.itemXlsxData.go_type})
                        elseif cell_data.status == 1 then
                            self:updateMsg("item_taskEvent", {quest_id = cell_data.id})
                        end
                    end
                end
            end
        }
        self.m_taskScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_taskScroll_view:reloadData(data, true)
    end
end

function M:refreshTaskItem(cell_obj, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    local transform = cell_obj.transform
    if luaBehaviour then
        local taskType = cell_data.taskType
        local itemXlsxData = cell_data.itemXlsxData
        -- 1每日登陆，2每日限购，3任务
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "num_bg", false)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "buy_limit_text", false)
        if taskType == 1 then
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_hint", cell_data.isGot)
            LuaBehaviourUtil.setImg(luaBehaviour, "btn_canGotBtn", "a_ui_currency_btn_small_2", "common_ui")
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_canGotBtn", (not cell_data.isGot))
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_hint", "flower_text_0014")
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_title", Language:getTextByKey(itemXlsxData.name))
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_canGotBtnText", "flower_text_0016")
        elseif taskType == 2 then
            local isCanBuy = cell_data.buyCount < itemXlsxData.time
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_hint", (not isCanBuy))
            LuaBehaviourUtil.setImg(luaBehaviour, "btn_canGotBtn", "a_ui_currency_btn_small_2", "common_ui")
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_canGotBtn", isCanBuy)
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_hint", "flower_text_0015")
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_title", Language:getTextByKey(itemXlsxData.name))
            local price_data = RewardUtil:getProcessRewardData(itemXlsxData.price[1])
            LuaBehaviourUtil.setImg(luaBehaviour, "icon_img", price_data.icon_name, price_data.atlas_name)
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "num_text", price_data.data_num)
            local residueCount = (itemXlsxData.time - cell_data.buyCount)
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "buy_limit_text", "flower_text_0018", residueCount)
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_canGotBtnText", "flower_text_0019")
            local isShow = residueCount > 0
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "num_bg", isShow)
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "buy_limit_text", isShow)
        elseif taskType == 3 then
            local status = cell_data.status
            local isShowBtn = (status ~= 2)
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_hint", (not isShowBtn))
            local icon_name = status == 1 and "a_ui_currency_btn_small_2" or "a_ui_currency_btn_small_3"
            LuaBehaviourUtil.setImg(luaBehaviour, "btn_canGotBtn", icon_name, "common_ui")
            LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_canGotBtn", isShowBtn)
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_hint", "flower_text_0014")
            local taskName = Language:getTextByKey(itemXlsxData.name)
            local curParams = cell_data.curProgress > itemXlsxData.target_value and itemXlsxData.target_value or cell_data.curProgress
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_title", taskName .. "（".. curParams.."/".. itemXlsxData.target_value .. "）")
            local btnText = status == 0 and "flower_text_0017" or "flower_text_0020"
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_canGotBtnText", btnText)
        end
        ---- 奖励
        local rewardXlsxData = itemXlsxData.reward
        for i = 1, 3 do
            local awardData = rewardXlsxData[i]
            local awardItemNode = luaBehaviour:FindGameObject("taskAward_"..i)
            awardItemNode:SetActive(awardData ~= nil)
            if awardData then
                local itemAwardInfo = RewardUtil:getProcessRewardData(awardData)
                if itemAwardInfo then
                    GameUtil:updateItemElementByData(awardItemNode, itemAwardInfo, true, true)
                end
            end
        end
    end
end
function M:bindUI()
    local mainActiveData = self.m_model:getXlsxActivityByOpenId(self.m_model.m_openId, false)
    self:setTextByLanKey("close_title_text", mainActiveData.name)
    self:bindGridBtnEvent()
end

function M:bindGridBtnEvent()
    for index = 1, 16 do
        local flowerLineNode = self:findGameObject("flowerLineNode"..index)
        local luaBehaviour = UIUtil.findLuaBehaviour(flowerLineNode)
        local btn_flowerLine = luaBehaviour:FindGameObject("btn_flowerLine")
        UIUtil.setButtonClick(
                btn_flowerLine.transform,
                function()
                    self:updateMsg("click_lineGameBtnEvent", {index = index})
                end
        )
    end
end

function M:destroy()
    if self.m_attr_node then
        self.m_attr_node:destroy()
        self.m_attr_node = nil
    end
    self.m_control:updateMsg("everyDayrefresh", nil, "FlowerFestival.FlowerMain")
    EventDispatcher:unRegisterEvent(GlobalConfig.EVENT_KEYS.EVERY_DAY_EVENT, {self, self.everyDayRefreshEvent})
    M.super.destroy(self)
end

return M


