---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 20:08
---

local M = class("PetardGiftBagControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
    --每隔1秒执行一次, 倒计时
    local timerFormat, residueTimer = self.m_model:getDayTimer()
    self.m_view:refreshDayTimer(timerFormat)
    self:setTimer(1,function()
        local timerFormat2, residueTimer2 = self.m_model:getDayTimer()
        self.m_view:refreshDayTimer(timerFormat2)
        -- 不会停止，新的一天会重新算
        --if residueTimer <= 0 then
        --end
    end)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_buySkinBtn" then
        --- 购买皮肤礼包
        local xlsxData = self.m_model.m_skinDatas.xlsxData
        if xlsxData then
            if self.m_model.m_skinDatas.isBuy then
                return
            end
            self:buyForSDK(xlsxData.charge_id)
        end
    elseif msg == "explain_btn" then
        -- 提示  
        local flowerData = ConfigManager:getCfgByName("flower")
        local versionData = flowerData[self.m_model.m_version]
        self:openView("Pops.CommonHelpPop", { title = self.m_model.m_mainActivityName, content = versionData.des })
    end
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView("PetardActivity.PetardMain")
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

--调用sdk充值
function M:buyForSDK(charge_id)
    if self.m_model.is_tokens == true then
        self:setOnceTimer(0.5,function()
            -- 需要延时，sdk到服务器有一个延时
            EventDispatcher:dipatchEvent("forceRefresh_petardInfoData")
        end)
        return
    end
    if self.timer_id then
        Logger.logWarningAlways(self.timer_id, "-------------IsPay-----------")
        return
    end
    self.m_view:lockTouch()
    self.timer_id = self:setOnceTimer(8, function ()
        self.m_view:unlockTouch()
        self.timer_id = nil
    end)
    PayUtil:rechargeByChargeId(charge_id, function ()
        self.m_view:unlockTouch()
        if self.timer_id then
            self:removeTimer(self.timer_id)
            self.timer_id = nil
        end
        self:setOnceTimer(0.5,function()
            -- 需要延时，sdk到服务器有一个延时
            EventDispatcher:dipatchEvent("forceRefresh_petardInfoData")
        end)
    end)
end

--使用代金券购买
function M:buyUseVoucher(data, callback)
    local function receivetCallback(response)
        if callback then
            callback()
        end
        if response and response.reward then
            RewardUtil:rewardTipsByData(response.reward)
        end
    end
    local charge = ConfigManager:getCfgByName("charge")
    local cfg = charge[data]
    if cfg == nil then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0129",data), delay_close = 2})
        return
    end
    local voucher_data = RewardUtil:getProcessRewardData({RewardUtil.REWARD_TYPE_KEYS.VOUCHER,0,0})
    if voucher_data.user_num < cfg.price then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0130",data), delay_close = 2})
        return
    end
    local params = {
        charge_id = data
    }
    self.m_model:getNetData("voucher", params, receivetCallback)
end

return M