---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 19:55
---

local M = class("PetardGiftBagView",LikeOO.OOPopBase)

M.m_uiName = "PetardActivity/PetardGiftBag"  -- prefab name
M.m_size_type = 1
M.m_iphoneXAdapter = true

function M:onEnter()
    EventDispatcher:registerEvent("petardActivity_everyDayEvent", {self, self.everyDayRefreshEvent})
    self.grayImage = self:findImage("img_grayImage")
    self:bindUI()
    self:refreshUI()
end

function M:everyDayRefreshEvent(event, data)
    -- 刷新
    self.m_model:refreshData(data[self.m_model.m_openId])
    self:refreshUI()
end

function M:bindUI()
    self:setTextByLanKey("close_title_text", self.m_model.m_xlsxActivity.name)
    self.dayTimerText = self:findText("text_giftTime")
    RedPointUtil:saveLocalRedPointFreshTime("petardGift_everyDayRedDot")
end

function M:refreshUI()
    self:refreshActivityTimer()
    self:refreshLeftNode()
    for index = 1, 3 do
        self:refreshShopItem(index)
    end
end

function M:refreshDayTimer(timerFormat)
    if not IsNull(self.dayTimerText) then
        self.dayTimerText.text = Language:getTextByKey("petard_text_0023",timerFormat);
    end
end

function M:refreshLeftHeroNode()
    
end

function M:refreshLeftNode()
    -- 价格
    local xlsxData = self.m_model.m_skinDatas.xlsxData
    local isBuy = self.m_model.m_skinDatas.isBuy
    self:setText("text_discountText", xlsxData.return_per)
    self:setTextByLanKey("text_originalMoney", "petard_text_0024", GameUtil:switchMoneyType(xlsxData.price_old))
    self:refreshSkinBtnType(isBuy)
    
    ---- 皮肤礼包刷新
    local reward = xlsxData.reward
    local reward_data = RewardUtil:getProcessRewardData(reward[1])
    if reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT then
        local cfg = UserDataManager.hero_data:getHeroConfigByCid(reward_data.data_id)
        if cfg then
            local icon = cfg.hero_spine
            if self.cacheSpineName == icon then
                return
            else
                self.cacheSpineName = icon
            end
        end
    elseif reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
        local cur_skin_cfg = ConfigManager:getHeroSkinCfg(reward_data.data_id)
        local icon = cur_skin_cfg.hero_spine
        if self.cacheSpineName == icon then
            return
        else
            self.cacheSpineName = icon
        end
    end
    if self.cacheSpineName then
        local play_img = self:findGameObject("hero_spine")
        GameUtil:updateSpineLoadSet(play_img, "RoleSpine/" .. self.cacheSpineName, "idle", 0, true)
    end

    -- 设置名字
    local heroId = reward_data.item_cfg.hero
    if heroId == nil then
        heroId = reward_data.data_id
    end
    local m_hero_cfg = UserDataManager.hero_data:getHeroConfigByCid(heroId)
    local m_shin_data_cfg = UserDataManager.hero_data:getHeroCurSkinCfgByData({skin = reward_data.data_id}, m_hero_cfg)
    --local frame_data = GlobalConfig.QUALITY_FRAME[m_hero_cfg.max_evo]
    self:setImg(GameUtil:get_lineframename(m_hero_cfg.Ex_hero,m_hero_cfg.max_evo), "common_ui","hero_evo")
    local race = GlobalConfig.TYPE_HERO_RACE[m_hero_cfg.race].big_race_icon
    self:setImg(race,  ResourceUtil:getLanAtlas(), "hero_race")
    local class_str = Language:getTextByKey(m_hero_cfg.class)
    local name_str = Language:getTextByKey(m_shin_data_cfg.name)
    if m_shin_data_cfg.name == nil then
        name_str = Language:getTextByKey(m_hero_cfg.name)
    end
    self:setTextByLanKey("hero_name", class_str)
    self:setTextByLanKey("hero_name2", name_str)
    self:setObjectVisible("hero_name_con", true)
    local btn_heroSkinBtn = self:findGameObject("btn_heroSkinBtn")
    UIUtil.setButtonClick(
            btn_heroSkinBtn.transform,
            function()
                if reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROS or reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HEROSEXT then
                    static_rootControl:openView("Pops.HeroLookInfo", {hero_id = heroId, is_new = false})
                elseif reward_data.data_type == RewardUtil.REWARD_TYPE_KEYS.HERO_SKIN then
                    static_rootControl:openView("Pops.HeroSkinLookInfo", {is_new = false, skin_id = reward_data.data_id})
                end
            end
    )
end

function M:refreshSkinBtnType(isBuy)
    local xlsxData = self.m_model.m_skinDatas.xlsxData
    local btn_buySkinBtn = self:findImage("btn_buySkinBtn")
    btn_buySkinBtn.material = isBuy and self.grayImage.material or nil
    local moneyHint = isBuy and Language:getTextByKey("petard_text_0018") or  GameUtil:getMoneyTypeNum(xlsxData.price_new) 
    self:setText("text_buySkinText", moneyHint)
end

function M:refreshShopItem(index)
    local itemObj = self:findGameObject("itemNode"..index)
    if IsNull(itemObj) then
        return
    end
    local luaBehaviour = UIUtil.findLuaBehaviour(itemObj)
    if not luaBehaviour then
        return
    end
    -- 奖励
    local transform = itemObj.transform
    local giftData = self.m_model.m_giftDatas[index]
    if not giftData then
        return
    end
    local xlsxData = giftData.xlsxData
    local awardData = xlsxData.return_money[1]
    local reward_node = UIUtil.findRectTransform(transform, "awardNode")
    UIUtil.destroyAllChild(reward_node)
    if awardData then
        local itemNode = GameUtil:createItemElement(awardData, true, true)
        itemNode.transform:SetParent(reward_node.transform, false)
    end
    
    -- 按钮
    local btn_buyBtn = luaBehaviour:FindGameObject("btn_buyBtn")
    UIUtil.setButtonClick(
            btn_buyBtn.transform,
            function()
                if giftData.residueBuyCount <= 0 then
                    return
                end
                self.m_control:buyForSDK(xlsxData.charge_id)
            end
    )
    LuaBehaviourUtil.setImg(luaBehaviour, "btn_awardBtn", xlsxData.background, "item_icon")
    local btn_awardBtn = luaBehaviour:FindGameObject("btn_awardBtn")
    UIUtil.setButtonClick(
            btn_awardBtn.transform,
            function()
                self.m_control:openView("Pops.LookRewardTips",{rewards = xlsxData.reward, click_transform = btn_awardBtn.transform, show_check_mark = false})
            end
    )
    
    local perFormat = math.floor(xlsxData.return_per * 100) .. "%"
    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_itemHint", "petard_text_0020", perFormat)   
    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_itemTitle", xlsxData.gift_name)    
    LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_astrictCount", "petard_text_0021", giftData.residueBuyCount)
    local isCanBuy = (giftData.residueBuyCount > 0)
    local priceFormat = (not isCanBuy) and Language:getTextByKey("petard_text_0018") or GameUtil:getMoneyTypeNum(xlsxData.price)
    LuaBehaviourUtil.setText(luaBehaviour, "text_buyText",priceFormat)
    local btn_buyBtnImg = luaBehaviour:FindImage("btn_buyBtn")
    btn_buyBtnImg.material = (not isCanBuy) and self.grayImage.material or nil
end

function M:refreshActivityTimer()
    local startTimer = self.m_model.m_activityData.start_ts
    local endTimer = self.m_model.m_activityData.end_ts
    local starT = TimeUtil.gmTime(startTimer)
    local endT = TimeUtil.gmTime(endTimer)
    local timerFormat = Language:getTextByKey("castingSword_str_0012", starT.year, starT.month, starT.day,
            endT.year, endT.month, endT.day)
    self:setTextByLanKey("text_timer", "castingSword_str_0011", timerFormat)
end

function M:destroy()
    EventDispatcher:dipatchEvent("petardMainRedDotRefresh")
    EventDispatcher:unRegisterEvent("petardActivity_everyDayEvent", {self, self.everyDayRefreshEvent})
    M.super.destroy(self)
end

return M