---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/13 11:03
---

local M = class("CastingSwordExchangeModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self.m_version = self.m_params.version
    self.m_activityData = self.m_params.actives[1]
    self:setExchangeAwardsData(self.m_params.exchange)  --self.m_exchangeData
    self:setTaskData(self.m_params.login_recv)  -- self.m_taskData
    self:setSpokesmanData()     -- self.m_spokesmanData
    self.m_spokesmanIndex = 1
    self:getData()
end

function M:switchSpokesmanIndex()
    self.m_spokesmanIndex = self.m_spokesmanIndex + 1
    self.m_spokesmanIndex = (self.m_spokesmanIndex > 3) and 1 or self.m_spokesmanIndex
end

function M:getLoginBagData(data)
    local tempData = {}
    for i = 1, #data do
        local dayId = data[i]
        tempData[dayId] = dayId
    end
    return tempData
end

function M:onEnter()
    -- 1 签到好礼， 2 信物兑换
    self.m_selectTabIndex = 1
end

function M:setSelectTabIndex(index)
    self.m_selectTabIndex = index
end

function M:setSpokesmanData()
    local tempData = {}
    local sword_questData = ConfigManager:getCfgByName("sword_star")
    local versionRankAwardData = sword_questData[self.m_version] or {}
    self.m_spokesmanData = versionRankAwardData
end

-- 获取最终奖励数据
function M:setExchangeAwardsData(exchangeData)
    local tempData = {}
    local sword_questData = ConfigManager:getCfgByName("sword_exchange")
    local versionRankAwardData = sword_questData[self.m_version] or {}
    for id, itemData in pairs(versionRankAwardData) do
        local gotCount = exchangeData[tostring(id)] or 0
        local residueExchangeCount = (itemData.times - gotCount)
        tempData[id] = {
            xlsxData = itemData,
            residueExchangeCount = residueExchangeCount,
            id = id,
            isInfinite = (itemData.times <= 0),
        }
    end
    self.m_exchangeData = tempData
end

-- 活动开启了几天
function M:getActityOpenDayCount()
    local serverTimer = UserDataManager:getServerTime()
    local startTimer = self.m_activityData.start_ts
    local openDayCount = GameUtil:NumberOfDaysIntervalDay(startTimer,serverTimer)
    openDayCount = math.floor(openDayCount)
    openDayCount = openDayCount <= 0 and 1 or openDayCount
    return openDayCount
end

-- 获取任务数据
function M:setTaskData(login_recv)
    local m_login_recv = self:getLoginBagData(login_recv)
    local sword_questData = ConfigManager:getCfgByName("sword_login")
    local versionRankAwardData = sword_questData[self.m_version] or {}
    local tempData = {}
    for dayId, itemData in pairs(versionRankAwardData) do
        tempData[dayId] = {
            xlsxData = itemData,
            isGot = (m_login_recv[dayId] ~= nil),
            dayId = dayId,
        }
    end
    self.m_taskData = tempData
end

return M