---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/13 10:57
---

local M = class("CastingSwordExchangeView",LikeOO.OOPopBase)

M.m_uiName = "CastingSwordMeeting/CastingSwordExchange"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

function M:onEnter()
    self:bindUI()
    self:refreshUI()
    self:refreshSpokesmanInfo(true)
end

function M:bindUI()
    self:setTextByLanKey("close_title_text", "castingSword_str_0040")
    self:setTextByLanKey("text_signTabBtnText", "castingSword_str_0033")
    self:setTextByLanKey("text_selectSignText", "castingSword_str_0033")
    self:setTextByLanKey("btn_exchangeTabBtnText", "castingSword_str_0034")
    self:setTextByLanKey("text_selectExchangeText", "castingSword_str_0034")
    self:setTextByLanKey("text_hintText", "castingSword_str_0050")
    self.spokesmanNode = self:findGameObject("img_npcImg")
    self.spokesmanImg = self:findImage("img_npcImg")
end

function M:refreshUI()
    self:refreshTabLoopScroll()
end

function M:switchTab(tabIndex)
    if self.m_model.m_selectTabIndex == tabIndex then
        return 
    end
    self.m_model:setSelectTabIndex(tabIndex)
    self:refreshUI()
end

function M:refreshTabLoopScroll()
    -- 是否签到好礼
    local isSign = (self.m_model.m_selectTabIndex == 1)
    self:setObjectVisible("img_selectSign", isSign)
    self:setObjectVisible("img_selectExchange", (not isSign))
    self:setObjectVisible("signViewNode", isSign)
    self:setObjectVisible("exchangeViewNode", (not isSign))
    if isSign then
        -- 签到好礼
        self:createSignLoopScroll()
    else
        -- 信物兑换
        self:createExchangeLoopScroll()
    end
end

-- 信物兑换
function M:createExchangeLoopScroll()
    local data = self.m_model.m_exchangeData
    if self.m_exchangeScroll_view == nil then
        local loopscroll = self:findGameObject("exchangeLoopscroll")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self:refreshExchangeItem(cell_obj, cell_data, index)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name) -- 点击回调
                if click_name == "btn_canGotBtn" then
                    local params = {vsn = self.m_model.m_version, gift_id = cell_data.id}
                    self.m_model:getNetData("sword_login_exchange", params, function(response)
                        if response then
                            if self.m_control:activityOverExamine(response) then
                                return
                            end
                            RewardUtil:rewardTipsByData(response.reward)
                            cell_data.residueExchangeCount = cell_data.residueExchangeCount - 1
                            self.m_model:setExchangeAwardsData(response.exchange)
                            self:refreshUI()
                        end
                    end, nil, nil, nil)                    
                end
            end
        }
        self.m_exchangeScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_exchangeScroll_view:reloadData(data,true)
    end
end

function M:refreshExchangeItem(cell_obj, cell_data, index)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local xlsxData = cell_data.xlsxData
        local need_reward = xlsxData.need_reward[1]
        local itemCurCount = RewardUtil:getProcessRewardData(need_reward)
        local isGot = (cell_data.residueExchangeCount <= 0) and (not cell_data.isInfinite)
        local isEnough = (itemCurCount.user_num >= itemCurCount.data_num)
        local isCanExchange = (cell_data.residueExchangeCount > 0) and isEnough
        isCanExchange = cell_data.isInfinite and isEnough or isCanExchange
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_canGotBtn", isCanExchange)
        local isShowNoGotBtn = (not isCanExchange) and (cell_data.residueExchangeCount > 0)
        isShowNoGotBtn = cell_data.isInfinite and true or isShowNoGotBtn
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_noGotBtn", isShowNoGotBtn)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_gotText","castingSword_str_0029")
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_gotText", isGot)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_line", index < #self.m_model.m_exchangeData )
        local needTextFormat1 = Language:getTextByKey("castingSword_str_0032", itemCurCount.user_num, itemCurCount.data_num)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_exchangeText1", needTextFormat1)
        local needTextFormat2 = Language:getTextByKey("castingSword_str_0044")
        if not cell_data.isInfinite then
            needTextFormat2 = Language:getTextByKey("castingSword_str_0031", cell_data.residueExchangeCount) 
        end
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_exchangeText2", needTextFormat2)
        -- 奖励
        local transform = cell_obj.transform
        for i = 1, 2 do
            local awardData = (i == 1) and xlsxData.need_reward[1] or xlsxData.out_reward[1]
            local reward_node = UIUtil.findRectTransform(transform, "iconNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData then
                local itemNode = GameUtil:createItemElement(awardData, true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
    end
end

function M:refreshSpokesmanInfo(isInit)
    local spokesmanData = self.m_model.m_spokesmanData[self.m_model.m_spokesmanIndex]
    GameUtil:updateResourcesImg(self.spokesmanImg, "Texture/castingSwordMeeting/"..spokesmanData.hero_id)
    if not isInit then
        self:moveSpokesman(false,function()
            self:switchSpokesman()
        end)
    else
        self:switchSpokesman()
    end
end

function M:moveSpokesman(isHideImg, moveOverEvent)
    local aValue = isHideImg and 0 or 1
    local m_sequence = Tweening.DOTween.Sequence()
    m_sequence:Append(DOTweenModuleUI.DOFade(self.spokesmanImg, aValue, 0.5))
    m_sequence:OnComplete(function()
        if moveOverEvent then
            moveOverEvent()
        end
        if isHideImg then
            local spokesmanData = self.m_model.m_spokesmanData[self.m_model.m_spokesmanIndex]
            if spokesmanData then
                self.spokesmanNode.transform.localPosition = Vector3(spokesmanData.x_offset,-5,0)
            end
        end
    end)
end

function M:switchSpokesman()
    self.m_control:setOnceTimer(2,function()
        self:moveSpokesman(true, function()
            self.m_model:switchSpokesmanIndex()
            self:refreshSpokesmanInfo(false)
        end)
    end)
end

-- 签到好礼
function M:createSignLoopScroll()
    local data = self.m_model.m_taskData
    if self.m_signScroll_view == nil then
        local loopscroll = self:findGameObject("signLoopscroll")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self:refreshTaskItem(cell_obj, cell_data, index)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name) -- 点击回调
                if click_name == "btn_canGotBtn" then
                    local params = {vsn = self.m_model.m_version, day = cell_data.dayId}
                    self.m_model:getNetData("sword_recv_login_reward", params, function(response)
                        if response then
                            if self.m_control:activityOverExamine(response) then
                                return
                            end
                            RewardUtil:rewardTipsByData(response.reward)
                            cell_data.isGot = true
                            self.m_model:setTaskData(response.login_recv)
                            self:refreshUI()
                        end
                    end, nil, nil, nil)
                end
            end
        }
        self.m_signScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_signScroll_view:reloadData(data,true)
    end
end

function M:refreshTaskItem(cell_obj, cell_data, index)
    local curDay = self.m_model:getActityOpenDayCount()
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local xlsxData = cell_data.xlsxData
        local isShowImg = (xlsxData.hade ~= "")
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_spokesman", isShowImg)
        if isShowImg then
            LuaBehaviourUtil.setImg(luaBehaviour, "img_spokesman", xlsxData.hade, "pub_ui")
        end
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour,"text_name",xlsxData.name)
        local isGot = cell_data.isGot
        local isCanGot = false
        local residueDay = math.floor(cell_data.dayId - curDay)
        if not isGot then
            isCanGot = (cell_data.dayId == curDay) and true or (residueDay <= 0)
        end
        local isNotGot = (not isGot) and (not isCanGot)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour,"text_gotBtnText","castingSword_str_0005")
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_gotBtn", isGot)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour,"text_canGotBtnText","castingSword_str_0014")
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_canGotBtn", isCanGot)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour,"text_gotTimerText","castingSword_str_0037", residueDay)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_gotTimerText", isNotGot)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "img_line", (index ~= #self.m_model.m_taskData))
        -- 奖励
        local transform = cell_obj.transform
        local allAward = xlsxData.reward
        for i = 1, 2 do
            local awardData = allAward[i]
            local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData then
                local itemNode = GameUtil:createItemElement(awardData, true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M