---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/11 20:17
---

local M = class("CastingSwordShareControl",LikeOO.OOControlBase)

function M:onEnter()
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_redPacketBtn" then
        -- 邀请好友得现金
        self:showRedBagH5()
    elseif msg == "btn_shareBtn" then
        -- 分享
        RedPointUtil:saveLocalRedPointFreshTime("CastingSwordShareBtnState")
        self:openView("CastingSwordMeeting.CastingSwordShareInfo", {m_version = self.m_model.m_version})
    end
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:showRedBagH5()
    if not self.m_model:isOpenRedBagActivity() then
        GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("tid#haogandutips_6"), delay_close = 2})
        return
    end
    local url = nil
    local active_tab = ConfigManager:getCfgByName("active")
    for i, v in pairs(active_tab) do
        if v.open_id == 178 then
            url = v.link
            break
        end
    end
    if url == nil then
        return
    end
    local url_new = url
    SDKUtil:openUrl(url_new)
end

function M:destroy()
    M.super.destroy(self)
end

return M