-- Dotween动画
Tweening = CS.DG.Tweening
DOTweenModuleUI = Tweening.DOTweenModuleUI
require("Battle.Init")
require("Framework.Init")
Bit = require("bit")
NetUrl = require("Net.NetUrl")
NetWork = require("Net.NetWork")
NetWorkTss = require("Net.NetWorkTss")
GameUtil = require("Util.GameUtil")
require("DataCenter.Init")
AnimUtil = require("Util.AnimUtil")
RewardUtil = require("Util.RewardUtil")
SDKUtil = require("Util.SDKUtil")
SDKUtil:init()
PushUtil = require("Util.PushUtil")
NineActiveUtil = require("Util.NineActiveUtil")
WhalSDKUtil = require("Util.WhaleSdkHelper")
WhalSDKUtil:init()
PayUtil = require("Util.PayUtil")
LoopScrollUtil = require("Util.LoopScrollUtil")
MaskSlider = require("Util.MaskSlider")
PingPangMotion = require("Util.PingPangMotion")
CarouselUtil = require("Util.CarouselUtil")
QuickOpenFuncUtil = require("Util.QuickOpenFuncUtil")
RedPointUtil = require("Util.RedPointUtil")
LoopScrollViewUtil = require("Util.LoopScrollViewUtil")
BtnOpenUtil = require("Util.BtnOpenUtil")
ResourceUtil = require("Util.ResourceUtil")
ChatUtil = require("Util.ChatUtil")
audio = require("Util.AudioUtil")
CommonUIUtil = require("Util.CommonUIUtil")
StatisticsUtil = require("Util.StatisticsUtil")
BattleModeUtil = require("Util.BattleModeUtil")
PrestigeUtil = require("Util.PrestigeUtil")