---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/11/9 18:05
---

local M = class("PetardSevenDayLoginControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "itemNode1" then
        self:gotEveryDayAward(1)
    elseif msg == "itemNode2" then
        self:gotEveryDayAward(2)
    elseif msg == "itemNode3" then
        self:gotEveryDayAward(3)
    elseif msg == "itemNode4" then
        self:gotEveryDayAward(4)
    elseif msg == "itemNode5" then
        self:gotEveryDayAward(5)
    elseif msg == "itemNode6" then
        self:gotEveryDayAward(6)
    elseif msg == "explain_btn" then
        -- 提示  
        local flowerData = ConfigManager:getCfgByName("flower")
        local versionData = flowerData[self.m_model.m_version]
        self:openView("Pops.CommonHelpPop", { title = self.m_model.m_mainActivityName, content = versionData.des })
    end
end

function M:gotEveryDayAward(index)
    local allAwardData = self.m_model.m_allAwardData
    local itemData = allAwardData[index]
    if not itemData.isCanGot then
        if itemData.isGot then
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("petard_text_0012"), delay_close = 2})
        end
        return
    end
    self.m_model:getNetData("double_twelve_receive_sign", {version = self.m_model.m_version, day = index}, function(response)
        if response then
            if self:activityOverExamine(response) then
                return
            end
            RewardUtil:rewardTipsByData(response.reward)
            EventDispatcher:dipatchEvent("forceRefresh_petardInfoData")
        end
    end, nil, nil, nil)
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView("PetardActivity.PetardMain")
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M