---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 17:58
---

local M = class("PetardSevenDayLoginModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:refreshData(self.m_params)
    self:getData()
end

function M:onEnter()

end

function M:refreshData(m_params)
    self.m_activityData = m_params.activityData or {}
    self.m_openId = self.m_activityData.open_id
    self.m_version = m_params.m_version
    self.m_xlsxActivity = m_params.xlsxActivity
    self.m_mainActivityName = m_params.mainActivityName
    
    self.m_serverData = {}
    for _, itemData in pairs(m_params.serverData) do
        self.m_serverData[itemData] = itemData
    end
    self:setAllAwardData()
end

function M:setAllAwardData()
    local openDay = GameUtil:getActityOpenDayCount(self.m_activityData.start_ts)
    local tempDatas = {}
    local loginXlsxData = ConfigManager:getCfgByName("flower_login")
    local versionData = loginXlsxData[self.m_version]
    for index, itemData in pairs(versionData) do
        local isGot = (self.m_serverData[index] ~= nil)
        tempDatas[index] = {
            itemTaskData = itemData,
            isCanGot = (index <= openDay) and (not isGot),
            isGot = isGot,
            isNoSign = (index > openDay),
        }
    end
    self.m_allAwardData = tempDatas
end

return M