---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/10 15:39
---

local M = class("FulwinArenaInviteListPopControl", LikeOO.OOControlBase)

function M:onEnter()

end

function M:onHandle(msg, data)
    if msg == 99999 then -- 关闭
        self:closeView()
    elseif msg == "item_click" then
        local item_data = data.cell_data
        local open_tab_index = self.m_model.m_team_type == 1 and 2 or 1
        self:openView("Pops.PlayerInfo", {uid = item_data.user.uid, look_model = 9, open_tab_index = open_tab_index, team_type = self.m_model.m_team_type, fair = self.m_model.m_fair and 1 or 0})
    elseif msg == "item_battle" then
        self:updateMsg("item_battle", {playerData = data.cell_data}, "FulwinArena.FulwinArenaInvitePop")
        self:closeView()
    end
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end


return M