---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/10 15:36
---

local M = class("FulwinArenaInviteListPopModel", LikeOO.OODataBase)

M.point = {}

function M:onCreate()
    self.m_transfer = "scale"
    self.m_team_type = self.m_params.team_type
    self.m_fair = self.m_params.fair
    self:getData("friend_arena_get_friends", {team_type = self.m_team_type, fair = self.m_fair and 1 or 0})
end

function M:onEnter()
    self.m_friendsData = self.m_data.friends
end

return M