---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/10 15:36
---

local M = class("FulwinArenaInviteListPopView", LikeOO.OOPopBase)

M.m_uiName = "FulwinArena/FulwinArenaInviteListPop"
M.m_size_type = 2

function M:onEnter()
    self:bindUI()
    self:refreshUI()
end

function M:refreshList()
    -- 任务列表
    local data = self.m_model.m_friendsData
    if self.m_inviteScroll_view == nil then
        local loopscroll = self:findGameObject("invite_loopscroll")
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshItem(cell_obj, cell_data)
            end,
            ui_name = self.m_uiName,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_fight" then
                    self:updateMsg("item_battle", {id = index, cell_data = cell_data})
                elseif click_name == "btn_playerInfo" then
                    self:updateMsg("item_click", {id = index, cell_data = cell_data})
                else
                    self:updateMsg("item_click", {id = index, cell_data = cell_data})
                end
            end
        }
        self.m_inviteScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_inviteScroll_view:reloadData(data, true)
    end
end


function M:refreshItem(cell_obj, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local head_node = luaBehaviour:FindGameObject("head_node")
        local user = cell_data.user
        GameUtil:setUserAvatar(head_node, user,false,false) -- ,{show_flag = false, scale = 1}
        LuaBehaviourUtil.setText(luaBehaviour, "text_name",user.name)
        LuaBehaviourUtil.setText(luaBehaviour, "text_battleValue", GameUtil:formatValueToString(cell_data.combat))
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_fight","fylt_str_0030")
        zfljArenaRank = cell_data.arena_rank or 0
        zfljArenaRank = zfljArenaRank > 0 and zfljArenaRank or Language:getTextByKey("fylt_str_0039")
        --LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_zfljRank", zfljArenaRank)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_zfljRank", "")
        txywArenaRank = cell_data.high_arena_rank or 1
        txywArenaRank = txywArenaRank <= 0 and 999999 or txywArenaRank
        local isShowRankLogo = txywArenaRank > 0 
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_txqwRank", (not isShowRankLogo))
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "segment_node", isShowRankLogo)
        if isShowRankLogo then
            local cfg = ConfigManager:getHighArenaCfgByRank(txywArenaRank)
            local segment_node = luaBehaviour:FindGameObject("segment_node")
            CommonUIUtil:setSegmentInfo(segment_node, cfg, true)
        else
            LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_txqwRank", "fylt_str_0040")
        end
        if user.is_online == 0 then
            local time = UserDataManager:getServerTime() - user.last_active_time
            local day, hour, min, sec = GameUtil:getTimeLayoutBySecond(time)
            if day > 0 then
                time_str = string.format(Language:getTextByKey("mail_str_0002"),day)
            elseif hour > 0 then
                time_str = string.format(Language:getTextByKey("mail_str_0003"),hour)
            elseif min > 0 then
                time_str = string.format(Language:getTextByKey("mail_str_0004"),min)
            else
                time_str = Language:getTextByKey("mail_str_0005")
            end
            UIUtil.setTextColor(cell_obj.transform, Color( 183/255, 65/255, 65/255), "text_timer")
        else
            time_str = Language:getTextByKey("mail_str_0006")
            UIUtil.setTextColor(cell_obj.transform, Color( 64/255, 118/255, 17/255), "text_timer")
        end
        LuaBehaviourUtil.setText(luaBehaviour, "text_timer", time_str)
    end
end

function M:bindUI()
    self:setTextByLanKey("common_title_text", "fylt_str_0026")
    self:setTextByLanKey("text_nameTitle", "fylt_str_0027")
    self:setTextByLanKey("text_rankTitle1", "fylt_str_0028")
    self:setObjectVisible("text_rankTitle1", false)
    self:setTextByLanKey("text_rankTitle2", "fylt_str_0029")
    self:setTextByLanKey("common_no_have_text", "fylt_str_0034")
end

function M:refreshUI()
    local data = self.m_model.m_friendsData or {}
    local isExistData = #data > 0
    self:setObjectVisible("loopscrollNode", isExistData)
    self:setObjectVisible("CommonTipsNode", (not isExistData))
    if isExistData then
        self:refreshList()
    end
end

return M














