---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:24
---


local M = class("SimulateTalentInheritControl",LikeOO.OOControlBase)

function M:onEnter()
    M.super.onCreate(self)
end

function M:onHandle(msg , data)
    if msg == 99999 then
        self:closeView()
    elseif msg == "btn_goBtn" then
        audio:SendEvtUI("UI_Quest")
        if table.nums(self.m_model.m_selectList) <= 0 then
            GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("simulateLeft_text_0050"), delay_close = 2})
            return
        end
        local talents = {}
        local m_talent = self.m_model.m_talents
        for _, index in pairs(self.m_model.m_selectList) do
            table.insert(talents, m_talent[index])
        end
        local params = {open_id = self.m_model.m_open_id, version = self.m_model.m_version, talents = talents}
        self.m_model:getNetData("select_inherit", params, function(response)
            if response then
                if self:activityOverExamine(response) then
                    return
                end
                self:closeView("SimulateLift.SimulateLiftInfo")
                self:updateMsg("refresh_lifeData",{response = response, isAgainStart = true},"SimulateLift.SimulateLiftMain")
                self:closeView()
            end
        end, nil, nil, nil)
    elseif msg == "btn_closeBtn" then
        self:closeView()
    end
end

function M:activityOverExamine(response)
    if response["end"] == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    if response.update == 1 then
        GameUtil:lookInfoTips(self, {msg = Language:getTextByKey("gf_str_0085"), delay_close = 2})
        self:closeView()
        return true
    end
    return false
end

function M:destroy()
    M.super.destroy(self)
end

return M