---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:26
---

local M = class("SimulateTalentInheritModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self:initData()
    self:getData()
end

function M:initData()
    self.m_talentValues = GlobalConfig.SimulateTalentValues
    self.m_qualityColourValues = GlobalConfig.SimulateQualityColourValues
    self.m_allCount = ConfigManager:getCommonValueById(663) or 1
    self.m_selectList = {  }
    self.m_talents = self.m_params.talents
    self.m_open_id = self.m_params.open_id
    self.m_version = self.m_params.version
end

function M:isCanSelect()
    return (table.nums(self.m_selectList) < self.m_allCount)
end

function M:modifySelectCount(index)
    if self.m_selectList[index] ~= nil then
        self.m_selectList[index] = nil
    else
        if not self:isCanSelect() then
            GameUtil:lookInfoTips(self.m_control, {msg = Language:getTextByKey("simulateLeft_text_0049"), delay_close = 2})
            return false
        end
        self.m_selectList[index] = index
    end
    return (self.m_selectList[index] ~= nil)
end

function M:onEnter()

end

return M