---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2022/2/9 14:27
---

local M = class("SimulateTalentInheritView",LikeOO.OOPopBase)
-- 侠客人生模拟器--天赋继承
M.m_uiName = "SimulateLift/SimulateTalentInherit"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

function M:onEnter()
    self:bindUI()
    self:refreshUI()
end

function M:refreshSelectNode()
    local talentXlsxData = ConfigManager:getCfgByName("reopen_talent")
    local allTalentData = self.m_model.m_talent
    local talentValues = self.m_model.m_talentValues
    local qualityColourValues = self.m_model.m_qualityColourValues
    local normalName = "a_hd_jhmnq_tfjc_xuanxiang_lv"
    local selectTalentNode = self:findGameObject("selectTalentNode")
    local selectTalentNodeLua = UIUtil.findLuaBehaviour(selectTalentNode)
    for index = 1, 10 do
        local itemTalentId = allTalentData[index]
        local itemXlsxData = talentXlsxData[itemTalentId]
        local itemNode = selectTalentNodeLua:FindGameObject("itemNode_"..index)
        local itemNodeLuaBehaviour = UIUtil.findLuaBehaviour(itemNode)
        LuaBehaviourUtil.setTextByLanKey(itemNodeLuaBehaviour, "text_name", itemXlsxData.name)
        local text_nameNode = itemNodeLuaBehaviour:FindText("text_name")
        local curQualityColour = qualityColourValues[itemXlsxData.quality]
        text_nameNode.color = Color(curQualityColour[1], curQualityColour[2],  curQualityColour[3])
        LuaBehaviourUtil.setTextByLanKey(itemNodeLuaBehaviour, "text_info", itemXlsxData.description)
        LuaBehaviourUtil.setImg(itemNodeLuaBehaviour, "itemBg",talentValues[itemXlsxData.quality] or normalName,  "pub_ui")
    end
end

function M:refreshUI()
    self:setTextByLanKey("text_content", "simulateLeft_text_0029", self.m_model.m_allCount)
    local talentXlsxData = ConfigManager:getCfgByName("reopen_talent")
    local allTalentData = self.m_model.m_talents
    local talentValues = self.m_model.m_talentValues
    local qualityColourValues = self.m_model.m_qualityColourValues
    local normalName = "a_hd_jhmnq_tfjc_xuanxiang_lv"
    for index = 1, 4 do
        local itemTalentId = allTalentData[index]
        local itemXlsxData = talentXlsxData[itemTalentId]
        if itemXlsxData then
            local itemNode = self:findGameObject("itemNode_"..index)
            local itemNodeLuaBehaviour = UIUtil.findLuaBehaviour(itemNode)
            LuaBehaviourUtil.setTextByLanKey(itemNodeLuaBehaviour, "text_name", itemXlsxData.name)
            local text_nameNode = itemNodeLuaBehaviour:FindText("text_name")
            local curQualityColour = qualityColourValues[itemXlsxData.quality]
            text_nameNode.color = Color(curQualityColour[1], curQualityColour[2],  curQualityColour[3])
            LuaBehaviourUtil.setTextByLanKey(itemNodeLuaBehaviour, "text_info", itemXlsxData.description)
            LuaBehaviourUtil.setImg(itemNodeLuaBehaviour, "itemBg",talentValues[itemXlsxData.quality] or normalName,  "pub_ui")
        else
            self:setObjectVisible("itemNode_"..index, false)
        end
    end
end

function M:bindUI()
    self:setTextByLanKey("text_content2", "simulateLeft_text_0063")
    self:setTextByLanKey("text_title", "simulateLeft_text_0026")
    self:setTextByLanKey("text_goText", "simulateLeft_text_0027")
    for index = 1, 4 do
        local itemNode = self:findGameObject("itemNode_"..index)
        local itemNodeLuaBehaviour = UIUtil.findLuaBehaviour(itemNode)
        local selectBtn = itemNodeLuaBehaviour:FindGameObject("btn_selectBtn")
        --itemBg
        UIUtil.setButtonClick(
                selectBtn.transform,
                function()
                    audio:SendEvtUI("Play_UI_Popup_3")
                    local isShow = self.m_model:modifySelectCount(index)
                    LuaBehaviourUtil.setObjectVisible(itemNodeLuaBehaviour, "img_selectImg", isShow)
                end
        )
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M
