---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/10/14 13:45
---

local M = class("FriendLikeLevelInfoView",LikeOO.OOPopBase)

M.m_uiName = "HeroBag/FriendLikeLevelInfo"  -- prefab name
M.m_size_type = 2

function M:onEnter()
    self:refreshUI()
end

function M:refreshUI()
    self:setTextByLanKey("text_HintText", "bag_text_0001")
    self:setTextByLanKey("common_title_text", "bag_text_0002")
    self:setTextByLanKey("send_gift_text", "bag_text_0003")
    self.reward_grid = self:findGameObject("reward_node")
    ------ 送的道具
    --self.m_params.allGiftData
    ---- 属性
    --self.m_params.attrsData
    ------侠客好感度信息
    --self.m_params.friendInfoData
    self:refreshLikeImgs()
    self:refreshPropertyLoopScroll()
    self:refreshGiftScroll()
end

function M:creatRewards(rewards)
    if rewards == nil then
        return
    end
    local num = #rewards
    UIUtil.destroyAllChild(self.reward_grid.transform)
    for i = 1, num do
        local data = rewards[i]
        local item_cfg = data.item_cfg
        local item_data = data.item_data
        local count = data.needCount
        local itemId = data.itemId
        local showNum = item_cfg.type ~= RewardUtil.REWARD_TYPE_KEYS.HEROS
        local item = GameUtil:createItemElement({RewardUtil.REWARD_TYPE_KEYS.ITEM, itemId,count}, showNum, true)
        if not showNum then
            GameUtil:creatCommonActiveEffect(item, item_cfg.quality, 1)
        end
        item.transform:SetParent(self.reward_grid.transform, false)
    end
end

function M:refreshGiftScroll()
    local giftData = self.m_model.m_params.allGiftData
    local items = self:creatRewards(giftData)
end

function M:refreshLikeImgs()
    local fetter_data = self.m_model.m_params.friendInfoData
    local isCanLevelUp = self.m_model.m_params.isCanLevelUp
    local curLikeLevel = fetter_data.lv
    local lastLikeLevel = isCanLevelUp and (curLikeLevel + 1) or curLikeLevel
    for i = 1, 2 do
        local likeLevel = (i == 1) and curLikeLevel or lastLikeLevel
        if likeLevel >= 10 then
            local num_1 = math.floor(likeLevel/10)
            local num_2 = likeLevel-(num_1*10)
            self:setImg(num_1,"active_ui","youqing"..i.."_lv_img_1")
            self:setImg(num_2,"active_ui","youqing"..i.."_lv_img_2")
            self:setObjectVisible("youqing"..i.."_lv_img_2", true)
            self:setObjectVisible("youqing"..i.."_lv_img_1", true)
            self:setObjectVisible("youqing"..i.."_lv_img", false)
        else
            self:setObjectVisible("youqing"..i.."_lv_img_2", false)
            self:setObjectVisible("youqing"..i.."_lv_img_1", false)
            self:setObjectVisible("youqing"..i.."_lv_img", true)
            self:setImg(likeLevel,"active_ui","youqing"..i.."_lv_img")
        end
    end
end

function M:refreshPropertyLoopScroll()
    local attrsData = self.m_model:getAttrListData()
    if self.m_scroll_view == nil then
        local loopscroll = self:findGameObject("property_loopscroll")
        local params = {
            show_data = attrsData,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
                if luaBehaviour then
                    local name_text = luaBehaviour:FindText("text_propertyName")
                    name_text.text = Language:getTextByKey(cell_data.attrsName)
                    local text_curValue = luaBehaviour:FindText("text_curValue")
                    text_curValue.text = Language:getTextByKey(cell_data.curNum)
                    local text_newValue = luaBehaviour:FindText("text_newValue")
                    text_newValue.text = Language:getTextByKey(cell_data.lastNum)
                    text_newValue.color = cell_data.isNotChange and Color.New(68/255, 85/ 255, 128/ 255, 1) or
                            Color.New(64/255, 118/ 255, 17/ 255, 1)
                end
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name)

            end
        }
        self.m_scroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_scroll_view:reloadData(attrsData, true)
    end
end

function M:destroy()
    M.super.destroy(self)
end
 

return M