---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 16:56
---
local M = class("PetardTaskInfoModel", LikeOO.OODataBase)

function M:onCreate()
    M.super.onCreate(self)
    self.m_scoreTaskData = self.m_params.m_scoreTaskData
    self.m_version = self.m_params.m_version
    self.m_titleName = self.m_params.titleName or ""
    self:getData()
end

function M:setScoreDataById(taskId)
    for _, itemData in pairs(self.m_scoreTaskData) do
        if itemData.id == taskId then
            itemData.isCanGot = false
            itemData.isGot = true
            itemData.isUnfinished = false
        end
    end
end

return M