---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/9 16:57
---
local M = class("PetardTaskInfoView",LikeOO.OOPopBase)

M.m_uiName = "PetardActivity/PetardTaskInfo"  -- prefab name
M.m_size_type = 2
M.m_iphoneXAdapter = true

function M:onEnter()
    self:refreshUI()
    self:bindUI()
end

function M:bindUI()
    self:setTextByLanKey("close_title_text", self.m_model.m_titleName)
    self:setTextByLanKey("text_title", "petard_text_0015")
end

function M:refreshUI()
    self:createLoopScroll()
end

function M:createLoopScroll()
    local data = self.m_model.m_scoreTaskData
    if self.m_scroll_view == nil then
        local loopscroll = self:findGameObject("loopscroll")
        local params ={
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell =function(index, cell_obj, cell_data)
                self:update_Gift(cell_obj, cell_data, index)
            end,
            click_func = function(index, cell_object, cell_data, click_object, click_name) -- 点击回调
                if click_name == "btn_canGotBtn" then
                    local params = {version = self.m_model.m_version, score_id = cell_data.id}
                    self:updateMsg("btn_canGotBtn", params)
                end
            end
        }
        self.m_scroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_scroll_view:reloadData(data)
    end
end

function M:update_Gift(cell_obj, cell_data, index)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local xlsxData = cell_data.xlsxData
        local transform = cell_obj.transform
        local isGot = cell_data.isGot
        local isCanGot = cell_data.isCanGot
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_gotBtnText", isGot)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_gotBtnText","castingSword_str_0005")
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "btn_canGotBtn", isCanGot and (not isGot))
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_canGotBtnText","castingSword_str_0014")
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_taskTitle", "petard_text_0016",xlsxData.score)
        LuaBehaviourUtil.setObjectVisible(luaBehaviour, "text_unfinished", cell_data.isUnfinished)
        LuaBehaviourUtil.setTextByLanKey(luaBehaviour, "text_unfinished", "gf_str_0071")
        -- 奖励
        for i = 1, 3 do
            local awardData = xlsxData.reward or {}
            local reward_node = UIUtil.findRectTransform(transform, "awardNode"..i)
            UIUtil.destroyAllChild(reward_node)
            if awardData[i] then
                local itemNode = GameUtil:createItemElement(awardData[i], true, true)
                itemNode.transform:SetParent(reward_node.transform, false)
            end
        end
    end
end

function M:destroy()
    M.super.destroy(self)
end

return M