---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/10 15:36
---

local M = class("FulwinArenaBattleLogPopModel", LikeOO.OODataBase)

M.point = {}

function M:onCreate()
    self.m_transfer = "scale"
    self.m_version = self.m_params.version
    self.m_selectIndex = self.m_params.index or 1
    self:getData("friend_arena_logs", {typ = self.m_selectIndex - 1})
end

function M:setSelectIndex(index)
    self.m_selectIndex = index
end

function M:onEnter()
    --Logger.log(self.m_data, "onEnter m_data ========")
    self.m_logData = {}
    self.m_logData[self.m_selectIndex] = self.m_data.logs
end

function M:updateData(data)
    if data then
        self.m_logData[self.m_selectIndex] = data.logs
    end
end

function M:getLogData()
    return self.m_logData[self.m_selectIndex] or {}
end

return M