---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xueruixiang.
--- DateTime: 2021/11/10 15:36
---

local M = class("FulwinArenaBattleLogPopView", LikeOO.OOPopBase)

M.m_uiName = "FulwinArena/FulwinArenaBattleLogPop"
M.m_size_type = 2

local __TAB_BTN_NODE = {
    {btn_key = "tog_1", text_key = "tog_1_text", show_text = "fylt_str_0019" }, -- 排行榜
    {btn_key = "tog_2", text_key = "tog_2_text", show_text = "fylt_str_0020" }, -- 奖励
    {btn_key = "tog_3", text_key = "tog_3_text", show_text = "fylt_str_0021" }, -- 奖励
}

function M:onEnter()
    self:bindUI()
    self.m_toggle_btns = {}
    for k,v in pairs(__TAB_BTN_NODE) do
        self:setTextByLanKey(v.text_key, v.show_text)
        local tog_btn = self:findToggle(v.btn_key)
        self.m_toggle_btns[k] = tog_btn
        UIUtil.addToggleListener(tog_btn, function(is_on) self:switchTabUpdate(is_on, k) end,nil,self.m_uiName)
        if k == self.m_model.m_open_tab_index then
            tog_btn.isOn = true
            --self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_1)
            self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_25)
        else
            --self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_5)
            self:setTextColor(v.text_key, GlobalConfig.COMMON_COLLOR.COMMON_24)
        end
    end
    
    self.m_avatar = UserDataManager.user_data:getUserStatusDataByKey("avatar")
    self.m_frame = UserDataManager.user_data:getUserStatusDataByKey("frame")
    self.m_name = UserDataManager.user_data:getUserStatusDataByKey("name")
    self.m_title_id = UserDataManager.user_data:getUserStatusDataByKey("title")
    self:refreshUI()
end

function M:refreshLogList()
    -- 任务列表
    local data = self.m_model:getLogData()
    if self.m_logScroll_view == nil then
        local loopscroll = self:findGameObject("log_loopscroll")
        local params = {
            show_data = data,
            loop_scroll_object = loopscroll,
            update_cell = function(index, cell_obj, cell_data)
                self:refreshTaskItem(cell_obj, cell_data)
            end,
            ui_name = self.m_uiName,
            click_func = function(index, cell_object, cell_data, click_object, click_name)
                if click_name == "btn_video" then
                    self:updateMsg("play_video", {battle_id = cell_data.battle_record_id, round = index, log_data = cell_data, index = index})
                elseif click_name == "btn_playerInfo" then
                    -- 不展示玩家信息
                    --local item_data = self.m_model.m_rivalData
                    --local open_tab_index = self.m_model.m_selectPeopleCount == 1 and 2 or 1
                    --self:openView("Pops.PlayerInfo", {uid = cell_data.user_info.uid, look_model = 9, open_tab_index = open_tab_index})
                end
            end
        }
        self.m_logScroll_view = LoopScrollViewUtil.new(params)
    else
        self.m_logScroll_view:reloadData(data)
    end
end


function M:refreshTaskItem(cell_obj, cell_data)
    local luaBehaviour = UIUtil.findLuaBehaviour(cell_obj)
    if luaBehaviour then
        local isWin = false
        local isWinByAtk = (cell_data.result == 1)
        for playerIndex = 1, 2 do
            local playerNode = luaBehaviour:FindGameObject("playerNode"..playerIndex)
            local playerLua = UIUtil.findLuaBehaviour(playerNode)
            local head_node = playerLua:FindGameObject("head_node")
            --if playerIndex == 1 then
            --    isWin = cell_data.result == 1
            --    title_id = self.m_title_id
            --    GameUtil:setUserAvatar(head_node, {avatar = self.m_avatar, frame = self.m_frame}, false)
            --    LuaBehaviourUtil.setText(playerLua, "text_name",self.m_name)
            --else
            --    isWin = cell_data.result == 0
            --    local user = cell_data.user_info
            --    title_id = user.title
            --    GameUtil:setUserAvatar(head_node, {avatar = user.avatar, frame = user.frame}, false)
            --    LuaBehaviourUtil.setText(playerLua, "text_name",user.name)
            --end
            local playerInfoData = (playerIndex == 1) and cell_data.atk_user_info or cell_data.def_user_info
            GameUtil:setUserAvatar(head_node, {avatar = playerInfoData.avatar, frame = playerInfoData.frame}, false)
            LuaBehaviourUtil.setText(playerLua, "text_name",playerInfoData.name)
            if playerIndex == 1 then
                LuaBehaviourUtil.setObjectVisible(playerLua, "img_win", isWinByAtk)
                LuaBehaviourUtil.setObjectVisible(playerLua, "img_fail", (not isWinByAtk))
            else
                LuaBehaviourUtil.setObjectVisible(playerLua, "img_win", (not isWinByAtk))
                LuaBehaviourUtil.setObjectVisible(playerLua, "img_fail", isWinByAtk)
            end
            local title_id = playerInfoData.title
            if title_id and title_id ~= 0 then
                LuaBehaviourUtil.setObjectVisible(playerLua, "head_title_img", true)
                local title_obj = playerLua:FindGameObject("head_title_img")
                local name_img = playerLua:FindImage("head_title_img")
                local cfg = UserDataManager.title_data:getTitleConfigById(title_id)
                if cfg and name_img and title_obj then
                    name_img.enabled = true
                    GameUtil:setTextureLoadTitleLanImgText(name_img, cfg.icon) -- 设置称号图片
                    name_img:SetNativeSize()
                    UIUtil.setScale(title_obj.transform, 0.7)
                end
                UIUtil.destroyAllChild(name_img.gameObject.transform)
                if cfg.title_effect and cfg.title_effect ~= "" then
                    name_img.enabled = false
                    ResourceUtil:GetUIEffectItem("Headtitle/" .. cfg.title_effect, name_img.gameObject)
                end
            else
                LuaBehaviourUtil.setObjectVisible(playerLua, "head_title_img", false)
            end
        end
    end
end

function M:switchTabUpdate(is_on, update_key)
    local tog_nod = __TAB_BTN_NODE[update_key]
    if is_on then
        self:updateMsg("check_tag", update_key)
        --self:setTextColor(tog_nod.text_key, GlobalConfig.COMMON_COLLOR.COMMON_1)
        self:setTextColor(tog_nod.text_key, GlobalConfig.COMMON_COLLOR.COMMON_25)
    else
        --self:setTextColor(tog_nod.text_key, GlobalConfig.COMMON_COLLOR.COMMON_5)
        self:setTextColor(tog_nod.text_key, GlobalConfig.COMMON_COLLOR.COMMON_24)
    end
end

function M:bindUI()
    self:setTextByLanKey("common_title_text", "fylt_str_0022")
    self:setTextByLanKey("text_leftTitle", "fylt_str_0023")
    self:setTextByLanKey("text_rightTitle", "fylt_str_0024")
end

function M:refreshUI()
    local data = self.m_model:getLogData()
    local isExistLog = #data > 0
    self:setObjectVisible("loopscrollNode", isExistLog)
    self:setObjectVisible("CommonTipsNode", (not isExistLog))
    self:refreshLogList()
end

return M














